### ISSUE TITLE
[FEATURE] cloudInit enhancement

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#523] opened 2021-03-11 06:57 UTC
**Is your feature request related to a problem? Please describe.**

add cloudInit template in vm
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment] 2021-04-13 06:11
duplicate of https://github.com/rancher/harvester/issues/640, will be tracked there.

**Closed as completed by guangbochen** 2021-04-13 06:12 UTC
Labels: kind/enhancement, area/ui
