### ISSUE TITLE
[BUG] Switching the host NIC could cause harvester to be unreachable

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#635] opened 2021-04-01 08:04 UTC
**Describe the bug**
Switching the host NIC could cause Harvester to be unreachable

**To Reproduce**
1. Set up Harvester with multiple NICs in a host
2. Configure the VLAN default NIC, e.g., eth0
3. Switch the NIC by editing the host, e.g., eth1

**Expected behavior**
Harvester is reachable via that URL in the console when its status is `Ready`.

**Result**
Harvester status displays `Ready` in the console, however, it is unreachable via that URL.
![image](https://user-images.githubusercontent.com/57614736/113262588-5aa6d500-9303-11eb-8f9f-42ddce84f59a.png)

**Environment:**
 - Harvester ISO version: 0.2.0-rc1
 - Installation Mode: ISO

**Comment by yaocw2020** [comment] 2021-04-01 08:33
Duplicate of https://github.com/rancher/harvester/issues/534

**Comment by DoNotSayYes** [comment] 2021-04-01 08:37
> #534

what is the solution to solve it?

**Comment by guangbochen** [comment] 2021-04-15 14:53
at times, the default gateway is not set via `connmanctl` using the DHCP configuration, and this will lead to an empty default route when the IP is changed, let's also track this in here.
```
$ connmanctl services ethernet_e0d55e29b31e_cable
connmanctl services ethernet_e0d55e29b31e_cable
/net/connman/service/ethernet_e0d55e29b31e_cable
  Type = ethernet
  Security = [  ]
  State = ready
  Favorite = True
  Immutable = False
  AutoConnect = True
  Name = Wired
  Ethernet = [ Method=auto, Interface=eth0, Address=E0:D5:5E:29:B3:1E, MTU=1500 ]
  IPv4 = [ Method=dhcp, Address=172.16.0.5, Netmask=255.255.0.0 ]
  IPv4.Configuration = [ Method=dhcp ]
  IPv6 = [  ]
  IPv6.Configuration = [ Method=auto, Privacy=disabled ]
  Nameservers = [ 114.114.114.114 ]
  Nameservers.Configuration = [  ]
  Timeservers = [ ntp.ubuntu.com ]
  Timeservers.Configuration = [  ]
  Domains = [  ]
  Domains.Configuration = [  ]
  Proxy = [ Method=direct ]
  Proxy.Configuration = [  ]
  mDNS = False
  mDNS.Configuration = False
  Provider = [  ]
```

**Comment by guangbochen** [comment] 2021-09-27 16:12
close due to in activity, feel free to reopen it similar issue occurs in v0.3 related releases, thanks.

**Closed as completed by guangbochen** 2021-09-27 16:12 UTC
Labels: kind/bug, area/control-plane
