### ISSUE TITLE
[BUG] Warning about CustomResourceDefinition being deprecated in logs

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#900] opened 2021-05-24 18:53 UTC
**Describe the bug**

The logs are showing repeated warnings about CustomResourceDefinition being deprecated
**To Reproduce**
1. Run a harvester cluster for a while
2. Check the logs

**Expected behavior**

We should change to something that is not being deprecated, or suppress the warnings in the logs
**Support bundle**

[harvester-supportbundle_e7e376da-3ef6-4216-b9ca-cc85c312de13_2021-05-24T18-47-25Z.zip](https://github.com/harvester/harvester/files/6534442/harvester-supportbundle_e7e376da-3ef6-4216-b9ca-cc85c312de13_2021-05-24T18-47-25Z.zip)

**Environment:**
 - Harvester ISO version: master-c13c2a35-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL160G9 

**Additional context**
I attached the logs and screenshots
![Greenshot 2021-05-24 11 47 36](https://user-images.githubusercontent.com/83787952/119394069-a2543800-bc86-11eb-82cd-de80290f431f.png)
[container.log](https://github.com/harvester/harvester/files/6534450/container.log)

**Comment by gitlawr** [comment] 2021-05-25 01:20
Duplicate of https://github.com/harvester/harvester/issues/648

**Closed as completed** 2021-05-25 02:12 UTC
Labels: kind/bug
