### ISSUE TITLE
[BUG] Add bond NIC configuration support

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1207] opened 2021-09-13 02:23 UTC
**Describe the bug**
When the user selects to join the Harvester cluster during the installation, they are permitted to select the management NIC of the current node, however, the NIC name is fixed and has to be consistent across all nodes once that was set by the first management node.

RKE2 canal config:
```
local:/home/rancher # kubectl get configmap -n kube-system rke2-canal-config -o yaml
apiVersion: v1
data:
  canal_iface: eth0
```

![image](https://user-images.githubusercontent.com/4569037/133014343-3bb9531d-e382-427f-91e4-8f7926bc0267.png)

**Expected behavior**
The management NIC is not configurable and should be consistent across all nodes. A proper solution is to create a bond NIC on each node using a same name.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by yaocw2020** [comment] 2021-09-13 02:41
Error logs are following.
```
wj-preview1:/home/rancher # kubectl logs -f -n kube-system rke2-canal-9nrnl kube-flannel
I0913 02:39:12.906317       1 main.go:212] Could not find valid interface matching eth0: error looking up interface eth0: route ip+net: no such network interface
E0913 02:39:12.906375       1 main.go:236] Failed to find interface to use that matches the interfaces and/or regexes provided
```

**Comment by yasker** [comment] 2021-09-13 03:15
This might be a major issue since we will require the mgmt NICs to be identical across the node. We at least need to document this behavior.

**Comment by guangbochen** [comment] 2021-09-13 08:40
The Harvester is defaulting to use `canal` and it is configurable via `--iface="": `
- interface to use (IP or name) for inter-host communication. Defaults to the interface for the default route on the machine. This can be specified multiple times to check each option in order. Returns the first match found.

**Comment by yaocw2020** [comment] 2021-09-13 09:47
Additionally, the VIP should be modified to support the default route if we want to support it. Currently, the VIP NIC is set to use the first default management NIC name.
I created the feature issue in the kube-vip repo to support the default VIP interface.

https://github.com/kube-vip/kube-vip/issues/273

**Comment by yaocw2020** [comment] 2021-09-14 00:30
It is reasonable to set the management NIC as the interface for the default route to make the network connectivity stable between nodes and pods. That is very basic for the Kubernetes.  Under this premise，it can be well to default the interface for the canal according to the default route on the machine.

**Comment by yasker** [comment] 2021-09-15 00:22
The problem pointed out by @bk201 is the default route is probably not set by Harvester. It can be set by the DHCP server.

**Comment by yaocw2020** [comment] 2021-09-15 09:15
The solution is to create a bond device with a fixed name for the management network. And configure this bond device as the canal interface.

**Comment by yaocw2020** [comment] 2021-09-15 09:19
> The problem pointed out by @bk201 is the default route is probably not set by Harvester. It can be set by the DHCP server.

We confirm that wicked can decide which interface is the default route device in the DHCP mode by adding `Set DHCLIENT_SET_DEFAULT_ROUTE='yes'` to the network configuration file.

**Comment by bk201** [comment] 2021-09-15 09:32
`DHCLIENT_SET_DEFAULT_ROUTE='yes'` is the default setting for all interfaces (in `/etc/sysconfig/network/dhcp`).
So the OS will apply the default gateway offered by DHCP server. The problem is when there are multiple DHCP servers and more than one of the servers offers a default gateway, we are not sure which one will be used. (`DHCLIENT_ROUTE_PRIORITY` can be set on per-interface config).

Moving to a common-name bonding device should work, we are working toward this direction.

**Comment by yaocw2020** [comment] 2021-09-15 10:03
> `DHCLIENT_SET_DEFAULT_ROUTE='yes'` is the default setting for all interfaces (in `/etc/sysconfig/network/dhcp`).
> So the OS will apply the default gateway offered by DHCP server. The problem is when there are multiple DHCP servers and more than one of the servers offers a default gateway, we are not sure which one will be used. (`DHCLIENT_ROUTE_PRIORITY` can be set on per-interface config).
> 
> Moving to a common-name bonding device should work, we are working toward this direction.

No matter which gateway is configured if there are multiple DHCP servers, the network connectivity around different nodes and pods will be fine. The key task is to keep the default route device fixed. Assume that there are multiple NICs in different VLAN networks, the pods that depend on the default routes to communicate with the apiserver will not work if the device of the default route changes.

**Comment by yaocw2020** [comment] 2021-09-18 10:30
When configuring management bond, for DHCP mode, we can call the function `getIPThroughDHCP` to get the IP and use the netlink package to configure the IP and route, rather than using wicked reload command which is too slow. Wicked interface configuration is still required. @weihanglo

**Comment by lanfon72** [comment] 2021-09-30 08:52
> Expected behavior
The management NIC is not configurable and should be consistent across all nodes. A proper solution is to create a bond NIC on each node using a same name.

Verified a bond NIC named `harvester-mgmt` is created and used as the management NIC.
It could be configured in ISO install as below:
![image](https://user-images.githubusercontent.com/5169694/135418352-8fb29806-e80a-4974-8522-0152a7c65952.png)

and in PXE install, use configure options as below:
```
  networks:
    harvester-mgmt:       # The management bond name. This is mandatory.
      interfaces:
      - name: ens49
      default_route: true
      method: dhcp
      bond_option:
        mode: balance-rr
```
advanced configure options available in [document](https://docs.harvesterhci.io/v0.3-dev/install/harvester-configuration/#installnetworks)

Test Information
----
* Environment: **Bare mental DL360** secondary nodes
* Harvester Version: **v0.3.0-rc1**
### Verify Steps:
  1. Install havester
     - for ISO installation, select at least one NIC port for the management NIC
     - for PXE Boot installation, follow the [document](https://docs.harvesterhci.io/v0.3-dev/install/harvester-configuration/#installnetworks) to configure management NIC
  2. use `ip a show harvester-mgmt` to check bonded NIC is exists
  3. check `/etc/sysconfig/network/ifcfg-harvester-mgmt`'s content
     - selected NIC port should be listed in the option `BONDING_SLAVE`
     - selected bond mode should be listed in the option `BONDING_MODULE_OPTS=`

**Closed as completed by lanfon72** 2021-09-30 08:52 UTC
Labels: kind/bug, area/installer, priority/0, blocker
