### ISSUE TITLE
[Question] How do I change host IP, and host network from DHCP to static?

### ISSUE THREAD

**Issue by averyfreeman** [harvester/harvester#3103] opened 2022-11-04 01:33 UTC
I am getting an error on my `hosts` screen:

```
Host IP is inconsistent, current IP: 10.0.0.41,2601:603:4d01:7fb0:77c1:6140:c24c:3d63, initial IP: 10.0.0.41
```

The hosts all have reservations, I am using AD.  I thought I'd change the hosts from having DHCP to static addresses, and change one host's IP address.

How do I do this?  I tried with one host by editing 

```
# /etc/sysconfig/network/ifcfg-mgmt-br

BOOTPROTO='static'
IPADDRESS='10.0.0.43'
NETMASK='255.255.255.0'
```

If I restarted the network, ala `systemctl restart network`, and checked `wicked ifstatus mgmt-br`, it appeared that the changes were propagated.

However, once I restarted the node, it was back to the original DHCP configuration, with the old IP address.  

Note: I removed the DHCP lease and reservation from AD DHCP server and set up a static IP in AD DNS server for the new IP address I wanted the host to have BEFORE restarting the Harvester node I was trying to change.

What is the correct way to change the IP address and from DHCP to static in Harvester config?

**Comment by ibrokethecloud** [comment] 2022-11-04 05:29
duplicate of https://github.com/harvester/harvester/issues/2962

Please refer to work around: https://github.com/harvester/harvester/issues/2962#issuecomment-1281385465

Fix will be available v1.1.1

**Comment by averyfreeman** [comment] 2022-11-04 06:44
OK cool, thanks for the reference, I appreciate it.

edit: @ibrokethecloud this doesn't address my question, the bug is inconsequential

**How do you change the node IP?  or change mgmt-br from DHCP to static?**

I tried `wicked` (bc, SUSE) and it did not work.

If you help me figure it out, I'll contribute to the docs 😊 This should definitely be documented.

**Closed as completed** 2022-11-05 05:29 UTC
Labels: kind/question

**Comment by ibrokethecloud** [comment] 2022-11-06 22:32
If the plan is to change IP addresses of the node, then it is likely to cause issues since the node is likely to show up as another in the cluster. In this case the easier option would be to delete the node from cluster, and add it back into the cluster with static address specified.

If you only wish to move the ip allocation from dhcp to static while retaining the address, then the change will be needed in /oem/99_custom.yaml

The interface definition will be available there, and will need to be changed, and node rebooted to change node to use static addressing.

```
    - path: /etc/sysconfig/network/ifcfg-mgmt-br
      permissions: 384
      owner: 0
      group: 0
      content: |+
        STARTMODE='onboot'
        BOOTPROTO='dhcp'
        BRIDGE='yes'
        BRIDGE_STP='off'
        BRIDGE_FORWARDDELAY='0'
        BRIDGE_PORTS='mgmt-bo'
        PRE_UP_SCRIPT="wicked:setup_bridge.sh"
        POST_UP_SCRIPT="wicked:setup_bridge.sh"

        DHCLIENT_SET_DEFAULT_ROUTE='yes'

      encoding: ""
      ownerstring: ""
```
