### ISSUE TITLE
[BUG] cluster member can create namespace, but has no access to view it after creation

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2309] opened 2022-05-24 08:56 UTC
**Describe the bug**

cluster member can create namespace, but has no access to view it after creation， 

**To Reproduce**
1. create a user, choose `Standard User`
2. assign a harvester cluster to the new user and select cluster member
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/2e9a1179-b02d-40a1-9f72-78d06a1436e4)
3. login with this user and go to the harvester cluster
4. at this point you can only see the resources in the harvester-public namespace, and you cannot edit them (as expected)
5. go to `Project/Namespace` page, and create a project (cluster-member-project)
6. Create a namespace (cluster-member-namespace) in the cluster-member-project
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/1020ff81-f00c-44c2-b654-75ddc5f1e790)
7. at this point the user can create resources under cluster-member-namespace
  - Problem 1: The `Create` button is not displayed in the volume page  (backend issue)
  - Problem 2: Users should not create resources in the `harvester-public` namespace, but the image creation page can select `harvester-public`   (UI issue)
  ![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/916b38c6-58f4-4f5c-8778-8afb3f017200)
8. go to Project/Namespace page,  Create a namespace that does not belong to any Project  （such as test-no-namespace）

9.  refresh page,  This user does not have permission to view test-no-namespace  （backend issue）
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/8eefe242-e0fb-4472-bee3-b11faffe4a80)

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment] 2022-07-05 08:36
1. 
> * Problem 1: The `Create` button is not displayed in the volume page (backend issue)

![image](https://user-images.githubusercontent.com/15064560/177279767-e64daf6f-d8ae-4f80-9379-76b0b48cbcdd.png)

unable to reproduce, user can see the `Create` button in the volume page

---
2. 

> refresh page, This user does not have permission to view test-no-namespace （backend issue）

even if it's not a Harvester cluster, it has the same behavior, so I'm not sure if this is the behavior that Rancher itself expects

Since Rancher permissions are configured according to project, a namespace that is not associated with a project should be invisible to the standard user.

harvester-public is visible because Harvester does something special.

cc @guangbochen

**Comment by TachunLin** [comment] 2022-07-15 10:24
Try to reproduce the issues on master-8f01b558-head (7/14). 

For the three problems highlighted in this issue. 

- Problem 1: The `Create` button is not displayed on the image and volume page while already having project namespace assigned to the cluster member use 
- Problem 2: Users should not create resources in the harvester-public namespace, but the image creation page can select harvester-public  -> `This would be the current design`
- Problem 3: Create a namespace that does not belong to any Project and refresh page, this user does not have permission to view test-no-namespace -> `This would be the expected behavior`

Problem 1 `can't be reproduced`, when a cluster member privilege user have assigned the project and namespace
This user can see create button on the volume and image page 
  ![image](https://user-images.githubusercontent.com/29251855/179202853-90efcb88-360a-4a50-bc08-dfc911d8fc16.png)
  ![image](https://user-images.githubusercontent.com/29251855/179202906-fa86f8e0-09cb-4528-89c1-d14899981743.png)
  ![image](https://user-images.githubusercontent.com/29251855/179202954-1e67dd9f-a110-4db5-bdac-9dc2160446fa.png)


Since the only problem here can't be reproduced, thus close this issue.

**Closed as completed by TachunLin** 2022-07-15 10:24 UTC
Labels: kind/bug, area/control-plane, priority/0, area/multi-tenancy
