### ISSUE TITLE
[BUG] can not config storage network through UI settings

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5741] opened 2024-05-06 10:28 UTC
**Describe the bug**
On v1.3.0 with witness node, we can not config the storage network through UI

**To Reproduce**
1. create 3 node cluster, 2 management, 1 witness
2. create cluster network (use the workaround mentioned here [[BUG] Unable to select NIC to create network config when cluster contains witness node](https://github.com/harvester/harvester/issues/5325#top)
![cluster_network_status](https://github.com/harvester/harvester/assets/1615081/8f1e038f-9165-49aa-912e-1e714cbc27fb)
3. try to create storage network but the cluster network is shown `not ready`
![cluster_network_not_ready](https://github.com/harvester/harvester/assets/1615081/81d46dba-d8c7-4e0e-93b5-add1ccc6c5d7)

**Expected behavior**
Can create storage network as usual

**Support bundle**
No need

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
We can directly update the storage network by following command
```
kubectl patch settings storage-network --type='json' -p='[{"op": "add", "path": "/value", "value": "{\"clusterNetwork\":\"<cluster network name>\",\"vlan\":<vlan id>,\"range\":\"<ip range>\"}"}]'
```

**Comment by a110605** [comment] 2024-05-21 09:22
The issue can also be reproduced in 1 witness node + 1 management node 
![aa](https://github.com/harvester/harvester/assets/5744158/87652ab3-6ed4-482d-8980-a04986cd8690)

**Comment by a110605** [comment] 2024-05-22 07:30
> The issue can also be reproduced in 1 witness node + 1 management node ![aa](https://private-user-images.githubusercontent.com/5744158/332364797-87652ab3-6ed4-482d-8980-a04986cd8690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjI3MjMsIm5iZiI6MTcxNjM2MjQyMywicGF0aCI6Ii81NzQ0MTU4LzMzMjM2NDc5Ny04NzY1MmFiMy02ZWQ0LTQ4MmQtODk4MC1hMDQ5ODZjZDg2OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDcyMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FhMzRiYTg2YmYxOWJiZmUyYjY3MjdiZTM1ZjBmMzk2OTY5ZmEyMDMxYTExMzgxOTZjNTI3ZDg1NjdiMDhhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.36cJZbhAFBvqq7HDLn6hLIqgQPmj8J9LRNtupod0lXI)

In above screenshot, my new created cluster network `test-network` only have 1 harvester-node-0 vlan and it marked as `disabled` due to [isReadyForStorageNetwork = false](https://github.com/harvester/dashboard/blob/cc05d263b1f5ecde6951dfb3ba371a20a6b1d14d/pkg/harvester/components/settings/storage-network.vue#L93-L98).


The reason why it got `isReadyForStorageNetwork = false` is the [isReadyForStorageNetwork()](https://github.com/harvester/dashboard/blob/cc05d263b1f5ecde6951dfb3ba371a20a6b1d14d/pkg/harvester/models/network.harvesterhci.io.clusternetwork.js#L60-L65) got only one [vlanstatuses](https://github.com/harvester/dashboard/blob/cc05d263b1f5ecde6951dfb3ba371a20a6b1d14d/pkg/harvester/models/network.harvesterhci.io.clusternetwork.js#L50), but got two `this.nodes`  (harvester-node-0 and harvester-node-1) from API
```
https://localhost:8006/v1/harvester/network.harvesterhci.io.vlanstatuses 
```

cc @torchiaf , @bk201 

See below screenshots
![vlanstatuses](https://github.com/harvester/harvester/assets/5744158/55652939-0e09-4c6a-ae48-780b4a8814b5)
![2](https://github.com/harvester/harvester/assets/5744158/6c1a4993-e663-4108-917e-0a92f03c91dd)

**Comment by a110605** [comment] 2024-05-22 10:26
After discussed with @Vicente-Cheng , we should filter out `witness node` by checking `metadata.labels['node-role.harvesterhci.io/witness]` not equals 'true' in the case.

**Comment by lanfon72** [comment] 2024-07-02 18:38
stuck in creating cluster network as https://github.com/harvester/harvester/issues/5325#issuecomment-2204040239

**Comment by lanfon72** [comment] 2024-07-03 14:07
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 2 nodes (1 witness)**
* Harvester Version: **master-25937fe-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes having 1 witness
2. Login to dashboard, Create cluster network and config
4. Enable storage network with the created cluster network
5. Storage network should created and operating successfully

**Closed as completed by lanfon72** 2024-07-03 14:07 UTC
Labels: kind/bug, priority/1, reproduce/always, require/severity, backport-needed/1.3.1
