### ISSUE TITLE
ceph support

### ISSUE THREAD

**Issue by showsmall** [harvester/harvester#887] opened 2021-05-20 10:05 UTC
Does it support distributed storage ceph?
Is there a configuration document for docking with ceph?

**Comment by yaocw2020** [comment] 2021-05-20 10:07
Currently no.

**Comment by showsmall** [comment] 2021-05-20 10:27
Very much looking forward to supporting ceph.

**Comment by guangbochen** [comment] 2021-05-20 14:44
close as duplicate of https://github.com/harvester/harvester/issues/888

**Closed as completed by guangbochen** 2021-05-20 14:44 UTC
Labels: kind/question
