### ISSUE TITLE
[BUG] An Off VM in v1.3.2 with backup can not be restore replace after upgrade to v1.4.0-rc4

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6895] opened 2024-10-27 17:20 UTC
**Describe the bug**
![image](https://github.com/user-attachments/assets/c8206d93-eade-465b-9aaf-26d0b925030d)

**To Reproduce**
1. Setup single node Harvester `v1.3.2`
2. Create 2 VMs _vm-running_ and _vm-stopped_
3. Stop _vm-stopped_
4. Take VM Backup on both VM
   ![image](https://github.com/user-attachments/assets/6904cf91-447a-46f9-9872-c7b3afb5f30a)
5. Upgrade Harvester to `v1.4.0-rc4`
6. For now all VMs are `Off`, manually start _vm-running_
7. Restore backup _vm-stopped_
   * Restore Replace: VM stucking in `Restoring` and VirtualMachine status is still `Stopped`
   * Restore New: Successfully restored
   ![image](https://github.com/user-attachments/assets/b09c8c0c-b98a-43f7-b34e-ce68f24aa1be)

**Expected behavior**
Should be able to restore a VM no matter what its status when trigging upgrade 

**Support bundle**
[supportbundle_StuckRestoringAnOffVMBeforeUpgrade.zip](https://github.com/user-attachments/files/17534796/supportbundle_StuckRestoringAnOffVMBeforeUpgrade.zip)

**Environment**
 - Harvester ISO version: `v1.3.2` => `v1.4.0-rc4` single node
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): single node QEMU/KVM

**Additional context**
1. Can reproduce on both local QEMU/KVM and Bare-metal HPE ProLiant DL360
2. The original `Running` VM does not hit this problem

**Comment by FrankYang0529** [comment] 2024-10-28 06:52
The root cause is that when we try to start vm, its `runStrategy` is `RerunOnFailure`, but related VMI is not existent. From the source code, we do nothing in this case.

 We should fix it by sending a start request if VMI is not found.

https://github.com/harvester/harvester/blob/19bc22db86ec0c9d796ec1d9116c3ddce908082a/pkg/controller/master/backup/restore.go#L914-L938

**Comment by khushboo-rancher** [comment] 2024-10-28 17:45
Moved it back to review as the PR is not merged yet.

**Comment by FrankYang0529** [comment] 2024-10-29 02:11
> Moved it back to review as the PR is not merged yet.

Thanks for updating it. I intended to move to review, but not sure why it's in ready for testing 😅.

**Comment by noahgildersleeve** [comment] 2024-11-05 17:44
Tested with upgrade from `v1.3.2` -> `v1.4-daf68d56-head` on 3 node libvirt ipxe-examples cluster. Validated that restore worked after upgrade with below steps. Validated as fixed.

> **Describe the bug** ![image](https://private-user-images.githubusercontent.com/2773781/380515817-c8206d93-eade-465b-9aaf-26d0b925030d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTc4NjgsIm5iZiI6MTczMDc1NzU2OCwicGF0aCI6Ii8yNzczNzgxLzM4MDUxNTgxNy1jODIwNmQ5My1lYWRlLTQ2NWItOWFhZi0yNmQwYjkyNTAzMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMjE1OTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ0MTA5ZjYxMDIzYjBiNDcyYTkxMTliNjkyMDU5NmQyZTc5YWI2NGNkYWQ4OTBjOGIwODk4ZDQzNmMyZTFiMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FqfwfyjbCuBa4ejlUwKuEIQB4cTYINr45scKO4hBpxY)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Setup single node Harvester `v1.3.2`
> 2. Create 2 VMs _vm-running_ and _vm-stopped_
> 3. Stop _vm-stopped_
> 4. Take VM Backup on both VM
>    ![image](https://private-user-images.githubusercontent.com/2773781/380516287-6904cf91-447a-46f9-9872-c7b3afb5f30a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTc4NjgsIm5iZiI6MTczMDc1NzU2OCwicGF0aCI6Ii8yNzczNzgxLzM4MDUxNjI4Ny02OTA0Y2Y5MS00NDdhLTQ2ZjktOTg3Mi1jN2IzYWZiNWYzMGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMjE1OTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzIwZTg4OTU2OTc0ZDBmNzM4M2E2MzY4MjQwNGUwNjYwMDZiMDhmYjE4ODYwNmIzNTg1NzM2NDI3MmJmMTcxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Xhu_78s_hTPMtWCBCclsHk8VMH5Lcg60wq2ptBEjEXw)
> 5. Upgrade Harvester to `v1.4.0-rc4`
> 6. For now all VMs are `Off`, manually start _vm-running_
> 7. Restore backup _vm-stopped_
>    
>    * Restore Replace: VM stucking in `Restoring` and VirtualMachine status is still `Stopped`
>    * Restore New: Successfully restored
>      ![image](https://private-user-images.githubusercontent.com/2773781/380516540-b09c8c0c-b98a-43f7-b34e-ce68f24aa1be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NTc4NjgsIm5iZiI6MTczMDc1NzU2OCwicGF0aCI6Ii8yNzczNzgxLzM4MDUxNjU0MC1iMDljOGMwYy1iOThhLTQzZjctYjM0ZS1jZTY4ZjI0YWExYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDRUMjE1OTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJlY2IwNWFiZDUyNzhkNWVmNjAyNDFmOWZjNjAxMjQ5MjMwZWRiN2VlMjg4YmYwOTcxYTY4YmRkYWMwZmQ3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6VEqQDuoiIcJz6F2uBZ8WO8Hzp4BXid0a6b3Xy6xwVM)
> 
> **Expected behavior** Should be able to restore a VM no matter what its status when trigging upgrade
> 
> **Support bundle** [supportbundle_StuckRestoringAnOffVMBeforeUpgrade.zip](https://github.com/user-attachments/files/17534796/supportbundle_StuckRestoringAnOffVMBeforeUpgrade.zip)
> 
> **Environment**
> 
> * Harvester ISO version: `v1.3.2` => `v1.4.0-rc4` single node
> * Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): single node QEMU/KVM
> 
> **Additional context**
> 
> 1. Can reproduce on both local QEMU/KVM and Bare-metal HPE ProLiant DL360
> 2. The original `Running` VM does not hit this problem

**Closed as completed by noahgildersleeve** 2024-11-05 17:44 UTC
Labels: kind/bug, severity/2, area/install-upgrade, reproduce/always, require/severity, area/vm-backup-restore
