### ISSUE TITLE
[BUG] Cannot create a Namespace inside a Project

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1000] opened 2021-07-05 09:44 UTC
**Describe the bug**
After a fresh install I successfully created a new project called `test-project`. I then had the option to create a new namespace inside that project, so I tried to create on called `test-ns` but I have this error message: `Cannot read property 'id' of undefined`. 

**To Reproduce**
1. Go to `Projects/Namespaces`
2. Click on `Create Project`
3. Set `Name` to `test-project`, click `Create`
4. Click on `Create Namespace` in the new created `test-project` project
5. Set `Name` to `test-ns`, click `Create`
6. You ended with the error message : `Cannot read property 'id' of undefined`

**Expected behavior**
New namespace created? But as the new created project `test-project` is in fact a namespace, is it really possible to create a new namespace inside a namespace?

**Support bundle**
[harvester-supportbundle_e707144b-450c-4130-b3a9-3255c3159c1d_2021-07-05T09-44-23Z.zip](https://github.com/harvester/harvester/files/6763314/harvester-supportbundle_e707144b-450c-4130-b3a9-3255c3159c1d_2021-07-05T09-44-23Z.zip)

**Environment:**
 - Harvester ISO version: master-88f1d22c-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HP ProLiant DL360 Gen9

**Additional context**
None.

**Comment by DaiYuzeng** [comment] 2021-09-07 09:56
Tested in `master-661ee801-head`, i couldn't reproduce this issue. It seems like be fixed.

Could you re-validate it? Thanks!

**Comment by noahgildersleeve** [comment] 2021-09-24 01:30
Closing as N/A anymore per @guangbochen . Tested in version master-1a041d23-head.

**Closed as completed by noahgildersleeve** 2021-09-24 01:30 UTC
Labels: kind/bug, area/ui, area/multi-tenancy
