### ISSUE TITLE
[BUG] Enabling maintenance mode does not support migrating all virtual machines  to the target node.

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#687] opened 2021-04-14 02:07 UTC
**Describe the bug**

Enabling maintenance mode does not support migrating all virtual machines on the node to the target node.
**To Reproduce**
1. Go to the Host list
2. Enable maintenance mode for one of the nodes
![image](https://user-images.githubusercontent.com/15829074/114643427-34703480-9d08-11eb-979f-cfc2ec396c00.png)

**Expected behavior**

Similar to the figure below, this operation supports the migration of all virtual machines on the node to the target node.
![image](https://user-images.githubusercontent.com/15829074/114643725-ced07800-9d08-11eb-90db-fe4bf4c53dd7.png)

**Log**

**Environment:**
 - Harvester ISO version: master-95a5828a-head
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by gitlawr** [comment] 2021-04-14 02:25
Node maintenance is to perform a node eviction and migrate all VMs to other nodes. A target node is not required for this operation. The requirement is specified in https://github.com/rancher/harvester/issues/573.

**Comment by guangbochen** [comment] 2021-04-19 08:21
close as duplicate of https://github.com/rancher/harvester/issues/573

**Closed as completed by guangbochen** 2021-04-19 08:21 UTC
Labels: kind/bug
