### ISSUE TITLE
[FEATURE] Retry on fetching Harvester configuration in PXE boot installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#907] opened 2021-05-28 02:17 UTC
**Is your feature request related to a problem? Please describe.**
The network stack (DHCP process) might be not ready when the installer is run, which causes configuration fetching failure.

**Describe the solution you'd like**
In https://github.com/harvester/harvester/issues/720, we add a workaround in the document to wait for the network stack to ready. We can add a limited-number retry in the installer to avoid using this workaround.

**Describe alternatives you've considered**
An "OS" way to wait for the network stack ready, but it doesn't guarantee the installer can reach the boot file server.

**Additional context**

**Comment by guangyee** [comment] 2021-06-02 17:46
We captured two screenshots from the iLO console. Harvester installer seem to attempt to fetch files before the NICs are ready. Strangely, in some cases the NICs are showing ready by only just gotten v6 IPs.

![harvester_ipxe_ilo_screen_1](https://user-images.githubusercontent.com/1808417/120527905-bc310180-c38f-11eb-9656-95ce3856c4f7.png)
![harvester_ipxe_ilo_screen_2](https://user-images.githubusercontent.com/1808417/120527930-c18e4c00-c38f-11eb-915c-b1ebec5a0dde.png)

**Comment by janeczku** [comment] 2021-06-03 14:29
Reproduced on v0.2.0 (PXE install). Can be worked around by re-starting the installer manually from another terminal session

![thumbnail_image003](https://user-images.githubusercontent.com/3813921/120661433-8d4a8680-c488-11eb-95a9-c1fab2291f18.png)

**Comment by alexdepalex** [comment] 2021-06-03 18:17
Regarding the screenshot above. On the console the message `Checking if the networkis online` is displayed followed by `ok`. At that time, the adapter might be online, but it takes another 10 seconds before an actual dhcp requests goes over the line and reaches the dhcp server. In the meantime, the installer is already started, the network is unreachable and fetching the configuration yaml fails.

The installation process can be restarted by opening another console and running `sudo /usr/bin/start-harvester-console.sh`. This is pretty trivial, but it's not something that scales very well ;)

![rpviewer (31)](https://user-images.githubusercontent.com/713019/120692919-ae22d400-c4a8-11eb-850b-2108ee7bfad7.png)

**Comment by juadk** [comment] 2021-06-03 18:29
That's weird because the workaround from #720 made the problem completely disappear for our environment.

**Comment by alexdepalex** [comment] 2021-06-03 20:16
That's not weird. It just means that the workaround isn't yet included in the online documentation.

**Comment by janeczku** [comment] 2021-06-03 22:37
Nothing weird happening here @juadk. Just goes to show that users are still being affected by this issue.

As an improvement, maybe we should update the docs to include the `boot_cmd` workaround in **all the documented kernel arguments**. This would save users from running into this issue in the first place and having to spend time troubleshooting the failed PXE install.
/cc @guangbochen

**Comment by guangbochen** [comment] 2021-06-09 05:07
This should be addressed via https://github.com/harvester/harvester-installer/pull/87, and u should be able to test via downloading the master build assets.

master-head.iso: https://releases.rancher.com/harvester/master/harvester-amd64.iso
master-initrd: https://releases.rancher.com/harvester/master/harvester-initrd-amd64
master-vmlinuz: https://releases.rancher.com/harvester/master/harvester-vmlinuz-amd64

**Comment by juadk** [comment] 2021-06-09 13:41
Tested successfully in build `master-2f77a633-head` ​with ISO mod and 5 nodes cluster.

With v0.2.0, I was able to reproduce the reported issue by removing the following workaround #720  from the kernel cmd line:
`"boot_cmd=\"echo include_ping_test=yes >> /etc/conf.d/net-online\""`

![Screenshot from 2021-06-09 14-46-27](https://user-images.githubusercontent.com/6025636/121363828-91b6e980-c937-11eb-9057-319200ba12ad.png)
As expected the installation failed because the network stack was not ready.

Then, I tried the last master build assets (`master-2f77a633-head`):
![Screenshot from 2021-06-09 15-34-00](https://user-images.githubusercontent.com/6025636/121364741-57018100-c938-11eb-9100-42df4868600e.png)
We can see on the screenshot that the first try failed and a retry happened 10 seconds after, and finally, the installer was able to download files.
I'm closing the issue, @janeczku @alexdepalex @guangyee , if you have the time, it could be valuable if you could validate it too. Feel free to reopen the issue if needed.

**Comment by juadk** [comment] 2021-06-16 07:16
We have to remove the workaround (https://github.com/harvester/docs/blob/main/docs/install/pxe-boot-install.md - Troubleshooting section) from the documentation for the 0.3.0 release.

**Comment by juadk** [comment] 2021-06-23 13:51
Doc updated on the v0.3-dev branch

**Closed as completed by juadk** 2021-06-23 13:51 UTC
Labels: kind/enhancement, area/installer
