### ISSUE TITLE
Update support links

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1278] opened 2021-09-26 04:25 UTC
The support links are referring to the Rancher docs/issues, etc. Change to Harvester links.

**To Reproduce**
1. Click `Support` in the bottom-left corner.
2. Check the links in `Community Support`

**Environment:**
 - Harvester ISO version: master-48c97ea7-head

**Comment by guangbochen** [comment] 2021-09-28 07:14
duplicate of https://github.com/harvester/harvester/issues/1300, close as that one is more detailed.

**Closed as completed by guangbochen** 2021-09-28 07:14 UTC
Labels: kind/bug, area/ui, priority/0
