### ISSUE TITLE
[BUG] Display for node in ready status sometimes doesn't clear

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1672] opened 2021-12-13 20:19 UTC
**Describe the bug**

Some nodes will have text that wasn't cleared when going to ready status. This seems to be intermittent
**To Reproduce**
1. Deploy 4 node Harvester setup
2. Check display of all nodes after install and going to ready
**Expected behavior**

**Support bundle**

[supportbundle_f765ca68-2e41-4020-acd8-9de651f15648_2021-12-13T20-15-36Z.zip](https://github.com/harvester/harvester/files/7706723/supportbundle_f765ca68-2e41-4020-acd8-9de651f15648_2021-12-13T20-15-36Z.zip)

**Environment:**
 - Harvester ISO version: master-5d739671-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
This seems to be intermittent and I only saw it on one of my 4 nodes.

![Greenshot_2021-12-13_11_54_20](https://user-images.githubusercontent.com/83787952/145882341-d2c12044-0f3e-487c-aa5f-cd75d0a696f6.jpg)

**Comment by guangbochen** [comment] 2021-12-14 03:10
duplicate of https://github.com/harvester/harvester/issues/1132 and aims to get fixed on the next `v1.0.1` release, also just press `F12` to login and logout again will clear those systemd messages.

**Closed as completed by guangbochen** 2021-12-14 03:10 UTC
Labels: kind/bug
