### ISSUE TITLE
[BUG] Some unexpected 404 requests occurred while creating the image

### ISSUE THREAD

**Issue by aiwantaozi** [harvester/harvester#1857] opened 2022-01-23 13:53 UTC
**Describe the bug**
Some unexpected 404 requests occurred while creating the image

**To Reproduce**

1. when creating 20 virtualmachineimages at the same time, get lots of 404 request
```
// psql
sum(rate(apiserver_request_total{group=~".*harvester.*", verb=~"LIST|GET|WATCH"}[5m])) by (code, resource, group)
```
<img width="999" alt="截屏2022-01-23 下午9 46 27" src="https://user-images.githubusercontent.com/5936271/150681539-ff10cf2a-d797-4287-8f02-f97b3472c238.png">

2. enabled audit log for apiserver to check what happen

add configuration to kube-apiserver in harvester-installer, for example https://github.com/aiwantaozi/harvester-installer/commit/d5cccac783706b6905e53e593619b77238578016

3. update harvester-installer address in harvester project for test

```
// harvester/harvester/scripts/build-iso

HARVESTER_INSTALLER_VERSION=test

git clone --branch ${HARVESTER_INSTALLER_VERSION} --single-branch --depth 1 https://github.com/aiwantaozi/harvester-installer.git ../harvester-installer
```

4. build iso, run in harvester project 
```
make build-iso
```

5. get built iso and use it to create a virtualmachine

6. then follow the step to start harvester

7. after harvester started, login and keep the UI opening

8. create am image 
```
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  name: image-gd8xx
  namespace: default
spec:
  checksum: ""
  displayName: ubuntu-18.04-server-cloudimg-amd64.img
  pvcName: ""
  pvcNamespace: ""
  sourceType: download
  url: http://172.16.4.20/os-images/ubuntu-18.04-server-cloudimg-amd64.img
```

9. check the audit log from kube-apiserver container
```
cat /var/log/kube-audit/audit-log.json | grep image-gd8xx | grep 'code":404'
```

10. find some unexpected 404 requests occurred while creating the image
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"4d5cc9c0-9f04-453c-a786-813ef3052572","stage":"ResponseComplete","requestURI":"/api/v1/namespaces/default-image-gd8xx?includeObject=Object","verb":"get","user":{"username":"system:serviceaccount:harvester-system:harvester","uid":"91389acc-4abd-40f7-a5ed-8b5332d1416b","groups":["system:serviceaccounts","system:serviceaccounts:harvester-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["harvester-75b8486758-qkkf8"],"authentication.kubernetes.io/pod-uid":["567996a5-3b97-4066-ab95-246bf5bca29c"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.26"],"userAgent":"harvester/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"namespaces","namespace":"default-image-gd8xx","name":"default-image-gd8xx","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.707219Z","stageTimestamp":"2022-01-23T13:11:48.713198Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"3c5990c7-22a0-45e5-991c-da9cccbd5e1c","stage":"ResponseComplete","requestURI":"/apis/harvesterhci.io/v1beta1/settings/default-image-gd8xx?includeObject=Object","verb":"get","user":{"username":"system:serviceaccount:harvester-system:harvester","uid":"91389acc-4abd-40f7-a5ed-8b5332d1416b","groups":["system:serviceaccounts","system:serviceaccounts:harvester-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["harvester-75b8486758-qkkf8"],"authentication.kubernetes.io/pod-uid":["567996a5-3b97-4066-ab95-246bf5bca29c"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.26"],"userAgent":"harvester/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"settings","name":"default-image-gd8xx","apiGroup":"harvesterhci.io","apiVersion":"v1beta1"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.707162Z","stageTimestamp":"2022-01-23T13:11:48.713559Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"ee47c777-24f7-4d3e-998e-0734d571689e","stage":"ResponseComplete","requestURI":"/api/v1/namespaces/default-image-gd8xx?includeObject=Object\u0026timeout=15m0s","verb":"get","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"68bceada-9e5a-41d9-8ea8-30297964b194","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-686b894578-fft9l"],"authentication.kubernetes.io/pod-uid":["3583c99c-f786-4fbe-8f3b-f17b49807546"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.59"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"namespaces","namespace":"default-image-gd8xx","name":"default-image-gd8xx","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.741272Z","stageTimestamp":"2022-01-23T13:11:48.744424Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"ba2d68df-8ed4-4433-9a7b-04548f580519","stage":"ResponseComplete","requestURI":"/apis/management.cattle.io/v3/clusters/default-image-gd8xx?includeObject=Object\u0026timeout=15m0s","verb":"get","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"68bceada-9e5a-41d9-8ea8-30297964b194","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-686b894578-fft9l"],"authentication.kubernetes.io/pod-uid":["3583c99c-f786-4fbe-8f3b-f17b49807546"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.59"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"clusters","name":"default-image-gd8xx","apiGroup":"management.cattle.io","apiVersion":"v3"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.740246Z","stageTimestamp":"2022-01-23T13:11:48.744680Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"2ed7cad1-b941-4b45-9b0e-bcc446ed3cef","stage":"ResponseComplete","requestURI":"/apis/management.cattle.io/v3/clusters/default-image-gd8xx?includeObject=Object\u0026timeout=15m0s","verb":"get","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"68bceada-9e5a-41d9-8ea8-30297964b194","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-686b894578-fft9l"],"authentication.kubernetes.io/pod-uid":["3583c99c-f786-4fbe-8f3b-f17b49807546"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.59"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"clusters","name":"default-image-gd8xx","apiGroup":"management.cattle.io","apiVersion":"v3"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.742583Z","stageTimestamp":"2022-01-23T13:11:48.745508Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"588db4b8-5618-4a50-a194-8e916c293ad2","stage":"ResponseComplete","requestURI":"/apis/management.cattle.io/v3/settings/default-image-gd8xx?includeObject=Object\u0026timeout=15m0s","verb":"get","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"68bceada-9e5a-41d9-8ea8-30297964b194","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-686b894578-fft9l"],"authentication.kubernetes.io/pod-uid":["3583c99c-f786-4fbe-8f3b-f17b49807546"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.59"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"settings","name":"default-image-gd8xx","apiGroup":"management.cattle.io","apiVersion":"v3"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.740193Z","stageTimestamp":"2022-01-23T13:11:48.746722Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"f9ad0d23-4746-4270-bb17-c22cce21b7b8","stage":"ResponseComplete","requestURI":"/apis/management.cattle.io/v3/fleetworkspaces/default-image-gd8xx?includeObject=Object\u0026timeout=15m0s","verb":"get","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"68bceada-9e5a-41d9-8ea8-30297964b194","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-686b894578-fft9l"],"authentication.kubernetes.io/pod-uid":["3583c99c-f786-4fbe-8f3b-f17b49807546"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.59"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"fleetworkspaces","name":"default-image-gd8xx","apiGroup":"management.cattle.io","apiVersion":"v3"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.746609Z","stageTimestamp":"2022-01-23T13:11:48.749078Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Metadata","auditID":"8d3447a1-5dc1-4503-9ccb-335142546935","stage":"ResponseComplete","requestURI":"/apis/management.cattle.io/v3/features/default-image-gd8xx?includeObject=Object\u0026timeout=15m0s","verb":"get","user":{"username":"system:serviceaccount:cattle-system:rancher","uid":"68bceada-9e5a-41d9-8ea8-30297964b194","groups":["system:serviceaccounts","system:serviceaccounts:cattle-system","system:authenticated"],"extra":{"authentication.kubernetes.io/pod-name":["rancher-686b894578-fft9l"],"authentication.kubernetes.io/pod-uid":["3583c99c-f786-4fbe-8f3b-f17b49807546"]}},"impersonatedUser":{"username":"user-x9n69","groups":["system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["local://user-x9n69"],"username":["admin"]}},"sourceIPs":["10.52.0.59"],"userAgent":"rancher/v0.0.0 (linux/amd64) kubernetes/$Format","objectRef":{"resource":"features","name":"default-image-gd8xx","apiGroup":"management.cattle.io","apiVersion":"v3"},"responseStatus":{"metadata":{},"code":404},"requestReceivedTimestamp":"2022-01-23T13:11:48.746780Z","stageTimestamp":"2022-01-23T13:11:48.751145Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"default-admin-n5f69\" of ClusterRole \"cluster-admin\" to User \"user-x9n69\""}}
```

11. kube-apiserver audit log shows that harvester request these resources with id default-image-gd8xx, default-image-gd8xx is the name for the resource `backingimages.longhorn.io` and `backingimagedatasources.longhorn.io`
```
"/api/v1/namespaces/default-image-gd8xx?includeObject=Object"
"/apis/harvesterhci.io/v1beta1/settings/default-image-gd8xx?includeObject=Object"
"/api/v1/namespaces/default-image-gd8xx?includeObject=Object&timeout=15m0s"
"/apis/management.cattle.io/v3/clusters/default-image-gd8xx?includeObject=Object&timeout=15m0s"
"/apis/management.cattle.io/v3/clusters/default-image-gd8xx?includeObject=Object&timeout=15m0s"
"/apis/management.cattle.io/v3/settings/default-image-gd8xx?includeObject=Object&timeout=15m0s"
"/apis/management.cattle.io/v3/fleetworkspaces/default-image-gd8xx?includeObject=Object&timeout=15m0s"
"/apis/management.cattle.io/v3/features/default-image-gd8xx?includeObject=Object&timeout=15m0s"
```

12. check websocket, subscribe resource are same as the resource harvester requested and got 404
<img width="840" alt="截屏2022-01-23 下午11 20 26" src="https://user-images.githubusercontent.com/5936271/150685692-917c4201-48f1-4496-b9c2-dc68e0af5185.png">

13. The 404 request is triggered [here](https://github.com/rancher/steve/blob/e7119828b8f9a9ca2cb2620ba650bd0508ca463e/pkg/stores/proxy/proxy_store.go#L315), the 404 response because mismatch the id and resource kind, the function `OnInboundRelationshipChange` return wrong result.

14. while the websocket subscribe to the change for this resource, websocket should receive an event at these time:
- when this resource is created/updated/deleted
- when this resource relative resource is changed, for example, ws watch resource virtualmachineimage, and virtualmachineimage Image1 is the owner of keypair key1, when key1 changed, ws should receive a virtualmachineimage`resource.change` event. Base on the Framework [steve](https://github.com/rancher/steve/blob/e7119828b8f9a9ca2cb2620ba650bd0508ca463e/pkg/summarycache/summarycache.go#L71)

14. Based on No. 13, we create a keypair, set the owner to virutualmachineimage, and open harvester UI, go to page virtualmachineimage, so the websocket should watch resource virtualmachineimage. Now apply the yaml by kubectl, and check whether ws receive virtualmachineimage event. Finally, I don't get the expected virtualmachineimage event and the audit log begin to show 404 response.
```
apiVersion: harvesterhci.io/v1beta1
kind: KeyPair
metadata:
  name: test6
  namespace: default
  ownerReferences:
  - apiVersion: harvesterhci.io/v1beta1
    kind: VirtualMachineImage
    name: test4-image
    uid: fb31efb6-4744-44b8-b19f-dad9fe01f202
spec:
  publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDi87qzZV3YU1XkwQmr6tw66NguxAdrVemk/U3OOc7y/JNiFpRMHyNzXIArFVPhtqRWQtt6+zjgHA+1uoCDfmVDFrI2oOe8AlesRHCyQEC8tLBfEY8hTdOSNRvBE3Znpmq9rj/u48cpBOf4oyZqMI18BWFCwigYVWs6Ulcst0MR/QeuNOrC0tLS9eGjG0g7+RN/Im2VQKA0NW20YvrapvUXuSroM+Zcsk704RaIXaBb5Q==
    test.test@gmail.com
```
**Expected behavior**
OnInboundRelationshipChange should return the correct relative objects, when we create a virtualmachineImage, should not request namespace, setting, cluster etc.

**Support bundle**

**Environment:**
 - Harvester ISO version: base on https://github.com/harvester/harvester/commit/7cf729c8a9667d51642b036865c1fc1f4e9098c2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): VirtualBox test environment

**Additional context**

**Comment by yasker** [comment] 2022-01-27 23:13
@aiwantaozi The related PR has been merged on the Rancher side. cc @guangbochen

**Comment by guangbochen** [comment] 2022-03-15 08:34
The 404 issues is addressed via https://github.com/harvester/harvester/pull/1896, moving the auditing and monitoring enhancement work to the next milestone because of the library dependency bump issue of https://github.com/longhorn/longhorn/issues/3720.

**Comment by bk201** [comment] 2024-03-21 06:29
@WebberHuang1118 From the history, the issue in the dependencies is fixed. Please help check if the issue is still present.

**Comment by bk201** [comment] 2024-11-19 02:17
Please re-open if seeing the issue again. cc @harvester/qa

**Closed as completed by bk201** 2024-11-19 02:17 UTC
Labels: kind/bug, area/control-plane, priority/2
