### ISSUE TITLE
[BUG] Invalid KubeConfig provided by UI

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1245] opened 2021-09-17 12:59 UTC
**Describe the bug**
The KubeConfig downloaded from UI does not work because its missing the CA certificate information.

Harvster 0.3-preview

**Comment by guangbochen** [comment] 2021-09-17 13:46
duplicate of https://github.com/harvester/harvester/issues/1131 and already fixed by the master-head version

**Closed as completed by guangbochen** 2021-09-17 13:46 UTC
Labels: kind/bug
