### ISSUE TITLE
[BUG] Can't use Secrets to create Cluster Output

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#6427] opened 2024-08-27 15:42 UTC
**To Reproduce**
1. Enable "rancher-logging" addon
2. Create secret. I created secret in the "elk-stack" namespace
3. Go to `Monitoring & Logging -> Logging -> Cluster Output` and click CREATE

**Expected behavior**
I expect that I'll be able to use Secret I created.

**Actual behavior**
1. The "Secret Key" or "Key Id" fields lists entries only from "cattle-logging-system" and I can't use the secret I created in another namespace
2. But I also can't create the secret in the  "cattle-logging-system" namespace, because when I go to SECRETS page - that namespace is hidden there.

**Environment**
 - Harvester 1.3.1

![Screenshot 2024-08-27 at 08 40 27](https://github.com/user-attachments/assets/a8560bbf-4288-4d8d-bbf7-fa93348ce2ba)

**Comment by votdev** [comment] 2024-08-28 10:36
> Expected behavior
> I expect that I'll be able to use Secret I created.

The `Output` must belong to the same namespace as your secret to be visible in the dropdown.

[Example](https://github.com/user-attachments/assets/011a9a01-04b2-4af2-aed5-4f56b4ef91d5)

**Comment by SlavikCA** [comment] 2024-09-02 15:27
@votdev Thank you for the reply.

You response is about `Output`, and looks like it is working, as expected.

My issue is not about `Output`, but about `Cluster Output`.
Currently in Harvester, there is no way to select namespace for `Cluster Output`.

Also, I read some docs here:
https://kube-logging.dev/docs/quickstarts/single/#configure-the-logging-operator

> Note: The control namespace is where the Logging operator deploys the forwarder’s resources, like the StatefulSet and the configuration secrets. Usually it’s called logging.

> By default, this namespace is used to define the cluster-wide resources: SyslogNGClusterOutput, SyslogNGClusterFlow, ClusterOutput, and ClusterFlow. For details, see [Configure log routing](https://kube-logging.dev/docs/configuration/).

It looks like that means, that `Cluster Output` can only use secret from the "control namespace", which is missing in Harvester UI

**Comment by brandboat** [comment] 2024-09-10 11:22
Thanks for reporting this issue, @SlavikCA. This one seems a little bit similar to https://github.com/harvester/harvester/issues/6107, though in different scenario. One possible workaround is use `Edit as YAML` to create secret under `cattle-logging-system` namespace.
![image](https://github.com/user-attachments/assets/59cf226c-6622-4ef1-a9e6-236529762110)

**Comment by brandboat** [comment] 2024-09-11 01:08
Closing this issue as it is a duplicate of https://github.com/harvester/harvester/issues/6107. @SlavikCA, if you have any questions, feel free to reach out, thank you.

**Closed as completed by brandboat** 2024-09-11 01:08 UTC
Labels: kind/bug, require/reproduce, require/severity
