### ISSUE TITLE
need add support for sriov

### ISSUE THREAD

**Issue by tscswcn** [harvester/harvester#1752] opened 2021-12-27 09:32 UTC
**Is your feature request related to a problem? Please describe.**

need add support for sriov because the network  have been with large bandwith

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yaocw2020** [comment] 2021-12-29 09:26
duplicated with https://github.com/harvester/harvester/issues/992

**Comment by yasker** [comment] 2022-02-10 00:27
Close as the duplicate of #992

**Closed as completed by yasker** 2022-02-10 00:27 UTC
Labels: kind/enhancement
