### ISSUE TITLE
[BUG] Agent nodes can't join a cluster

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1243] opened 2021-09-17 03:38 UTC
**Describe the bug**
A new agent node can't join an existing Harvester cluster. Rancherd keeps pulling connection info.

Rancherd logs:
```
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="Bootstrapping Rancher (master-head/v1.21.4-rc1+rke2r4)"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="Writing plan file to /var/lib/rancher/rancherd/plan/plan.json"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="Applying plan with checksum "
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="No image provided, creating empty working directory /var/lib/rancher/rancherd/plan/work/20210916-233656-applied.plan/_0"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="Running command: /usr/bin/env [sh /var/lib/rancher/rancherd/install.sh]"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Using default agent configuration directory /etc/rancher/agent"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Using default agent var directory /var/lib/rancher/agent"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stderr]: [WARN]  /usr/local is read-only or a mount point; installing to /opt/rancher-system-agent"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Determined CA is necessary to connect to Rancher"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Successfully downloaded CA certificate"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Value from https://10.84.132.2:8443/cacerts is an x509 certificate"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Successfully tested Rancher connection"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Downloading rancher-system-agent from https://10.84.132.2:8443/assets/rancher-system-agent-amd64"
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Successfully downloaded the rancher-system-agent binary."
Sep 16 23:36:56 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:36:56Z" level=info msg="[stdout]: [INFO]  Generating Cattle ID"
Sep 16 23:37:57 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:37:57Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received"
Sep 16 23:37:57 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:37:57Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:39:02 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:39:02Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received"
Sep 16 23:39:02 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:39:02Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:40:07 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:40:07Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received"
Sep 16 23:40:07 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:40:07Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:41:12 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:41:12Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received"
Sep 16 23:41:12 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:41:12Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:42:17 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:42:17Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received"
Sep 16 23:42:17 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:42:17Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:43:22 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:43:22Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60000 milliseconds with 0 bytes received"
Sep 16 23:43:22 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:43:22Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:44:27 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:44:27Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received"
Sep 16 23:44:27 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:44:27Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:45:32 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:45:32Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60000 milliseconds with 0 bytes received"
Sep 16 23:45:32 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:45:32Z" level=info msg="[stderr]: [ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again"
Sep 16 23:46:37 harvester-lqfg9 rancherd[2103]: time="2021-09-16T23:46:37Z" level=info msg="[stderr]: curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received"
```

**To Reproduce**
1. Install one node as a server role.
2. Install another one to join the previous server node.
3. The second node never appears in the cluster.

**Expected behavior**

The second node should appear in the cluster.

**Support bundle**

A full support bundle can be provided if needed.

**Environment:**
 - Harvester ISO version: Master ISO: (Harvester: master-8afedf0a-head, Installer: 29903fe)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): QA baremetal machines

**Additional context**

Rancherd bootstrap of first server node doesn't complete: [rancherd.log](https://github.com/harvester/harvester/files/7182403/rancherd.log)

```
Sep 16 23:23:35 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:35Z" level=info msg="Running command: /usr/bin/rancherd [retry /var/lib/rancher/rke2/bin/kubectl apply --validate=false -f /var/lib/rancher
/rancherd/bootstrapmanifests/rancherd.yaml]"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: Warning: resource nodes/harvester-xs8p8 is missing the kubectl.kubernetes.io/last-applied-configuration anno
tation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched au
tomatically."
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stdout]: node/harvester-xs8p8 configured"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: Warning: resource namespaces/fleet-local is missing the kubectl.kubernetes.io/last-applied-configuration ann
otation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched a
utomatically."
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stdout]: namespace/fleet-local configured"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: Warning: resource clusters/local is missing the kubectl.kubernetes.io/last-applied-configuration annotation
which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatic
ally."
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stdout]: secret/local-rke-state created"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: Warning: resource clusterregistrationtokens/default-token is missing the kubectl.kubernetes.io/last-applied-
configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation
will be patched automatically."
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stdout]: clusterregistrationtoken.management.cattle.io/default-token configured"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: Error from server: error when applying patch:"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: {\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\
\\"provisioning.cattle.io/v1\\\",\\\"kind\\\":\\\"Cluster\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"labels\\\":{\\\"rke.cattle.io/init-node-machine-id\\\":\\\"p54nncxk7tzfxgdpwx58bnqv6djkxb7bpfxjfwhsv9qf
r6xdszzrbh\\\"},\\\"name\\\":\\\"local\\\",\\\"namespace\\\":\\\"fleet-local\\\"},\\\"spec\\\":{\\\"kubernetesVersion\\\":\\\"v1.21.4-rc1+rke2r4\\\",\\\"rkeConfig\\\":{\\\"controlPlaneConfig\\\":null}}}\\n\"},\
"labels\":{\"rke.cattle.io/init-node-machine-id\":\"p54nncxk7tzfxgdpwx58bnqv6djkxb7bpfxjfwhsv9qfr6xdszzrbh\"}},\"spec\":{\"kubernetesVersion\":\"v1.21.4-rc1+rke2r4\",\"rkeConfig\":{\"controlPlaneConfig\":null}}
}"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: to:"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: Resource: \"provisioning.cattle.io/v1, Resource=clusters\", GroupVersionKind: \"provisioning.cattle.io/v1, K
ind=Cluster\""
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: Name: \"local\", Namespace: \"fleet-local\""
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: for: \"/var/lib/rancher/rancherd/bootstrapmanifests/rancherd.yaml\": admission webhook \"rancherauth.cattle.
io\" denied the request without explanation"
Sep 16 23:23:50 harvester-xs8p8 rancherd[2092]: time="2021-09-16T23:23:50Z" level=info msg="[stderr]: time=\"2021-09-16T23:23:50Z\" level=error msg=\"failed to run [/var/lib/rancher/rke2/bin/kubectl apply --val
idate=false -f /var/lib/rancher/rancherd/bootstrapmanifests/rancherd.yaml]: exit status 1\""
```

The rancher-webhook rejects the operation. Turn on debug in rancher-webhook and see the log: [rancher-webhook.log](https://github.com/harvester/harvester/files/7182411/rancher-webhook.log)

```
2021-09-17T03:04:47.490566605Z time="2021-09-17T03:04:47Z" level=debug msg="no route match found for UPDATE provisioning.cattle.io/v1, Kind=Cluster fleet-local/local"
2021-09-17T03:04:53.263386033Z time="2021-09-17T03:04:53Z" level=debug msg="no route match found for UPDATE provisioning.cattle.io/v1, Kind=Cluster fleet-local/local"
2021-09-17T03:04:59.245018888Z time="2021-09-17T03:04:59Z" level=debug msg="no route match found for UPDATE provisioning.cattle.io/v1, Kind=Cluster fleet-local/local"
2021-09-17T03:05:05.353380960Z time="2021-09-17T03:05:05Z" level=debug msg="no route match found for UPDATE provisioning.cattle.io/v1, Kind=Cluster fleet-local/local"
```

```
harvester-xs8p8:~ # kubectl get  clusters.provisioning.cattle.io -A
NAMESPACE     NAME    READY   KUBECONFIG
fleet-local   local   true    local-kubeconfig
```

Rancher pod log: [rancher.log](https://github.com/harvester/harvester/files/7182418/rancher.log)

**/var/lib/rancher/rancherd/bootstrapmanifests/rancherd.yaml**

```
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/etcd: "true"
  name: harvester-xs8p8

---
apiVersion: v1
kind: Namespace
metadata:
  name: fleet-local

---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  labels:
    rke.cattle.io/init-node-machine-id: p54nncxk7tzfxgdpwx58bnqv6djkxb7bpfxjfwhsv9qfr6xdszzrbh
  name: local
  namespace: fleet-local
spec:
  kubernetesVersion: v1.21.4-rc1+rke2r4
  rkeConfig:
    controlPlaneConfig: null

---
apiVersion: v1
data:
  agentToken: dG9rZW4=
  serverToken: dG9rZW4=
kind: Secret
metadata:
  name: local-rke-state
  namespace: fleet-local

---
apiVersion: management.cattle.io/v3
kind: ClusterRegistrationToken
metadata:
  name: default-token
  namespace: local
spec:
  clusterName: local
status:
  token: token
```

**Comment by brandond** [comment] 2021-09-17 05:24
This appears to be the same webhook error logged here: https://github.com/rancher/rancher/issues/34691#issuecomment-919646498

**Comment by guangbochen** [comment] 2021-09-17 05:37
thank you @brandond, let's patch the embedded `rancher-webhook` image from `docker.io/rancher/rancher-webhook:v0.2.0` to `v0.2.1-rc2` to verify if it will works, thanks.

**Comment by johnliu55tw** [comment] 2021-09-22 02:47
Can't seem to reproduce the issue on KVM with one server and two agent nodes. Agent nodes are automatically added to the cluster:
![image](https://user-images.githubusercontent.com/5047724/134275422-19593d52-5500-4292-ae4d-237a50d2efc0.png)

Seems like an intermittent issue or is only reproducible on bare-metal and QA networking? I will change the networking of KVM and try to reproduce it.

**Comment by guangbochen** [comment] 2021-09-22 03:49
sure thanks @johnliu55tw, additionally we can bump the `rancher-webhook` to the latest version as the `no route match found` is a known issue of it and get the QA team to re-validate it again in their environment, thanks.
cc @bk201 do u know if there are any reproducible steps of this issue?

**Comment by johnliu55tw** [comment] 2021-09-22 07:13
@guangbochen ok I'll bump the version of `rancher-webhook` to the latest and test it out.

**Comment by bk201** [comment] 2021-09-22 09:48
The rancher-webhook is deployed by Rancher from the rancher-charts in the rancher image (`/var/lib/rancher-data/local-catalogs/v2/rancher-charts/4b40cac650031b74776e87c1a726b0484d0877c3ec137da0872547ff9b73a721/assets/rancher-webhook/`) and the image tag can't be changed (it only accept [min version of chart](https://github.com/rancher/rancher/blob/053d4c4ea4ce8218a55fc7efc34f22209239211c/pkg/controllers/dashboard/systemcharts/controller.go#L25)).

A workaround is to patch the image tag in the current Rancher image, otherwise we'll need to wait for a new Rancher image that includes the change: https://github.com/rancher/charts/pull/1483

**Comment by guangbochen** [comment] 2021-09-22 09:55
@bk201 @johnliu55tw we can use the tagged `v2.6-head` image here as long it includes both https://github.com/rancher/rancher/issues/34716 and the `webhook` changes, therefore we don't need to wait for the rancher RC release and continue the verification AEAP, thanks.

**Comment by johnliu55tw** [comment] 2021-09-23 04:40
@guangbochen I suppose tag `v2.6-head` is a dynamic tag that points to different images whenever a new one is pushed? If so I think we could use tag [`v2.6.1-rc2`](https://github.com/rancher/rancher/releases/tag/v2.6.1-rc2) which deploys `rancher-webhook v0.2.1-rc3` and includes the fix of https://github.com/rancher/rancher/issues/34716.

**Comment by guangbochen** [comment] 2021-09-23 05:44
sure, rc2 works for us, thanks @johnliu55tw

**Comment by johnliu55tw** [comment] 2021-09-23 07:31
@guangbochen The latest version of rancher has some issues: https://github.com/rancher/rancher/issues/34866. @bk201 found this issue on `head` version, I just tested `v2.6.1-rc2` and the issue still exists.

**Comment by guangbochen** [comment] 2021-09-30 04:19
@guangyee we have bumped the built-in rancher and rancher-webhook in the current master-head ISO, can u please help to verify if this issue can still be re-produced, thanks.

**Comment by guangyee** [comment] 2021-10-04 04:51
Closing it as the problem is no longer occurring.

**Closed as completed by guangyee** 2021-10-04 04:51 UTC
Labels: kind/bug, area/installer, priority/0
