### ISSUE TITLE
[BUG] VM age goes back in time as is initially created

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#2657] opened 2022-08-11 19:56 UTC
**Describe the bug**
VM creation age goes back in time

**To Reproduce**
1. Create a VM
2. See Age in the Virtual Machines section

https://user-images.githubusercontent.com/5146963/184227819-ffe61bb6-9ede-46ae-a7f8-b78a30536343.mov

**Expected behavior**

**Support bundle**
[supportbundle_c2c9cfb1-d5b4-4d28-b014-c7e0b7716cef_2022-08-11T19-52-00Z.zip](https://github.com/harvester/harvester/files/9311664/supportbundle_c2c9cfb1-d5b4-4d28-b014-c7e0b7716cef_2022-08-11T19-52-00Z.zip)

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure: R620

**Comment by lanfon72** [comment] 2022-08-12 01:38
this probably caused by https://github.com/harvester/harvester/issues/2119

**Comment by FrankYang0529** [comment] 2022-08-17 07:06
I can't reproduce this on `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`. Not sure how UI shows the `Age` field. Does it get `vm.metadata.creationTimestamp` and calculate the age by UI? Or does it use WebSocket to get the `Age` field update from the server?

cc @WuJun2016 Thank you.

**Comment by WuJun2016** [comment] 2022-08-17 07:25
@FrankYang0529 
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/24985926/185057614-281666ec-cd9d-4a88-b251-5f66b60da9e3.png">

The frontend is based on metadata.creationTimestamp.

There is a similar problem here：   https://github.com/harvester/harvester/issues/394

**Comment by w13915984028** [comment] 2022-08-17 09:33
Is it possible that the Cluster's time is few minutes ahead of the client side,  e.g. Custer side's NTP is failure, or client side is behind standard time?  Then it caused this tricky issue, the computed age is decreasing.

**Comment by rrajendran17** [comment] 2024-10-15 21:16
same as #3252, closing this

**Closed as completed by rrajendran17** 2024-10-15 21:16 UTC
Labels: kind/bug, require/reproduce, require/severity
