### ISSUE TITLE
[BUG] Trying to set maintenance mode on the last available node shouldn't be allowed

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1014] opened 2021-07-09 14:47 UTC
**Describe the bug**
On a 5 nodes cluster where 4 nodes are maintenance/cordon mode I tried to set the last mode in maintenance and so the cluster tries to migrate 2 VMs, which is not possible as there is no free worker. So the `Migrating` state for VMs stay after hours and the node as the same issue with `Entering maintenance mode` state. And, of course, the VMs that are in `Migrating` state are not available.

**To Reproduce**
1. Create some VM on a cluster with at least 3 nodes
2. Set 2 nodes in maintenance/cordon state
3. Tries to set maintenance mode on the remaining node

**Expected behavior**
We shouldn't be able to try to set the remaining node in maintenance mode, or at least a warning should be shown.

**Support bundle**
FYI: I was not able to generate a support bundle for this issue: it stucks at 0%... Is it because all nodes are in maintenance/cordon mode? Is a another issue needed for this?

**Environment:**
 - Harvester ISO version: `master-902bee60-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HP ProLiant DL360 Gen9

**Additional context**
None.

**Comment by ldevulder** [comment] 2021-07-09 14:53
After a quick discussion on slack here a comment from @yasker :
```
I feel maintenance should be allowed but we should have a warning showing that migrating all the running VMs
won't be possible. Since this will happen not only for the last node, but also if the cluster is at full capacity.
We definitely shouldn't shutdowns all the VMs automatically.
```

**Comment by FrankYang0529** [comment] 2021-11-04 07:55
@guangbochen do we need to consider whether a node is a server or agent for this issue? For example, we restrict users to enable maintenance mode on the last server node if there is only one server node or on the last 2-server node if there is a cluster.

**Comment by TachunLin** [comment] 2021-11-05 02:38
Verified **behavior as expected** for 3 nodes scenario on master-b5dadc82-head 
We need further confirm how 2 nodes expected behavior should be as above comment

### Result
Within 3 nodes and 3 virtual machines testing environment.
Set maintenance from node 3 -> node 2 -> node 1 in sequence 
The final remaining node will prompt `can't enable maintenance in last available node `

![image](https://user-images.githubusercontent.com/29251855/140376151-a93b69f5-a3d6-4120-b754-c39aec4feadf.png)

![image](https://user-images.githubusercontent.com/29251855/140376294-4bf9d0a1-bcf6-4908-b286-0f79f3d9003b.png)


### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: master-b5dadc82-head


### Verify Steps

1. Create 3 vms located on node2 and node3
![image](https://user-images.githubusercontent.com/29251855/140375836-50cfdb48-a37f-4d86-b931-04983e837cdc.png)

2. Open host page
3. Set node 3 into maintenance mode
4. Wait for virtual machine migrate to node 2
5. Set node 2 into maintenance mode
6. wait for virtual machine migrate to node 1
7. Set node 2 into maintenance mode

### Additional Context
None

**Comment by FrankYang0529** [comment] 2021-11-05 07:39
> @guangbochen do we need to consider whether a node is a server or agent for this issue? For example, we restrict users to enable maintenance mode on the last server node if there is only one server node or on the last 2-server node if there is a cluster.

Since control-plane pods are [static pods](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/), it is okay to enable maintenance mode on all control-plane nodes.

cc @bk201

**Comment by TachunLin** [comment] 2021-11-05 12:03
According to @FrankYang0529 comment, we would treat 2 nodes and 3 nodes in the same manner to prevent setting last available node into maintenance mode. Close this issue

**Closed as completed by TachunLin** 2021-11-05 12:03 UTC
Labels: kind/bug, area/ui, priority/1, area/admission-webhook
