### ISSUE TITLE
[BUG] Error message about invalid backup target doesn't go away

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1051] opened 2021-07-28 22:03 UTC
**Describe the bug**

If you get an error message about invalid backup target it doesn't go away when you remove the backup target
**To Reproduce**
1. Create new backup target with S3
2. Enter in bogus info like `7` for each entry
3. Save
4. Refresh page
5. Look for error
6. Edit config again and remove all entries
**Expected behavior**

If you remove the entries for the backup target it should clear the error
**Support bundle**

[harvester-supportbundle_0278c74f-2ced-4d9a-ae93-7776ce875960_2021-07-28T22-01-11Z.zip](https://github.com/harvester/harvester/files/6896692/harvester-supportbundle_0278c74f-2ced-4d9a-ae93-7776ce875960_2021-07-28T22-01-11Z.zip)

**Environment:**
 - Harvester ISO version: master-bc40fc79-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal with DL160

**Additional context**
![Greenshot_2021-07-28_15_00_30](https://user-images.githubusercontent.com/83787952/127402173-e46cc880-7562-4987-87af-e1a05525dfc7.jpg)

**Comment by guangbochen** [comment] 2021-08-19 03:25
will need to reset the config using the  `Use the default value` option, this will require both UI and backup modification support. cc @WuJun2016

**Comment by w13915984028** [comment] 2021-11-16 14:53
When the backup target config is failed, the error will always be there, to notify the user.
User can modify the config to a correct one, or clear/reset the error config. The latter does not work now.

We may  either add a new button beside "show/hide backup target", called "reset/clear backup target";  or in the "edit" pop up, enable "Use the default value" button (it is not usable now), to reset/clear current config.

"Use the default value" button looks to be a better option. UI is checking why it is disabled.
@guangbochen @WuJun2016 @n313893254

**Comment by w13915984028** [comment] 2021-11-17 13:49
The "Use the default value" button in the harvester UI (edit backup target) is available now, the corresponding backend source code must be added to do related processing. Coding.

DON´T use/test the button at the moment.

**Comment by w13915984028** [comment] 2021-11-19 12:26
With "Use the default value" button, and the coming commit, we can set the backup target to initial value, the error message will disappear.
Sure, it also needs a fix regarding #1555, it will be committed together.

**Comment by w13915984028** [comment] 2021-11-25 14:09
After PR of #1447, the error message will be shown only once, will not be always there.

And, when the UI encounters error, the config will not be saved.  After refresh, you will still find the previous successful config or initial config.

But if you only want to clear the config / reset it back to initial, it is not possible now.

the "Use the default value" will be refused by webhook, the error message is:
`admission webhook "validator.harvesterhci.io" denied the request: Destination URL hasn't been specified`

**Comment by w13915984028** [comment] 2021-11-29 14:05
@guangbochen  @FrankYang0529 

To reset the backup target to the default value, we need to consider a few specifications:

1. If some vm backup has been configured, should "reset backup target" give the user information to confirm the action?

2. If a vm backup is right happening, what to do when "reset backup target"? e.g., prompt the user to try later, or delete the vm backup first

3. If backup target is the default value(NULL), when the user creates VM backup, allow or deny?

4. If backup target  is the default value(NULL), for those existing VM backups, how to process?
a. be silent, loop until a valid backup target is configure then do the work
b. report warning/error each time when it tries to do backup
c. others...

Your idea?

**Comment by guangbochen** [comment] 2021-11-29 14:19
IMO I would prefer the following approaches, feel free to comment on it, thanks.
1. should be fine to continue the process and validate it via the webhook validations.
2. prefer to `reject and ask the user to either remove the pending VM backups first or try reset later`.
3. should be rejected as the current approach.
4. keep silent and do nothing.

**Comment by FrankYang0529** [comment] 2021-11-30 02:27
IMO For the fourth question, probably we can follow the design in LH Backup. When users change backup target, we remove VM Backup CR which is not in the new backup target. Also, we create VM Backup CR which is not in Kubernetes but in the new backup target.

**Comment by w13915984028** [comment] 2021-12-02 13:55
@FrankYang0529 @guangbochen 

Suppose the backup target setting changes as:   initial-> S3 -> NFS...,  if we only call h.updateBackupTargetSecret when S3, then it means in the NFS backup, the previous S3 secret is till remaining there.

It looks we need to update all information of backup target setting whenever changes happens (initial -> s3/nfs -> nfs/s3 -> init -> any...)


```
OnBackupTargetChange

	h.updateBackupTargetSecret (when S3)
		getBackupSecretData
		h.secretCache.Get
		 h.secrets.Create
		 h.secrets.Update
		h.updateLonghornBackupTargetSecretSetting
			h.longhornSettingCache.Get
			 h.longhornSettings.Create
			 h.longhornSettings.Update
```

```
// OnBackupTargetChange handles backupTarget setting object on change
func (h *TargetHandler) OnBackupTargetChange(key string, setting *harvesterv1.Setting) (*harvesterv1.Setting, error) {
..
	if target.Type == settings.S3BackupType {
		if err = h.updateBackupTargetSecret(target); err != nil {
			return nil, err
		}
	}
...
}

```

**Comment by w13915984028** [comment] 2021-12-02 14:20
@gitlawr  @FrankYang0529 

Regarding the change in:
https://github.com/harvester/harvester/pull/1601/files

If http proxy field is not filled in the web UI, empty/initial value is sent to back end?

need to check settings.HTTPProxy.Get() != "" ?

  json.Unmarshal([]byte(settings.HTTPProxy.Get()), &httpProxyConfig)

pkg/controller/master/backup/backup_target.go
```
func getBackupSecretData(target *settings.BackupTarget) (map[string]string, error) {
..
	if settings.AdditionalCA.Get() != "" {
		data[AWSCERT] = settings.AdditionalCA.Get()
	}

	var httpProxyConfig util.HTTPProxyConfig
	if err := json.Unmarshal([]byte(settings.HTTPProxy.Get()), &httpProxyConfig); err != nil {
		return nil, err
	}
	data[util.HTTPProxyEnv] = httpProxyConfig.HTTPProxy
	data[util.HTTPSProxyEnv] = httpProxyConfig.HTTPSProxy
	data[util.NoProxyEnv] = util.AddBuiltInNoProxy(httpProxyConfig.NoProxy)

	return data, nil
}
```

**Comment by w13915984028** [comment] 2021-12-02 15:18
Another doubt:

```
func (h *TargetHandler) OnBackupTargetChange
..
	// Since we remove S3 access key id and secret access key after S3 backup target has been verified,
	// we stop the controller to reconcile it again.
	if target.Type == settings.S3BackupType && (target.SecretAccessKey == "" || target.AccessKeyID == "") {
		return nil, nil
	}
```
When  "it is reconciled by controller"  (I am not fully sure about when the controller will trig this action,  but given it happens.):

```
1. Case backup target is not S3, then following codes are run. 
    Controller has all setting data, config again brings no harm.
    longhorn will be aligned.

2. Case backup target is S3, then following codes are skipped. 
   Controller has no secrets, not possible to config again. 
   return OK directly 

What will happen if longhorn side also has no such setting/is inconsistent?
```

Consider to do a check that the backup target & secrets are existing at longhorn side. If it is not true, an error message could to be thrown to tell user config it again.

@FrankYang0529 @guangbochen  your idea?

```
// OnBackupTargetChange handles backupTarget setting object on change
func (h *TargetHandler) OnBackupTargetChange(key string, setting *harvesterv1.Setting) (*harvesterv1.Setting, error) {
...

	// Since we remove S3 access key id and secret access key after S3 backup target has been verified,
	// we stop the controller to reconcile it again.
	if target.Type == settings.S3BackupType && (target.SecretAccessKey == "" || target.AccessKeyID == "") {
		return nil, nil
	}

	if err = h.updateLonghornTarget(target); err != nil {
..

..
		if err = h.updateBackupTargetSecret(target); err != nil {
..

	return h.updateBackupTargetSetting(setting.DeepCopy(), target, err)
}
```

**Comment by FrankYang0529** [comment] 2021-12-03 07:59
> @FrankYang0529 @guangbochen
> 
> Suppose the backup target setting changes as: initial-> S3 -> NFS..., if we only call h.updateBackupTargetSecret when S3, then it means in the NFS backup, the previous S3 secret is till remaining there.
> 
> It looks we need to update all information of backup target setting whenever changes happens (initial -> s3/nfs -> nfs/s3 -> init -> any...)
> ...

Yes, I think we should remove `harvester-backup-target-secret` secret when users change to non S3 backup target.

**Comment by guangbochen** [comment] 2021-12-03 08:08
both the secret and setting should be reset on both Harvester and LH sides, additionally, I think we should keep the original backup data on the remote server for now, as an enhancement we can add an option to ask users whether to clean up all backups or keep it when updating the backup target setting.

**Comment by FrankYang0529** [comment] 2021-12-03 08:27
> When "it is reconciled by controller" (I am not fully sure about when the controller will trig this action, but given it happens.):
> 
> ```
> 1. Case backup target is not S3, then following codes are run. 
>     Controller has all setting data, config again brings no harm.
>     longhorn will be aligned.
> 
> 2. Case backup target is S3, then following codes are skipped. 
>    Controller has no secrets, not possible to config again. 
>    return OK directly 
> 
> What will happen if longhorn side also has no such setting/is inconsistent?
> ```
> ...

Yes, good catch! I just try setup NFS backup target first and change to S3 without `accessKeyId ` and `secretAccessKey`. It can pass. We should check whether `harvester-backup-target-secret` exists and can access to AWS S3.

**Comment by w13915984028** [comment] 2021-12-03 08:57
> both the secret and setting should be reset on both Harvester and LH sides, additionally, I think we should keep the original backup data on the remote server for now, as an enhancement we can add an option to ask users whether to clean up all backups or keep it when updating the backup target setting.

@guangbochen @FrankYang0529 
"Use the default value" is a bit more complex than my initial estimation. The vm backup, backup_metadata ... all need to enhance the processing when backup target is changed (to initial). Now it assumes the backup target is always already validated and usable.

**Comment by lanfon72** [comment] 2021-12-16 12:58
Verified the origin bug has been fixed.

- For the content of error message, it is related to #1339 which has been fixed.
- For the box of error message,I can't reproduce the error message box outside because the root cause has been fixed.
  Also tested on some negative input, the error message will not appear outside as below.
![image](https://user-images.githubusercontent.com/5169694/146373402-b593c774-d083-41c2-81c7-2868d9552775.png)

- For `Use the default value`, tested and not work as expected, please discuss in #1687

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-3d096946-head**
* **ui-source** Option: **Auto**

**Closed as completed by lanfon72** 2021-12-16 12:58 UTC
Labels: kind/bug, area/control-plane, priority/0
