### ISSUE TITLE
[BUG] Upgrade stuck on the logging pod provision

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4096] opened 2023-06-16 02:55 UTC
**Describe the bug**
The upgrade will be stuck because some upgrade logging pods fail to mount the volume.
We could find some error messages on the `hvst-upgrade-79jcs-upgradelog-downloader-84db4b5569-fzz9v` and `hvst-upgrade-79jcs-upgradelog-infra-fluentd-0` as below:
```
message: 'AttachVolume.Attach failed for volume "pvc-5993c598-c97e-4f6c-a1f4-1e874e23936f"
: rpc error: code = DeadlineExceeded desc = volume pvc-5993c598-c97e-4f6c-a1f4-1e874e23936f
failed to attach to node harvester-node-1'
```
and
```
Warning  FailedMount  2m5s  kubelet            Unable to attach or mount volumes: unmounted volumes=[log-archive], unattached volumes=[log-archive]: timed out waiting for the condition
```
These two pods are stuck on **ContainerCreating** for the above reason.

**To Reproduce**
1. install harvester v1.1.2
2. upgrade to harvester v1.2.0-rc2
3. Do not disable the logging when upgrade
4. You have a chance to see the above error.

**Expected behavior**
The upgrade should not be stuck here.

**Support bundle**
[supportbundle_e7c74feb-9e22-42ba-988f-278741172c8d_2023-06-15T17-28-18Z.zip](https://github.com/harvester/harvester/files/11765623/supportbundle_e7c74feb-9e22-42ba-988f-278741172c8d_2023-06-15T17-28-18Z.zip)

**Environment**
 - Harvester ISO version: 1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3VMs cluster

**Additional context**
The problematic volume is `pvc-5993c598-c97e-4f6c-a1f4-1e874e23936f`.
When we see this error, this volume is attached to node2.  (for previous and others logging pod)

**Comment by guangbochen** [comment] 2023-06-20 09:04
might be duplicate with https://github.com/harvester/harvester/issues/4095, need further investigation.

**Comment by guangbochen** [comment] 2023-06-28 10:09
close as duplicate of #4095, feel free to re-open this one if u found is different.

**Closed as completed by guangbochen** 2023-06-28 10:09 UTC
Labels: kind/bug, area/install-upgrade, require/reproduce, require/severity
