### ISSUE TITLE
[FEATURE] Support dynamic ssh key/password injection  via AccessCredentials

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1538] opened 2021-11-12 02:27 UTC
**Is your feature request related to a problem? Please describe.**

Support dynamic ssh key/password injection via AccessCredentials

## User Experience

- Add an additional `Credentials` tab page to the virtual machine details.
- Users  can select virtual machine's `Edit Config` and click `Credentials` to enter the credential tab page.
- The `Credentials` tab page is similar to the `Volumes` tab page.
- Similar to adding volumes, users can add multiple credentials.
- There are two types of credentials: "Password" and "SSH Public Key" .
- Users can add a password credential by click button `Add Password Credential ` .
- Users can add a SSH public key credential by click button `Add SSH Public Key Credential  ` 
- Users can add user options on user drop-down box by `Add User`.
- For a password credential, the user needs to select user names and enter a password.
- For a SSH public key credential, the user needs to select user names and select SSH public keys.

## Expected behavior

1. This feature depends on qemu-guest-agent
2. After modifying the content of the credential, it will take effect after a while.
3. After a credential is added, the credential takes effect only after being restarted
4. Deleting a credential does not delete the information that has been injected into the VM and does not affect the access of existing users
5. After backup and restore, the credentials are still work fine (#1789)

## API reference

http://kubevirt.io/api-reference/master/definitions.html#_v1_accesscredential
1. dynamic ssh-key injection via qemu-guest-agent
https://kubevirt.io/user-guide/virtual_machines/accessing_virtual_machines/#dynamic-ssh-key-injection-via-qemu-user-agent
2. dynamic password set via qemu-guest-agent
vm:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test
  namespace: default
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      accessCredentials:
      - userPassword:
          source:
            secret:
              secretName: my-new-password
          propagationMethod:
            qemuGuestAgent: {}
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: disk-1
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 2Gi
      hostname: test
      networks:
      - name: default
        pod: {}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/fedora-with-test-tooling-container-disk:latest
        name: disk-1
```
secret:
```yaml
apiVersion: v1
data:
  fedora: cm9vdGEK
kind: Secret
metadata:
  creationTimestamp: null
  name: my-new-password
```
**Additional context**

**Comment by DaiYuzeng** [comment] 2022-03-02 01:29
@futuretea PR from UI side merged, can you please do a test?

**Comment by futuretea** [comment] 2022-03-02 01:34
> @futuretea PR from UI side merged, can you please do a test?

@DaiYuzeng  I have done a quick test and will add a test plan later.

**Comment by futuretea** [comment] 2022-03-02 14:57
## test plan:
- Create a VM (include qemu-guest-agent)
- Select the virtual machine's `Edit Config` and click `Access Credentials` to enter the credential tab page.
- The `Access Credentials` tab page is similar to the `Volumes` tab page.
- Similar to adding volumes, users can add multiple credentials.
- Users can add a user/password credential by click button `Add Basic Auth` .
- Users can add a SSH public key credential by click button `Add SSHKey ` 
- Users can add user options on user drop-down box by `Add User`.
Note: The user to be added must already exist; otherwise, the credentials will not take effect.
- For a password credential, the user needs to select user names and enter a password.
- For a SSH public key credential, the user needs to select user names and select SSH public keys.

## Expected behavior

1. After modifying the content of the credential, it will take effect after a while.
2. After a credential is added, the credential takes effect only after being restarted
3. Deleting a credential does not delete the information that has been injected into the VM and does not affect the access of existing users
4. After backup and restore, the added credentials are still work fine

**Comment by noahgildersleeve** [comment] 2022-03-03 22:39
What is the expected behavior if I add an SSH key to the cloud init via the VM creation then add another SSH key for that same user via access controls? I also have the same question about expected behavior with the cloud init and password. You can set passwords via cloud init with something like
```
#cloud-config
password: password
chpasswd: {expire: False}
sshpwauth: True
```

**Comment by futuretea** [comment] 2022-03-04 01:20
> What is the expected behavior if I add an SSH key to the cloud init via the VM creation then add another SSH key for that same user via access controls? I also have the same question about expected behavior with the cloud init and password. You can set passwords via cloud init with something like
> 
> ```
> #cloud-config
> password: password
> chpasswd: {expire: False}
> sshpwauth: True
> ```
@noahgildersleeve 
1. If no conflict, both cloud-init, and access credentials take effect
2. if conflict, access credential has higher priority.

**Comment by noahgildersleeve** [comment] 2022-03-17 01:48
Tested in v1.0.1-RC1. The scenarios that are failing are the ones at the end. If you change anything from access controls you can't remove them then change it with cloud init. This might be due to the access controls using qemu-guest-agent and it having blank settings after removing them that override cloud init. If we have that though we might want to disable the dropdown for SSH keys on the main page of VM create if you add SSH keys in access control. 

## Validation Steps
###
1. Create a new VM
1. Let it reboot
1. Add basic auth to the VM
1. Verify that basic auth works
pass
###
1. Create a new VM with a password in cloud init
1. Verify that the password works for login
1. Add basic auth to the VM and change the password
1. Verify that the basic auth password works and the cloud init password doesn't work
pass
###
1. Create a new VM
1. Let it reboot
1. Add a username and ssh key in access controls
1. Verify that the ssh key is working and allows login
pass
###
1. Create a new VM with an SSH key in cloud init
1. Verify that the ssh key is working and allows login
1. Add a username and ssh key in access controls
1. Verify that the new ssh key is working and allows login. You can also verify it in `~/.ssh/authorized_keys
pass
###
1. Create a new VM
1. Let it reboot
1. Add a username and ssh key in access controls
1. Verify that the ssh key is working and allows login
1. Add an SSH key to the cloud init
1. Verify that the access control ssh key is the one working
pass
###
1. Create a new VM
1. Let it reboot
1. Add basic auth to the VM
1. Verify that basic auth works
1. Add a password via cloud init
1. Verify that the password being used for login is the one from basic auth
pass
###
1. Create a new VM
1. Let it reboot
1. Add a username and ssh key in access controls
1. Verify that the ssh key is working and allows login
1. Remove the SSH key from access controls
1. Add an SSH key to the cloud init
1. Verify that the cloud init ssh key is the one working
fail
###
1. Create a new VM
1. Let it reboot
1. Add basic auth to the VM
1. Verify that basic auth works
1. Remove the basic auth from access controls
1. Add a password via cloud init
fail
1. Verify that the password being used for login is the one from cloud init

**Comment by futuretea** [comment] 2022-03-18 02:49
@noahgildersleeve cloud-init only take effect in the first boot, so editing cloud-init after the first boot will not change anything.

U can remove cloud-init artifacts from `/var/lib/cloud` to simulate a clean instance. On reboot, cloud-init will re-run all stages as it did on first boot, or using `$ cloud-init clean --logs --reboot`.

**Comment by noahgildersleeve** [comment] 2022-04-07 02:12
Retested with updates. Closing as done.

> @noahgildersleeve cloud-init only take effect in the first boot, so editing cloud-init after the first boot will not change anything.
> 
> U can remove cloud-init artifacts from `/var/lib/cloud` to simulate a clean instance. On reboot, cloud-init will re-run all stages as it did on first boot, or using `$ cloud-init clean --logs --reboot`.

**Closed as completed by noahgildersleeve** 2022-04-07 02:12 UTC
Labels: require/doc, kind/enhancement, area/ui, area/control-plane, priority/0, highlight
