### ISSUE TITLE
[BUG] Harvester UI does not display more than 5 nodes

### ISSUE THREAD

**Issue by pgonin** [harvester/harvester#596] opened 2021-03-27 18:34 UTC
**Describe the bug**
I successfully installed 7 nodes, but only 5 are displayed in Harvester UI

On the harvester (shell) console on the installed nodes they are reporting to be running fine.

With `kubectl get nodes` all nodes are properly listed.

**Environment:**
 - Harvester ISO version: master-c5a265d5-head
 - Installation Mode: ISO
 - Underlying Infrastructure: Baremetal with HP DL360G9

**Comment by gitlawr** [comment] 2021-03-29 06:45
Tested a cluster with 6 nodes in ISO mode, and a cluster with 9 nodes in app mode.
I am not able to reproduce the issue.
![image](https://user-images.githubusercontent.com/5697937/112796870-29c56680-909d-11eb-9a3f-563e4527047f.png)

Can you check how many items the API returns?(`<Harvester-URL>/v1/nodes`)

**Comment by pgonin** [comment] 2021-03-29 07:27
I think I got another issue. The UI does not update but it's not because of number of nodes indeed.

**Comment by pgonin** [comment] 2021-03-30 13:47
I am reopening since I am having the issue again.
I added a node and it is node displayed in the UI although it is reported as properly 'Running' in the Console of the node and appears with `kubectl get nodes` from the main / console node.
I think with a reboot of the node it will be fixed, but I don't plan to reboot the node every few days.

**Comment by gitlawr** [comment] 2021-03-30 14:48
Does the node show up after refreshing in the browser?

Can you check what the API returns(`<Harvester-URL>/v1/nodes`)

**Comment by guangbochen** [comment] 2021-04-06 08:13
@pgonin please let us know if it is ok to close this issue since I remember this is an internal network issue of your working environment, thanks.

**Comment by pgonin** [comment] 2021-04-06 10:17
@guangbochen I am closing for now. Something is happening after some time with a mismatch between the UI (not updating) and out of sync with `kubectl get nodes`
I'll do more investigation to figure it out.

**Closed as completed** 2021-04-06 10:18 UTC
Labels: kind/bug
