### ISSUE TITLE
[BUG] DHCP fails for tagged VLAN on mgmt cluster network

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2891] opened 2022-10-07 00:57 UTC
**Describe the bug**

When you assign a tagged VLAN that isn't 1 to the `mgmt` cluster network DHCP fails.
**To Reproduce**
1. Provision a Harvester cluster
2. Create a new network with a tagged VLAN that is not 1, that has DHCP on it
3. Save the network
**Expected behavior**

DHCP should work on network
**Support bundle**
[supportbundle_1d94fc6f-8d87-49e4-80ae-b24bc69e72e8_2022-10-07T00-48-34Z.zip](https://github.com/harvester/harvester/files/9729606/supportbundle_1d94fc6f-8d87-49e4-80ae-b24bc69e72e8_2022-10-07T00-48-34Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160G9

**Additional context**
This works fine with `VLAN ID=1` on the ipxe-examples vagrant setup.

You can create a new cluster network, assign that to another NIC and setup a tagged VLAN on that one and is seems to work. I'm attaching the support bundle here of a 4 node setup with both the failed network and a new one setup
[supportbundle_54e82655-ba89-45d8-b279-da33fa4b91e1_2022-10-07T00-55-41Z.zip](https://github.com/harvester/harvester/files/9729747/supportbundle_54e82655-ba89-45d8-b279-da33fa4b91e1_2022-10-07T00-55-41Z.zip)
![Greenshot 2022-10-06 17 50 43](https://user-images.githubusercontent.com/83787952/194443791-cd1a416e-6bb9-420a-af56-ad60ffb92d52.png)

**Comment by irishgordo** [comment] 2022-10-07 01:23
I wasn't able to reproduce this on v1.1.0-rc2 on my bare-metal Dell PowerEdge R720.
I do know that, with my switch, I can't do "trunking" but I can tag VLAN traffic, so my gear isn't at pairity with most DCs too :sweat_smile: - so there might be some differences.  But the subnets are different as documented in screenshots due to tagging and dhcp server for my network.
And the Harvester Config, is old but I'm using it as just a cross reference to my devices :sweat_smile: :smile: 

![Screenshot from 2022-10-06 18-20-45](https://user-images.githubusercontent.com/5370752/194446376-8a464b7d-9d3e-4acd-baea-e9ffc9ebec4d.png)
![Screenshot from 2022-10-06 18-20-17](https://user-images.githubusercontent.com/5370752/194446379-b70193b8-df6e-4f0c-bbd5-699678832153.png)
![Screenshot from 2022-10-06 18-19-58](https://user-images.githubusercontent.com/5370752/194446380-6bde4b2f-8632-4994-b99d-304968955f4d.png)
![Screenshot from 2022-10-06 18-19-35](https://user-images.githubusercontent.com/5370752/194446382-2604a9b5-48f1-4789-9c89-ea3e5f463390.png)
![Screenshot from 2022-10-06 18-19-07](https://user-images.githubusercontent.com/5370752/194446383-f061e50d-71a2-4b9b-95a0-05a94c91d427.png)
![Screenshot from 2022-10-06 18-18-34](https://user-images.githubusercontent.com/5370752/194446384-7b65352c-5f87-4181-814b-88e087e23172.png)

Support:
[supportbundle_a55276f1-d2d3-4885-a91f-905a3e6d9aa0_2022-10-07T01-21-47Z.zip](https://github.com/harvester/harvester/files/9729848/supportbundle_a55276f1-d2d3-4885-a91f-905a3e6d9aa0_2022-10-07T01-21-47Z.zip)

**Comment by guangbochen** [comment] 2022-10-11 08:10
If you need to use a specific PVID other than 1, you must configure it to allow the PVID in ur physical switch, otherwise, the network will not work.

**Comment by irishgordo** [comment] 2022-10-18 22:29
I can not reproduce this on my bare-metal.
My guess is this might be related to something else.

I have a network set that only accepts the VLAN ID of 100 - not 101 (as 101 will fail in the screenshot).
That once tagging traffic to 100, from the switch's port(s) that feed the patch down panel then out to the Dell PowerEdge R720.
That setting up the VLAN with a different ID than 1 succeeds.
As well as it "fails" when expected, if for instance the switch ports only accept VLAN traffic tagged 100 to talk to the DHCP server and we created a VLAN that was of `101` that will fail to talk to the DHCP server via my Ubiquiti Unifi Gear.
I validated as well that VMs will utilize the VLAN appropriately getting their IP assigned from the VLAN tagged traffic, the Switch's DHCP server handing them an address that is within the expected subnet.  Cross-Ref, attached screen grab of VM titled "testing" on the Unifi web user-interface we see it's assigned it to the proper subnet, on the proper network, due to the network traffic being tagged appropriately.

Network Loadout:
- Unifi UDM Pro
- Unifi USW-16-PoE Switch
- US-8 Switch
- USW-Flex-Mini
- UAP-nanoHD x 2
I figure a lot of small to medium size business's and orgs could also have Unifi gear.

I'm going to go ahead and close this out as I'm not able to reproduce the issue with my networking gear and the single Harvester bare-metal node running on my Dell PowerEdge R720.

![Screenshot from 2022-10-18 15-26-28](https://user-images.githubusercontent.com/5370752/196557142-af38ec3e-67e2-44d3-a333-9530aab0ba1a.png)
![Screenshot from 2022-10-18 14-49-14](https://user-images.githubusercontent.com/5370752/196557143-8edf97ba-f93e-4bd3-92db-604f1588c650.png)

**Closed as completed by irishgordo** 2022-10-18 22:29 UTC
Labels: kind/bug, area/network, priority/0, severity/1, reproduce/always
