### ISSUE TITLE
[BUG] rc3 not installable via iso media

### ISSUE THREAD

**Issue by ebauman** [harvester/harvester#3017] opened 2022-10-23 23:13 UTC
**Describe the bug**
Installing Harvester v1.1.0-rc3 via ISO fails during cluster creation setup screen.

**To Reproduce**
1. Create 8x32 VM on vSphere, set for Linux x64 "Other" compat, 200G root vol, two NICs
2. Mount ISO and start VM
3. Press Enter to reach installer
4. Press Enter to create a new Harvester cluster
5. Enter in hostname, and press "Tab" to go to next field

**Expected behavior**
The next field to be highlighted

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vSphere VM environment

**Additional context**

<img width="908" alt="Screen Shot 2022-10-23 at 6 09 36 PM" src="https://user-images.githubusercontent.com/5565738/197422750-b6a06caf-3d12-4fc0-a1fb-66c4560367aa.png">

**Comment by ibrokethecloud** [comment] 2022-10-24 00:38
duplicate of: https://github.com/harvester/harvester/issues/2937

**Comment by ibrokethecloud** [comment] 2022-10-25 02:31
closing as its already being tracked.

**Closed as completed by ibrokethecloud** 2022-10-25 02:31 UTC
Labels: kind/bug, area/installer, require/reproduce, require/severity
