### ISSUE TITLE
[BUG]   cluster-registration-url cannot be set to null. 

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2650] opened 2022-08-10 08:59 UTC
**Describe the bug**

1. cluster-registration-url cannot be set to null. 
2. Import the harvester in the rancher cluster, and after the harvester is successfully imported, go to another rancher cluster and import the harvester cluster again, at this time the imported harvester cluster is always in the pending state

**To Reproduce**
case 1:
1. Create a harvester cluster, set cluster-registration-url to any value， save
2.  Then reset the cluster-registration-url to empty
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/75d57070-b967-4e4f-a16f-d4f2f24d1d61)
3. It does not make sense to display an error message when the value is empty, because this is the default value

case 2:
1. Import harvester in the rancher cluster and wait for the import to succeed.
2. Import the previous harvester cluster again in another rancher cluster，  （The cluster will always be in pending and no error message will be displayed）

**Expected behavior**

case 2:  When importing harvester in multiple clusters, the last imported harvester cluster should import successfully and the previous imported harvester clusters should become unavailable

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
3

**Comment by irishgordo** [comment] 2022-08-17 18:25
Validated that while #2510 passes, the ability to set the cluster-registration-url to null is still exists as an issue in Harvester Master iso: 9631b136
and v2.6.7-rc-9 Rancher.
![Screenshot from 2022-08-17 11-25-21](https://user-images.githubusercontent.com/5370752/185214980-7a2faeaf-70ca-4610-a0d4-96be03dad17e.png)

**Comment by noahgildersleeve** [comment] 2022-09-07 00:00
@FrankYang0529 How long should it take for the cluster-registration to clear after deleting it in Harvester settings? Is it on some sort of a polling timer?

**Comment by noahgildersleeve** [comment] 2022-09-07 23:55
I tested this in `master-eb3e1f3e-head` with a 3 node ipxe setup from the vagrant ipxe-examples setup. The Rancher setup was on a single node Docker instance. I tested it with `v2.6.7` and `v2.6.8`.

## Validation Steps
### case 1

1. Create a harvester cluster and rancher v2.6.8.
2. Import the harvester cluster to rancher.
3. After successful import, reset the cluster-registration-url to empty.

### Expected Results

- You should get an error in the virtualization management section of Rancher on the connection

Failed

### case 2

1. Create a harvester cluster and rancher v2.6.8.
2. Import the harvester cluster to rancher.
3. After successful import, create another rancher v2.6.8.
4. Import the harvester cluster to the new rancher.

### Expected Results
- You should be able to open Harvester cluster from virtualization management

[supportbundle_b41a6d98-59bb-4967-943d-a182e251a973_2022-09-07T20-13-20Z.zip](https://github.com/harvester/harvester/files/9522234/supportbundle_b41a6d98-59bb-4967-943d-a182e251a973_2022-09-07T20-13-20Z.zip)

**Comment by FrankYang0529** [comment] 2022-09-12 02:37
Hi @noahgildersleeve, for case 1, we only make sure users can set `cluster-registration-url` to `null` and delete `cattle-cluster-agent` deployment. For other resources like ClusterRole and Namespace, we didn't clean it, so the harvester cluster can still be accessed from Rancher.

For case 2, did you get any error in this case? I can access the harvester cluster from the new Rancher.

**Comment by noahgildersleeve** [comment] 2022-09-12 18:22
@FrankYang0529 Case 2 worked fine. I thought I put `passed` in there. Sorry about any confusion. So is the desired functionality of case 1 that you can still access the cluster, or is that change out of scope for this ticket? Could we get clarification on desired functionality?  CC @rebeccazzzz @guangbochen

**Comment by FrankYang0529** [comment] 2022-09-13 01:50
Hi @noahgildersleeve, thanks for the testing. For case 1, the better way is we delete harvester cluster registration in Rancher, but we can't do it from Harvester, because we don't have a Rancher credential in Harvester.

**Comment by noahgildersleeve** [comment] 2022-09-15 22:23
@FrankYang0529 I tested this again and checked if you could create a cluster with the `cluster-registration-url` set to empty
### case 1
1. Create a harvester cluster and rancher v2.6.8.
1. Import the harvester cluster to rancher.
1. Create a RKE2 cluster in the Harvester cluster via node driver
1. After successful creation, reset the cluster-registration-url to empty
1. Create a new RKE2 cluster in Harvester cluster

What happens when you do this is that the VMs are created on the Harvester cluster (even though there is no `cluster-registration-url`, but the config never finishes and it just starts looping. I'm attaching a support bundle. I'm not sure what the desired functionality is, but I'm assuming it's not that. CC @bk201 
[supportbundle_75ddd3a9-8abe-47a8-941c-345c92f0af16_2022-09-15T22-19-10Z.zip](https://github.com/harvester/harvester/files/9579373/supportbundle_75ddd3a9-8abe-47a8-941c-345c92f0af16_2022-09-15T22-19-10Z.zip)

**Comment by FrankYang0529** [comment] 2022-09-20 05:32
Hi @noahgildersleeve, I moved the issue back to Ready for Testing, because imported Harvester is different from traditional imported k8s cluster. Although `cattle-cluster-agent` deployment is moved and we can see `Cluster health check failed:`, harvester is a special design with [aggregated apiserver](https://github.com/rancher/rancher/blob/release/v2.7/pkg/api/steve/aggregation/aggregation.go). Rancher will store the downstream cluster credentials locally. This is required for Rancher to proxy requests to downstream Harvester /v1 apis. Additionally, Rancher has added the [retry mechanism](https://github.com/rancher/rancher/commit/ab6949b81fc0985f19bf23075c93f99d7e6047c4), and that's why we are still able to see and click the cluster even if the agent pod is deleted in the downstream cluster. The situation is unavoidable since we can't manage the upstream Rancher server. I think we can just verify whether `cattle-cluster-agent` is removed after we set `cluster-registration-url` to a default value.

**Comment by noahgildersleeve** [comment] 2022-09-28 23:00
@FrankYang0529 I retested this with Harvester `v1.1.0-rc` and Rancher `v2.6.9-rc2`. and the base cases work, but it doesn't remove the cattle-cluster-agent when you do an add -> replace -> remove as in Case 3 below. It removes the cattle-cluster-agent pods then creates new ones. The same way it seems as it does when you replace the original `cluster-registration-url`

## Validation Steps
### case 1

1. Create a harvester cluster and rancher v2.6.9-rc2.
2. Validate that `cattle-cluster-agent` doesn't exist on the Harvester system in the `cattle-system` namespace with `kubectl`
3. Import the harvester cluster to rancher.
4. Validate that `cattle-cluster-agent` exists in the `cattle-system` namespace with `kubectl`
5. After successful import, reset the cluster-registration-url to empty.

### Expected Results

-  `cattle-cluster-agent` doesn't exist on the Harvester system in the `cattle-system` namespace with `kubectl`


Pass

### case 2

1. Create a harvester cluster and rancher v2.6.8.
2. Validate that `cattle-cluster-agent` doesn't exist on the Harvester system in the `cattle-system` namespace with `kubectl`
3. Import the harvester cluster to rancher.
4. After successful import, create another rancher v2.6.8.
5. Import the harvester cluster to the new rancher.

### Expected Results
- You should be able to open Harvester cluster from virtualization management

Pass

### case 3

1. Create a harvester cluster and rancher v2.6.8.
2. Validate that `cattle-cluster-agent` doesn't exist on the Harvester system in the `cattle-system` namespace with `kubectl`
3. Import the harvester cluster to rancher.
4. After successful import, create another rancher v2.6.8.
5. Import the harvester cluster to the new rancher.
6. Validate that you can open Harvester cluster from virtualization management
7. After successful import, reset the cluster-registration-url to empty

### Expected Results
-  `cattle-cluster-agent` doesn't exist on the Harvester system in the `cattle-system` namespace with `kubectl`

Failed

**Comment by FrankYang0529** [comment] 2022-09-29 03:01
> @FrankYang0529 I retested this with Harvester `v1.1.0-rc` and Rancher `v2.6.9-rc2`. and the base cases work, but it doesn't remove the cattle-cluster-agent when you do an add -> replace -> remove as in Case 3 below. It removes the cattle-cluster-agent pods then creates new ones. The same way it seems as it does when you replace the original `cluster-registration-url`

Hi @noahgildersleeve, do you have support-bundle? I try to do case 3 again and `cattle-system/cattle-cluster-agent` deployment is removed from my cluster. Also, the `configured` status of `cluster-registration-url` setting is changed to `False`.

**Comment by noahgildersleeve** [comment] 2022-09-29 16:08
@FrankYang0529 I'll repro case 3 and then upload the support bundle.

**Comment by noahgildersleeve** [comment] 2022-09-30 02:16
Support Bundle: 
[supportbundle_f38f7cce-19a6-4965-802b-b03e84ba1e6c_2022-09-30T02-01-15Z.zip](https://github.com/harvester/harvester/files/9680118/supportbundle_f38f7cce-19a6-4965-802b-b03e84ba1e6c_2022-09-30T02-01-15Z.zip)

This was taken right after doing the Rancher stuff.

**Comment by FrankYang0529** [comment] 2022-09-30 08:22
@noahgildersleeve, thanks for the testing. I also can reproduce case 3 with v1.1.0-rc1 in a 4-node cluster. It looks like rancher will try to redeploy `cattle-system/cluster-system-agent` if we don't remove the harvester registration from rancher.

https://github.com/rancher/rancher/blob/3952135b27088744efde1e0d52b97063dc72d950/pkg/controllers/management/clusterdeploy/clusterdeploy.go#L222-L229

cc @bk201 @guangbochen , do you think it's good to add some description on UI to ask users to delete harvester registration from rancher first before setting `cluster-registration-url` to the default value? If yes, I will update content in case 3.

**Comment by guangbochen** [comment] 2022-09-30 09:12
Yes, adding a proper messages when unset the registration url would be useful, so users will also know they need to delete the cluster from the upstream Rancher. cc @WuJun2016, thanks.

**Comment by FrankYang0529** [comment] 2022-09-30 09:18
@noahgildersleeve, I updated case 3 in https://github.com/harvester/tests/issues/465. In my cluster, the `cattle-system/cattle-cluster-agent` deployment will not be deployed again. May you help to test again? Thank you.

**Comment by WuJun2016** [comment] 2022-10-12 04:05
> Yes, adding a proper messages when unset the registration url would be useful, so users will also know they need to delete the cluster from the upstream Rancher. cc @WuJun2016, thanks.

@noahgildersleeve   UI has been completed, please help test it, thanks!

**Comment by noahgildersleeve** [comment] 2022-10-14 00:30
Tested in Harvester master-61a6124a-head with previous steps

> ### case 1
> 
> 1. Create a harvester cluster and rancher v2.6.9-rc2.
> 2. Validate that `cattle-cluster-agent` doesn't exist on the Harvester system in the `cattle-system` namespace with `kubectl`
> 3. Import the harvester cluster to rancher.
> 4. Validate that `cattle-cluster-agent` exists in the `cattle-system` namespace with `kubectl`
> 5. After successful import, reset the cluster-registration-url to empty.
> 
> ### Expected Results
> 
> -  `cattle-cluster-agent` doesn't exist on the Harvester system in the `cattle-system` namespace with `kubectl`

When removing the `cluster-registration-url` in Harvester you now get a notification

![Screenshot_20221013_172831](https://user-images.githubusercontent.com/83787952/195735719-ccff6a44-3829-4cdc-88cc-25569d2e401e.png)

**Closed as completed by noahgildersleeve** 2022-10-14 00:30 UTC
Labels: kind/bug, area/ui, area/control-plane, priority/1, severity/2, reproduce/always
