### ISSUE TITLE
[Harvester] when a cluster member is added and then removed from the harvester cluster RBAC logged in as a Cluster owner all the members disappear

### ISSUE THREAD

**Issue by anupama2501** [harvester/harvester#1377] opened 2021-10-07 17:53 UTC
**Describe the bug**
If a cluster member is added by a cluster owner and then removed from the harvester cluster, we see the RBAC members page display a blank page. 

**To Reproduce**

- Create a local user from rancher --> Users and auth --> create user1,user2 [standard user permissions]
- As an admin from virtualization management --> harvester cluster --> RBAC --> add the user1 as cluster Owner
- Login as user1 and verify the harvester cluster is seen
- As user1 [Cluster owner] virtualization management --> harvester cluster --> RBAC --> add user2 and user1 as a cluster member
- Remove user1 cluster member logged in as user1 from the RBAC page

**Expected behavior**
Should not go blank and expected to display all the members in the cluster.

**Additional context**

Few observations:

- Refresh the UI and the users are seen listed in the RBAC
- Create a new user and verify all the users are listed.
- The issue happens sometimes.

ref: Found when verifying the ticket #4299
Related rancher issue: https://github.com/rancher/dashboard/issues/4347

**Comment by n313893254** [comment] 2021-11-17 09:13
The issue is caused by `/v3` WebSocket disconnect. UI send a request to find a not existing CRTB, which causes UI to fail in fetch hook and shows list empty.

Cluster member list:
- Fetch norman CRTB
- According to every CRTB find the match steve CRTB

When adding a member:
- Create steve CRTB by sending a request to the server
- Create a new norman CRTB and restore in UI store

When removing a member:
- Delete norman CRTB by sending a request to the server
- Received the remove event of norman CRTB from WebSocket and then remove the data from the UI store

Logout current user and log in caused the WebSocket won't auto-reconnect.

**Reproduce Steps**
- Logout
- Login, and nav to the harvester member page
- Open the chrome dev network, wait for the '/v3/subscribe' websocket to be closed.
- Add a member
- Delete the member
- Nav to other page(e.g. Image)
- Nav to member page

**Additional Context**

![image](https://user-images.githubusercontent.com/18737885/142166444-d3625803-0523-4a92-ae39-7a84e571258f.png)

![image](https://user-images.githubusercontent.com/18737885/142166464-11634ca1-1569-4f55-9929-b4fbda4d8300.png)

[Console about reset rancher]
![image](https://user-images.githubusercontent.com/18737885/142416271-e32c5331-990b-4593-89e6-b567deb4ecca.png)

[Auto reconnect property verify]
![image](https://user-images.githubusercontent.com/18737885/142450544-6174145f-31a8-477a-b87f-015850b81b35.png)

**Comment by n313893254** [comment] 2021-11-18 08:40
Hi, @anupama2501. The issue happens sometimes is caused by WebSocket disconnect. I try many times and found that add/delete member won't cause WebSocket disconnect.

Could you give me more information to reproduce the issue? I guess there is another reason cause WebSocket disconnect .

**Comment by TachunLin** [comment] 2021-11-23 17:12
Verified **fixed** on master-f5bde7fa-head with Rancher `v2.6-head`.Close this issue.

### Result
In harvester cluster member (RBAC) page, login user1 (owner) -> add user2 (member) -> add user1 (member) -> delete user1(member)  then navigate to other page in harvester then login RBAC again. 

All the members are displayed in the cluster member page correctly without blank page. 
![image](https://user-images.githubusercontent.com/29251855/143068643-c035b013-3aa4-4675-b63b-73c711f7828b.png)

Logout and login user1 again, it still can 

### Test Information
* Test Environment: 3 nodes harvester on provo bare machines
* Harvester version: master-f5bde7fa-head
* Rancher version: v2.6-head

### Environment Preparation
1. Install harvester v2.6-head through docker command

### Verify Steps

1. Environment preparation as above steps
2. Import harvester in rancher 
3. Create `user1` and `user2` as standard user in user&authentication
![image](https://user-images.githubusercontent.com/29251855/143063544-d72412d2-4bcd-46a0-b89a-06c6ec7a1a66.png)
4. Add user1 as cluster owner in harvester RBAC page
5. Login with user user1 and access harvester RBAC page
6. Add user2 as cluster member 
7. Add user1 as cluster member
![image](https://user-images.githubusercontent.com/29251855/143066665-6aef3410-faeb-4973-9aef-4cb8c38df534.png)
8. Delete user1 (cluster member)
9. Navigate to other page (e.g image)
10. Access RBAC page again 
11. Logout and login with user1 again 
12. Access RBAC page

**Closed as completed by TachunLin** 2021-11-23 17:12 UTC
Labels: kind/bug, area/ui, priority/1
