### ISSUE TITLE
[BUG] unable to add node as VIP:8443/ping is connection refused

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1830] opened 2022-01-17 19:47 UTC
**Describe the bug**
After adding a node, and trying to add another node, there will be a connection refused trying to access VIP:8443/ping

**To Reproduce**
1. Add node to the cluster
2. Try adding another node

**Support bundle**
https://drive.google.com/file/d/16f64xNk7ZdVOLV6uTQgNOUaBA-9VRrSr/view?usp=sharing

**Environment:**
 - Harvester ISO version: 1.0
 - Underlying Infrastructure: R620

**Additional**
```
|local:default)abonilla@MacBookPro ~ % curl -k https://10.0.0.240:443/ping
pong% 

|local:default)abonilla@MacBookPro ~ % curl -k https://10.0.0.240:8443/ping
curl: (7) Failed to connect to 10.0.0.240 port 8443: Connection refused
```

**Comment by bk201** [comment] 2022-01-18 08:30
The reason is VIP is on node `r620-6`, but two rancher pods are on node `r620-1` and `r620-2`.
The Rancher pod opens host port `8443`. If the VIP doesn't coexist with any rancher pods, then we'll see this problem.

**Steps to reproduce**
- Create a 3-node cluster and wait for node promotion done. Assume `node[1-3]`.
- Check VIP location, the easiest way to check is to ssh VIP and check the hostname. Assume the VIP is on `node1`.
- There should be two rancher pods, if any of them is on `node1`, delete it until a new pod is created on another node.

To check:
```
╰─$ kubectl get pods -l app=rancher -n cattle-system -o wide
NAME                      READY   STATUS    RESTARTS   AGE     IP           NODE    NOMINATED NODE   READINESS GATES
rancher-cbbdd7df9-2nk6j   1/1     Running   0          3m23s   10.52.2.10   node3   <none>           <none>
rancher-cbbdd7df9-6rq9q   1/1     Running   0          4m47s   10.52.0.70   node1   <none>           <none>
```

To delete:
```
kubectl delete pod <pod_name> -n cattle-system
```
-  Create a new node `node4` and use VIP to join.
    - Text UI path: the new node can't join after typing the server VIP. 
    - PXE Boot: The new can't join after the node is rebooted (checking `journalctl -u rancherd` logs on node4).

**Comment by bk201** [comment] 2022-01-18 13:27
Workaround for 1.0.0 nodes (only works for PXE boot):

- Check the node that can't join the cluster, user should see messages like:
```
# journalctl -u rancherd

Jan 18 13:19:57 node4 rancherd[1896]: time="2022-01-18T13:19:57Z" level=info msg="Bootstrapping Rancher (master-head/v1.21.7+rke2r1)"
Jan 18 13:19:57 node4 rancherd[1896]: time="2022-01-18T13:19:57Z" level=info msg="failed to bootstrap system, will retry: generating plan: insecure cacerts download from https://10.10.0.100:8443/cacerts: Get \"https://10.10.0.100:8443/cacerts\": dial tcp 10.10.0.100:8443: connect: connection refused"
```

- Edit rancherd config on that node, modify the server port from `8443` to `443`. For example:
```
# vim /etc/rancher/rancherd/config.yaml
```

Change from
```
server: https://10.10.0.100:8443
```

to
```
server: https://10.10.0.100:443
```

**Comment by TachunLin** [comment] 2022-02-08 04:03
- [x]  ISO installation for VIP node join scenario 

Verified `fixed` on for ISO installation scenario on `master-1a861fc1-head` (02/07/22).

### Result
In ISO installation, we can add node 4 while rancher pod and VIP on different node


### Test Information
* Test Environment: 4 nodes harvester on local kvm machine
* Harvester version: master-d05a6cc7-head

### Verify Steps

1. ISO install harvester node1 in create mode
2. ISO install harvester node2 and node3 in join mode
3. ssh to VIP 
4. Check the hostname to confirm which node is the VIP located 
5. Check where the rancher pod located in which nodes 
   `$ kubectl get pods -l app=rancher -n cattle-system -o wide`
6. Delete the rancher pod with the same node as the VIP 
   `$ kubectl delete pod <pod_name> -n cattle-system` 
7. Wait rancher pod recreated on another node rather than the same with VIP 
8. ISO install harvester node4 in join mode
9. Check can join node4 with typing VIP in the console Text UI path 

### Additional Context
When rancher pod and VIP on the same node, we would be able to ping both VIP:8443 and VIP:443

```
localhost:~ # curl -k https://192.168.122.179:443/ping
pong
localhost:~ # curl -k https://192.168.122.179:8443/ping
pong
```

**Comment by TachunLin** [comment] 2022-02-08 04:05
- [x]  PXE Boot for VIP node join scenario 

### Status
Verified `fixed` on for PXE boot installation scenario on master-1a861fc1-head (02/07/22) 


Can add node4 to cluster when rancher pod and VIP located on different nodes
![image](https://user-images.githubusercontent.com/29251855/152976493-5cb36bed-91c7-473f-b366-2b9b827b8713.png)

After node 4 joined to cluster, check the rancher pod and VIP are located on different nodes
```
ancher@harvester-node-0:~> hostname
harvester-node-0
rancher@harvester-node-0:~> sudo -i kubectl get pods -l app=rancher -n cattle-system -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE               NOMINATED NODE   READINESS GATES
rancher-7c6ffbc8d8-42h9z   1/1     Running   0          31m   10.52.2.12   harvester-node-2   <none>           <none>
rancher-7c6ffbc8d8-mp9sj   1/1     Running   0          73m   10.52.1.9    harvester-node-1   <none>           <none>
```
### Test Information
- Test Environment: 4 nodes harvester on local kvm machine
- Harvester version: master-d05a6cc7-head

### Verify Steps

1. Prepare ipxe example for PXE boot installation
2. Edit config-join.yaml according to [ipxe-examples/pull/41](https://github.com/harvester/ipxe-examples/pull/41)
3. Install pxe_server and node 1 first
4. Use `reinstall_harvester_node.sh` to install node 2
5. Use `reinstall_harvester_node.sh` to install node 3
6. Check the hostname to confirm which node is the VIP located
7. Check where the rancher pod located in which nodes
    $ kubectl get pods -l app=rancher -n cattle-system -o wide
8. Delete the rancher pod with the same node as the VIP
    $ kubectl delete pod <pod_name> -n cattle-system
9. Wait rancher pod recreated on another node rather than the same with VIP
10. Use `reinstall_harvester_node.sh` to install node 4
11. Check can join node4 with PXE boot installation

### Additional Context
After PXE boot install 3 nodes harvester, rancher pod and VIP on the same host node 1
```
rancher@harvester-node-0:~> sudo -i kubectl get pods -l app=rancher -n cattle-system -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE               NOMINATED NODE   READINESS GATES
rancher-7c6ffbc8d8-mp9sj   1/1     Running   0          35m   10.52.1.9    harvester-node-1   <none>           <none>
rancher-7c6ffbc8d8-pns55   1/1     Running   0          47m   10.52.0.64   harvester-node-0   <none>           <none>
rancher@harvester-node-0:~> hostname
harvester-node-0
```

delete rancher pod on node 1 to recreate on different node
```
$ curl -k https://192.168.0.131:443/ping
pong
$ curl -k https://192.168.0.131:8443/ping
pong
```
recreated rancher pod locate on different node with the VIP
```
rancher@harvester-node-0:~> sudo -i kubectl get pods -l app=rancher -n cattle-system -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE               NOMINATED NODE   READINESS GATES
rancher-7c6ffbc8d8-42h9z   0/1     Running   0          26s   10.52.2.12   harvester-node-2   <none>           <none>
rancher-7c6ffbc8d8-mp9sj   1/1     Running   0          42m   10.52.1.9    harvester-node-1   <none>           <none>
```

**Comment by TachunLin** [comment] 2022-02-08 11:29
According to above test result. 
Verified fixed to add node 4 in the following scenario on master-1a861fc1-head (02/07/22). Close this issue.

- [x] ISO installation for VIP node join scenario
- [x] PXE Boot for VIP node join scenario

**Closed as completed by TachunLin** 2022-02-08 11:29 UTC
Labels: kind/bug, area/control-plane, area/installer, priority/0

**Comment by fadjar340** [comment] 2022-02-13 14:06
Hi...

Since I have more than 4 nodes, the problem in the 
```
$ curl -k https://192.168.0.131:443/ping
pong
$ curl -k https://192.168.0.131:8443/ping
pong
```
The pod of:
```
rancher@harvester-node-0:~> sudo -i kubectl get pods -l app=rancher -n cattle-system -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE               NOMINATED NODE   READINESS GATES
rancher-7c6ffbc8d8-mp9sj   1/1     Running   0          35m   10.52.1.9    harvester-node-1   <none>           <none>
rancher-7c6ffbc8d8-pns55   1/1     Running   0          47m   10.52.0.64   harvester-node-0   <none>           <none>
```

Both pods should be in the first 3 nodes.
Since I add the deployment of rancher in the node scheduling as follow:
```
Key | operator | value
kubernetes.io/hostname | in list | node01,node02,node03
```
Then the resources :443 and : 8443 always pong.


Regards,
Fadjar Tandabawana
