### ISSUE TITLE
[BUG] When enable network controller in PCI Devices passthrough, the current node cordoned with Kubelet stopped posting node status.

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2960] opened 2022-10-17 14:39 UTC
**Describe the bug**

When we enable the PCI device addon then enable network controller devices of current nodes 
![image](https://user-images.githubusercontent.com/29251855/196203359-1ece5325-fc7b-4f56-99bf-6149e85f3e08.png)

The current node can't be reached, display cordoned status with error `Kubelet stopped posting node status.`
![image](https://user-images.githubusercontent.com/29251855/196204499-ba381038-6c42-4f9e-b793-fd6db816a30c.png)

While the Ethernet controller keep displaying `In Progress` 
![image](https://user-images.githubusercontent.com/29251855/196205074-82234fb6-0d68-42b0-89c9-4ea68b984787.png)

**To Reproduce**
1. Go to Addons page
2. Enable PCI devices 
3. Wait for the PCI devices addon deployed successfully
  ![image](https://user-images.githubusercontent.com/29251855/196205324-5d990ca1-6ae4-401a-9a5c-99d3bf1857ad.png)
4. Go to PCI Devices page
5. Click group by device
6. Find the devices under `Ethernet controller` group
7. Enable the passthrough of Ethernet controller device
8. Check the Host status 

**Expected behavior**

The availability of Ethernet devices enabled should not made the node cordoned and unable to access

**Support bundle**

[supportbundle_e162b3db-9b2d-4046-bfad-7e6a9210852f_2022-10-17T14-43-09Z.zip](https://github.com/harvester/harvester/files/9801648/supportbundle_e162b3db-9b2d-4046-bfad-7e6a9210852f_2022-10-17T14-43-09Z.zip)

**Environment**
 - Harvester ISO version: 4 nodes Harvester on bare metal machines
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): `master-3c164f95-head` (10/17 before cut rc3)

**Additional context**
If we enable all the network controller in the same time by clicking the `Enable Group`
Then we are no longer able to access Harvester dashboard through VIP, The connection to VIP will lost

**Comment by tlehman** [comment] 2022-10-20 21:03
Was that network interface the management interface?

**Comment by bk201** [comment] 2022-10-21 03:47
It should be the management interface. We create an [issue](https://github.com/harvester/harvester/issues/3003) to add a warning before users enable any device.

**Comment by tlehman** [comment] 2022-10-27 21:31
Since #3003  is closed, can we close this issue?

**Comment by guangbochen** [comment] 2022-10-28 02:50
would prefer to filter out those harvester-owned devices on the UI by labels, so it will prevent wrong operations from bringing down/damaging the cluster.

**Comment by tlehman** [comment] 2022-11-29 18:58
So what are the next steps on this issue? The problem sounds like the management interface was enabled for passthrough, which will cause the node to become inaccessible (explains the cordoned status).

Based on @guangbochen 's comment above, it sounds like the next step is to do the UI labeling/filtering to prevent the management interface from showing up, is that right?

**Comment by tlehman** [comment] 2022-11-29 19:58
This [feature request](https://github.com/harvester/harvester/issues/3199)  sounds like it's a duplicate with this bug ticket. Should we close either? Or keep them both open and then close them when the feature is done and the bug is confirmed as fixed?

**Comment by guangbochen** [comment] 2022-11-30 00:43
if that's the only case, we can close it because of the duplication. But can we double-check first that when the node is not available, will the pci-deivces show properly on the UI, if not would prefer to fix it on both the backend and UI, thanks?

**Comment by tlehman** [comment] 2022-11-30 02:03
@guangbochen I'm not sure I understand, the pcidevices are stored in the cluster's etcd, so whether or not the node is available, those objects will be available. Currently the PCI Devices controller doesn't delete the objects, but that suggests a feature request. I made it here: https://github.com/harvester/harvester/issues/3224

**Comment by guangbochen** [comment] 2022-11-30 02:08
We can list and watch the node status and then update the PCI devices' status accordingly if needed.

**Comment by tlehman** [comment] 2023-02-10 00:15
Is this still an issue?

**Comment by guangbochen** [comment] 2023-02-20 08:21
cc @ibrokethecloud can u PTAL to see if ur PR https://github.com/harvester/pcidevices/pull/41 will address the above issue?

**Comment by ibrokethecloud** [comment] 2023-02-20 09:08
duplicate of issue: https://github.com/harvester/harvester/issues/3199

v1.1.2-rc1 already has the fixes to skip mgmt-bo and mgmt-br interfaces.

The second PR will also skip interfaces used for custom cluster networks.

**Comment by bk201** [comment] 2023-02-20 09:08
Close as this is duplicated.

**Closed as completed by bk201** 2023-02-20 09:08 UTC
Labels: kind/bug, area/network, priority/1, severity/1, reproduce/always, area/device-passthrough
