### ISSUE TITLE
Saving the network-setting failed

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#309] opened 2020-12-08 08:28 UTC
**Steps to reproduce:**
1. On the settings page, edit the network-setting, remove the Physical NIC, then save
2. Edit it again, fill in the Physical NIC again, then save

**Result:**
Save failed, along with an error message
`Operation cannot be fulfilled on settings.harvester.cattle.io "network-setting": the object has been modified; please apply your changes to the latest version and try again`
![image](https://user-images.githubusercontent.com/57614736/101458502-ee7a1d00-3971-11eb-8de2-b28e279e267b.png)

**Comment by guangbochen** [comment] 2021-04-02 08:16
duplicate of https://github.com/rancher/harvester/issues/594

**Closed as completed by guangbochen** 2021-04-02 08:16 UTC
Labels: kind/bug, area/ui
