### ISSUE TITLE
[BUG] SupportBundle enhancement

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#839] opened 2021-05-10 03:07 UTC
**Describe the bug**
When the websocket is disconnected, the progress bar will be stuck at 97%. I hope that the function can be used normally when the websocket is disconnected.

**Comment by guangbochen** [comment] 2021-05-10 05:20
duplicate of https://github.com/harvester/harvester/issues/783, should be able to get addressed when the backup adds more tracking status.

**Closed as completed by guangbochen** 2021-05-10 05:20 UTC
Labels: kind/bug, area/ui
