### ISSUE TITLE
[BUG] Multiple nodes pre-drains in an upgrade

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3216] opened 2022-11-28 06:22 UTC
**Describe the bug**

(This is initially tracked in https://github.com/rancher/rancher/issues/39167. We create one to track on the Harvester side.)
During an upgrade, multiple nodes are cordoned off. The consequence is the upgrade might be stuck waiting for volumes to become healthy.

**To Reproduce**
1. Upgrade from v1.0.3 to v1.1.0. Or v1.1.0 to v1.1.1.
2. Seeing this:
    <img width="564" alt="Screen Shot 2022-11-28 at 12 25 10 PM" src="https://user-images.githubusercontent.com/1691518/204207150-5ca6d715-55a0-4373-a49d-bc916aaf3168.png">
3. And more than one node have scheduling disabled.

    ```
    $ kubectl get nodes
    NAME    STATUS                     ROLES                       AGE   VERSION
    node1   Ready                      control-plane,etcd,master   20d   v1.24.7+rke2r1
    node2   Ready,SchedulingDisabled   control-plane,etcd,master   20d   v1.24.7+rke2r1
    node3   Ready,SchedulingDisabled   control-plane,etcd,master   20d   v1.24.7+rke2r1
    ```

**Expected behavior**

Only one node should be cordoned off during the upgrade.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0/v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment] 2022-11-28 06:31
The following is the workaround to this issue.
- From the GUI, we know `node2` is the upgrading node (pre-draining):
    <img width="564" alt="Screen Shot 2022-11-28 at 12 25 10 PM" src="https://user-images.githubusercontent.com/1691518/204209082-fefdec8f-4b89-4813-b40d-591077e75e80.png">

- Verify multiple nodes have scheduling disabled:
    ```
    $ kubectl get nodes
    NAME    STATUS                     ROLES                       AGE   VERSION
    node1   Ready                      control-plane,etcd,master   20d   v1.24.7+rke2r1
    node2   Ready,SchedulingDisabled   control-plane,etcd,master   20d   v1.24.7+rke2r1
    node3   Ready,SchedulingDisabled   control-plane,etcd,master   20d   v1.24.7+rke2r1
    ```
- Check the pre-drain job, it should wait for volumes to become healthy:
    ```
    # get the pending upgrade
    $ kubectl get upgrades.harvesterhci.io -n harvester-system --selector=harvesterhci.io/latestUpgrade=true
    NAME                 AGE
    hvst-upgrade-7b597   26m
    
    # list jobs of the upgrade
    $ kubectl get jobs -n harvester-system --selector=harvesterhci.io/upgrade=hvst-upgrade-7b597
    NAME                                  COMPLETIONS   DURATION   AGE
    hvst-upgrade-7b597-apply-manifests    1/1           6m2s       21m
    hvst-upgrade-7b597-post-drain-node1   1/1           2m53s      12m
    hvst-upgrade-7b597-pre-drain-node1    1/1           9s         15m
    hvst-upgrade-7b597-pre-drain-node2    0/1           7m49s      7m50s
    
    # View the non-completed job:
    $ kubectl logs -f -n harvester-system jobs/hvst-upgrade-7b597-pre-drain-node2
    <...>
    ++ kubectl get volumes.longhorn.io/pvc-24607080-9077-4db3-bfa0-fb295bd3ecfa -n longhorn-system -o 'jsonpath={.status.robustness}'
    Waiting for volume pvc-24607080-9077-4db3-bfa0-fb295bd3ecfa to be healthy...
    + robustness=degraded
    + '[' degraded = healthy ']'
    + '[' -f /tmp/skip-pvc-24607080-9077-4db3-bfa0-fb295bd3ecfa ']'
    + echo 'Waiting for volume pvc-24607080-9077-4db3-bfa0-fb295bd3ecfa to be healthy...'
    + sleep 10
    ```
- [Visit Longhorn GUI](https://docs.harvesterhci.io/v1.1/troubleshooting/harvester#access-embedded-longhorn). Go to the Volumes page and check the volume status:
    <img width="1136" alt="Screen Shot 2022-11-28 at 12 29 05 PM" src="https://user-images.githubusercontent.com/1691518/204208801-7a633b04-89dc-4764-a9ac-75e50ba74c4e.png">
    The last replica is on the accidentally-cordoned node `node3`. In this case, we can uncordon the node continue the upgrade:
    ```
    $ kubectl uncordon node3
    ```

**Comment by guangbochen** [comment] 2023-04-27 08:30
Depends on the upstream fix of https://github.com/rancher/rancher/issues/39167, this is planned in the Rancher v2.7-Q2 release.

**Comment by starbops** [comment] 2023-05-26 02:55
Since rancher/rancher#41459 was merged, we can start integrating Harvester with Rancher v2.7-head to test if the multi-cordon issue happens during Harvester upgrades.

**Comment by bk201** [comment] 2023-05-26 03:07
We can bump Rancher to 2.7.5-rc2 to verify.

**Comment by starbops** [comment] 2023-07-10 07:52
# Test plan

1. Prepare a multi-node (at least 3 nodes) cluster in v1.1.2
2. Upgrade the cluster with v1.2.0-rc3/master ISO image; the point is to include Rancher v2.7.5
3. Keep an eye on the upgrade progress when it proceeds to the "node upgrade" phase ([the phase 4](https://docs.harvesterhci.io/assets/images/ts_upgrade_phases-7336371ca32df446a0f9da46e79729b6.png))

To check whether an upgrade proceeds to the "node upgrade" phase, see the `NodesUpgraded` condition. When the condition shows up and its status is `Unknown`, means the nodes are starting to be upgraded:
```
$ kubectl -n harvester-system get upgrades <upgrade-name> -o yaml | yq e '.status.conditions'
- status: Unknown
  type: Completed
- lastUpdateTime: "2023-07-10T07:46:33Z"
  status: "True"
  type: LogReady
- lastUpdateTime: "2023-07-10T07:46:57Z"
  status: "True"
  type: ImageReady
- lastUpdateTime: "2023-07-10T07:48:03Z"
  status: "True"
  type: RepoReady
- lastUpdateTime: "2023-07-10T07:48:31Z"
  status: "True"
  type: NodesPrepared
- lastUpdateTime: "2023-07-10T07:50:27Z"
  status: "True"
  type: SystemServicesUpgraded
- status: Unknown
  type: NodesUpgraded
```

Each node should be cordon **ONE AT A TIME** like the following:
```
$ kubectl get nodes
NAME    STATUS                     ROLES                       AGE   VERSION
node-0   Ready                      control-plane,etcd,master   20d   v1.25.9+rke2r1
node-1   Ready,SchedulingDisabled   control-plane,etcd,master   20d   v1.24.11+rke2r1
node-2   Ready                      control-plane,etcd,master   20d   v1.24.11+rke2r1
```

Things like the following **SHOULD NOT HAPPEN**:
```
$ kubectl get nodes
NAME    STATUS                     ROLES                       AGE   VERSION
node-0   Ready                      control-plane,etcd,master   20d   v1.25.9+rke2r1
node-1   Ready,SchedulingDisabled   control-plane,etcd,master   20d   v1.24.11+rke2r1
node-2   Ready,SchedulingDisabled   control-plane,etcd,master   20d   v1.24.11+rke2r1
```

If it did happen, please collect the support bundle and download the upgrade log archive.

4. The upgrade should be successful, and no multi-cordon situation happened during the "node upgrade" phase

**Comment by lanfon72** [comment] 2023-07-11 15:22
Reproduce **4** times with **v1.1.2** upgrade to **v1.2.0-rc3**, not encountered this bug, close as fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1.2** upgrade to **v1.2.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Perform upgrade[^1]
3. Login to last node, execute command `watch -n 5 "kubectl get nodes | grep SchedulingDisabled | wc -l | tee -a counts"`
4. Wait until upgrade completed
5. Login to last node, execute command `uniq counts`, values should be `0` or `1`


[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade

**Closed as completed by lanfon72** 2023-07-11 15:22 UTC
Labels: kind/bug, priority/0, severity/2, area/embedded-rancher, reproduce/often

**Comment by albinsun** [comment] 2023-12-12 15:34
Hi @starbops,

For `v1.1.1` installations, is there any workaround except monitoring upgrade status and uncordon manually?
Since in recent upgrade test from `v1.1.1` to `v1.1.3-rc2`, at least in qemu/kvm (ipxe-example) env., there is a high chance to hit this issue (even more than one times).
