### ISSUE TITLE
add v3 schema check on harvester ui

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#522] opened 2021-03-11 04:15 UTC
install Harvester without rancher integration e.g the App mode installation, the Harvester UI should not either be crashed or blocked by /v3 schema not found error.

**Comment by kingsd041** [comment] 2021-04-06 07:29
Validated on v0.2.0-rc1

I can't reproduce it, close it.
If you still have doubts, please reopen it and let me know.

**Closed as completed by kingsd041** 2021-04-06 07:29 UTC
Labels: kind/bug, area/ui
