### ISSUE TITLE
[BUG] Duplicate extra disk entry

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1795] opened 2022-01-11 06:14 UTC
**Describe the bug**
A duplicate disk entry is created when adding storage/disks via the UI

**To Reproduce**
1. Add Disk via UI
2. System asked to reboot because the disk partition could not be read by the kernel
3. Rebooted, then two entries for the new disk appear in the UI.

**Expected behavior**
No Warning, no duplicate disk entries.

**Environment:**
 - Harvester ISO version: 1.0
 - Underlying Infrastructure: Dell R620

**Additional context**

![Screen Shot 2022-01-11 at 1 10 17 AM](https://user-images.githubusercontent.com/5146963/148890730-6c6c68d1-5c4f-45d1-8989-453cd853144b.png)

**Comment by weihanglo** [comment] 2022-02-10 06:24
Related to #1718

**Comment by erSitzt** [comment] 2022-02-15 21:02
Same here after rebooting the node.
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/1625376/154148557-f40acdcc-2ae8-4e1a-84f8-a556dc63dd77.png">

**Comment by weihanglo** [comment] 2022-03-07 08:07
This should be fixed once #1718 is resolved.

**Comment by weihanglo** [comment] 2022-03-11 09:40
This should be a duplicate of #1718. Any subsequent updates and verifications will be posted there. Closing.

**Closed as completed by weihanglo** 2022-03-11 09:40 UTC
Labels: kind/bug, priority/0, area/node-disk-mgmt
