### ISSUE TITLE
[BUG] registration of Harvester cluster in Rancher prime fails

### ISSUE THREAD

**Issue by m-ildefons** [harvester/harvester#5723] opened 2024-05-02 07:41 UTC
**Describe the bug**

Registration process of a Harvester cluster does not complete successfully in Rancher Prime

**To Reproduce**
1. Install Harvester cluster (e.g. v1.2.2-rc1)
2. Install Rancher in a prime-only version (e.g. v2.7.12)
3. Try to register Harvester cluster in Rancher

**Expected behavior**
The registration process should complete without error and the Harvester cluster should be available in the Rancher UI for management.

**Environment**
 - Harvester ISO version: v1.2.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare-metal

**Additional context**
Log excerpt from the rancher-agent cleanup job:

```
 ErrImagePull (rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/rancher-agent:v2.7.12": failed to resolve reference "docker.io/rancher/rancher-agent:v2.7.12": docker.io/rancher/rancher-agent:v2.7.12: not found) 
```

The problem here seems to be a misconfiguration of Rancher's registration job as in case of a prime-only version of Rancher the image is not available from `docker.io` but needs to be pulled from the rancher-prime registry.

**Comment by innobead** [comment] 2024-05-02 07:45
cc @bk201 @FrankYang0529

**Comment by bk201** [comment] 2024-05-06 03:33
I can't reproduce this. `cattle-cluster-agent` pods run with prime images.
The `cattle-cleanup` pod runs with a non-existent community image after deleting the Harvester cluster, it might be worth filing an issue in Rancher.

**Comment by ibrokethecloud** [comment] 2024-05-06 03:52
the manifest for agent is generated via this template: https://github.com/rancher/rancher/blob/release/v2.7/pkg/systemtemplate/template.go#L3

That seems to be generated from here: https://github.com/rancher/rancher/blob/release/v2.7/pkg/systemtemplate/import.go#L161

Might be useful to check what the cluster spec and also the setting is pointing to.

**Comment by albinsun** [comment] 2024-05-06 05:44
FYR, I tried to reproduce on my ecm machine but in vain.


1. <details>
   <summary> Fresh install <code>harvester-v1.2.2-rc1</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/7ab43c91-1039-4440-ad09-97e36b52fb60)
   </details>

1. <details>
   <summary> SSH to node-0, download <code>rancher-vcluster.yaml</code>, also a copy <code>rancher-vcluster.yaml.orig</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/8338551d-7c11-41b7-9031-5ed185e80ec3)
   </details>
   
   * Ref. https://docs.harvesterhci.io/v1.2/advanced/addons/rancher-vcluster/

1. <details>
   <summary> Edit <code>rancher-vcluster.yaml</code> w/ rancher-prime values and apply
   </summary> 
   
   ![image](https://github.com/harvester/harvester/assets/2773781/ee25982a-fcf9-4c8e-8def-4da307fb0836)
   </details>

1. <details>
   <summary> Follow https://docs.harvesterhci.io/v1.2/advanced/addons/rancher-vcluster/ to enable rancher-vcluster
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/5c348522-0b7c-4fe9-ae8b-5408e1026e00)
   </details>



1. <details>
   <summary> Import Harvester to Rancher
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/23a7003e-51ba-47e6-89f6-cbcfb1de2a0f)
   ![image](https://github.com/harvester/harvester/assets/2773781/82e534c4-3e22-4b4a-a4ce-0da7eb149956)
   </details>

   ![image](https://github.com/harvester/harvester/assets/2773781/2fae6c6f-6207-4ab8-8d30-da4d8dfd4fd4)

**Comment by m-ildefons** [comment] 2024-05-07 06:57
I've done some more debugging yesterday and ended up finding out that the image pull error and the failing cluster import are unrelated.
The image pull error originates from a cleanup job, which is spawned by the Rancher agent when the Harvester cluster's `cluster-registration-url` is set to empty.
The cluster import failing is a bug in Rancher's handling of user-input. If a user configures Rancher with a server URL that has a trailing `/` character and Rancher is running behind an Nginx ingress proxy, the import process fails due to the Rancher agent trying to connect with a wrong API path.
I've filed two separate bugs against Rancher:
https://github.com/rancher/rancher/issues/45404
https://github.com/rancher/rancher/issues/45403
Feel free to close this issue, as I believe there isn't anything more to be done for the Harvester team here.

**Comment by khushboo-rancher** [comment] 2024-05-07 22:24
Thanks @m-ildefons, closing this as per @m-ildefons debugging. 
Also, we have seen passed test result with Rancher prime.

**Closed as completed by khushboo-rancher** 2024-05-07 22:24 UTC
Labels: kind/bug, require/investigate, severity/1, area/embedded-rancher, require/reproduce
