### ISSUE TITLE
[ENHANCEMENT] Create ippools.network.harvesterhci.io objects with ease

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5045] opened 2024-01-29 11:19 UTC
**Is your enhancement related to a problem? Please describe.**

Creating IPPool objects (under the API group `network.harvesterhci.io`) is a bit painful. Users need to explicitly specify the pool's range despite the subnet already being given. The DHCP server's IP must also be determined. These configurations are fine-grained details that users can manipulate. However, chances are users don't bother filling in that information. Without the `serverIP`, `start`, and `end` fields being provided, vm-dhcp-controller cannot work correctly.

**Describe the solution you'd like**

Add an IPPool mutator to help fill in those fields with sane defaults according to the other provided fields, such as `cidr` or `router`.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by lanfon72** [comment] 2024-03-05 16:26
@starbops please add milestone, thanks.

**Comment by irishgordo** [comment] 2024-03-05 22:02
**Validation Issue;**

@starbops I'm not able to get this to load in.

My flow for getting this rigged up was:

1. Disable Addon.
2. Log on to a given Harvester node, `sudo su` then blow away the images with `crictl`:
```
crictl rmi docker.io/rancher/harvester-vm-dhcp-agent:main-head docker.io/rancher/harvester-vm-dhcp-agent:v0.2.1 docker.io/rancher/harvester-vm-dhcp-controller:main-head docker.io/rancher/harvester-vm-dhcp-controller:v0.2.1 docker.io/rancher/harvester-vm-dhcp-webhook:v0.2.1 docker.io/rancher/harvester-vm-dhcp-webhook:main-head
```
3. Jump back into the addons
4. Edit Config of addon, providing valuesContent of:
```
  valuesContent: |
    image:
      pullPolicy: Always
      tag: main-head
    agent:
      image:
        pullPolicy: Always
        tag: main-head
    webhook:
      image:
        pullPolicy: Always
        tag: main-head
```
3. Enable Addon, but before clicking the Save, check "Edit as YAML" to validate ValuesContent was populated
4. Allow rollout to take place
5. Audit the content, to ensure the valuesContent was reflected appropriately per service like:
```
kubectl edit rs/harvester-vm-dhcp-controller -n harvester system

^ checking the imagePullPolicy / pullPolicy and the image & tag
```
6. Attempt to create the following YAML
```
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    cidr: 192.168.30.1/24
  networkName: default/test-net
```
7. It fired an error complaining about webhook validation:
```
error: error validating "../ippool-autofill.yaml": error validating data: [ValidationError(IPPool.spec.ipv4Config): missing required field "pool" in io.harvesterhci.network.v1alpha1.IPPool.spec.ipv4Config, ValidationError(IPPool.spec.ipv4Config): missing required field "serverIP" in io.harvesterhci.network.v1alpha1.IPPool.spec.ipv4Config]; if you choose to ignore these errors, turn validation off with --validate=false
```

So my best guess, is that for the:
- vm-dhcp-controller
- vm-dhcp-controller-webhook
- vm-dhcp-controller-agent

It's not got the most recent code in the image?

I'm noticing on a node with `crictl` it seems to only have the main-head images which look appropriate:
```
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065/vm-dhcp-controller on main✔
╰─± ssh rancher@192.168.12.69
(rancher@192.168.12.69) Password: 
Last login: Tue Mar  5 21:52:57 2024 from 192.168.9.163
rancher@node5-v121:~> sudo su
node5-v121:/home/rancher # crictl images | grep -ie "vm"
docker.io/rancher/harvester-vm-dhcp-controller                              main-head                                   4df1c01448726       67.2MB
docker.io/rancher/harvester-vm-dhcp-webhook                                 main-head                                   491a6e5c82f21       66.9MB
docker.io/rancher/harvester-vm-import-controller                            v0.1.5                                      b7d628dac3772       255MB
docker.io/rancher/harvester-vm-import-controller                            v0.1.7                                      1e380af070705       261MB
registry.suse.com/suse/vmdp/vmdp                                            2.5.4.2                                     90567499610d4       66.3MB

```

**Comment by irishgordo** [comment] 2024-03-05 22:59
**Validation Issue Cont.**

@starbops after some digging I realized we need:

https://hub.docker.com/r/rancher/harvester-vm-dhcp-webhook/tags - at v0.3.0
https://hub.docker.com/r/rancher/harvester-vm-dhcp-controller/tags - at v0.3.0
https://hub.docker.com/r/rancher/harvester-vm-dhcp-agent/tags - at v0.3.0

And not `main-head`

So rolling out then:
```yaml

apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  creationTimestamp: '2024-03-05T22:15:56Z'
  generation: 2
  labels:
    addon.harvesterhci.io/experimental: 'true'
  managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:addon.harvesterhci.io/experimental: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:version: {}
      manager: kubectl-create
      operation: Update
      time: '2024-03-05T22:15:56Z'
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
          f:valuesContent: {}
      manager: harvester
      operation: Update
      time: '2024-03-05T22:17:00Z'
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: '2024-03-05T22:17:10Z'
  name: harvester-vm-dhcp-controller
  namespace: harvester-system
  resourceVersion: '1613438'
  uid: e0892daa-b299-442d-ab66-a95f6ccc61ad
spec:
  chart: harvester-vm-dhcp-controller
  enabled: true
  repo: https://charts.harvesterhci.io/
  valuesContent: |
    image:
      pullPolicy: Always
      tag: v0.3.0
    agent:
      image:
        pullPolicy: Always
        tag: v0.3.0
    webhook:
      image:
        pullPolicy: Always
        tag: v0.3.0
  version: v0.2.0
status:
  conditions:
    - lastUpdateTime: '2024-03-05T22:17:10Z'
      status: 'True'
      type: Completed
    - lastUpdateTime: '2024-03-05T22:17:10Z'
      status: 'False'
      type: InProgress
    - lastUpdateTime: '2024-03-05T22:15:56Z'
      status: 'False'
      type: OperationFailed
  status: AddonDeploySuccessful
```

But, while the images download at v0.3.0 for the respective elements, the chart version is still old.

```bash

╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065/vm-dhcp-controller on main✔
╰─± helm search repo harvester -l --devel | grep -ie "vm-dhcp-controller"
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/mike/Downloads/local(130).yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/mike/Downloads/local(130).yaml
harvester/harvester-vm-dhcp-controller   	0.2.0           	v0.2.1     	A Helm chart for Harvester VM DHCP Controller    
harvester/harvester-vm-dhcp-controller   	0.1.0           	v0.1.0     	A Helm chart for Harvester VM DHCP Controller    
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065/vm-dhcp-controller on main✔
```

As I tried to additionally pass in the `--devel` flag for the harvester helm repo and still only noticing:
- v0.2.0
- v0.1.0

And was expecting to be able to do something like:
```yaml
chart: harvester-vm-dhcp-controller
  enabled: true
  repo: https://charts.harvesterhci.io/
  valuesContent: |
    image:
      pullPolicy: Always
      tag: v0.3.0
    agent:
      image:
        pullPolicy: Always
        tag: v0.3.0
    webhook:
      image:
        pullPolicy: Always
        tag: v0.3.0
  version: v0.3.0
```

But I notice that ^ that doesn't work, causing a ContainerCreating -> Error Image Pull Backoff, with the suggestion to update helm.

Even with helm there's no corresponding v0.3.0 version.


Trying again to run the loadout with all elements at v0.3.0 and then version at v0.2.0 with the yaml of:
```yaml
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    cidr: 192.168.30.1/24
  networkName: default/test-net
```

I'm still seeing errors of:
```
kubectl create -f ../ippool-autofill.yaml
error: error validating "../ippool-autofill.yaml": error validating data: [ValidationError(IPPool.spec.ipv4Config): missing required field "pool" in io.harvesterhci.network.v1alpha1.IPPool.spec.ipv4Config, ValidationError(IPPool.spec.ipv4Config): missing required field "serverIP" in io.harvesterhci.network.v1alpha1.IPPool.spec.ipv4Config]; if you choose to ignore these errors, turn validation off with --validate=false

```

Is there perhaps a separate charts repo for "dev" / "alpha" Harvester charts something besides:
```
NAME                  	URL                                                             
harvester             	https://charts.harvesterhci.io                                  
```
that I should be using?

To ensure all code-changes are bundled into the corresponding rs, svc, etc for vm-dhcp-addon?

**Comment by starbops** [comment] 2024-03-07 10:20
Hi @irishgordo Sorry for the late reply. The `0.3.0` chart has just released, it should be ok now :)

And please drop the `v` character for the chart version. Only AppVersion has a `v` prefix.

**Comment by irishgordo** [comment] 2024-03-08 00:24
**Validation Issue**

@starbops thanks for that mention - after updating

With a loadout of:
```yaml

apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  creationTimestamp: '2024-03-08T00:15:23Z'
  generation: 3
  labels:
    addon.harvesterhci.io/experimental: 'true'
  managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:addon.harvesterhci.io/experimental: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
      manager: kubectl-create
      operation: Update
      time: '2024-03-08T00:15:23Z'
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
          f:valuesContent: {}
          f:version: {}
      manager: harvester
      operation: Update
      time: '2024-03-08T00:18:44Z'
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: '2024-03-08T00:18:54Z'
  name: harvester-vm-dhcp-controller
  namespace: harvester-system
  resourceVersion: '111341'
  uid: 1bad56fc-750d-4681-9879-d104e3dad8dc
spec:
  chart: harvester-vm-dhcp-controller
  enabled: true
  repo: https://charts.harvesterhci.io
  valuesContent: |
    image:
      pullPolicy: Always
      tag: v0.3.0
    agent:
      image:
        pullPolicy: Always
        tag: v0.3.0
    webhook:
      image:
        pullPolicy: Always
        tag: v0.3.0
  version: 0.3.0
status:
  conditions:
    - lastUpdateTime: '2024-03-08T00:18:54Z'
      status: 'True'
      type: Completed
    - lastUpdateTime: '2024-03-08T00:18:54Z'
      status: 'False'
      type: InProgress
    - lastUpdateTime: '2024-03-08T00:15:23Z'
      status: 'False'
      type: OperationFailed
  status: AddonDeploySuccessful

```

I'm still getting:
```
kubectl create -f ippool-autofill.yaml
error: error validating "ippool-autofill.yaml": error validating data: [ValidationError(IPPool.spec.ipv4Config): missing required field "pool" in io.harvesterhci.network.v1alpha1.IPPool.spec.ipv4Config, ValidationError(IPPool.spec.ipv4Config): missing required field "serverIP" in io.harvesterhci.network.v1alpha1.IPPool.spec.ipv4Config]; if you choose to ignore these errors, turn validation off with --validate=false
```

On v1.3.0-rc4.
But if I do:
```
kubectl create -f ippool-autofill.yaml --validate=false
ippool.network.harvesterhci.io/test-net created
```

It is successful.
And does look appropriate as it autofills things:
```yaml
╭─mike at suse-workstation-team-harvester in ~/Projects/test-5065
╰─○ kubectl get ippls.network test-net -o yaml | yq
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  creationTimestamp: "2024-03-08T00:20:19Z"
  generation: 1
  name: test-net
  namespace: default
  resourceVersion: "113268"
  uid: b6aa57b5-7653-4d74-acaa-caaf5dd3faed
spec:
  ipv4Config:
    cidr: 192.168.30.1/24
    pool:
      end: 192.168.30.254
      start: 192.168.30.1
    serverIP: 192.168.30.1
  networkName: default/test-net
status:
  agentPodRef:
    image: rancher/harvester-vm-dhcp-agent:v0.3.0
    name: default-test-net-agent
    namespace: harvester-system
    uid: 4dcfcd51-4cdf-4034-9da6-216670f9d667
  conditions:
    - lastUpdateTime: "2024-03-08T00:20:19Z"
      status: "True"
      type: Registered
    - lastUpdateTime: "2024-03-08T00:20:19Z"
      status: "True"
      type: CacheReady
    - lastUpdateTime: "2024-03-08T00:20:46Z"
      status: "True"
      type: AgentReady
    - lastUpdateTime: "2024-03-08T00:20:19Z"
      status: "False"
      type: Stopped
  ipv4:
    allocated:
      192.168.30.1: RESERVED
    available: 253
    used: 0
  lastUpdate: "2024-03-08T00:20:19Z"

```

When the `ippool-autofil.yaml` was:
```yaml
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: test-net
spec:
  ipv4Config:
    cidr: 192.168.30.1/24
  networkName: default/test-net

```

Are we expecting the user to pass in that flag of?:
```
--validate=false
```

**Comment by irishgordo** [comment] 2024-03-08 02:36
My issue was the kubectl version locally.
On the node the issue isn't encountered.
Things look good - since:
https://github.com/harvester/harvester/issues/5225

I'll go ahead and close this out :smile: :+1: 
Thanks @starbops

**Closed as completed by irishgordo** 2024-03-08 02:36 UTC
Labels: kind/enhancement, area/vm-ipam

**Comment by khushboo-rancher** [comment] 2024-04-08 19:51
@irishgordo Could you please help add the manual tests on test repo?
