### ISSUE TITLE
[BUG] In app mode, log out of harvester, and rancher UI will follow to log out

### ISSUE THREAD

**Issue by kingsd041** [harvester/harvester#603] opened 2021-03-29 09:22 UTC
**Describe the bug**

In app mode, log out of harvester, and rancher UI will follow to log out

**To Reproduce**
1. Log in to rancher UI
2. Access the harvester UI via rancher `Apps`
3. Log out from the harvester UI

**Expected behavior**

Rancher UI should not be log out

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vmware vm

**Additional context**
harvester version：master-67244e23-head

**Comment by guangbochen** [comment] 2021-03-29 10:43
duplicate of https://github.com/rancher/harvester/issues/599

**Closed as completed by guangbochen** 2021-03-29 10:43 UTC
Labels: kind/bug, area/ui
