### ISSUE TITLE
[BUG] upgrade will stuck without any error meessage if the checksum is invalid 

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#5480] opened 2024-03-28 07:44 UTC
### Describe the bug
The upgrade will stuck if we input the checksum like `v`

### To Reproduce
1. Install Harvester with any nodes
2. Create upgrade version
3. Perform upgrade

### Expected behavior
Upgrade should failed with error message

## Environment:
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360G9 3 nodes**
 - Harvester ISO version: **v1.2.1**
 - **ui-source** Option: **Auto**

### Additional context
It would similar  #3123 but the check sum is invalid, in #3123, we will detect that the **inputted** is mismatch to the ISO's, but this issue is, the **inputted** checksum is not a **valid** checksum, maybe length is not enough, or something else.

**Comment by starbops** [comment] 2024-03-28 08:46
For detailed reproduced steps:

1. Create the Version CR with a **malformed** (not just mismatched) checksum string

```shell
$ cat <<EOF | kubectl apply -f -
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  namespace: harvester-system
  name: master
spec:
  isoURL: http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso
  isoChecksum: 'asdf'
EOF
```

2. Check the created Version CR

```shell
$ kubectl -n harvester-system get versions master -o yaml
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"harvesterhci.io/v1beta1","kind":"Version","metadata":{"annotations":{},"name":"master","namespace":"harvester-system"},"spec":{"isoChecksum":"asdf","isoURL":"http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso"}}
  creationTimestamp: "2024-03-28T08:18:45Z"
  generation: 1
  name: master
  namespace: harvester-system
  resourceVersion: "44990"
  uid: c70b4396-9c6c-47b2-b452-56c6eabdba14
spec:
  isoChecksum: asdf
  isoURL: http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso
```

3. Click the "Upgrade" button on the dashboard to start the upgrade
4. Check the created VMImage CR

```shell
$ kubectl -n harvester-system get vmimages hvst-upgrade-r2c77 -o yaml
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  creationTimestamp: "2024-03-28T08:19:25Z"
  finalizers:
  - wrangler.cattle.io/vm-image-controller
  generation: 1
  labels:
    harvesterhci.io/upgrade: hvst-upgrade-r2c77
  name: hvst-upgrade-r2c77
  namespace: harvester-system
  ownerReferences:
  - apiVersion: harvesterhci.io/v1beta1
    kind: Upgrade
    name: hvst-upgrade-r2c77
    uid: 122e89b1-67f7-45ba-82ca-db9680cb971a
  resourceVersion: "45581"
  uid: 52014bce-2e14-479a-b13d-3f401a7170af
spec:
  checksum: asdf
  displayName: hvst-upgrade-r2c77-master
  pvcName: ""
  pvcNamespace: ""
  retry: 3
  sourceType: download
  storageClassParameters:
    migratable: "true"
    numberOfReplicas: "3"
    staleReplicaTimeout: "30"
  url: http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso
status:
  failed: 0
```

5. Check the Harvester Pod's log

```shell
$ kubectl -n harvester-system logs harvester-7bf5959cb6-jpwj7
time="2024-03-28T08:19:25Z" level=info msg="Initialize upgrade harvester-system/hvst-upgrade-r2c77"
time="2024-03-28T08:19:25Z" level=info msg="Upgrade observability is administratively disabled"
W0328 08:19:25.342616       7 warnings.go:70] unknown field "type"
time="2024-03-28T08:19:25Z" level=info msg="Creating upgrade repo image"
time="2024-03-28T08:19:25Z" level=info msg="handle upgrade harvester-system/hvst-upgrade-r2c77 with labels map[harvesterhci.io/latestUpgrade:true harvesterhci.io/upgradeState:LoggingInfraPrepared]"
time="2024-03-28T08:19:25Z" level=error msg="error syncing 'harvester-system/hvst-upgrade-r2c77': handler vm-image-controller: admission webhook \"validator.longhorn.io\" denied the request: invalid checksum asdf, requeuing"
time="2024-03-28T08:19:25Z" level=error msg="error syncing 'harvester-system/hvst-upgrade-r2c77': handler vm-image-controller: admission webhook \"validator.longhorn.io\" denied the request: invalid checksum asdf, requeuing"
...
```

This is because Harvester tries to create the BackingImage CR derived from the VMImage CR but gets denied by the Longhorn validating admission webhook:

https://github.com/longhorn/longhorn-manager/blob/103bcaaae5e080dc93af66bf0f8355c31d2f1b0e/util/util.go#L288-L291

```go
func ValidateChecksumSHA512(checksum string) bool {
    validChecksum := regexp.MustCompile(`^[a-f0-9]{128}$`)
    return validChecksum.MatchString(checksum)
}
```

If you provide it with a valid but mismatched SHA512 hex string, the backing-image-manager will show you the following log lines:

```
$ kubectl -n longhorn-system logs backing-image-ds-harvester-system-hvst-upgrade-7ht7c -f      
time="2024-03-28T08:25:09Z" level=debug msg="Sync Service: initialized" component=sync-server listen="0.0.0.0:8001"
time="2024-03-28T08:25:09Z" level=info msg="Started sync server at 0.0.0.0:8001"
time="2024-03-28T08:25:10Z" level=debug msg="DataSource Service: initializing" component=data-source-service diskUUID=6c3d7ea2-00ca-49e4-bc12-90cac83d5a35 expectedChecksum=2ee2abb2952fb7d29eaa9b3ce776ff094e56d087e860ac737d0b7cd572f454b2a8e7aadc1634faf0a9b6d4155d036765da7772e2550aab9ad1df7f1f9083dd93 filePath=/data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c name=harvester-system-hvst-upgrade-7ht7c parameters="map[url:http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso]" sourceType=download uuid=4ee3904c
time="2024-03-28T08:25:10Z" level=debug msg="Sync Service: initializing sync file /data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c" component=sync-server listen="0.0.0.0:8001"
time="2024-03-28T08:25:10Z" level=info msg="SyncingFile: cannot to reuse the existing file, will clean it up then start processing: stat /data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c: no such file or directory" component=sync-file filePath=/data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c uuid=4ee3904c
time="2024-03-28T08:25:10Z" level=debug msg="DataSource Service: initialized" component=data-source-service diskUUID=6c3d7ea2-00ca-49e4-bc12-90cac83d5a35 expectedChecksum=2ee2abb2952fb7d29eaa9b3ce776ff094e56d087e860ac737d0b7cd572f454b2a8e7aadc1634faf0a9b6d4155d036765da7772e2550aab9ad1df7f1f9083dd93 filePath=/data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c name=harvester-system-hvst-upgrade-7ht7c parameters="map[url:http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso]" sourceType=download uuid=4ee3904c
time="2024-03-28T08:25:10Z" level=info msg="Started data source server at 0.0.0.0:8000"
time="2024-03-28T08:25:11Z" level=info msg="SyncingFile: start to download sync file from URL http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso" component=sync-file filePath=/data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c uuid=4ee3904c
time="2024-03-28T08:25:11Z" level=debug msg="DataSource Service: datasource file is state starting, the processing is not begin yet" component=data-source-service diskUUID=6c3d7ea2-00ca-49e4-bc12-90cac83d5a35 expectedChecksum=2ee2abb2952fb7d29eaa9b3ce776ff094e56d087e860ac737d0b7cd572f454b2a8e7aadc1634faf0a9b6d4155d036765da7772e2550aab9ad1df7f1f9083dd93 filePath=/data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c name=harvester-system-hvst-upgrade-7ht7c parameters="map[url:http://123.123.123.123:8000/harvester/master/harvester-master-amd64.iso]" sourceType=download uuid=4ee3904c
time="2024-03-28T08:26:20Z" level=debug msg="SyncingFile: failed to get the checksum from a valid config during processing wrap-up, will directly calculated it then"
time="2024-03-28T08:26:30Z" level=error msg="SyncingFile: failed to process sync file: the expected checksum 2ee2abb2952fb7d29eaa9b3ce776ff094e56d087e860ac737d0b7cd572f454b2a8e7aadc1634faf0a9b6d4155d036765da7772e2550aab9ad1df7f1f9083dd93 doesn't match the file actual checksum f2d29671b33f1bdfafca198e2515e75c13ba43130b0c68a06025c79af312f7f3d633322fecfc2a2cec22c6ccd653e250a267dccf8d144dcfbe8db1af3162613c" component=sync-file filePath=/data/tmp/harvester-system-hvst-upgrade-7ht7c-4ee3904c uuid=4ee3904c
```

IMO we have at least two ways to address this, either

- Adding a validating admission webhook for the Version CRD in Harvester's webhook, or
- Handle such a BackingImage CR creation failure to also fail the entire Harvester upgrade

**Comment by bk201** [comment] 2024-06-26 10:16
@lanfon72 should we close this issue? since its backport issues are all closed.

**Comment by lanfon72** [comment] 2024-06-26 11:32
Close as the issue has been verified in backport issues.

**Closed as completed** 2024-06-26 11:31 UTC
Labels: kind/bug, severity/2, require/reprioritize, area/install-upgrade, reproduce/always, backport-needed/1.2.2, backport-needed/1.3.1
