### ISSUE TITLE
[BUG] You can upload an image from you local machine that isn't valid

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1425] opened 2021-10-13 16:47 UTC
**Describe the bug**

You can upload an image from you local machine that isn't valid
**To Reproduce**
1. Try to upload invalid image file to images pageSomething like dmg, or tar.gz |  
**Expected behavior**

You should get an error, or it should be filtering more aggressively on file extension
**Support bundle**

[supportbundle_37983fef-de90-4501-918e-4bcba996be9c_2021-10-13T16-34-17Z.zip](https://github.com/harvester/harvester/files/7340015/supportbundle_37983fef-de90-4501-918e-4bcba996be9c_2021-10-13T16-34-17Z.zip)
**Environment:**
 - Harvester ISO version: `0.3.0`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
I'm not sure what this should be. Currently it allows you to create an invalid image in the images list, it looks like it's filtering via the image upload dialogue, but I'm not sure what it's filtering on.
![Greenshot 2021-10-13 09 31 25](https://user-images.githubusercontent.com/83787952/137177432-7a64e9c2-68cd-4ba0-b706-a14d3e6e403d.png)
![Greenshot 2021-10-13 09 31 46](https://user-images.githubusercontent.com/83787952/137177439-7af1c417-ec92-450e-ad8b-94fc914206a0.png)
![Greenshot 2021-10-12 12 00 32](https://user-images.githubusercontent.com/83787952/137177466-14b1a47e-7eed-4033-81a2-64440b1089e3.png)

**Comment by guangbochen** [comment] 2021-10-14 03:29
duplicate of https://github.com/harvester/harvester/issues/1415

**Closed as completed by guangbochen** 2021-10-14 03:29 UTC
Labels: kind/bug, area/control-plane
