### ISSUE TITLE
[BUG] Rancher upgrade fail: Failed to find system chart "fleet"

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#2011] opened 2022-03-15 10:11 UTC
**Describe the bug**
During the upgrade Rancher step of upgrading Harvester, Rancher failed to upgrade "fleet" due to the following error:
```
[ERROR] available chart version (100.0.2+up0.3.8) for fleet is less than the min version (100.0.3+up0.3.9-rc1) 
[ERROR] Failed to find system chart fleet will try again in 5 seconds: no chart name found
```

It's caused by the `rancher-charts` resource (of `clusterrepo.catalog.cattle.io`) is not updating the cached chart index even if the `gitBranch` is changed:

![image (1)](https://user-images.githubusercontent.com/5047724/158352464-e9ec9e61-ec82-4b2d-8ad5-a3e270342227.png)

Here the `spec.gitBranch` is `dev-v2.6`, but the `status.commit` still shows the old commit. ([`5d21c199`](https://github.com/rancher/charts/commit/5d21c199dc7db29b6a5c755558edf4f6343b4c2b) is a very old).

**To Reproduce**
1. Create a v1.0.0 Harveser cluster (one node would be sufficient)
2. Use `wharfie` to pull the data for upgrading Rancher
    ```
    wharfie rancher/system-agent-installer-rancher:v2.6.4-rc8 ./rancher
    ```
3. `cd` into the pulled data `cd ./rancher`
4. Use the included `helm` to get current values of Rancher and dump it into `values.yaml`
    ```
    $ ./helm get values rancher -n cattle-system -o yaml > values.yaml
    ```
5. Update `values.yaml` to specify the Rancher version to upgrade
    ```
    ...
    rancherImageTag: v2.6.4-rc8
    ...
    ```
6. Use `helm` to upgrade Rancher
    ```
    ./helm upgrade rancher ./*.tgz --namespace cattle-system -f values.yaml
    ```
7. Wait for Rancher deployment to finish then check the log

These steps are basically executing the function `upgrade_rancher()` in [upgrade_manifests.sh](https://github.com/harvester/harvester/blob/de4cec35944ab5e3aee0a3ac17ee1ce44136d4b6/package/upgrade/upgrade_manifests.sh#L13) manually.

**Expected behavior**

fleet should be successfully upgraded.

**Workaround**
1. Remove the following resources from `clusterrepos.catalog.cattle.io`:
    - `rancher-charts`
    - `rancher-partner-charts`
    - `rancher-rke2-charts`
2. Restart `rancher` deployment: `kubectl rollout restart -n cattle-system deployment rancher`

This way, the leader of `rancher` replicas will recreate those deleted `clusterrepos` with the charts embed in Rancher.

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
- Rancher log: [rancher.log](https://github.com/harvester/harvester/files/8252153/rancher.log)

**Comment by bk201** [comment] 2022-03-17 06:09
https://github.com/rancher/rancher/issues/36914

**Comment by tlehman** [comment] 2022-04-11 19:57
I walked through the steps to reproduce this, but used a later version of harvester (on master branch, commit [d0f7376](https://github.com/harvester/harvester/commit/d0f7376)), the upgrade succeeded. 

![image](https://user-images.githubusercontent.com/261552/162819102-2293b14e-4126-4a45-9e37-b3ae681696fe.png)

That particular commit, [d0f7376](https://github.com/harvester/harvester/commit/d0f7376), reverts a workaround for rancher that is tracked on [rancher#37113](https://github.com/rancher/rancher/issues/37113). That rancher issue is closed, and my repro here shows that this issue is solved on the harvester side.

**Comment by rebeccazzzz** [comment] 2022-04-12 00:35
Moved to ~~1.0.3~~ v1.1.0 because associated Rancher fix is being moved to a future release. Also, we now have a workaround for this issue.

**Comment by FrankYang0529** [comment] 2022-07-18 09:13
After testing Harvester master-head with Rancher v2.6.7-rc2, fleet-controller can be upgraded from `v0.3.9` to `v0.3.10-rc2` and rancher-charts clusterrepo is from `release-2.6` to `dev-2.6`.

We can merge https://github.com/harvester/harvester/pull/2516 when we want to bump Rancher to v2.6.7.

**Comment by bk201** [comment] 2022-08-09 01:45
We can bump embedded Rancher to v2.6.7 to test after it's released.

**Comment by FrankYang0529** [comment] 2022-08-24 04:11
I have a draft PR https://github.com/harvester/harvester-installer/pull/325 to bump rancher. However, there is an issue https://github.com/rancher/rancher/issues/38706 when we install harvester on a new cluster.

**Comment by irishgordo** [comment] 2022-10-12 23:03
@FrankYang0529 I was looking into validating this, did we want to validate on `master-head` from v2.6.9-rc3 to v2.6.9-rc4?

On Harvester Version: master-937f333c-head (10/12)
With qemu/kvm

I was able to apply:
```
suse-workstation-team-harvester➜  test_2011  ᐅ  cd rancher 
suse-workstation-team-harvester➜  rancher  ᐅ  export KUBECONFIG=~/Projects/test_2011/master-head-harvester-vm.yaml 
suse-workstation-team-harvester➜  rancher  ᐅ  kubectl get nodes
NAME                         STATUS   ROLES                       AGE    VERSION
harvester-master-iso-10-12   Ready    control-plane,etcd,master   5h9m   v1.24.6+rke2r1
suse-workstation-team-harvester➜  rancher  ᐅ  ls
helm  rancher-2.6.9-rc4.tgz  run.sh
suse-workstation-team-harvester➜  rancher  ᐅ  ./helm get values rancher -n cattle-system -o yaml > values.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/mike/Projects/test_2011/master-head-harvester-vm.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/mike/Projects/test_2011/master-head-harvester-vm.yaml
suse-workstation-team-harvester➜  rancher  ᐅ  cat values.yaml 
antiAffinity: required
bootstrapPassword: admin
features: multi-cluster-management=false,multi-cluster-management-agent=false
hostPort: 0
ingress:
  enabled: false
noDefaultAdmin: false
rancherImage: rancher/rancher
rancherImagePullPolicy: IfNotPresent
rancherImageTag: v2.6.9-rc3
replicas: -3
systemDefaultRegistry: ""
tls: external
useBundledSystemChart: true
suse-workstation-team-harvester➜  rancher  ᐅ  nvim values.yaml 
suse-workstation-team-harvester➜  rancher  ᐅ  cat values.yaml 
antiAffinity: required
bootstrapPassword: admin
features: multi-cluster-management=false,multi-cluster-management-agent=false
hostPort: 0
ingress:
  enabled: false
noDefaultAdmin: false
rancherImage: rancher/rancher
rancherImagePullPolicy: IfNotPresent
rancherImageTag: v2.6.9-rc4
replicas: -3
systemDefaultRegistry: ""
tls: external
useBundledSystemChart: true
suse-workstation-team-harvester➜  rancher  ᐅ  ./helm upgrade rancher ./*.tgz --namespace cattle-system -f values.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/mike/Projects/test_2011/master-head-harvester-vm.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/mike/Projects/test_2011/master-head-harvester-vm.yaml
Release "rancher" has been upgraded. Happy Helming!
NAME: rancher
LAST DEPLOYED: Wed Oct 12 15:25:55 2022
NAMESPACE: cattle-system
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
Rancher Server has been installed.

NOTE: Rancher may take several minutes to fully initialize. Please standby while Certificates are being issued, Containers are started and the Ingress rule comes up.

Check out our docs at https://rancher.com/docs/

If you provided your own bootstrap password during installation, browse to https:// to get started.

If this is the first time you installed Rancher, get started by running this command and clicking the URL it generates:
echo https:///dashboard/?setup=$(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}')

To get just the bootstrap password on its own, run:
kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ "\n" }}'


Happy Containering!
suse-workstation-team-harvester➜  rancher  ᐅ  ./helm get values rancher -n cattle-system -o yaml > post_upgrade_values.yaml
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/mike/Projects/test_2011/master-head-harvester-vm.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/mike/Projects/test_2011/master-head-harvester-vm.yaml
suse-workstation-team-harvester➜  rancher  ᐅ  cat post_upgrade_values.yaml 
antiAffinity: required
bootstrapPassword: admin
features: multi-cluster-management=false,multi-cluster-management-agent=false
hostPort: 0
ingress:
  enabled: false
noDefaultAdmin: false
rancherImage: rancher/rancher
rancherImagePullPolicy: IfNotPresent
rancherImageTag: v2.6.9-rc4
replicas: -3
systemDefaultRegistry: ""
tls: external
useBundledSystemChart: true
suse-workstation-team-harvester➜  rancher  ᐅ  
``` 
Initially there were some errors in the log it looked like (deployments/rancher):
![Screenshot from 2022-10-12 15-29-06](https://user-images.githubusercontent.com/5370752/195462678-49938da6-758d-4b5c-a595-da62060a2214.png)

Then, it seemed to download repo index from https://releases/rancher.com -
![Screenshot from 2022-10-12 15-56-57](https://user-images.githubusercontent.com/5370752/195462851-7235198e-77f2-4219-a5ad-cc68babb3695.png)

But then after those stdout messages in the log it looks like it finished?
![Screenshot from 2022-10-12 15-48-55](https://user-images.githubusercontent.com/5370752/195462560-52e6a434-5776-4ef3-b409-c33aeafe5418.png)

Is that process to be expected?

[supportbundle_cb4a11f9-0f99-4fb7-8c4a-151fadf95c8a_2022-10-12T22-59-10Z.zip](https://github.com/harvester/harvester/files/9769160/supportbundle_cb4a11f9-0f99-4fb7-8c4a-151fadf95c8a_2022-10-12T22-59-10Z.zip)

**Comment by FrankYang0529** [comment] 2022-10-13 13:21
Hi @irishgordo, thanks for your detailed test! Yes, I think the process is expected. Another way to test this issue is that bump harvester from v1.0.3 to v1.1.0-rc2 and check whether the version of `fleet-controller` is changed. Thank you 👍

**Comment by irishgordo** [comment] 2022-10-13 20:58
@FrankYang0529  - I attempted to watch the `fleet-controller` and `rancher` deployment in an attempt to upgrade from v1.0.3 to v1.1.0-rc2, but I was seeing issues in the upgrade process.
I may have been missing something, however?

https://user-images.githubusercontent.com/5370752/195709067-d22f6201-fb22-40d0-a93b-fab5e5722f9d.mp4
(video is sped up)

[supportbundle_d7a95d75-99ff-4475-b7f5-e15ac920f291_2022-10-13T20-54-31Z.zip](https://github.com/harvester/harvester/files/9780618/supportbundle_d7a95d75-99ff-4475-b7f5-e15ac920f291_2022-10-13T20-54-31Z.zip)

**Comment by irishgordo** [comment] 2022-10-13 22:32
@FrankYang0529 thanks for providing me a bit more insight :smile: ! 
So checking the second case you mentioned, upgrading from `v1.0.3` on a single-node to `v1.1.0-rc2` - seems to have worked, from the `fleet-controller`:
```
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:36:48Z" level=info msg="No access to list CRDs, assuming CRDs are pre-created."                                                                                      
fleet-controller-5d9ff8f9df-zqm5m I1013 21:36:48.998706       1 leaderelection.go:248] attempting to acquire leader lease cattle-fleet-system/fleet-controller-lock...                                                     
fleet-controller-5d9ff8f9df-zqm5m I1013 21:36:49.044961       1 leaderelection.go:258] successfully acquired lease cattle-fleet-system/fleet-controller-lock                                                               
fleet-controller-5d9ff8f9df-zqm5m E1013 21:36:50.861266       1 memcache.go:206] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request                               
fleet-controller-5d9ff8f9df-zqm5m E1013 21:36:51.699909       1 memcache.go:206] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request                        
fleet-controller-5d9ff8f9df-zqm5m E1013 21:36:55.867130       1 memcache.go:206] couldn't get resource list for subresources.kubevirt.io/v1: the server is currently unable to handle the request                          
fleet-controller-5d9ff8f9df-zqm5m E1013 21:36:55.867135       1 memcache.go:206] couldn't get resource list for subresources.kubevirt.io/v1alpha3: the server is currently unable to handle the request                    
fleet-controller-5d9ff8f9df-zqm5m E1013 21:36:55.870670       1 memcache.go:104] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request                               
fleet-controller-5d9ff8f9df-zqm5m E1013 21:37:00.873911       1 memcache.go:104] couldn't get resource list for subresources.kubevirt.io/v1alpha3: the server is currently unable to handle the request                    
fleet-controller-5d9ff8f9df-zqm5m E1013 21:37:05.876566       1 memcache.go:104] couldn't get resource list for subresources.kubevirt.io/v1: the server is currently unable to handle the request                          
fleet-controller-5d9ff8f9df-zqm5m E1013 21:37:10.880329       1 memcache.go:104] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request                        
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting gitjob.cattle.io/v1, Kind=GitJob controller"                                                                                        
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting /v1, Kind=ServiceAccount controller"                                                                                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ImageScan controller"                                                                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Bundle controller"                                                                                   
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=BundleDeployment controller"                                                                         
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterGroup controller"                                                                             
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterRegistration controller"                                                                      
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Content controller"                                                                                  
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting /v1, Kind=ConfigMap controller"                                                                                                     
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=RoleBinding controller"                                                                          
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"                                                                   
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=Cluster controller"                                                                                  
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=Role controller"                                                                                 
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting /v1, Kind=Secret controller"                                                                                                        
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=GitRepoRestriction controller"                                                                       
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=ClusterRegistrationToken controller"                                                                 
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=GitRepo controller"                                                                                  
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting fleet.cattle.io/v1alpha1, Kind=BundleNamespaceMapping controller"                                                                   
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRole controller"                                                                          
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="Starting /v1, Kind=Namespace controller"                                                                                                     
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:10Z" level=info msg="All controllers have been started"                                                                                                           
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:32Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:94c9146b24ef7c96ad11fe8bbbe4e2548802f21d]) 1.002448781s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:33Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:2e7a88e501de42c6185c99456f7a93f263ff9050]) 1.000417394s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:34Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:2e7a88e501de42c6185c99456f7a93f263ff9050]) 1.014982013s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:35Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:8f9c7460cde5c8859324b5e2043f60d877bc31c4]) 1.002800878s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:35Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:6ab6580457879680a221401c2207e295a2b29213]) 1.003120496s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:35Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:ea476abea833a7a049113cc1ff17bd777c8e3889]) 1.00663459s"                                 
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:41Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:0f24c6e62b33db3f574f05fecc96beddb0dc2d09]) 1.009760138s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:41Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:2e7a88e501de42c6185c99456f7a93f263ff9050]) 1.000701065s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:44Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:2e7a88e501de42c6185c99456f7a93f263ff9050]) 1.000379704s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:50Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:56498b2b99c518c1749e0cff5d0875eda2e8589f]) 1.002632719s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:51Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:ea476abea833a7a049113cc1ff17bd777c8e3889]) 1.001081645s"                                
fleet-controller-5d9ff8f9df-zqm5m time="2022-10-13T21:37:51Z" level=info msg="rate limited bundle(map[objectset.rio.cattle.io/hash:8f9c7460cde5c8859324b5e2043f60d877bc31c4]) 1.03470333s"                                                                                                                                                                                                                            
```

I found that it was necessary to implment the workaround as mentioned here:
https://github.com/harvester/harvester/issues/2894#issuecomment-1276142797

In order to have the upgrade be successful - otherwise the v1.0.3 node was seeing the error of: `Job was active longer than specified deadline`.

Once the workaround was implemented to increase the `systemUpgradeJobActiveDeadlineSeconds` with a `kubectl patch`

`rancher/fleet:v0.4.0-rc3` and `rancher/rancher:v2.6.9-rc3`.

![Screenshot from 2022-10-13 15-26-22](https://user-images.githubusercontent.com/5370752/195722639-5d192a77-0dea-4c05-a703-8874739d7e0a.png)
![Screenshot from 2022-10-13 14-24-01](https://user-images.githubusercontent.com/5370752/195722641-d376c5d1-34c6-4774-8278-92baef5d64f7.png)
![Screenshot from 2022-10-13 14-23-26](https://user-images.githubusercontent.com/5370752/195722642-976bbf8a-9468-48bf-9767-d34f6bd5fcd8.png)

It looks good with the work-around:
https://github.com/harvester/harvester/issues/2894

So I'll go ahead and close this out :smile:

**Closed as completed by irishgordo** 2022-10-13 22:32 UTC
Labels: kind/bug, priority/0, area/embedded-rancher, require/release-note, area/install-upgrade
