### ISSUE TITLE
[BUG] When assigning a image to windows vm cdrom it changes the disk type

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2057] opened 2022-03-22 01:04 UTC
**Describe the bug**

When creating a windows-iso-image vm and assigning the ISO it changes the type of disk and BUS it's using
**To Reproduce**

1. Upload a windows file to images from your local machine
2. Create a new vm
3. Select windows-iso-image-base-template
4. Navigate to volumes
5. Select the WIndows installer ISO for the CDROM drive

**Expected behavior**

It should stay as a CDROM drive
**Support bundle**

[supportbundle_16da291a-06c6-430e-9a21-f16b2f6fab37_2022-03-22T01-02-58Z.zip](https://github.com/harvester/harvester/files/8320053/supportbundle_16da291a-06c6-430e-9a21-f16b2f6fab37_2022-03-22T01-02-58Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node KVM virtualized setup

**Additional context**
Here's the GIF of it happening. This doesn't seem to happen with the iso-image template. I think it might be related to having two cdrom drives in the list. If you change the drive back to CDROM before you create the VM it works fine.
![windows-template](https://user-images.githubusercontent.com/83787952/159387057-0c22f29d-348a-4001-b110-18222268f707.gif)

**Comment by WuJun2016** [comment] 2022-03-22 01:30
workaround: 
  Click `type` again, select `cd-rom`, and you can create a volume using the `cd-rom `type.

**Comment by WuJun2016** [comment] 2022-04-14 09:45
Test step:
case 1:
When creating the image,  You can choose to fill in the following two labels
case 2:
When creating an image from a url, the UI will try to automatically fill the label

case 3:
When creating a vm, it can correctly determine whether the `type` of `Image Volume` is `disk` or `cd-rom`


![image](https://user-images.githubusercontent.com/24985926/163355384-f6942213-7f09-4e07-8fe8-e1b2ca3536f4.png)

**Comment by TachunLin** [comment] 2022-04-21 14:42
Verified **fixed** on `master-03ee6213-head` (04/18). Close this issue.

### Result
With the new feature of `image-type` and `os-type` label. 

* Test plan 1, windows iso from **`file`** (specify `os` and `image-type` label)

   When we upload image file and specify correct `ISO` and `windows` label. 
   We can assign the iso image to windows vm cd-rom from template file. 
  ![image](https://user-images.githubusercontent.com/29251855/164453326-14620f54-a0fc-4d5d-94f1-1946deabd399.png)
  ![image](https://user-images.githubusercontent.com/29251855/164453440-c0d58b33-fb6e-43ab-a25e-9f652bcc08ff.png)

* Test plan 2, windows iso from **`url`** 
   When we create image file from external URL, it will automatically detect and provide the image and os type 
   label. And can also the iso image to windows vm cd-rom from template file. 
  ![image](https://user-images.githubusercontent.com/29251855/164454380-a9b65c65-2785-4bc4-9105-26383f9b6ea7.png)
  ![image](https://user-images.githubusercontent.com/29251855/164454414-1299757c-013d-4ace-804e-254a23689fcd.png)
  ![image](https://user-images.githubusercontent.com/29251855/164478869-6e2a1bbe-3ab2-4704-8793-1b6c92779e86.png)

* Test plan 3, windows iso from **`file`** (default no label)
  If we upload image file  with default value, no os and image label will provide
  Assign the windows iso image to windows vm it will change the cd-rom to disk type 
  ![image](https://user-images.githubusercontent.com/29251855/164451065-02a0264e-d21a-47f2-99e9-18efc2576923.png)
  

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-03ee6213-head` (04/18)

### Verify Steps
#### Create from File
1. Upload a windows file to images from your local machine
2. Create a new vm
3. Select windows-iso-image-base-template
4. Navigate to volumes
5. Select the WIndows installer ISO for the CDROM drive

#### Create from URL
1. Upload a windows image from external URL 
2. Create a new vm
3. Select windows-iso-image-base-template
4. Navigate to volumes
5. Select the WIndows installer ISO for the CDROM drive

### Additional Context
If you encounter the VM created from windows-iso-image template can't start automatically with error message 
Please refer to issue #2172  
![image](https://user-images.githubusercontent.com/29251855/164483130-94f5450d-3aa4-4645-9b48-9e2ae123ebee.png)

**Comment by noahgildersleeve** [comment] 2022-07-18 19:05
This is happening in v1.0.2. Tested with v1.0.2. I tested this with the dynamic and bundled ui-source.
## Test Steps

1. Upload a windows file to images from your local machine
2. Create a new vm
3. Select windows-iso-image-base-template
4. Navigate to volumes
5. Select the WIndows installer ISO for the CDROM drive

**Comment by TachunLin** [comment] 2022-07-19 03:02
@noahgildersleeve, 
To assign a image uploaded from local file to windows vm cdrom, we need to specify the `harvesterhci.io/image-type` to `ISO` and `harvesterhci.io/os-type` to `Windows` in the image label page. 


Then when we use windows-iso-image-base-template and select windows image file, it will automatically change to the **cdrom** type

Since according to the 1.0 document https://docs.harvesterhci.io/v1.0/upload-image/, this would be the current mechanism
![image](https://user-images.githubusercontent.com/29251855/179652943-b7d3bed5-5718-4296-91ea-636928e3a496.png)


* When we upload a windows to images from our local machine, Harvester can't automatically recognize the OS type and image
  ![image](https://user-images.githubusercontent.com/29251855/179651230-ce8a2de9-1161-4d00-be30-34be01dc173d.png)

* We can manually specify the image-type and os-type in the label page
  ![image](https://user-images.githubusercontent.com/29251855/179651385-d29a2bdd-bab8-411c-9b35-3db5d786fefa.png)

* After that while we use `windows-iso-image-base-template` and select windows image file, the type would be automatically change to `cdrom`
![image](https://user-images.githubusercontent.com/29251855/179651559-c5485626-9c0a-4379-a790-bafb39837dc2.png)


I should provide the reproduce steps more precisely for the upload file scenarios
Update the test steps as the following: 

### Test Steps

1. Create from File
2. Upload a windows file to images from your local machine
3. Open Labels page of the image
4. Select `harvesterhci.io/image-type` to `ISO` and `harvesterhci.io/os-type` to `Windows`
5. Create a new vm
6. Select windows-iso-image-base-template
7. Navigate to volumes
8. Select the WIndows installer ISO for the CDROM drive

### Test Information
- Test Environment: 1 node harvester on local kvm machine
- Harvester version: v1.0-859ede43-head (07/14)
- ui-index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html
- ui-source: Auto

**Closed as completed by TachunLin** 2022-07-19 03:02 UTC
Labels: kind/bug, require/doc, area/ui, priority/0, require/release-note, reproduce/always
