### ISSUE TITLE
[Bug] Incorrect error message when virtualization is disabled by BIOS

### ISSUE THREAD

**Issue by tlehman** [harvester/harvester#2153] opened 2022-04-14 17:42 UTC
**Describe the bug**
When Installing Harvester on a bare metal server, if the BIOS has disabled kvm (hardware virtualization), then the installation will proceed normally, but when you attempt to create and run a VM on Harvester, the error message is cryptic and not helpful. The error is "_0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims._"

**To Reproduce**
1. Install Harvester 1.0.1+ on an Intel-based server and disable virtualization support in the BIOS
2. Boot up the installed Harvester and create a VM
3. Observe that the error message is "_0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims._"

**Expected behavior**
The error should say that "Virtualization is disabled by the BIOS", this information can be found using `dmesg`

**Environment:**
 - Harvester ISO version: 1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell Precision T7500)

**Note**
Assigning to myself for now since I have a good idea about how to fix it

**Comment by tlehman** [comment] 2022-04-18 23:25
The approach to solving this:

# Backend
- Add a boolean to the Harvester nodes' `status.nodeInfo`
     - Definition of done: 
     - `kubectl get nodes janus -o yaml | yq .status.nodeInfo` should contain a `kvmEnabled` boolean, this value can be populated by checking for `/dev/kvm` on the harvester node
# Frontend
- https://github.com/tlehman/dashboard/commit/4bf9af778114ee58afc1957ec57476b99e147fdc
- Add a `isKVMEnabled` method to Node model
- Display banner error on host page if isKVMEnabled is false
- Screenshot:
- 
![image](https://user-images.githubusercontent.com/261552/163893044-50a44df6-94f4-4405-8c23-ca6dca1ea777.png)

**Comment by tlehman** [comment] 2022-04-19 00:23
Move this to an Annotation (since Node is not a custom resource)

**Comment by bk201** [comment] 2022-04-19 00:31
FWIW, I got this annotation on my AMD nested host:

```
cpu-feature.node.kubevirt.io/svm=true
```

Not quite sure if that's enough. For Intel machines, it could be `cpu-feature.node.kubevirt.io/vmx` (need verification, I don't have any Intel machines ATM sorry).

**Comment by tlehman** [comment] 2022-04-19 00:33
@bk201 Thank you! I'll look to see if there are the annotations I need. For `cpu-feature.node.kubevirt.io/vmx`, I don't think that will work, I had an Intel machine with `vmx` but then KVM was still disabled by BIOS. I had to find it through dmesg

**Comment by WuJun2016** [comment] 2022-08-19 08:42
Hi, @tlehman   I see that you have already done the [frontend](https://github.com/tlehman/dashboard/commit/4bf9af778114ee58afc1957ec57476b99e147fdc) part of this issue, I don't know if  still need the frontend colleagues to intervene?  if there is anything that needs to be handled by the frontend, please let me know.  Thanks

**Comment by tlehman** [comment] 2022-08-19 22:23
yeah I think this should be done by the frontend team, since my work in the commit you linked to is not complete

**Comment by WuJun2016** [comment] 2022-12-21 13:54
@bk201  @tlehman 
I only need to use the `cpu-feature.node.kubevirt.io/svm  = true` to determine whether to disable the KVM ?    

If `cpu feature. node. kubevirt.io/svm=true`, it means that KVM is disabled. 
If there is no such label, or `cpu feature. node. kubevirt.io/svm=false`, it means that KVM is enabled.

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/24985926/208916311-45e668c1-751e-4856-b554-0eb625377326.png">

**Comment by noahgildersleeve** [comment] 2023-02-14 00:55
I tested this in `master-0f10441a-head` and it is showing properly in the hosts page. However this bug was originally referencing the virtual machine page. That still has the error
`0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.`
Is that by design? I want to check before I close this. CC @rebeccazzzz @guangbochen 

![Greenshot 2023-02-13 16 53 15](https://user-images.githubusercontent.com/83787952/218610320-adf27c28-7ab3-40a5-b1dd-d3c7f12d4da0.png)
![Greenshot 2023-02-13 16 52 15](https://user-images.githubusercontent.com/83787952/218610324-e3303630-ab6d-4cdc-a968-7510e65268c6.png)
![Greenshot 2023-02-13 16 57 05](https://user-images.githubusercontent.com/83787952/218610496-097ca4b4-9ed8-4e1f-b3a7-e41438768867.png)

**Comment by guangbochen** [comment] 2023-02-14 06:30
@noahgildersleeve this is expected and we only need to change the error message on the host page. VM will contain its own error messages, thanks.

**Comment by noahgildersleeve** [comment] 2023-02-14 17:54
Closing as fixed. Error message is only supposed to show up on Hosts page.

**Closed as completed by noahgildersleeve** 2023-02-14 17:54 UTC
Labels: kind/bug, kind/enhancement, area/ui, priority/2
