### ISSUE TITLE
Multiple Disks Swapping Paths

### ISSUE THREAD

**Issue by lucasajackson** [harvester/harvester#1874] opened 2022-01-27 02:25 UTC
I'm running into some problems with my Harvester setup.  My power went out today, and my Harvester box came back up with the /dev/sdc and /dev/sdb switched around.  Harvester didn't like that, and showed that my partitions were missing due to the disks being swapped.  I was able to get the drives back in the correct order by restarting the server, but I blew away the partitions and recreated them.   I did notice after a few reboots it would swap the disks every third or fourth reboot

[supportbundle_cb61fc33-2eb0-45c5-b007-5e2b3079352f_2022-01-27T02-22-45Z.zip](https://github.com/harvester/harvester/files/7947023/supportbundle_cb61fc33-2eb0-45c5-b007-5e2b3079352f_2022-01-27T02-22-45Z.zip)
.

**Comment by bk201** [comment] 2022-01-27 02:34
@lucasajackson Harvester uses FS labels to find the partitions, device name switching around should have no impact on the boot. Does the second disk have Harvester installed before or any existing partitions?

**Comment by lucasajackson** [comment] 2022-01-27 02:41
It boots up correctly, but doesn't find the extra disks I have attached due to the path being swapped on reboot.   The disks originally had NTFS partitions on them; however, when I first setup the server I had Harvester force format the disks to ext4 and added them to the storage pool.   Everything was working until it swapped yesterday after the power outage.

**Comment by bk201** [comment] 2022-01-27 02:47
@lucasajackson Thanks for the reply. How did you add the extra disk to the storage pool? From the Harvester GUI?

**Comment by bk201** [comment] 2022-01-27 02:51
> @lucasajackson Thanks for the reply. How did you add the extra disk to the storage pool? From the Harvester GUI?

Never mind. I follow the Slack discussion thread and it's from the GUI.

**Comment by lucasajackson** [comment] 2022-01-27 02:51
Yeah, I did it in the Harvester UI under Hosts > host > disks > edit config.

**Comment by lucasajackson** [comment] 2022-01-27 02:55
I will mention that before I figured out it was swapping disk paths, I reformatted the hard drive yesterday from the command line via ssh.   The old partitions were stuck in the harvester GUI, and I had a fun time getting that straightened out, but I was able to get into the Longhorn UI and get everything worked out.

**Comment by bk201** [comment] 2022-01-27 03:12
The WIP PR: https://github.com/harvester/node-disk-manager/pull/24 might fix this issue.

**Comment by lanfon72** [comment] 2022-02-15 08:56
I think the issue is not fixed as expected?
based on my test case, disks can not be scheduled after swapped.

![image](https://user-images.githubusercontent.com/5169694/154026076-a5523419-5d28-413e-8dd6-a8d4dfe472f3.png)
![image](https://user-images.githubusercontent.com/5169694/154026271-69daaa53-eada-4c61-84ac-29664583d6d1.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-9091d7d0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Create a VM with 3 volumes (150G, 20G, 30G)
2. Install Harvester
3. login to console, format disks as `ext4`
4. Login to Dashboard then navigate to host details, add new disks
5. power off VM, modify disk's XML configuration
    i. swap `slot` number in XML's `address` node
6. power on VM then check host's disks tab

**Comment by lanfon72** [comment] 2022-03-01 08:56
Verified not fixed.
disks' status lost.

swapped (vdb 30G, vdc 20G)
![image](https://user-images.githubusercontent.com/5169694/156131786-1df093f5-d976-4461-aed1-0ba27bec4a25.png)

swap back (vdb 20G, vdc 30G)
![image](https://user-images.githubusercontent.com/5169694/156131906-c55cba8a-dcc1-4b8c-bd32-03bd373803ad.png)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-bfd6a8a9-head**
* **ui-source** Option: **Auto**

### Verify Steps:
Same as https://github.com/harvester/harvester/issues/1874#issuecomment-1040017172

**Comment by lanfon72** [comment] 2022-03-08 08:30
Verified not fixed.

swapped with WWN (sda 30Gi, sdb 20Gi), error message displayed
![image](https://user-images.githubusercontent.com/5169694/157196642-2c7c99bf-b0a0-486e-8ab9-b0b355faca38.png)

swapped without WWN (vdb 30Gi, vdc 20Gi), error message NOT displayed, but the size **incorrect**.
![image](https://user-images.githubusercontent.com/5169694/157196872-8cb0f93b-8d6f-43ce-8d16-5b79295bffca.png)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-da3f1778-head**
* **ui-source** Option: **Auto**

### Verify Steps:
Same as https://github.com/harvester/harvester/issues/1874#issuecomment-1040017172

**Comment by lanfon72** [comment] 2022-03-08 09:17
update the case:

swapped with WWN (sda 30Gi, sdb 20Gi, WWN be bound with the filename), same as _without WWN_ case
![image](https://user-images.githubusercontent.com/5169694/157205705-5d8c1974-2f0c-41aa-b749-fdc7368e34a5.png)

**Comment by weihanglo** [comment] 2022-03-08 09:25
> swapped without WWN (vdb 30Gi, vdc 20Gi), error message NOT displayed, but the size incorrect.

For this case, in fact, the size and the mount point match. You can compare the info from console and from dashboard. It's the `Name` field in the dashboard incorrect. The name is fixed once you plug in the disk. And subsequent swapping or re-plugging won't change the value. It is a **known** bug that is confusing but won't affect any actual operations.

I plan to address this in the next iteration since it cannot catch up current release train. Thanks!

**Comment by lanfon72** [comment] 2022-03-08 09:31
According to
>  ... It's the `Name` field in the dashboard incorrect. The name is fixed once you plug in the disk. And subsequent swapping or re-plugging won't change the value. ...

The functionality works as expected, and we will address UI's bug in another issue, so close this issue.

**Closed as completed by lanfon72** 2022-03-08 09:31 UTC
Labels: kind/bug, priority/0, severity/2, area/node-disk-mgmt

**Comment by clust3rsekt0r** [comment] 2022-06-04 23:44
Hello here, I know this problem is closed but I just lost all my data I change how the disks are organize and turns out that I format the wrong disk just because the GUI does not refresh the latest FDISK information please this feature needs more rework and more constrains the loss of data in the actual state is very likely, is there any way to add how to correct this problem manually in the documentation?

**Comment by lanfon72** [comment] 2022-06-05 18:08
Hi @clust3rsekt0r, I'm pretty sorry to hear that, we had enhanced it in `v1.0.2`, you can check #2149 for more details.
If there still have something to be enhanced, please file a new issue for it.

Thanks.

**Comment by bk201** [comment] 2022-06-06 03:24
@clust3rsekt0r Could you share what Harvester version you used when seeing the problem?
