### ISSUE TITLE
[BUG] PXE boot installation doesn't give an error if `iso_url` field is missing

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1439] opened 2021-10-15 14:44 UTC
**Describe the bug**
For PXE boot installation, if `iso_url` is missing, the installation still finishes with the error:
![iso_url-missing](https://user-images.githubusercontent.com/1691518/137505864-14208a07-f39a-44a6-9c92-d4424e87dbd6.png)

**To Reproduce**
Do PXE boot installation without specifying [the `iso_url` field](https://docs.harvesterhci.io/v0.3/install/harvester-configuration/#installiso_url). 

**Expected behavior**

We should verify the `iso_url` field because it's mandatory in PXE boot installation.

**Support bundle**

**Environment:**
 - Harvester ISO version: 0.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment] 2021-11-08 09:57
host os: SUSE SLE 15
hardware: provo DAY0, HP server
One VM to serve as http server

create another new VM, boot with iPXE
sudo virt-install --name=pxevm3 --ram=16384 --vcpus=8 --cpu host \
--disk path=/var/lib/libvirt/images/pxevm2-disk.qcow2,bus=ide,size=50 \
--pxe --noautoconsole --graphics=spice --hvm \
--network network=default,model=e1000 \
--arch x86_64

cat /srv/tftp/ipxe-create
#!ipxe
kernel http://192.168.122.85/harvester/harvester-v0.3.0-vmlinuz-amd64 ip=enp1s0:dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl console=tty1 root=live:http://192.168.122.85/harvester/harvester-v0.3.0-rootfs-amd64.squashfs harvester.install.automatic=true harvester.install.config_url=http://192.168.122.85/harvester/config-create.yaml
initrd http://192.168.122.85/harvester/harvester-v0.3.0-initrd-amd64
boot


new vm starts up, iPXE downloads related file, but finally goes into Dracut Emergency Shell

![image](https://user-images.githubusercontent.com/31133476/140720254-7d305bc2-1efb-416a-a511-eefc80cdde62.png)


under investigation now

**Comment by w13915984028** [comment] 2021-11-08 10:26
reproduced now:
fix the interface name in ipxe-create file as:
sudo cat /srv/tftp/ipxe-create
#!ipxe
kernel http://192.168.122.85/harvester/harvester-v0.3.0-vmlinuz-amd64 _ip=:dhcp_ net.ifnames=1 rd.cos.disable rd.noverifyssl console=tty1 root=live:http://192.168.122.85/harvester/harvester-v0.3.0-rootfs-amd64.squashfs harvester.install.automatic=true harvester.install.config_url=http://192.168.122.85/harvester/config-create.yaml
initrd http://192.168.122.85/harvester/harvester-v0.3.0-initrd-amd64
boot

notice:
guide here needs to be updated, all those related files should have full http path
https://docs.harvesterhci.io/v0.3/install/pxe-boot-install/


set a bad ios_url in  /var/www/html/harvester/config-create.yaml
  device: /dev/sda
  iso_url: http://192.168.122.85/harvester/harvester-v0.3.011-amd64.iso
  vip: 192.168.122.133       # The VIP to access the Harvester GUI. Make sure the IP is free to use.

the harvester installer goes here:

![image](https://user-images.githubusercontent.com/31133476/140725093-d86f4b0e-8da3-4689-adc9-9821ac40df45.png)

**Comment by w13915984028** [comment] 2021-11-08 10:49
when iso_url is bank in config-create.yaml, the installation will finish with related error message as claimed in the bug description,
  device: /dev/sda
  #iso_url: http://192.168.122.85/harvester/harvester-v0.3.011-amd64.iso
  iso_url:
  vip: 192.168.122.133       # The VIP to access the Harvester GUI. Make sure the IP is free to use.

the vm will reboot, and then goes into below state.

comparing, if the iso_url link is not fetchable (404), or download fail,  then the installation will suspend in the error. 

![image](https://user-images.githubusercontent.com/31133476/140728342-6937ee10-f96b-4dea-b6dc-fbfcb91483a3.png)

next, add error processing when iso_url is blank

**Comment by w13915984028** [comment] 2021-11-08 15:29
planed solution is: add processing when COS_INSTALL_ISO_URL is blank/empty, return error.
(for ISO installation, here COS_INSTALL_ISO_URL is already set)

@guangbochen @yasker   Your idea?

package/harvester-os/files/usr/sbin/harv-install

```
get_iso()
{
    if [ -n "$COS_INSTALL_ISO_URL" ]; then
        ISOMNT=$(mktemp -d -p /tmp cos.XXXXXXXX.isomnt)
        TEMP_FILE=$(mktemp -p /tmp cos.XXXXXXXX.iso)
        get_url ${COS_INSTALL_ISO_URL} ${TEMP_FILE}
        ISO_DEVICE=$(losetup --show -f $TEMP_FILE)
        mount -o ro ${ISO_DEVICE} ${ISOMNT}
    else
        echo "ERROR: ISO_URL must be set correctly for PXE boot, please check. 1>&2"
        exit 1
    fi
}
```

**Comment by bk201** [comment] 2021-11-08 15:33
@w13915984028 We can also add a check in the validations: https://github.com/harvester/harvester-installer/blob/14be631bdcba753368b46396a14e5cb8775c9f82/pkg/console/validator.go#L220

if HarvesterConfig.Install.Automatic is true, iso_url can't be empty.

**Comment by w13915984028** [comment] 2021-11-08 15:43
> @w13915984028 We can also add a check in the validations: https://github.com/harvester/harvester-installer/blob/14be631bdcba753368b46396a14e5cb8775c9f82/pkg/console/validator.go#L220
> 
> if HarvesterConfig.Install.Automatic is true, iso_url can't be empty.

My test setting is in below,  it finished and went into state as previous said here.

the "iso_url" is in config-create.yaml, but it is blank.
```
type Install struct {
...
ISOURL    string `json:"isoUrl,omitempty"`
}
```

 cat /var/www/html/harvester/ipxe-create
#!ipxe
kernel harvester-v0.3.0-vmlinuz-amd64 ip=:dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl console=tty1 root=live:http://192.168.122.85/harvester/harvester-v0.3.0-rootfs-amd64.squashfs **harvester.install.automatic=true** harvester.install.config_url=http://192.168.122.85/harvester/config-create.yaml
initrd harvester-v0.3.0-initrd-amd64
boot

 cat /var/www/html/harvester/config-create.yaml
```
token: ..
os:
  hostname: node1
..
install:
  mode: create
  networks:
    harvester-mgmt:       # (Mandatory) The management bond name.
      interfaces:
      - name: ens3
      default_route: true
      method: dhcp
      bond_options:
        mode: balance-tlb
        miimon: 100
  device: /dev/sda
  #iso_url: http://192.168.122.85/harvester/harvester-v0.3.011-amd64.iso
  iso_url:
  vip: 192.168.122.133       # The VIP to access the Harvester GUI. Make sure the IP is free to use.
  vip_mode: static        # Or dhcp
```

**Comment by w13915984028** [comment] 2021-11-08 15:47
> @w13915984028 We can also add a check in the validations: https://github.com/harvester/harvester-installer/blob/14be631bdcba753368b46396a14e5cb8775c9f82/pkg/console/validator.go#L220
> 
> if HarvesterConfig.Install.Automatic is true, iso_url can't be empty.

Yes, we can check it in earlier stage.

And, for PXE booting,  if the interface name is not correct, what will happen ?

**Comment by w13915984028** [comment] 2021-11-09 15:57
with check in package/harvester-os/files/usr/sbin/harv-install/get_iso()

the effect is:

![image](https://user-images.githubusercontent.com/31133476/140958420-660df2da-bded-451c-9ea5-d272c3cc6f0b.png)

**Comment by w13915984028** [comment] 2021-11-10 10:40
When I add the ISO_URL check in layoutInstall(), then the auto installation will terminate in case it is blank, it is difficult to figure out the root cause, as it splashed in the screen and then disappear, you need to get log info.

But if only with check in harv-install shell script, the install window will stop right on the error page, it is good for trouble-shooting.

And, the ISOURL check is not easily to put into ValidateConfig:

layoutInstall -> setPannels -> addInstallPanel -> ValidateConfig

after ValidateConfig, then, the "Autmatic" is read from config (/proc/cmdline, set via config-create.yaml) to check and merge into c.config.

At this moment, I would like to commit change in harv-install (shell script)

```
diff --git a/pkg/console/install_panels.go b/pkg/console/install_panels.go
index c5f1644..5ce5d24 100644
--- a/pkg/console/install_panels.go
+++ b/pkg/console/install_panels.go
@@ -57,6 +57,11 @@ func (c *Console) layoutInstall(g *gocui.Gui) error {
 
               ...
                setPannels(c)
               ...
  
                if cfg, err := config.ReadConfig(); err == nil {
                        if cfg.Install.Automatic && isFirstConsoleTTY() {
+                               //if cfg.Install.ISOURL == "" {
+                               //      logrus.Error("Iso_rul is missing in automatic installation")
+                               //      err = fmt.Errorf("iso_url is missing in automatic installation")
+                               //      return
+                               //}
                                logrus.Info("Start automatic installation...")
                                mergo.Merge(c.config, cfg, mergo.WithAppendSlice)
                                initPanel = installPanel
```

**Comment by bk201** [comment] 2021-11-10 12:07
@w13915984028 
Could you see if this change does the trick? https://github.com/bk201/harvester-installer/commit/a7661260b5da2f7650bdfa20b6d4da51b352a731

**Comment by w13915984028** [comment] 2021-11-10 12:52
> @w13915984028 Could you see if this change does the trick? [bk201/harvester-installer@a766126](https://github.com/bk201/harvester-installer/commit/a7661260b5da2f7650bdfa20b6d4da51b352a731)

highly possible:  no.

the time line is:
layoutInstall -> setPannels -> addInstallPanel -> ValidateConfig ->commonCheck(
then below code

That is:  in commonCheck,    Install.Automatic is not read out and merged into c.config yet, it is FALSE.

I did not find a proper time to call config.ReadConfig() in advance, here it also checks isFirstConsoleTTY,  only when both TRUE, then consider automatic mode and merge them into c.config.

Your idea?

```
@@ -57,6 +57,11 @@ func (c *Console) layoutInstall(g *gocui.Gui) error {
 
               ...
                setPannels(c)
               ...
  
                if cfg, err := config.ReadConfig(); err == nil {
                        if cfg.Install.Automatic && isFirstConsoleTTY() {
+                               //if cfg.Install.ISOURL == "" {
+                               //      logrus.Error("Iso_rul is missing in automatic installation")
+                               //      err = fmt.Errorf("iso_url is missing in automatic installation")
+                               //      return
+                               //}
                                logrus.Info("Start automatic installation...")
                                mergo.Merge(c.config, cfg, mergo.WithAppendSlice)
                                initPanel = installPanel
```

**Comment by bk201** [comment] 2021-11-10 13:37
In a PXE boot installation, `cfg.Install.Automatic` is `true` after this line: https://github.com/harvester/harvester-installer/blob/52c560d85c1b2d0a499c640695e5153ba5486c38/pkg/console/install_panels.go#L58

**Comment by w13915984028** [comment] 2021-11-10 13:52
> In a PXE boot installation, `cfg.Install.Automatic` is `true` after this line: https://github.com/harvester/harvester-installer/blob/52c560d85c1b2d0a499c640695e5153ba5486c38/pkg/console/install_panels.go#L58

Yes.  My comment modification is checking it this way.

```
                if cfg, err := config.ReadConfig(); err == nil {
                        if cfg.Install.Automatic && isFirstConsoleTTY() {
+                               //if cfg.Install.ISOURL == "" {
+                               //      logrus.Error("Iso_rul is missing in automatic installation")
+                               //      err = fmt.Errorf("iso_url is missing in automatic installation")
+                               //      return
+                               //
```

**Comment by w13915984028** [comment] 2021-11-10 14:33
With commit now:
https://github.com/w13915984028/harvester-installer/commit/52a21c58089d37e2a23932cbfee629d0d79c03bf

Both PXE and ISO install as expected
![image](https://user-images.githubusercontent.com/31133476/141132137-e7dc5189-63bd-4b04-9c32-c36b1c5901ab.png)

**Comment by noahgildersleeve** [comment] 2021-12-07 21:46
Tested in  master-655c251a-head with vagrant pxe install. Verified as fixed
![Screenshot from 2021-12-07 13-38-54](https://user-images.githubusercontent.com/83787952/145110270-1e4ff666-6eda-494d-88fa-bb5905540d57.png)

**Closed as completed by noahgildersleeve** 2021-12-07 21:46 UTC
Labels: kind/bug, area/installer, priority/2
