### ISSUE TITLE
[FEATURE] Metallb support

### ISSUE THREAD

**Issue by inmanturbo** [harvester/harvester#1165] opened 2021-09-07 20:26 UTC
It would be nice to have support within the ui for metalLb and be able to use that to assign floating ips to VM's.

**Comment by davidspek** [comment] 2021-09-12 21:58
I believe the kube-vip implementation should be able to take care of that already.

**Comment by yasker** [comment] 2022-09-16 17:20
Duplicate of #1676

**Closed as completed by yasker** 2022-09-16 17:20 UTC
Labels: kind/enhancement

**Comment by inmanturbo** [comment] 2022-09-17 03:40
This predates #1676 by over 500 tickets. I would have thought it would have been be the duplicate!

**Comment by yasker** [comment] 2022-09-17 03:43
LOL. The reason I marked this as duplicate is because the other item has been worked on and scheduled. 

Either way the feature is coming!
