### ISSUE TITLE
[BUG] Upgrade from v1.2.1 to v1.2-head stuck in Upgrading System Service stage

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5507] opened 2024-04-03 11:16 UTC
**Describe the bug**

Upgrade from v1.2.1 to v1.2-ba51e92e-head, the upgrade process stuck in `Upgrading System Service` 

![image](https://github.com/harvester/harvester/assets/29251855/a35f0255-0762-4e0e-a55f-de5b51f19a16)

Check the upgrade pod log, it indicate error waitin for the fleet-agent rollout to finish

```
│ ```                                                                                                                                                        │
│ echo https:///dashboard/?setup=$(kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}')  │
│ ```                                                                                                                                                        │
│                                                                                                                                                            │
│ To get just the bootstrap password on its own, run:                                                                                                        │
│                                                                                                                                                            │
│ ```                                                                                                                                                        │
│ kubectl get secret --namespace cattle-system bootstrap-secret -o go-template='{{.data.bootstrapPassword|base64decode}}{{ "\n" }}'                          │
│ ```                                                                                                                                                        │
│                                                                                                                                                            │
│                                                                                                                                                            │
│ Happy Containering!                                                                                                                                        │
│ Wait for Rancher dependencies helm releases...                                                                                                             │
│ Wait for Rancher dependencies rollout...                                                                                                                   │
│ Waiting for deployment "fleet-agent" rollout to finish: 0 of 1 updated replicas are available...                                                           │
│ deployment "fleet-agent" successfully rolled out                                                                                                           │
│ deployment "fleet-controller" successfully rolled out                                                                                                      │
│ deployment "rancher-webhook" successfully rolled out                                                                                                       │
│ Wait for cluster settling down...                                                                                                                          │
│ CAPI cluster fleet-local/local is provisioned (current generation: 2298).                                                                                  │
│ cluster.fleet.cattle.io/local patched                                                                                                                      │
│ Waiting for deployment spec update to be observed...                                                                                                       │
│ Waiting for deployment spec update to be observed...                                                                                                       │
│ Waiting for deployment "fleet-agent" rollout to finish: 0 out of 1 new replicas have been updated...                                                       │
│ Waiting for deployment "fleet-agent" rollout to finish: 0 of 1 updated replicas are available...                                                           │
│ error: object has been deleted                                                                                                                             │
│ Stream closed EOF for harvester-system/hvst-upgrade-fwgdb-apply-manifests-cnmzs (apply)   
```

**To Reproduce**
1. Prepare three nodes v1.2.1 cluster 
2. Create one vm 
3. Shutdown the vm after started
4. Upgrade to v1.2-ba51e92e-head
5. Apply the annotation to skip the version check
https://github.com/harvester/harvester/pull/5208
6. Check the upgrade status

**Expected behavior**

Can correctly upgrade from v1.2.1 to v1.2-head 

**Support bundle**

[supportbundle_f1567af5-53f3-4e30-a8e4-765131c1a09c_2024-04-03T11-17-34Z.zip](https://github.com/harvester/harvester/files/14851337/supportbundle_f1567af5-53f3-4e30-a8e4-765131c1a09c_2024-04-03T11-17-34Z.zip)

**Upgrade log**
[hvst-upgrade-fwgdb-upgradelog-archive-2024-04-03T11-04-27Z.zip](https://github.com/harvester/harvester/files/14851236/hvst-upgrade-fwgdb-upgradelog-archive-2024-04-03T11-04-27Z.zip)

**Environment**
 - Harvester ISO version: `v1.2-ba51e92e-head` (24/04/03)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Three nodes on remote kvm machine

**Comment by khushboo-rancher** [comment] 2024-04-05 18:00
Looping in @lanfon72 as he is modifying upgrade automation.

**Comment by TachunLin** [comment] 2024-04-09 16:19
After checking with the development team.
I retried the three nodes upgrade from v1.2.1 to v1.2-head, the issue did not exists there.

In the second upgrade trial, I did not set the skip version check [workaround ](https://github.com/harvester/harvester/pull/5208)

This time can successfully upgrade to `v1.2-f414942f-head`
![image](https://github.com/harvester/harvester/assets/29251855/81916fc7-849c-400e-bf8d-3421c90189cc)



I think the original issue maybe caused by I set the unnecessary skip version workaround.

**Comment by khushboo-rancher** [comment] 2024-04-09 19:00
Looks like the upgrade failed because `fleet-agent` didn't get rollout. I don't think `skip version check` will have any impact on it.

Let's keep it open for now and observe the upgrade pipeline for next 10-15 runs. If we don't encounter this, we can close it.

**Comment by lanfon72** [comment] 2024-07-02 17:54
close as not reproduced in a month of daily upgrade testing.

**Closed as completed by lanfon72** 2024-07-02 17:54 UTC
Labels: kind/bug, severity/2, area/install-upgrade, reproduce/rare
