### ISSUE TITLE
[BUG]State for powered down node stays in-progress

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#1035] opened 2021-07-22 20:51 UTC
**Describe the bug**
State of a powered down node is 'in-progress'. It should be 'down'

**To Reproduce**
Power down an Active node on a multi cluster env 

**Expected behavior**
The State should change from Active to down

**Support bundle**

**Environment:**
 - Harvester ISO version: main 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe vagrant env

**Additional context**

**Comment by FrankYang0529** [comment] 2021-11-16 08:09
Is this a UI area issue? When I click `View in API`, `in-progress` occurs in `metadata.state`. However, `state` field is not in [ObjectMeta](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1?utm_source=gopls#ObjectMeta). So we can't find `in-progress` from `kubectl get nodes node -o yaml`. Probably, UI should check `Ready` condition in status. For a shutdown node, `Ready` condition shows `Unknown`.

```
metadata: {
  # ...
  state: {
    "error": false,
    "message": "Kubelet stopped posting node status.",
    "name": "in-progress",
    "transitioning": true
  }
}
```

**Comment by guangbochen** [comment] 2021-11-18 15:17
nope, actually this is a backend issue as the harvester node API has a different state in contrast with the Rancher's [`v1/nodes`](https://github.com/harvester/harvester/issues/1272#issuecomment-970143102), close as a duplicate of  https://github.com/harvester/harvester/issues/1272.

**Closed as completed by guangbochen** 2021-11-18 15:17 UTC
Labels: kind/bug, area/control-plane, priority/2
