### ISSUE TITLE
[BUG] The alerts KubeVirtComponentExceedsRequestedMemory and KubeVirtComponentExceedsRequestedCPU not working

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#3562] opened 2023-02-28 03:44 UTC
**Describe the bug**
KubeVirtComponentExceedsRequestedMemory syntax problem causes an execution error https://github.com/kubevirt/kubevirt/issues/6481.
KubeVirtComponentExceedsRequestedCPU record node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate was replaced by node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate https://github.com/prometheus-operator/kube-prometheus/issues/1056#issuecomment-934617638.

**To Reproduce**

**Expected behavior**
It will be executed successfully.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment] 2023-05-26 07:02
close as duplicate of https://github.com/harvester/harvester/issues/3792

**Closed as completed by guangbochen** 2023-05-26 07:02 UTC
Labels: kind/bug, area/observability, require/reproduce, require/severity
