### ISSUE TITLE
[BUG] Creating VM with larger size than schedulable Longorn storage doesn't give error

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1609] opened 2021-12-01 21:28 UTC
**Describe the bug**

**To Reproduce**
1. Check how much space is schedulable in Longhorn for cluster
2. Create a VM with a larger volume size than that.
3. Check event log
4. Check for detached volumes in Longhorn

**Expected behavior**

You should either get an error that there isn't enough space/schedulable space, or it shouldn't allow you to create it.
**Support bundle**

[supportbundle_676e8bdf-3c83-4b6b-abe0-d4c672b11962_2021-12-01T21-23-34Z.zip](https://github.com/harvester/harvester/files/7637212/supportbundle_676e8bdf-3c83-4b6b-abe0-d4c672b11962_2021-12-01T21-23-34Z.zip)

**Environment:**
 - Harvester ISO version: master-1e042e04-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node virtualized vagrant environment

**Additional context**
Add any other context abou
![Screenshot from 2021-12-01 13-24-50](https://user-images.githubusercontent.com/83787952/144316784-b205958a-8b88-40ce-ac90-6185181e8f9e.png)
![Screenshot from 2021-12-01 13-22-55](https://user-images.githubusercontent.com/83787952/144316787-2d84e588-c2c5-492e-84e3-e420c229f995.png)
![Screenshot from 2021-12-01 13-17-14](https://user-images.githubusercontent.com/83787952/144316788-283847e2-0140-4738-9948-05eae4593dc5.png)
t the problem here.

**Comment by yasker** [comment] 2021-12-01 21:32
This looks like a regression due to the feature should be already implemented in https://github.com/harvester/harvester/issues/1167

**Comment by guangbochen** [comment] 2021-12-03 02:19
duplicate of https://github.com/harvester/harvester/issues/1400, and this issue is moved to 1.1 as backend enhancement is needed as normal users won't be able to check the `longhorn-system` namespace volumes directly.

**Closed as completed by guangbochen** 2021-12-03 02:19 UTC
Labels: kind/bug, area/ui
