### ISSUE TITLE
[BUG] Disable Maintenance Mode menu options don't seem to do anything

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#1731] opened 2021-12-21 19:51 UTC
**Describe the bug**
Wanting to change a BIOS setting for one of my nodes, I set it to Enable Maintenance Mode. Since it didn't seem to do anything I clicked it again. This time it showed the node in Maintenance mode. Once I had rebooted and made my change I then set it to Disable Maintenance Mode. Despite waiting and multiple attempts, both on the Hosts page (three dots for relevant host) and the specific node's page, my node is stuck in Maintenance mode!

**To Reproduce**
1. Set a node in Maintenance mode
2. Disable Maintenance mode

May possibly need to reboot node in between steps 1 & 2

**Expected behavior**
Disable Maintenance Mode should take the relevant node out of maintenance mode

**Support bundle**
Can't generate support bundle as it's reporting a network error!

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with 2x Intel NUC7i7DNxE

**Additional context**
Fresh install following earlier release of 1.0.0 GA.

**Comment by simonflood** [comment] 2021-12-21 19:56
Support bundle
[supportbundle_afac18dc-92db-412a-922d-2b86a05e199d_2021-12-21T19-54-01Z.zip](https://github.com/harvester/harvester/files/7757806/supportbundle_afac18dc-92db-412a-922d-2b86a05e199d_2021-12-21T19-54-01Z.zip)

**Comment by simonflood** [comment] 2021-12-22 12:58
Unexpectedly retrying to disable maintenance mode just now actually worked - almost immediately after I clicked it the host changed. So either time was a healer or something else has changed (other than logging out and back in again today nothing has changed in my Harvester 1.0.0 setup).

**Comment by simonflood** [comment] 2022-01-04 14:45
Having shutdown both of my NUCs to upgrade RAM I again tested maintenance mode - they were both quick to enable but disabling not so. One I left overnight before I could disable, the other seemed to work after I refreshed the page, so perhaps it's a UI thing? Would be useful to know what enable & disable maintenance mode buttons do under the hood so I can try running manually from CLI to see what, if anything, happens.

**Comment by gitlawr** [comment] 2022-01-18 08:22
UI posts
```
MGMT_URL/v1/harvester/nodes/harvester-node-2?action=enable/disableMaintenanceMode
```

under the hood, it adds/removes the following content to the node manifest
```
metadata:
  annotations:
      harvesterhci.io/maintain-status: running
spec:
  taints:
  - effect: NoSchedule
    key: kubevirt.io/drain
    value: scheduling
```

Can you check if the API call succeeds in the browser console?

**Comment by TachunLin** [comment] 2022-01-25 11:45
@guangbochen, @gitlawr 
This issue can be reproduced on v1.0.0 GA on 3 nodes provo bare metal machine with no VM created on node. 

### Result
Unable to disable maintenance mode after rebooting 1st controller harvester node
Host can be discover to running status, keep in maintenance mode status 

Wait for 10 minutes and disable several times, still can't disable maintenance mode

![image](https://user-images.githubusercontent.com/29251855/150966439-9f853191-f817-4247-8d1c-3f0e2fd3099b.png)

![image](https://user-images.githubusercontent.com/29251855/150968215-df3e66f9-dbe8-41e9-8bb0-c5acb9238b68.png)

![image](https://user-images.githubusercontent.com/29251855/150968813-ae002b70-0c76-49eb-a8e1-41523850204f.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: v1.0.0 GA

### Reproduce steps
1. 3 nodes harvester 
2. Enable virtual network in management mgmt
3. Create virtual network vlan 1 and vlan 806
4. Open Host page
5. Select node 1, enter maintenance mode 
6. Reboot node 1 machine 
  ![image](https://user-images.githubusercontent.com/29251855/150965074-77fdbcae-d42f-4afb-a011-ace99021e48d.png)

  ![image](https://user-images.githubusercontent.com/29251855/150965788-a6d163bd-fb62-4887-97ca-eff85bba3a8f.png)
7. Confirm node reboot finish
8. Select node 1, disable maintenance mode

### Support Bundle 
[supportbundle_65ca7f14-3072-4ea7-ace6-d3d562b23393_2022-01-25T11-30-42Z.zip](https://github.com/harvester/harvester/files/7933174/supportbundle_65ca7f14-3072-4ea7-ace6-d3d562b23393_2022-01-25T11-30-42Z.zip)

**Comment by TachunLin** [comment] 2022-01-25 14:46
I found after `leaving harvester node for hours` then back to check. After refresh harvester dashboard page, It's able to disable maintenance mode to let harvester node back to `running` status.

**Comment by FrankYang0529** [comment] 2022-02-11 08:54
Looks like if we refresh the page and we can disable maintenance mode. Like the following video.
* At the beginning, a node is in red maintenance mode. It means that the node is in maintenance mode and can't be connected.
* The node is recovered to yellow maintenance mode. It can be connected now.
* If we click `Disable Maintenance Mode`, the request can be sent to the backend and the response is `204`.
* If we refresh the page and click `Disable Maintenance Mode`, the node can be back to Active.

https://user-images.githubusercontent.com/4927361/153561991-895be077-2290-4fd3-b21c-aa56a24385c5.mp4

**Comment by TachunLin** [comment] 2022-02-16 03:32
Reproduce this issue on `master-9091d7d0-head` (02/14) 

### Result
After rebooting harvester node1, the enabled maintenance mode will keep in maintenance status unless we refresh (ctrl+r) the dashboard UI. 

![1731](https://user-images.githubusercontent.com/29251855/154190347-bf451236-43dd-4de3-84b6-961dece2b4d7.gif)

After above operation, we disable the maintenance mode again, node 1 can back to `Active` status
![image](https://user-images.githubusercontent.com/29251855/154190490-81617fce-27bd-44be-b4f2-50866ab1461d.png)

Thus we could enhance the UX to real time reflect the status change of disabling maintenance mode on host page

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: `master-9091d7d0-head` (02/14)

### Verify Steps
1. Enable virtual network in management mgmt
2. Create virtual network vlan 1 and vlan 806
3. Open Host page
4. Select node 1, enter maintenance mode 
5. Reboot node 1 machine 
6. Confirm node reboot finish
7. Select node 1, disable maintenance mode

**Comment by WuJun2016** [comment] 2022-04-21 03:46
> Reproduce this issue on `master-9091d7d0-head` (02/14)
> 
> ### Result
> After rebooting harvester node1, the enabled maintenance mode will keep in maintenance status unless we refresh (ctrl+r) the dashboard UI.
> 
> ![1731](https://user-images.githubusercontent.com/29251855/154190347-bf451236-43dd-4de3-84b6-961dece2b4d7.gif)
> 
> After above operation, we disable the maintenance mode again, node 1 can back to `Active` status ![image](https://user-images.githubusercontent.com/29251855/154190490-81617fce-27bd-44be-b4f2-50866ab1461d.png)
> 
> Thus we could enhance the UX to real time reflect the status change of disabling maintenance mode on host page
> 
> ### Test Information
> * Test Environment: 3 nodes harvester on provo bare machine
> * Harvester version: `master-9091d7d0-head` (02/14)
> 
> ### Verify Steps
> 1. Enable virtual network in management mgmt
> 2. Create virtual network vlan 1 and vlan 806
> 3. Open Host page
> 4. Select node 1, enter maintenance mode
> 5. Reboot node 1 machine
> 6. Confirm node reboot finish
> 7. Select node 1, disable maintenance mode

Currently I have not been able to reproduce the problem in the v1.0.1 environment, based on the screenshot information I guess the possible causes are as follows.

When you refresh the page and see a message like `Your connection is not private`
![image](https://user-images.githubusercontent.com/24985926/164366792-2c2d36f2-8531-4c25-8836-003d828c6fc3.png)

 it means that the harvester environment's credentials have changed, so you can't see the websocket message push when you refresh the previous page.

Verification method:
1. When the `Disable maintenance` button is clicked, the UI does not change state
2. Don't close this page, reopen a new page and re-operate Enable Maintenance & Disable Maintenance, you will see the status change in the new UI page, but the previous page will not change（Because all the websocket links of the old page have been disconnected）

I will try to install the v1.0.0 environment to reproduce the problem.

**Comment by WuJun2016** [comment] 2022-04-21 06:15
I reproduced this problem in v1.0.0, the UI did not change state because the UI did not receive any websocket messages

**Comment by TachunLin** [comment] 2022-04-22 09:11
### Reproduce Result
This issue can be reproduced on latest v1.0.1 master-head release `master-c5f4564f-head`. (04/18)


https://user-images.githubusercontent.com/29251855/164674780-be964f94-44c6-49b1-8a4d-de93356e0504.mov

### Verify Steps
1. Enable virtual network in management mgmt
2. Create virtual network vlan 1 and vlan 806
3. Open Host page
4. Select node 1, enter maintenance mode
5. Reboot node 1 machine
6. Confirm node reboot finish
7. Select node 1, disable maintenance mode

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: `master-c5f4564f-head` (04/18)

### Support Bundle
[supportbundle_65ca7f14-3072-4ea7-ace6-d3d562b23393_2022-01-25T11-30-42Z.zip](https://github.com/harvester/harvester/files/8539379/supportbundle_65ca7f14-3072-4ea7-ace6-d3d562b23393_2022-01-25T11-30-42Z.zip)

**Comment by TachunLin** [comment] 2022-04-22 10:00
* During further investigation, the web socket failed to connect during rebooting node 1. This may caused by the certificate changes. 
![image](https://user-images.githubusercontent.com/29251855/164680718-cfb5f63f-79d3-4f2c-98e2-afe353c85065.png)

* By refreshing or open a new page, we can enable/disable maintenance mode 
![image](https://user-images.githubusercontent.com/29251855/164682692-30f13994-7720-4706-b275-9a7d637abcef.png)

* The workaround to disable maintenance is by refreshing the page (ctrl+r)

@guangbochen, it looks like the issue caused by websocket failed to connect, suggest we can have a backend team member to look deep into it if needed.

**Comment by guangbochen** [comment] 2022-04-24 08:54
This looks to be an expected behavior since we are using the [dynamicLister](https://github.com/rancher/dynamiclistener) as our default cert management, a node change or reboot will require users to re-enable the CA trust manipulation. As a workaround, users can use Rancher to manage the Harvester cluster or add a custom proxy and cert in the front of the Harvester UI.

As an enhancement, we may consider adding more obvious UI notifications when the WebSocket connection is disconnected instead require users to check it via the `F12` console. cc @WuJun2016 . Also moving this to v1.0.3 due to time release constraints, thanks.

**Comment by WuJun2016** [comment] 2022-05-16 10:37
Created a new issue tracking websocket hint message enhancement, so closed the issue.    https://github.com/harvester/harvester/issues/2186

**Closed as completed by WuJun2016** 2022-05-16 10:37 UTC
Labels: kind/bug, area/ui, priority/1
