### ISSUE TITLE
[BUG] harvester-cloud-provider roll out different image in Rancher cross-upgrade (Community <-> Prime)

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6799] opened 2024-10-16 14:22 UTC
## Description
1. When apply cross-upgrade (Community <-> Prime) on Rancher, harvester-cloud-provider will experience an unexpected roll out to different image.
3. From observation,
   * Community version uses `rancher/harvester-cloud-provider:vA.B.C`
   * Prime version uses `registry.rancher.com/rancher/harvester-cloud-provider:vA.B.C`

## Environment
* `harvester-v1.4.0-rc2`
  * Profile: Single node AMD64 QEMU/KVM
  * ui-source: `Auto`
* `rancher-v2.8.5` => `rancher-v2.8.6`
  * Profile: K3s on single node AMD64 QEMU/KVM
  * Dependeny: `v1.28.14+k3s1` and `cert-manager-v1.5.1` 
* Guest Cluster
  * Profile: RKE2 `v1.28.13+rke2r1`

## Prerequisite
1. <details>
   <summary> Create image <i>ubuntu-22.04-server-cloudimg-amd64.img</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/a8159621-c5ba-4d77-8b5a-f03276ffe585)
   </details>

1. <details>
   <summary> Create VM network <i>mgmt-vlan1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3931e443-4008-41f6-beda-ceb18f106c4c)
   </details>

1. <details>
   <summary> Import Harvester to Rancher
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3afce7a0-ff9a-4731-9fad-916e3936862c)
   </details>

## Steps
1. <details>
   <summary> :green_circle: Provision RKE2 cluster
   </summary>

   * Rancher
     ![image](https://github.com/user-attachments/assets/ca84e924-5802-4a37-9b0a-e052bd111207)
   * Harvester
   </details>

1. <details>
   <summary> :green_circle: Check harvester-cloud-provider
   </summary>
   
   * Chart
     ![image](https://github.com/user-attachments/assets/03dfd808-ca46-4ab3-966e-b22411c3b2e1)
   * Image
     ![image](https://github.com/user-attachments/assets/5f55314f-4033-44c3-b699-8dbec9ff85ae)
   </details>

   > Chart: `harvester-cloud-provider:0.2.400`
   > Image: `rancher/harvester-cloud-provider:v0.2.1`

1. <details>
   <summary> :green_circle: Deploy Nginx with a PVC
   </summary>
   
   ![image](https://github.com/user-attachments/assets/014def12-bf4e-4dc3-bc10-cb69a1997c0a)
   </details>

1. <details>
   <summary> :green_circle: Upgrade to <code>rancher-v2.8.6</code> (Prime)
   </summary>
   
   * Harvester
     ![image](https://github.com/user-attachments/assets/e7fe7247-c821-4c72-bdce-b92cc401bfc0)
   * Guest Cluster
     ![image](https://github.com/user-attachments/assets/e03920cd-800a-48de-9b75-556f7dc64ab7)

   Ref. https://ranchermanager.docs.rancher.com/v2.8/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades#upgrade-outline
   </details>

1. <details open>
   <summary> :red_circle: Check harvester-cloud-provider
   </summary>
   
   > Chart: `harvester-cloud-provider:0.2.400`
   > Image: `registry.rancher.com/rancher/harvester-cloud-provider:v0.2.1` :x: Changed
   * Deployment
     ![image](https://github.com/user-attachments/assets/bf717b64-ea31-4e48-a808-b4d50d57e1a2)
   * App
     ![image](https://github.com/user-attachments/assets/a21d957b-eaab-4d42-acd6-20f00827687a)
   </details>

## Attachment
* Support bundle: [supportbundle_HarvesterCloudProviderWhenRancherCrossUpgrade_2024-10-16T13-41-59Z.zip](https://github.com/user-attachments/files/17396628/supportbundle_HarvesterCloudProviderWhenRancherCrossUpgrade_2024-10-16T13-41-59Z.zip)
* RKE rancher2_logs: [myrke2-pool1-9c0233d3-g92d2-2024-10-16_13_45_02.tar.gz](https://github.com/user-attachments/files/17396660/myrke2-pool1-9c0233d3-g92d2-2024-10-16_13_45_02.tar.gz)

## Note
1. A known workaround is to delete the old pod.

## Reference
1. harvester/harvester/issues/5348
1. harvester/harvester/issues/5382

**Comment by FrankYang0529** [comment] 2024-10-17 08:49
I can reproduce the issue when upgrade Rancher from v2.8.5 to v2.8.6. The root cause is that:

* In `rancher/rancher:v2.8.5`, the `system-default-registry` default value is empty.
* In `registry.rancher.com/rancher/rancher:v2.8.6`, the `system-default-registry` default value is `registry.rancher.com`.

This value is not hard code in rancher v2.8.6. It's from environment variable.

https://github.com/rancher/rancher/blob/17221038da5bfbc17e5cd728c50925b599941ee8/pkg/settings/setting.go#L234-L236

When we upgrade rancher, the controller rerun all CRs. Although the cluster / rkecontrolplane CR don't update, rancher still get `system-default-registry` from setting.

https://github.com/rancher/rancher/blob/17221038da5bfbc17e5cd728c50925b599941ee8/pkg/capr/planner/config.go#L142-L144

https://github.com/rancher/rancher/blob/17221038da5bfbc17e5cd728c50925b599941ee8/pkg/provisioningv2/image/resolve.go#L52-L60

The machine plan will have new value in `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml`, so all pods in guest cluster will be updated with new registry.

```
{
  "agent-token": "fds8d6mqxgmmx8q5md7nn2zk2kfgnz56zbthpsp62jm7524t658jkn",
  "cloud-provider-config": "/var/lib/rancher/rke2/etc/config-files/cloud-provider-config",
  "cloud-provider-name": "harvester",
  "cni": "calico",
  "disable-kube-proxy": false,
  "etcd-expose-metrics": false,
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-label": [
    "rke.cattle.io/machine=cbe2afab-4c31-452c-aff7-4fdd6825c8b1"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
  "system-default-registry": "registry.rancher.com",
  "token": "ksxfk2tt5brv4j6qvh7np4pp58fmrnf8rgl4v2cjrmsfm9tdfltt9v"
}
```

**Comment by FrankYang0529** [comment] 2024-11-28 06:10
Close this since it's solved in prime document.

**Closed as completed by FrankYang0529** 2024-11-28 06:10 UTC
Labels: kind/bug, severity/3, area/embedded-rancher, reproduce/always, area/guest-cluster-cloud-provider
