### ISSUE TITLE
[BUG] Harvester node never gets to 'ready' state on console (but is up and running) on 1.4.0-RC1

### ISSUE THREAD

**Issue by bcdurden** [harvester/harvester#6705] opened 2024-10-03 19:13 UTC
**Describe the bug**
When installing a fresh new cluster on 1.4.0-rc1 via PXE boot, the console shows 'notready' for both the cluster and the node states. However, I verified through SSH that the cluster was up and running with no Pods in a non-running or error state. The VIP was successfully being assigned to my network device.

Following that, I went to the VIP address via browser and was able to set the UI password and sign into Harvester. Everything appears to be nominal at first glance.

Hardware is used to test various harvester installations so it is 'known good' as is the PXE boot config (mac-id and disk mapping for install params).

When joining the cluster with a second node, that node shows the proper state.

**To Reproduce**
1. Install Harvester onto node (PXE boot may or may not be relevant here)
2. Wait for console to appear and never reach ready state

**Expected behavior**
After installing harvester, the console shows a green ready state for the node and the cluster.

**Support bundle**

[supportbundle_732d3205-0608-4b0d-bb8b-6e9d813060f1_2024-10-03T19-07-27Z.zip](https://github.com/user-attachments/files/17248936/supportbundle_732d3205-0608-4b0d-bb8b-6e9d813060f1_2024-10-03T19-07-27Z.zip)

**Environment**
 - Harvester ISO version: v1.4.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 
     - Minisforum UM780: AMD Ryzen 9 6900H (8c/16t), 64gb DDR5, 1TB NVME Samsung 980Pro

**Comment by bcdurden** [comment] 2024-10-03 19:54
EDIT: So it appears my reboot issue was self-inflicted, but the system still does not show as 'ready'.

**Comment by irishgordo** [comment] 2024-10-03 20:34
@bcdurden :wave: ,  thanks for opening this :smile: :+1: 

This seems to be a duplicate of:
- https://github.com/harvester/harvester/issues/6690#issuecomment-2389519046

That Minisforum UM780 is awesome by the way!  :100: :tada:

**Comment by bk201** [comment] 2024-10-07 09:13
Duplicated with https://github.com/harvester/harvester/issues/6690, please check https://github.com/harvester/harvester/issues/6690 for the fix.

**Closed as completed by bk201** 2024-10-07 09:13 UTC
Labels: kind/bug, wontfix, require/reproduce, require/severity
