### ISSUE TITLE
[BUG] NVMe drive can be added multiple times in host config in UI

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#1608] opened 2021-12-01 19:13 UTC
**Describe the bug**
When editing the host disk config, an NVMe drive can be added multiple times.

**To Reproduce**
- Go the a host configuration screen in the Harvester UI
- Add an NVMe drive
- Add the same NVMe drive

**Expected behavior**
When selecting a drive, it should be removed from the *Add Disk* drop down menu.

**Environment:**
 - Harvester ISO version: 1.0.0-rc1

**Additional context**

**Comment by guangbochen** [comment] 2021-12-02 09:51
https://gist.github.com/janeczku/a70f94912848e88a24b8df1d48eb7c33

**Comment by alexdepalex** [comment] 2021-12-02 10:05
![Annotation 2021-12-02 110437](https://user-images.githubusercontent.com/713019/144400803-78f418ec-aa8f-49ec-92bd-a125899f1b7e.png)


Disks can be selected multiple times.

**Comment by alexdepalex** [comment] 2021-12-02 10:07
![Annotation 2021-12-02 110438](https://user-images.githubusercontent.com/713019/144401013-0f4e35bd-4bb0-4d1c-814e-d1b9d3d75757.png)

Still, both the parent device *and* the already existing partition can be selected from the drop down.

**Comment by alexdepalex** [comment] 2021-12-02 10:12
The devices mentioned in the ndm output also don't exist on the system.

```
crw------- 1 root root 244,  0 Dec  2 09:44 /dev/nvme0
brw-rw---- 1 root disk 259, 10 Dec  2 09:44 /dev/nvme0n1
brw-rw---- 1 root disk 259, 16 Dec  2 09:44 /dev/nvme0n1p1
crw------- 1 root root 244,  1 Dec  2 09:44 /dev/nvme1
brw-rw---- 1 root disk 259,  5 Dec  2 09:44 /dev/nvme1n1
brw-rw---- 1 root disk 259, 12 Dec  2 09:44 /dev/nvme1n1p1
crw------- 1 root root 244,  2 Dec  2 09:44 /dev/nvme2
brw-rw---- 1 root disk 259,  8 Dec  2 09:44 /dev/nvme2n1
brw-rw---- 1 root disk 259, 17 Dec  2 09:44 /dev/nvme2n1p1
crw------- 1 root root 244,  3 Dec  2 09:44 /dev/nvme3
brw-rw---- 1 root disk 259,  7 Dec  2 09:44 /dev/nvme3n1
brw-rw---- 1 root disk 259, 13 Dec  2 09:44 /dev/nvme3n1p1
crw------- 1 root root 244,  4 Dec  2 09:44 /dev/nvme4
brw-rw---- 1 root disk 259,  9 Dec  2 09:44 /dev/nvme4n1
brw-rw---- 1 root disk 259, 15 Dec  2 09:44 /dev/nvme4n1p1
crw------- 1 root root 244,  5 Dec  2 09:44 /dev/nvme5
brw-rw---- 1 root disk 259, 11 Dec  2 09:44 /dev/nvme5n1
brw-rw---- 1 root disk 259, 14 Dec  2 09:44 /dev/nvme5n1p1
```

```
time="2021-12-02T10:09:30Z" level=info msg="Scan block devices of node: node1"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme0c0n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme0c0n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme0c0n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme1c1n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme1c1n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme1c1n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme2c2n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme2c2n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme2c2n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme3c3n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme3c3n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme3c3n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme4c4n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme4c4n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme4c4n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme5c5n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme5c5n1 : exit status 2\n"
time="2021-12-02T10:09:30Z" level=warning msg="failed to read disk uuid of /dev/nvme5c5n1 : exit status 2\n"
time="2021-12-02T10:09:31Z" level=warning msg="failed to generate GUID for device nvme0c0n1"
time="2021-12-02T10:09:31Z" level=info msg="Skip adding non-identifiable block device /dev/nvme0c0n1"
time="2021-12-02T10:09:31Z" level=warning msg="failed to generate GUID for device nvme1c1n1"
time="2021-12-02T10:09:31Z" level=info msg="Skip adding non-identifiable block device /dev/nvme1c1n1"
time="2021-12-02T10:09:31Z" level=warning msg="failed to generate GUID for device nvme2c2n1"
time="2021-12-02T10:09:31Z" level=info msg="Skip adding non-identifiable block device /dev/nvme2c2n1"
time="2021-12-02T10:09:31Z" level=warning msg="failed to generate GUID for device nvme3c3n1"
time="2021-12-02T10:09:31Z" level=info msg="Skip adding non-identifiable block device /dev/nvme3c3n1"
time="2021-12-02T10:09:31Z" level=warning msg="failed to generate GUID for device nvme4c4n1"
time="2021-12-02T10:09:31Z" level=info msg="Skip adding non-identifiable block device /dev/nvme4c4n1"
time="2021-12-02T10:09:31Z" level=warning msg="failed to generate GUID for device nvme5c5n1"
time="2021-12-02T10:09:31Z" level=info msg="Skip adding non-identifiable block device /dev/nvme5c5n1"
```

**Comment by weihanglo** [comment] 2021-12-02 12:17
Hi @alexdepalex. Have some quetions about the environment. Thanks.

- Do we enable multipath or use dual port NVMe disks in that environment? 
- Do we enable any software RAID in the environment?

**Comment by alexdepalex** [comment] 2021-12-02 12:21
There's no multipathing or software raid. These are plain NVMe drives in a PCIe slot.

```
60:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172Xa/172Xb (rev 01) (prog-if 02 [NVM Express])
        Subsystem: Dell Express Flash PM1725b 1.6TB SFF
        Physical Slot: 182
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 35
        NUMA node: 0
        Region 0: Memory at b8c00000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: [40] Power Management version 3
                Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0-,D1-,D2-,D3hot-,D3cold-)
                Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [50] MSI: Enable- Count=1/32 Maskable+ 64bit+
                Address: 0000000000000000  Data: 0000
                Masking: 00000000  Pending: 00000000
        Capabilities: [70] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 256 bytes, PhantFunc 0, Latency L0s unlimited, L1 unlimited
                        ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 25.000W
                DevCtl: Report errors: Correctable- Non-Fatal+ Fatal+ Unsupported+
                        RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+ FLReset-
                        MaxPayload 256 bytes, MaxReadReq 512 bytes
                DevSta: CorrErr- UncorrErr- FatalErr- UnsuppReq- AuxPwr- TransPend-
                LnkCap: Port #0, Speed 8GT/s, Width x4, ASPM not supported
                        ClockPM- Surprise- LLActRep- BwNot- ASPMOptComp+
                LnkCtl: ASPM Disabled; RCB 64 bytes Disabled- CommClk-
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 8GT/s, Width x4, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Not Supported, TimeoutDis+, LTR-, OBFF Via message
                         AtomicOpsCap: 32bit- 64bit- 128bitCAS-
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR-, OBFF Disabled
                         AtomicOpsCtl: ReqEn-
                LnkCtl2: Target Link Speed: 8GT/s, EnterCompliance- SpeedDis-
                         Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
                         Compliance De-emphasis: -6dB
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete+, EqualizationPhase1+
                         EqualizationPhase2+, EqualizationPhase3+, LinkEqualizationRequest-
        Capabilities: [b0] MSI-X: Enable+ Count=129 Masked-
                Vector table: BAR=0 offset=00003000
                PBA: BAR=0 offset=00002000
        Capabilities: [100 v2] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt+ RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES+ TLP+ FCP+ CmpltTO+ CmpltAbrt+ UnxCmplt- RxOF+ MalfTLP+ ECRC+ UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr-
                CEMsk:  RxErr+ BadTLP+ BadDLLP+ Rollover+ Timeout+ NonFatalErr+
                AERCap: First Error Pointer: 00, ECRCGenCap+ ECRCGenEn- ECRCChkCap+ ECRCChkEn-
                        MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
                HeaderLog: 00000000 00000000 00000000 00000000
        Capabilities: [148 v1] Device Serial Number xx
        Capabilities: [158 v1] Power Budgeting <?>
        Capabilities: [178 v1] #19
        Kernel driver in use: nvme
        Kernel modules: nvme
```

```
60:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172Xa/172Xb (rev 01) (prog-if 02 [NVM Express])
61:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172Xa/172Xb (rev 01) (prog-if 02 [NVM Express])
62:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172Xa/172Xb (rev 01) (prog-if 02 [NVM Express])
63:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172Xa/172Xb (rev 01) (prog-if 02 [NVM Express])
b1:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172Xa/172Xb (rev 01) (prog-if 02 [NVM Express])
b2:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller 172Xa/172Xb (rev 01) (prog-if 02 [NVM Express])
```

**Comment by weihanglo** [comment] 2021-12-02 14:43
Thanks for the info. I guess I can reproduce the environment.
It's about private nvme namespace. I use qemu to emulate NVMe and add following args. 
The [`shared=off`](https://qemu.readthedocs.io/en/latest/system/devices/nvme.html#nvm-subsystems) in the last line is the most important property.

```
-device nvme-subsys,id=nvme-subsys-0,nqn=subsys0
-device nvme,id=nvme-ctrl-0,serial=deadbeef,subsys=nvme-subsys-0
-drive file=/path/to/nvm-1.img,format=raw,if=none,id=nvm-1
-device nvme-ns,drive=nvm-1,shared=off
``` 

And here is the result:

![image](https://user-images.githubusercontent.com/14314532/144442694-ef95d58a-e106-4a9f-a5e7-8d4d3103cbfc.png)

Since node-disk-manager are not interested in namespace but partition. I propose we can simply skip namespaces. Feel free to comment.

**Comment by weihanglo** [comment] 2021-12-02 15:33
Turns out that it is both a UI bug and a backend enhancement, not what I guess in the beginning.

In the edit mode, the dashboard should not display the same device twice if it is already selected. For the backend, it should reject bad payload from the client but it doesn't.

![image](https://user-images.githubusercontent.com/14314532/144452350-faac41e5-b5fb-4b63-8546-9c66c6ceb44d.png)

**Comment by janeczku** [comment] 2021-12-02 15:45
@weihanglo does that bug also explain why disk manager looks for non-existent devices? https://github.com/harvester/harvester/issues/1608#issuecomment-984482993

**Comment by weihanglo** [comment] 2021-12-02 15:54
> @weihanglo does that bug also explain why disk manager looks for non-existent devices? [#1608 (comment)](https://github.com/harvester/harvester/issues/1608#issuecomment-984482993)

They are two separate issues. For "non-existent devices", if you refer to `/dev/nvme0c?n?`, those are NVMe private namespaces located in `/sys/block`, where disk manager collects disk/partition info. They causes no harm during scanning devices. I just need further survey to make sure it's safe to skip them.

**Comment by weihanglo** [comment] 2021-12-06 04:04
- ✅ Verified that the same disk cannot be added twice with https://github.com/harvester/dashboard/pull/186/commits/3807b7f0ad0cc20ffaea768e442a4ad5c67681e3
- ❓ I tend to disable parent device option when a child device has been selected (and vice versa). Can we resolve this within the same issue? Or creating another issue is better?

<img src="https://user-images.githubusercontent.com/14314532/144784978-a00bb7e6-9693-4601-89f9-d4afb1a421b9.png" width="500px">

**Comment by n313893254** [comment] 2021-12-06 04:33
Sure, let me fix it.

**Comment by lanfon72** [comment] 2021-12-13 17:57
Verified this issue should be fixed.

![image](https://user-images.githubusercontent.com/5169694/145861027-2b7575c8-a467-43eb-99ca-28a7c0026dba.png)
![image](https://user-images.githubusercontent.com/5169694/145861276-d9cab21a-7c82-4287-af2f-3b60fab11a3f.png)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-5d6f3db0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with 2 nodes
2. Power off 2nd node
3. Update VM's xml definition (by using `virsh edit` or virt-manager)
    - Create **nvme.img** block: `dd if=/dev/zero of=/var/lib/libvirt/images/nvme.img bs=1M count=4096`
    - change owner `chown qemu:qemu /var/lib/libvirt/images/nvme.img`
    - update `<domain type="kvm">` to `<domain type="kvm" xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0">`
    - append xml node into **domain** as below:
```xml
  <qemu:commandline>
    <qemu:arg value="-drive"/>
    <qemu:arg value="file=/var/lib/libvirt/images/nvme.img,if=none,id=D22,format=raw"/>
    <qemu:arg value="-device"/>
    <qemu:arg value="nvme,drive=D22,serial=1234"/>
  </qemu:commandline>
```
4. Power on 2nd node
5. login to dashboard, then click `Edit Config` on 2nd node
6. Navigate to **Disks** tab, then add the NVMe disk from the drop-down list of **Add Disk**
7. The NVMe disk should disappear from the drop-down list
8. Cick **Save**, `Edit Config` on 2nd node again
9. The NVMe disk should not able to be added again

**Closed as completed by lanfon72** 2021-12-13 17:57 UTC
Labels: kind/bug, area/ui, priority/0, blocker, area/node-disk-mgmt
