### ISSUE TITLE
[BUG] backup restore on new cluster without available vm network will silently fail and queue

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#6630] opened 2024-09-24 23:23 UTC
**Describe the bug**

When you restore a backup on a new cluster with backups from an old cluster it won't work without the associated VM network. If you try it will silently fail, but if you create the VM network it will create all of the queued failed VMs at once. This is on NFS backup target

**To Reproduce**
1. Create a backup on a VM in a cluster
2. Create a new cluster with no VM networks
3. Connect the old backup target to the new cluster
4. Don't create any VM networks
5. Try to restore to a new VM with the backup
6. Wait for it to create
7. Now create a VM network with the old name

**Expected behavior**

You should get an error if you can't create a VM from backup. It also might be necessary to specify the VM network on restore

**Support bundle**

[supportbundle_0252517e-6219-48e7-b1a3-2bd44fdc32d7_2024-09-24T23-19-08Z.zip](https://github.com/user-attachments/files/17122105/supportbundle_0252517e-6219-48e7-b1a3-2bd44fdc32d7_2024-09-24T23-19-08Z.zip)

**Environment**
 - Harvester ISO version: v1.4-63a0567-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node vagrant-harvester libvirt cluster

**Additional context**

This did not give any UI errors on create in the browser console. It also went through all three VM creations I had tried once I added the VM network.

Found while testing #6371

**Comment by noahgildersleeve** [comment] 2024-10-02 20:41
I checked this with a new 3 node libvirt cluster running `v1.4-047b046-head` and it will not auto-assign a new VM network. It has to be named the same thing, or it silently fails/queues.

**Comment by w13915984028** [comment] 2024-10-07 07:51
This could be a more general topic, the source  VM may be running:
- On a specific node/node group
- With CPU pinning (v140 new feature)
- With PCI-passthrough devices
- With vGPU
- With customized network
- With encrypted volumes
- ...

When restoring the VM from a backup, all the the above may lead to a failure. Use webhook to check all or fail the restore explicitly after a certain amount of try?

**Comment by FrankYang0529** [comment] 2024-10-07 08:27
> When restoring the VM from a backup, all the the above may lead to a failure. Use webhook to check all or fail the restore explicitly after a certain amount of try?

Yeah, good catch. I would prefer to use webhook to check all resources, because we don't have a VMRestore UI now. Users can't check VMRestore condition on UI. WDYT?

cc @bk201

**Comment by w13915984028** [comment] 2024-10-07 08:47
@FrankYang0529 
Another scenario needs to be taken into account:

If VM restore fails, can user edit the VM spec to amend some configs to get vm running ? When it is true, the webhook may not be a best solution, it denies the possibility.

On the other hand, the webhook will be quite complex to check all the above scenarios.

**Comment by FrankYang0529** [comment] 2024-10-07 08:53
> If VM restore fails, can user edit the VM spec to amend some configs to get vm running ? When it is true, the webhook may not be a best solution, it denies the possibility.

The issue here is VM can't be created because there is no related resources. For updating VM, I think it's another case. Users can update VM even if it's from VMRestore.

> On the other hand, the webhook will be quite complex to check all the above scenarios.

I agree. Another way is that we don't create VM in the controller. We just load the VMBackup spec to the UI and users can create a new VM like normal process.

**Comment by brandboat** [comment] 2024-10-22 14:10
gentle ping @FrankYang0529, in the test plan I tried to backup a VM, and restore it in a brand new harvester cluster. However, after setting up the same backup-target and waiting for over 30 mins, no VM backup have appeared. Am I doing something wrong ?

# Environment
- ipxe 3 nodes (each 8 cores / 16 GB RAM / 250 GB disk)
- 1.4.0-rc3
- minio, build from docker
```bash
docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  -e "MINIO_ROOT_USER=$YOUR_USER" \
  -e "MINIO_ROOT_PASSWORD=$YOUR_PASSWORD" \
  quay.io/minio/minio server /data --console-address ":9001"
```

# Test steps
## Test VM backup and restore in the same cluster
✅  test ok
<details>
  <summary>Create VM `test` with VM network `default/test`</summary>

  ![image](https://github.com/user-attachments/assets/076dad8f-c913-4401-a3b4-4af694afe73b)
</details>

<details>
  <summary>Create backup</summary>

  ![image](https://github.com/user-attachments/assets/f7e40ee3-21dd-412b-a6b5-9a287778f70e)
</details>

<details>
  <summary>Delete VM `test`</summary>

  ![image](https://github.com/user-attachments/assets/38a9d0bb-ddfc-4fbd-8786-c40a0b003730)
</details>

<details>
  <summary>Delete VM network `test`</summary>

  ![image](https://github.com/user-attachments/assets/fb9e4174-56d2-4f43-b00d-a71a95bddb82)
</details>

<details>
  <summary>Restore VM `test`, encounter expected error message:  
  `admission webhook "validator.harvesterhci.io" denied the request: Failed to get network attachment definition default/test, err: network-attachment-definitions.k8s.cni.cncf.io "test" not found`</summary>

  ![image](https://github.com/user-attachments/assets/da016610-58c8-4282-893c-9250c6063294)
</details>

## Test VM backup in old cluster and restore VM in new cluster
❌ test failed
- In minio we already have a vm backup `test-bk` after testing **_Test VM backup and restore in the same cluster_**
- Create a brand new harvester cluster with 3 nodes (each 8 cores / 16 GB RAM / 250 GB disk, also v1.4.0-rc3)
- Setup the same backup-target used in old harvester cluster
<img width="1667" alt="image" src="https://github.com/user-attachments/assets/a0fbaf64-6dbe-4dcb-ad34-404f9d353f43">


- No VM backup show up
<img width="1674" alt="image" src="https://github.com/user-attachments/assets/d08d3fe7-9393-4d3f-9057-d6811d81de43">

Below is the log from harvester deployment
```
time="2024-10-22T13:38:23Z" level=info msg="start syncing vm image metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:38:23Z" level=info msg="create vm image from backup target" displayName=focal-server-cloudimg-amd64.img name=image-hh6ns namespace=default
time="2024-10-22T13:38:23Z" level=info msg="start syncing vm backup metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:38:23Z" level=warning msg="skip creating vm backup, because the storage class is not found" error="storageclasses.storage.k8s.io \"longhorn-image-hh6ns\" not found" name=test-bk namespace=default storageClasss=longhorn-image-hh6ns
time="2024-10-22T13:38:23Z" level=info msg="start syncing vm image metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:38:23Z" level=info msg="start syncing vm backup metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:38:23Z" level=warning msg="skip creating vm backup, because the storage class is not found" error="storageclasses.storage.k8s.io \"longhorn-image-hh6ns\" not found" name=test-bk namespace=default storageClasss=longhorn-image-hh6ns
time="2024-10-22T13:38:23Z" level=info msg="start syncing vm image metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
W1022 13:38:23.070745       7 warnings.go:70] metadata.finalizers: "longhorn.io": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
time="2024-10-22T13:38:23Z" level=info msg="start syncing vm backup metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:38:23Z" level=warning msg="skip creating vm backup, because the storage class is not found" error="storageclasses.storage.k8s.io \"longhorn-image-hh6ns\" not found" name=test-bk namespace=default storageClasss=longhorn-image-hh6ns
time="2024-10-22T13:38:27Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:38:42Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:38:51Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:39:16Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:39:21Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
W1022 13:46:00.785046       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
W1022 13:52:32.786240       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
time="2024-10-22T13:54:41Z" level=error msg="Error during subscribe websocket: close sent"
time="2024-10-22T13:54:42Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
time="2024-10-22T13:54:47Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
W1022 13:58:21.788188       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
time="2024-10-22T14:00:45Z" level=error msg="Error during subscribe websocket: close sent"
time="2024-10-22T14:00:46Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
W1022 14:05:59.789809       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
```

**Comment by WebberHuang1118** [comment] 2024-10-23 00:45
> gentle ping @FrankYang0529, in the test plan I tried to backup a VM, and restore it in a brand new harvester cluster. However, after setting up the same backup-target and waiting for over 30 mins, no VM backup have appeared. Am I doing something wrong ?
> 
> # Environment
> * ipxe 3 nodes (each 8 cores / 16 GB RAM / 250 GB disk)
> * 1.4.0-rc3
> * minio, build from docker
> 
> ```shell
> docker run \
>   -p 9000:9000 \
>   -p 9001:9001 \
>   -e "MINIO_ROOT_USER=$YOUR_USER" \
>   -e "MINIO_ROOT_PASSWORD=$YOUR_PASSWORD" \
>   quay.io/minio/minio server /data --console-address ":9001"
> ```
> 
> # Test steps
> ## Test VM backup and restore in the same cluster
> ✅ test ok
> 
> Create VM `test` with VM network `default/test`
> Create backup
> Delete VM `test`
> Delete VM network `test`
> Restore VM `test`, encounter expected error message: `admission webhook "validator.harvesterhci.io" denied the request: Failed to get network attachment definition default/test, err: network-attachment-definitions.k8s.cni.cncf.io "test" not found`
> ## Test VM backup in old cluster and restore VM in new cluster
> ❌ test failed
> 
> * In minio we already have a vm backup `test-bk` after testing **_Test VM backup and restore in the same cluster_**
> * Create a brand new harvester cluster with 3 nodes (each 8 cores / 16 GB RAM / 250 GB disk, also v1.4.0-rc3)
> * Setup the same backup-target used in old harvester cluster
> 
> <img alt="image" width="1667" src="https://private-user-images.githubusercontent.com/4344302/378821484-a0fbaf64-6dbe-4dcb-ad34-404f9d353f43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDMyODUsIm5iZiI6MTcyOTY0Mjk4NSwicGF0aCI6Ii80MzQ0MzAyLzM3ODgyMTQ4NC1hMGZiYWY2NC02ZGJlLTRkY2ItYWQzNC00MDRmOWQzNTNmNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDAyMzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY1MGEwNTY4MWFiNDM5ZGVhMTczMzM2MzI5NTU1NmJmMTgxMjhhYTc4YWQ3NmFlN2Q4OTc0ZDU1ZDcwZDFiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wscWMAHEKCyKK63n1NcRpdfeg8Wda54MPjsUfoEBT-8">
> * No VM backup show up
> 
> <img alt="image" width="1674" src="https://private-user-images.githubusercontent.com/4344302/378818570-d08d3fe7-9393-4d3f-9057-d6811d81de43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDMyODUsIm5iZiI6MTcyOTY0Mjk4NSwicGF0aCI6Ii80MzQ0MzAyLzM3ODgxODU3MC1kMDhkM2ZlNy05MzkzLTRkM2YtOTA1Ny1kNjgxMWQ4MWRlNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDAyMzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA0YTI1YTYzNmYyMmI5MzNiODkzODg4MGNjOTNlYjMzOWEwOGIxNjMzZTM3ZTRkZjcyMDdjYjQyN2Y4NTg1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0LRTwP9nWbLA7isO6VnhltvbnEoh2lZF2Znw3QIbyn4">
> Below is the log from harvester deployment
> 
> ```
> time="2024-10-22T13:38:23Z" level=info msg="start syncing vm image metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
> time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:38:23Z" level=info msg="create vm image from backup target" displayName=focal-server-cloudimg-amd64.img name=image-hh6ns namespace=default
> time="2024-10-22T13:38:23Z" level=info msg="start syncing vm backup metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
> time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:38:23Z" level=warning msg="skip creating vm backup, because the storage class is not found" error="storageclasses.storage.k8s.io \"longhorn-image-hh6ns\" not found" name=test-bk namespace=default storageClasss=longhorn-image-hh6ns
> time="2024-10-22T13:38:23Z" level=info msg="start syncing vm image metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
> time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:38:23Z" level=info msg="start syncing vm backup metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
> time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:38:23Z" level=warning msg="skip creating vm backup, because the storage class is not found" error="storageclasses.storage.k8s.io \"longhorn-image-hh6ns\" not found" name=test-bk namespace=default storageClasss=longhorn-image-hh6ns
> time="2024-10-22T13:38:23Z" level=info msg="start syncing vm image metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
> time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> W1022 13:38:23.070745       7 warnings.go:70] metadata.finalizers: "longhorn.io": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
> time="2024-10-22T13:38:23Z" level=info msg="start syncing vm backup metadata..." target.endpoint="http://192.168.100.1:9000/" target.type=s3
> time="2024-10-22T13:38:23Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:38:23Z" level=warning msg="skip creating vm backup, because the storage class is not found" error="storageclasses.storage.k8s.io \"longhorn-image-hh6ns\" not found" name=test-bk namespace=default storageClasss=longhorn-image-hh6ns
> time="2024-10-22T13:38:27Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:38:42Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:38:51Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:39:16Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:39:21Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> W1022 13:46:00.785046       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
> W1022 13:52:32.786240       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
> time="2024-10-22T13:54:41Z" level=error msg="Error during subscribe websocket: close sent"
> time="2024-10-22T13:54:42Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> time="2024-10-22T13:54:47Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> W1022 13:58:21.788188       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
> time="2024-10-22T14:00:45Z" level=error msg="Error during subscribe websocket: close sent"
> time="2024-10-22T14:00:46Z" level=info msg="Loaded driver for s3://foobar@asia-east-1/" pkg=s3
> W1022 14:05:59.789809       7 warnings.go:70] kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
> ```

Hi @brandboat 
The new cluster has an image with the same displayName as another in the source cluster. You may delete the image metadata in path `vmimages/<namespace>` for the remote target

**Comment by brandboat** [comment] 2024-10-23 01:37
> Hi @brandboat
The new cluster has an image with the same displayName as another in the source cluster. You may delete the image metadata in path vmimages/<namespace> for the remote target

Thanks, that's the root cause.

**Comment by brandboat** [comment] 2024-10-23 01:40
Test passed, will close the issue.

# Environment
- ipxe 3 nodes (each 8 cores / 16 GB RAM / 250 GB disk)
- 1.4.0-rc3
- minio, build from docker
```bash
docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  -e "MINIO_ROOT_USER=$YOUR_USER" \
  -e "MINIO_ROOT_PASSWORD=$YOUR_PASSWORD" \
  quay.io/minio/minio server /data --console-address ":9001"
```

# Test steps
## Test VM backup and restore in the same cluster
✅  test ok
<details>
  <summary>Create VM `test` with VM network `default/test`</summary>

  ![image](https://github.com/user-attachments/assets/076dad8f-c913-4401-a3b4-4af694afe73b)
</details>

<details>
  <summary>Create backup</summary>

  ![image](https://github.com/user-attachments/assets/f7e40ee3-21dd-412b-a6b5-9a287778f70e)
</details>

<details>
  <summary>Delete VM `test`</summary>

  ![image](https://github.com/user-attachments/assets/38a9d0bb-ddfc-4fbd-8786-c40a0b003730)
</details>

<details>
  <summary>Delete VM network `test`</summary>

  ![image](https://github.com/user-attachments/assets/fb9e4174-56d2-4f43-b00d-a71a95bddb82)
</details>

<details>
  <summary>Restore VM `test`, encounter expected error message:  
  `admission webhook "validator.harvesterhci.io" denied the request: Failed to get network attachment definition default/test, err: network-attachment-definitions.k8s.cni.cncf.io "test" not found`</summary>

  ![image](https://github.com/user-attachments/assets/da016610-58c8-4282-893c-9250c6063294)
</details>

## Test VM backup in old cluster and restore VM in new cluster
✅  test ok
- In minio we already have a vm backup `test-bk` after testing **_Test VM backup and restore in the same cluster_**
- Create a brand new harvester cluster with 3 nodes (each 8 cores / 16 GB RAM / 250 GB disk, also v1.4.0-rc3)
<details>
  <summary>Setup the same backup-target used in old harvester cluster</summary>
<img width="1667" alt="image" src="https://github.com/user-attachments/assets/a0fbaf64-6dbe-4dcb-ad34-404f9d353f43">
</details>
<details>
  <summary>Restore VM `test`, encounter expected error message:  
  `admission webhook "validator.harvesterhci.io" denied the request: Failed to get network attachment definition default/test, err: network-attachment-definitions.k8s.cni.cncf.io "test" not found`</summary>

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/750ab0a4-9dec-4a5c-9bdb-cf9a16f7f822">

</details>

**Closed as completed by brandboat** 2024-10-23 01:40 UTC
Labels: kind/bug, require/investigate, severity/3, reproduce/always, area/vm-backup-restore
