### ISSUE TITLE
[BUG] GUI throws errors after restoring a new VM

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#1928] opened 2022-02-18 04:00 UTC
**Describe the bug**

**To Reproduce**
1. Create a VM backup
2. Restore a new VM
3. The restoring VM does not have the annotation of `harvesterhci.io/volumeClaimTemplates`
4. GUI throws errors

![截屏2022-02-18 上午11 54 10](https://user-images.githubusercontent.com/15041915/154614813-c8d275f8-b152-4b50-bf51-b7a7b89314ff.png)

**Expected behavior**

1. GUI will not throw the error

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment] 2022-02-24 09:22
I don't think it's necessary to add any automation test or integration test, because it's an expected behavior，  Now just delete the information in the console。

**Comment by TachunLin** [comment] 2022-03-01 13:53
Verified **fixed** on master-bfd6a8a9-head. (2/27). Close this issue.

### Result
During and after restoring a new VM from existing backup. The GUI did not throw error

![image](https://user-images.githubusercontent.com/29251855/156179443-47562b11-0642-4a6b-8199-90c18c9b6705.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-bfd6a8a9-head

### Verify Steps
1. Setup S3 backup target
2. Create a backup from existing VM
3. Restore a new VM from existing backup
4. Check GUI did not error message

**Closed as completed by TachunLin** 2022-03-01 13:53 UTC
Labels: kind/bug, area/ui, priority/0
