### ISSUE TITLE
[BUG] Upgrade was stuck indefinitely in the "upgrade system services" phase due to fleet-agent unsuccessful registration

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5023] opened 2024-01-25 06:42 UTC
**Describe the bug**

When upgrading from v1.2.1 to the master build, chances are you'll encounter a hurdle upgrading harvester charts. This is majorly due to Fleet, the one inside Harvester. I suspect there's a race condition in between.

The following are some observations:

*Before upgrade*

```
# the original ClusterRegistration object
name: request-4wj85
clientID: 8qtzwh6rkwtqgdnvg68k2qnw88v6jts6xfvtlxqwvz4sqh2w67vstd
clientRandom: xh2d9cvqk8gdrplf8tc7vdxbg5mgc4sxhmfkn6jd4gm9vbs4ddcw7v
---
# the generated Secret name (concatenate clientID and clientRandom, then sha256sum)
c-aede10a154549ac332492cd8c380ae5bfde238098ab3b980520d9ef5343cf7b1
```

*During Harvester charts upgrade*

Logs from cattle-fleet-local-system/fleet-agent:

```
...
create clusterregistration with id 8qtzwh6rkwtqgdnvg68k2qnw88v6jts6xfvtlxqwvz4sqh2w67vstd
Waiting for secret 'cattle-fleet-clusters-system/c-0d366abda81eeb6e0e2e4639bd37d7a816630bd361315709cae728abdb7b7 for request 'fleet-local/request-xkrps'
...
```

Logs from fleet-controller:

```
...
time="2024-01-24T02:57:59Z" level=info msg="Deleted old agent for cluster (fleet-local/local) in namespace cattle-fleet-local-system"
time="2024-01-24T02:57:59Z" level=info msg="Cluster import for 'fleet-local/local'. Deployed new agent"
W0124 02:57:59.626726       1 warnings.go:70] unknown field "status.apiServerCAHash"
W0124 02:57:59.626742       1 warnings.go:70] unknown field "status.apiServerURL"
time="2024-01-24T02:58:00Z" level=info msg="Waiting for service account token key to be populated for secret cluster-fleet-local-local-1a3d67d0a899/request-xkrps-5dce76d5-d54a-4b94-a795-9e29a5fe93bd-token"
time="2024-01-24T02:58:01Z" level=info msg="Namespace assigned to cluster 'fleet-local/local' enqueues cluster registration 'fleet-local/request-xkrps'"
time="2024-01-24T02:58:03Z" level=info msg="Cluster registration request 'fleet-local/request-xkrps' granted, creating cluster, request service account, registration secret"
time="2024-01-24T02:58:03Z" level=info msg="Waiting for service account token key to be populated for secret cluster-fleet-local-local-1a3d67d0a899/request-4zplz-b9abe659-0af9-4f09-9972-76ec2a4f59eb-token"
time="2024-01-24T02:58:03Z" level=error msg="error syncing 'fleet-local/request-4wj85': handler cluster-registration: failed to delete fleet-local/request-4wj85 rbac.authorization.k8s.io/v1, Kind=Role for cluster-registration fleet-local/request-4wj85: roles.rbac.authorization.k8s.io \"request-4wj85\" not found, requeuing"
time="2024-01-24T02:58:03Z" level=info msg="Cluster registration request 'fleet-local/request-xkrps' granted, creating cluster, request service account, registration secret"
time="2024-01-24T02:58:03Z" level=info msg="Cluster registration request 'fleet-local/request-xkrps' granted, creating cluster, request service account, registration secret"
time="2024-01-24T02:58:05Z" level=info msg="Cluster registration request 'fleet-local/request-4zplz' granted, creating cluster, request service account, registration secret"
...
```

On the other hand, the newly generated ClusterRegistration seems not to match the one that fleet-agent is waiting for:

```
# the new ClusterRegistration object
name: request-4zplz
clientID: 8qtzwh6rkwtqgdnvg68k2qnw88v6jts6xfvtlxqwvz4sqh2w67vstd
clientRandom: cjj9x9vvfvnnxkfc85hj8kdtwcplscmtv55mkcxjbk9s28kkpgf9zq
---
# the generated Secret name which fleet-agent should be waiting for
c-03fe7ccb8065cca7ff088397262cf903c3d167c4629c79a65560a5ae79baaed8
```

*Summary*

Apparently, the `fleet-agent` is waiting for the Secret generated from an older ClusterRegistration object that no longer exists.

**To Reproduce**

1. Prepare a Harvester cluster in v1.2.1
2. Upgrade to with master-build ISO image
3. Check if the upgrade progress stuck at "upgrade system services" phase; To be more precisely, after the embedded Rancher is upgraded.

**Expected behavior**

The upgrade should not be stuck.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.1 to master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

As for the workaround, we need to remove the `fleet-controller` Pod to make it redeploy the agent and regenerate the ClusterRegistration object. Everything goes fine afterwards.

**Comment by w13915984028** [comment] 2024-02-13 07:34
Another issue #5139, same root cause?

**Comment by weyfonk** [comment] 2024-02-14 11:09
This may be related to [rancher#41848](https://github.com/rancher/rancher/issues/41848).

**Comment by bk201** [comment] 2024-02-26 02:38
Hit this too, need to delete fleet-controller pod to restart fleet-agent to continue.

**Comment by bk201** [comment] 2024-03-07 03:30
@harvester/qa I'd suggest we monitor if the issue happens during upgrade tests, and if not we can close it. it's hard to reproduce.

**Comment by lanfon72** [comment] 2024-03-10 19:01
Close as unable to reproduce this bug on the new installed cluster upgrade process (`v1.2-a822a3a4-head` -> `v1.3.0-rc4`)  in 10 times.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: `v1.2-a822a3a4-head` -> `v1.3.0-rc4`
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Perform upgrade
3. Upgrade should complete successfully.

**Closed as completed by lanfon72** 2024-03-10 19:01 UTC
Labels: kind/bug, area/install-upgrade, reproduce/often, require/severity, backport-needed/1.2.2
