### ISSUE TITLE
[BUG] Virtualization Management `...` does not have available options -> cluster owners should be able to edit / view the yaml of virtualization management clusters

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2573] opened 2022-07-26 19:30 UTC
**Rancher Server Setup**
- Rancher version:v2.6.7-rc3
- Installation option (Docker install/Helm Chart): docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):n/a
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version:any
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): virtualization management (harvester management) cluster(s)

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): admin, cluster owner

**Describe the bug**
when clicking the `...` option for a virtualization management cluster, user does not have any options to choose form

**To Reproduce**
* go to virtualization management
* connect a harvester management cluster to rancher using the registration cmd
* wait for the cluster to connect
* click the `...` from virtualization management page

**Result**
no options are available

**Expected Result**
user should be able to edit/view config/yaml through this option

**Screenshots**
<img width="196" alt="Screen Shot 2022-07-26 at 12 20 19 PM" src="https://user-images.githubusercontent.com/16691014/181094921-a0017001-f871-4417-a264-d05c6145263d.png">

**Comment by n313893254** [comment] 2022-07-27 01:58
Hi, @slickwarren. The issue is fixed in v2.6.4-rc4. Here is the related [PR](https://github.com/rancher/dashboard/pull/6397) and [commit](https://github.com/rancher/dashboard/pull/6397/commits/09b873fbd1ff3bda53c1be1e249feb572dff8539).

You could upgrade the rancher server to v2.6.4-rc4 or use the v2.6.4-rc4 ui-dashboard-index.

**Comment by TachunLin** [comment] 2022-08-01 06:29
Verified **fixed** on Rancher `v2.6.7-rc5` with Harvester `v1.0.3-rc1`. Close this issue.

### Result
* Now when clicking the `...` of the cluster in virtualization management page, 
  ![image](https://user-images.githubusercontent.com/29251855/182082933-b1522f4a-d6d8-4259-9363-b0d666786a9f.png)

* Check can open the following function and work as expected 
  - Kubectl
  - Download KubeConfig
  - Copy KubeConfig to clipboard 
  - Edit Config
  - View Yaml
  - Download Yaml 
  - Delete


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: v1.0.3-rc1
* Rancher version: `v2.6.7-rc5`
* Rancher ui-dashboard-index: `https://releases.rancher.com/dashboard/latest/index.html` 
* Rancher ui-offline-preferred: `Dynamic`

### Verify Steps
1. Import Harvester in Rancher Virtualization Management
2. Check Harvester in running status
3. Click the `...` besides the Manage button 
4. Check the menu options

**Closed as completed by TachunLin** 2022-08-01 06:29 UTC
Labels: kind/bug, area/ui, priority/0, severity/1, area/embedded-rancher, reproduce/always
