### ISSUE TITLE
[BUG] Grub boot stanza doesn't exclude floppy. Could result in grub hangs.

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2120] opened 2022-04-06 08:16 UTC
**Describe the bug**
Grub boot stanza doesn't exclude floppy (--no-floppy). In situations where disks are reshuffled or multiple controller setups, this might result in non-existing floppy drives to be scanned, which blocks the boot cycle, or dropping to grub rescue prompt for 30 minutes.
**To Reproduce**
  1. Have an awkward disk configuration or make the partition containing the boot label vanish.

**Expected behavior**
Don't scan for floppy's.

**Support bundle**

**Environment:**
- Harvester ISO version: 1.0.1-rc2
- Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell RX740d with iDrac 5.10.10.00

**Additional context**
We're trying to install Harvester on sdb, which seems to be causing issues as well.

**Comment by alexdepalex** [comment] 2022-04-06 08:18
Duplicate of https://github.com/harvester/harvester/issues/2115

😉

**Closed as completed** 2022-04-06 08:18 UTC
Labels: kind/bug
