### ISSUE TITLE
[Doc] upgrade stuck on create upgrade VM

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4246] opened 2023-07-17 15:02 UTC
### Describe the bug
![image](https://github.com/harvester/harvester/assets/5169694/022c7f49-b500-44a6-8ff9-c728629844e0)
![image](https://github.com/harvester/harvester/assets/5169694/e6f60276-0c4e-4c4f-b5e1-65c66c62e05a)
![image](https://github.com/harvester/harvester/assets/5169694/2376775c-6377-4739-945b-db4c27c847f8)

### To Reproduce
1. Install Harvester with at least 4 nodes
2. Create an image for VM creation
3. Create VLAN
4. Import Harvester into Rancher 2.7.4
5. Create RKE1 and RKE2 cluster (1 node)
6. Install Harvester Cloud Provider and CSI Driver
7. Create DHCP load balancer service (only RKE1 cluster)
8. Create Nginx deployment with new Harvester PVC
9. Upgrade Rancher to 2.7.5
10. Upgrade Harvester

## Environment:
 - Harvester ISO version: **v1.1.2** -> **v1.2.0**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 4 nodes**
 - Rancher Version: **v2.7.4** -> **v2.7.5**

### Additional context
**v1.2.0** Release testing for 4 nodes upgrade

### Support bundle
[supportbundle_eb8adc43-b57e-4e00-99b9-cb77dd4c07fb_2023-07-17T14-59-30Z.zip](https://github.com/harvester/harvester/files/12070820/supportbundle_eb8adc43-b57e-4e00-99b9-cb77dd4c07fb_2023-07-17T14-59-30Z.zip)

**Comment by Vicente-Cheng** [comment] 2023-07-21 11:31
The root cause can be found below:

1. We meet the known issue (https://github.com/longhorn/longhorn/issues/4305) for a stopped replica. (Backing image sync fail)
2. The engine needs to wait for whole replicas to be running, so that is why it is stuck on creating an upgrade VM (because one replica is stuck due to the above reason).

**Comment by lanfon72** [comment] 2023-07-24 06:48
It looks the bug has been fixed in newer version, for users upgrading from old version, we might need document a workaround to continue the upgrade.

**Comment by bk201** [comment] 2023-08-28 06:34
Doc merged: https://docs.harvesterhci.io/dev/upgrade/v1-1-2-to-v1-2-0#2-an-upgrade-is-stuck-in-creating-upgrade-repository

**Closed as completed** 2023-08-28 08:39 UTC
Labels: kind/bug, require/doc, priority/1, severity/1, regression, require/release-note, area/install-upgrade, reproduce/often
