### ISSUE TITLE
[BUG] Virtual machine status stuck in "Starting"

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1822] opened 2022-01-14 13:26 UTC
Harvester 1.0.0

**To Reproduce**
Create a virtual machine via Rancher -> Virtualization management

**Result**
Virtual machine stuck in the "Starting" state in the Rancher UI (Rancher -> Virtualization management)

In Harvester native UI the machine is shown "Running"

**Support bundle**

[supportbundle_e040cc7c-fcf3-4892-bcf4-514bca7bf53b_2022-01-14T13-27-14Z.zip](https://github.com/harvester/harvester/files/7870682/supportbundle_e040cc7c-fcf3-4892-bcf4-514bca7bf53b_2022-01-14T13-27-14Z.zip)

**Additional context**

The following event is occurring every 30 seconds:

> Reason: Created       Age:    30s (x9 over 6m1s)  From: virt-handler   Message: VirtualMachineInstance defined.

*VirtualMachineInstance object*

```
Name:         plo-jb
Namespace:    default
Labels:       harvesterhci.io/vmName=plo-jb
              kubevirt.io/nodeName=mike
Annotations:  harvesterhci.io/sshNames: ["default/jbruder"]
              kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2022-01-14T13:12:26Z
  Finalizers:
    kubevirt.io/virtualMachineControllerFinalize
    foregroundDeleteVirtualMachine
    wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs
  Generation:  12
  Managed Fields:
    API Version:  kubevirt.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs":
    Manager:      harvester
    Operation:    Update
    Time:         2022-01-14T13:12:26Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:harvesterhci.io/sshNames:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:finalizers:
          .:
          v:"kubevirt.io/virtualMachineControllerFinalize":
        f:labels:
          .:
          f:harvesterhci.io/vmName:
          f:kubevirt.io/nodeName:
        f:ownerReferences:
          .:
          k:{"uid":"9b939423-d589-4dce-a8e7-8bc085227746"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:domain:
          .:
          f:cpu:
            .:
            f:cores:
            f:sockets:
            f:threads:
          f:devices:
            .:
            f:disks:
            f:inputs:
            f:interfaces:
          f:firmware:
            .:
            f:uuid:
          f:machine:
            .:
            f:type:
          f:memory:
            .:
            f:guest:
          f:resources:
            .:
            f:limits:
              .:
              f:cpu:
              f:memory:
            f:requests:
              .:
              f:cpu:
              f:memory:
        f:evictionStrategy:
        f:hostname:
        f:networks:
        f:volumes:
      f:status:
        .:
        f:activePods:
          .:
          f:9534d977-3ad8-4c00-9e64-2c5eb26260b5:
        f:conditions:
        f:guestOSInfo:
          .:
          f:id:
          f:kernelRelease:
          f:kernelVersion:
          f:name:
          f:prettyName:
          f:version:
          f:versionId:
        f:interfaces:
        f:launcherContainerImageVersion:
        f:migrationMethod:
        f:nodeName:
        f:phase:
        f:phaseTransitionTimestamps:
        f:qosClass:
        f:virtualMachineRevisionName:
        f:volumeStatus:
    Manager:    Go-http-client
    Operation:  Update
    Time:       2022-01-14T13:13:18Z
  Owner References:
    API Version:           kubevirt.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  plo-jb
    UID:                   9b939423-d589-4dce-a8e7-8bc085227746
  Resource Version:        21738798
  UID:                     8b4788b0-42dd-449e-89d4-1f61416729a2
Spec:
  Domain:
    Cpu:
      Cores:    2
      Sockets:  1
      Threads:  1
    Devices:
      Disks:
        Boot Order:  1
        Disk:
          Bus:  virtio
        Name:   disk-0
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Inputs:
        Bus:   usb
        Name:  tablet
        Type:  tablet
      Interfaces:
        Bridge:
        Model:  virtio
        Name:   default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  76dcbf09-d23b-5c2d-8ff7-03e2e6ce2492
    Machine:
      Type:  q35
    Memory:
      Guest:  924Mi
    Resources:
      Limits:
        Cpu:     2
        Memory:  1Gi
      Requests:
        Cpu:          125m
        Memory:       682Mi
  Eviction Strategy:  LiveMigrate
  Hostname:           plo-jb
  Networks:
    Multus:
      Network Name:  default/net65
    Name:            default
  Volumes:
    Name:  disk-0
    Persistent Volume Claim:
      Claim Name:  plo-jb-disk-0-cutpe
    Cloud Init No Cloud:
      Network Data Secret Ref:
        Name:  plo-jb-df46i
      Secret Ref:
        Name:  plo-jb-df46i
    Name:      cloudinitdisk
Status:
  Active Pods:
    9534d977-3ad8-4c00-9e64-2c5eb26260b5:  mike
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2022-01-14T13:12:55Z
    Status:                True
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  LiveMigratable
    Last Probe Time:       2022-01-14T13:13:18Z
    Last Transition Time:  <nil>
    Status:                True
    Type:                  AgentConnected
  Guest OS Info:
    Id:              sles
    Kernel Release:  5.3.18-59.37-default
    Kernel Version:  #1 SMP Mon Nov 22 12:29:04 UTC 2021 (d10168e)
    Name:            SLES
    Pretty Name:     SUSE Linux Enterprise Server 15 SP3
    Version:         15.3
    Version Id:      15.3
  Interfaces:
    Interface Name:  eth0
    Ip Address:      10.65.0.188
    Ip Addresses:
      10.65.0.188
      fe80::54fb:40ff:fea5:65
    Mac:                             56:fb:40:a5:00:65
    Name:                            default
  Launcher Container Image Version:  registry.suse.com/suse/sles/15.3/virt-launcher:0.45.0-8.4.3
  Migration Method:                  BlockMigration
  Node Name:                         mike
  Phase:                             Running
  Phase Transition Timestamps:
    Phase:                        Pending
    Phase Transition Timestamp:   2022-01-14T13:12:26Z
    Phase:                        Scheduling
    Phase Transition Timestamp:   2022-01-14T13:12:26Z
    Phase:                        Scheduled
    Phase Transition Timestamp:   2022-01-14T13:12:55Z
    Phase:                        Running
    Phase Transition Timestamp:   2022-01-14T13:12:57Z
  Qos Class:                      Burstable
  Virtual Machine Revision Name:  revision-start-vm-9b939423-d589-4dce-a8e7-8bc085227746-1
  Volume Status:
    Name:    cloudinitdisk
    Target:  vdb
    Name:    disk-0
    Persistent Volume Claim Info:
      Access Modes:
        ReadWriteMany
      Capacity:
        Storage:    15Gi
      Volume Mode:  Block
    Target:         vda
Events:
  Type    Reason            Age                 From                         Message
  ----    ------            ----                ----                         -------
  Normal  SuccessfulCreate  6m32s               disruptionbudget-controller  Created PodDisruptionBudget kubevirt-disruption-budget-6kbzh
  Normal  SuccessfulCreate  6m32s               virtualmachine-controller    Created virtual machine pod virt-launcher-plo-jb-nhqj2
  Normal  Started           6m1s                virt-handler                 VirtualMachineInstance started.
  Normal  Created           30s (x9 over 6m1s)  virt-handler                 VirtualMachineInstance defined.
```

[virt-launcher.log](https://github.com/harvester/harvester/files/7870626/virt-launcher.log)
[virtualmachine.yaml.txt](https://github.com/harvester/harvester/files/7870628/virtualmachine.yaml.txt)

*Screenshots*

Rancher Virtualization UI:

<img width="1451" alt="Screenshot 2022-01-14 at 14 23 55" src="https://user-images.githubusercontent.com/3813921/149522389-cac37d10-fc95-4466-bd78-cef498b4f722.png">
<img width="1446" alt="Screenshot 2022-01-14 at 14 23 50" src="https://user-images.githubusercontent.com/3813921/149522394-9dda2aa4-715c-4aa7-83bf-808eb45ddba3.png">
<img width="1449" alt="Screenshot 2022-01-14 at 14 23 45" src="https://user-images.githubusercontent.com/3813921/149522396-8a5e7faf-d89d-4103-9e8e-380f4c9eeac3.png">
<img width="1441" alt="Screenshot 2022-01-14 at 14 23 32" src="https://user-images.githubusercontent.com/3813921/149522401-bdaa8e68-5f29-45bd-be98-fde61b310dab.png">
<img width="1447" alt="Screenshot 2022-01-14 at 14 15 25" src="https://user-images.githubusercontent.com/3813921/149522403-d777c776-897e-4818-a3d9-212c084c99e7.png">

Harvester native UI:

<img width="1448" alt="Screenshot 2022-01-14 at 14 27 58" src="https://user-images.githubusercontent.com/3813921/149522915-03667436-90dd-4512-87f5-8aec5cd06cf3.png">

**Comment by johnliu55tw** [comment] 2022-02-07 07:46
@janeczku Is the VM running fine, only that GUI incorrectly shown the status as "Starting"?

I could somewhat reproduce the issue: After I created the VM, it eventually enters Running status and the GUI shows "Running". However, if I **refreshed the page**, it falls back to "Starting":

https://user-images.githubusercontent.com/5047724/152745688-dec39828-13fc-49cc-b4b5-7534f76251c2.mp4

Could you help check whether this is the problem you're facing? Or the VM is actually in the "Starting" status?

**Note**: Harvester's own GUI also has this issue.

**Comment by janeczku** [comment] 2022-02-17 08:24
@johnliu55tw No, it's not that behaviour. I cannot reproduce this anymore though. So i think we can close this ticket until we identify steps to reproduce the behaviour.

**Comment by johnliu55tw** [comment] 2022-02-17 09:00
won't fix: Cannot reproduce. Also I've created another issue to track the [issue I found](https://github.com/harvester/harvester/issues/1822#issuecomment-1031163366): https://github.com/harvester/harvester/issues/1925.

**Comment by noahgildersleeve** [comment] 2022-03-02 21:04
Tested in Harvester `v2.6-1d2b7468851553f4b89f8af99d74305af9d1b594-head` with Rancher `v2.6-1d2b7468851553f4b89f8af99d74305af9d1b594-head`. 
## Verification Steps
1. Imported Harvester into Rancher
2. Created new opensuse VM from Harvester dashboard via Rancher Virtualization management
3. Checked for status update in VM list
![Screenshot from 2022-03-02 13-02-00](https://user-images.githubusercontent.com/83787952/156449316-77095ba5-136f-4ba4-a5a3-3ec6eaa8bd70.png)

**Closed as completed by noahgildersleeve** 2022-03-02 21:04 UTC
Labels: kind/bug, area/control-plane, priority/0

**Comment by Ganagaraj** [comment] 2025-04-06 16:19
Hi Everyone, this issue is happening for me. Could anyone help me to resolve this?

![Image](https://github.com/user-attachments/assets/3815fe17-af7b-447d-a1e8-954947351c6a)
