### ISSUE TITLE
[BUG] Network menu has some error messages

### ISSUE THREAD

**Issue by kingsd041** [harvester/harvester#628] opened 2021-03-31 09:19 UTC
**Describe the bug**

The network menu has some error messages
**To Reproduce**
1. Launch a 3-node harvester
2. When the status of all nodes becomes `Ready`, immediately set ClusterNetwork: vlan
![image](https://user-images.githubusercontent.com/19684717/113120866-9d55a800-9244-11eb-960d-e0d8362dce88.png)

3. Enter the `Networks` menu

At this time, the following error message will appear:
![image](https://user-images.githubusercontent.com/19684717/113119730-5915d800-9243-11eb-9a65-3d2b9da05c3b.png)

**Environment:**
 - Harvester ISO version:  v0.2.0-rc1
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment] 2021-03-31 09:58
duplicate of https://github.com/rancher/harvester/issues/611

**Closed as completed by guangbochen** 2021-03-31 09:58 UTC
Labels: kind/bug
