### ISSUE TITLE
[ENHANCEMENT] Harvester Single Node Cluster

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#3889] opened 2023-05-11 21:27 UTC
**Describe the solution you'd like**
We would like Harvester to be able to run on a single node with no HA and use no more than 50% of the resources to run the system.

**Comment by guangbochen** [comment] 2023-05-12 04:01
Harvester can run with the single node mode well, it will not have HA, fault-tolerant, and multi-replicas support with this mode, but all other features should work.
- single node cluster installation
- single node upgrade(no live-migration and zero-downtime support)
- support spin-up guest RKE2 clusters
- users can create a new SC and configure its replicas as one; for existing volumes like monitoring, users can modify them via the LH dashboard.
we can add single node doc description later, but it should not block regular QA validations, thanks.

similar issue: https://github.com/harvester/harvester/issues/2079#issuecomment-1146317659

**Comment by albinsun** [comment] 2023-05-29 07:45
Updated test result on "Single node cluster installation"

# Test Info
* Target: Single node cluster installation
* Harvester `v1.2.0-rc1`
  * profile: KVM, single node
  * **ui-source**: Auto

# Test Suite

## ISO Installation
* $\color{green}{\textsf{PASSED}}$

## PXE Boot Installation
* $\color{green}{\textsf{PASSED}}$

**Comment by albinsun** [comment] 2023-05-31 01:43
Updated test result on "harvester_e2e_tests/apis"

# Test Info
* Target: `harvester_e2e_tests/apis`
* Harvester `v1.2.0-rc1`
  * profile: KVM, single node
  * **ui-source**: Auto

# Test Suite

## test_authentication
* $\color{green}{\textsf{PASSED}}$ : **1**
* Tested on `harvester-runtests#281`
  <details>

    ![image](https://github.com/harvester/harvester/assets/2773781/c64c3102-b11b-434e-8560-08c614f1eac7)
  </details>


## test_hosts
* $\color{green}{\textsf{PASSED}}$ : **3**
* $\color{red}{\textsf{FAILED}}$ : **1**
  > **Note** : Expected for single node cluster
    1. `test_maintenance_mode`
      Harvester cannot place the only controlplane in maintenance mode, should filter this TC for the single node env.
      <img src="https://github.com/harvester/harvester/assets/2773781/118d5091-8337-4cac-a7a8-cd311debad6f" width="200">
* Tested on `harvester-runtests#276`
  <details>

    ![image](https://github.com/harvester/harvester/assets/2773781/619318c7-ad51-4fd8-a540-940a44ea072c)
  </details>


## test_images
* $\color{green}{\textsf{PASSED}}$ : **8**
* $\color{red}{\textsf{FAILED}}$: 2
  > **Note** : Discussing in [harvester#4027](https://github.com/harvester/harvester/issues/4027), a workaround in TC is [PR#840](https://github.com/harvester/tests/pull/840)
    1. `test_create_with_reuse_display_name`
    2. `test_create_with_invalid_url`
* Tested on `harvester-runtests#277`
  <details>

    ![image](https://github.com/harvester/harvester/assets/2773781/9bbd97e7-4c26-491d-9d95-c8ed9074bb80)
  </details>


## test_keypairs
* $\color{green}{\textsf{PASSED}}$ : **8**
* Tested on `harvester-runtests#279`
  <details>

    ![image](https://github.com/harvester/harvester/assets/2773781/5f7bca8d-5eca-486d-add5-eaf94fe5cf5d)
  </details>


## test_networks
* $\color{green}{\textsf{PASSED}}$ : **7**
* $\color{orange}{\textsf{SKIPPED}}$ : **3**
  > **Note** : Expected, they are only for version before `v1.0.3`.
    1. `TestNetworksNegative::test_create_with_invalid_id_103[0]`
    2. `TestNetworksNegative::test_create_with_invalid_id_103[4095]`
    4. `TestNetworks::test_create_103`
* Tested on `harvester-runtests#280`
  <details>
   
    ![image](https://github.com/harvester/harvester/assets/2773781/4cc38599-4eae-4a89-b590-d2ea2c2d3bcc)
  </details>


## test_settings
* $\color{green}{\textsf{PASSED}}$ : **8**
* Tested on `harvester-runtests#282`
  <details>
     
    ![image](https://github.com/harvester/harvester/assets/2773781/f2992a96-7282-44f7-aa6f-ff77713a4b6c)
  </details>


## test_support_bundle
* $\color{green}{\textsf{PASSED}}$ : **7**
* Tested on `harvester-runtests#283`
  <details>
     
    ![image](https://github.com/harvester/harvester/assets/2773781/454e14c4-43eb-4416-ac1c-36ab1c37c0ea)
  </details>


## test_users
* $\color{orange}{\textsf{SKIPPED}}$ : **3**
  > **Note** : User management feature is being deferred.
* Tested on `harvester-runtests#284`
  <details>
     
    ![image](https://github.com/harvester/harvester/assets/2773781/bfc0630f-5e65-43b2-bb79-4b9c5b5059b0)
  </details>


## test_vm_templates 
* $\color{green}{\textsf{PASSED}}$ : **9**
* Tested on `harvester-runtests#285`
  <details>
     
    ![image](https://github.com/harvester/harvester/assets/2773781/b40027fd-fa48-4ef4-aa34-b943cd69aa78)
  </details>


## test_volumes
* $\color{green}{\textsf{PASSED}}$ : **8**
* Tested on `harvester-runtests#286`
  <details>
    
    ![image](https://github.com/harvester/harvester/assets/2773781/26d157a0-9046-4506-9e56-57e9d7303bae)
  </details>

**Comment by albinsun** [comment] 2023-06-01 08:18
Update test result on `harvester_e2e_tests/integration`

# Test Info
* Target: `harvester_e2e_tests/integration`
* Harvester `v1.2.0-rc1`
  * profile: KVM, single node
  * **ui-source**: Auto

# Test Suite

## test_0_storage_network
* $\color{green}{\textsf{PASSED}}$ : **1**
* Tested on harvester-runtests#290
  <details>

    ![image](https://github.com/harvester/harvester/assets/2773781/5cd882df-9790-466b-91aa-32f752a74f6e)
  </details>


## test_backup_restore
* $\color{green}{\textsf{PASSED}}$ : **14**
* Tested on harvester-runtests#321
  <details>

    ![image](https://github.com/harvester/tests/assets/2773781/7d8d36c4-62a8-4316-a9ec-a0e546ac9b0e)
  </details>


## test_hosts
* $\color{green}{\textsf{PASSED}}$ : **1**
* $\color{orange}{\textsf{SKIPPED}}$ : **4**
  > **Note** : dependency on `host_poweroff`
  > 1. `test_host_poweron_state`
  > 1. `test_poweroff_node_trigger_vm_migrate`
  > 1. `test_delete_vm_after_host_shutdown`
  > 1. `test_vm_migrated_after_host_reboot`
* $\color{red}{\textsf{FAILED}}$ : **2**
  > **Note** : Expected due to single node can not poweroff and go maintenance_mode
  > 1. `test_maintenance_mode_trigger_vm_migrate::setup`
  > 1. `test_host_poweroff_state`
* Tested on harvester-runtests#326
  <details>

    ![Image](https://github.com/harvester/harvester/assets/2773781/9af8fd05-ad18-407f-a52e-c4674cc2934d)
  </details>


## test_images
* $\color{green}{\textsf{PASSED}}$ : **5**
* $\color{red}{\textsf{FAILED}}$ : **3**
  > **Warning** : Also fail in daily e2e test, root cause should be the same as [issues#4027](https://github.com/harvester/harvester/issues/4027)
  > 1. `test_delete_image_recreate[image_opensuse]`     
  >    ![image](https://github.com/harvester/harvester/assets/2773781/adaf64c6-0290-4c21-a892-b68dbd857e74)
  > 2. `test_delete_image_recreate[image_k3s]`
  >    ![image](https://github.com/harvester/harvester/assets/2773781/8c980a89-215a-484a-9ecd-d84c2f6d42f7)
  > 3. `test_create_invalid_file`
  >   ![image](https://github.com/harvester/harvester/assets/2773781/d683b954-d6c7-417e-80c8-a2286c5a5aec)
* Tested on harvester-runtests#304
  <details>

    ![image](https://github.com/harvester/harvester/assets/2773781/541caf1d-f131-4e34-bff0-3ea2bd52100d)
  </details>


## test_rancher_integration
* $\color{green}{\textsf{PASSED}}$ : **7**
* Tested on harvester-runtests#308
  <details>
 
    ![image](https://github.com/harvester/harvester/assets/2773781/501d0252-d3ad-4939-93f8-e0c027c9cf2d)
  </details>


## test_terraform
* $\color{green}{\textsf{PASSED}}$ : **1**
* $\color{orange}{\textsf{SKIPPED}}$ : **4**
  1. `test_create_keypairs_using_terraform`: unconditional skip
  2. `test_create_images_using_terraform`: unconditional skip
  3. `test_create_network_using_terraform`: get_vlan API removed
  4. `test_create_vol_with_image_terraform`: Timing Issue
* Tested on harvester-runtests#309
  <details>
 
    ![image](https://github.com/harvester/harvester/assets/2773781/342081dd-2fbc-442b-ac50-fb3bdc07ffac)
  </details>


## test_upgrade
Skip delete_host and upgrade


## test_vm_functions
* $\color{green}{\textsf{PASSED}}$ : **21**
* $\color{red}{\textsf{ERROR}}$ : **2**
  > **Note** : Expected since there is no other host to migrate.
  > <img src="https://github.com/harvester/harvester/assets/2773781/e0143269-4318-465e-b1de-ed6edd0bbbaa" width="200">
  > 1. `TestVMOperations::test_migrate`
  > 2. `TestVMOperations::test_abort_migrate`
* Tested on harvester-runtests#310
  <details>
    
    ![image](https://github.com/harvester/harvester/assets/2773781/2e90c315-f6e3-4a9b-86c2-1b50ddf89000)
  </details>


## test_vm
* $\color{red}{\textsf{ERROR}}$ : **3**
  > **Note** : Expected since there is no other host to migrate.
  > 1. `test_multiple_migrations::setup`
  > 2. `test_migrate_vm_with_user_data::setup`
  > 3. `test_migrate_vm_with_multiple_volumes::setup`
* Tested on harvester-runtests#311
  <details>
    
    ![image](https://github.com/harvester/harvester/assets/2773781/7fcd5e5d-6aab-4194-aada-b0a3e2c4e777)
  </details>


## test_volumes
* $\color{green}{\textsf{PASSED}}$ : **3**
* Tested on harvester-runtests#312
  <details>
    
    ![image](https://github.com/harvester/harvester/assets/2773781/f2bfe54d-0037-4d34-9cb2-c325df88f118)
  </details>

**Comment by albinsun** [comment] 2023-06-14 09:16
Update test result on `harvester_e2e_tests/scenarios`

# Test Info
* Target: `harvester_e2e_tests/scenarios`
* Harvester `v1.2.0-rc1`
  * profile: KVM, single node
  * **ui-source**: Auto

# Test Suite

## test_create_vm
* $\color{green}{\textsf{PASSED}}$ : **15**
* $\color{red}{\textsf{FAILED}}$ : **3**
  > **Warning** : Need to check (Also fail on daily e2e)
  > 1. `test_create_vm_on_available_cpu_node`
  > 2. `test_update_vm_on_available_cpu_node`

  > **Note** : Expected due to single node
  > 1. `test_host_maintenance_mode`
* Tested on harvester-runtests#330
  <details>

    ![Image](https://github.com/harvester/harvester/assets/2773781/ad4f0a05-cbab-466c-80e2-47b5d8b15452)
  </details>


## test_rancher_integration
* $\color{orange}{\textsf{SKIPPED}}$ : **4**
  > **Note** : Skipped due to https://github.com/harvester/tests/issues/384
  > 1. test_import_harvester_into_rancher
  > 1. test_add_prj_owner_user
  > 1. test_create_rke1_cluster
  > 1. test_create_rke2_cluster

**Comment by albinsun** [comment] 2023-06-15 01:07
Arrange current failed TCs in `apis` and `integration` package.

| Test Package | Test Suite        | Fail TC                                      | Comment                      |
|:------------:|-------------------|----------------------------------------------|------------------------------|
|     apis     | test_hosts        | test_maintenance_mode                        | Expected for single node.    |
|              | test_images       | test_create_with_reuse_display_name          | harvester#4027               |
|              |                   | ~test_create_with_invalid_url~                 | Passed with [tests#861](https://github.com/harvester/tests/issues/861) |
|  integration | test_hosts        | test_maintenance_mode_trigger_vm_migrate     | Expected for single node.    |
|              |                   | test_host_poweroff_state                     | Expected for single node.    |
|              | test_images       | test_delete_image_recreate[image_opensuse]   | harvester#4027               |
|              |                   | test_delete_image_recreate[image_k3s]        | harvester#4027               |
|              |                   | ~test_create_invalid_file~                     | Passed with [tests#861](https://github.com/harvester/tests/issues/861) |
|              | test_vm_functions | TestVMOperations::test_migrate               | Expected for single node.    |
|              |                   | TestVMOperations::test_abort_migrate         | Expected for single node.    |
|              | test_vm           | test_multiple_migrations::setup              | Expected for single node.    |
|              |                   | test_migrate_vm_with_user_data::setup        | Expected for single node.    |
|              |                   | test_migrate_vm_with_multiple_volumes::setup | Expected for single node.    |
|              |                   |                                              |                              |

**Comment by albinsun** [comment] 2023-07-03 02:28
Tested in `v1.2.0-rc2`, currently, except 3 fails caused by [harvester#4027](https://github.com/harvester/harvester/issues/4027), the remaining are expected for single node. Close it as done.

For more clear skip/error message, current implementation is to check node number in the beginning of TC, e.g. https://github.com/harvester/tests/blob/eef48eb86c8166a0926f09d64d4ec8e49ad25ec2/harvester_e2e_tests/integration/test_hosts.py#L133

Please comment and discuss any other implementations.

**Closed as completed by albinsun** 2023-07-03 02:28 UTC
Labels: require/doc, kind/enhancement, priority/1
