### ISSUE TITLE
[ENHANCEMENT]users can set Banners and Branding in Harvester UI 

### ISSUE THREAD

**Issue by 290760647** [harvester/harvester#3442] opened 2023-02-10 08:51 UTC
Like Rancher , We should allow users can setting Banners and Branding in Harvester UI .
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/42170674/218046438-bea89880-4815-44ec-a1b3-2ab54fb593bc.png">

**Comment by Martin-Weiss** [comment] 2023-02-10 08:55
Maybe a duplicate of https://github.com/harvester/harvester/issues/3396 ?

**Comment by guangbochen** [comment] 2023-02-14 06:26
close as duplicate with https://github.com/harvester/harvester/issues/3396

**Closed as completed by guangbochen** 2023-02-14 06:26 UTC
Labels: kind/enhancement
