### ISSUE TITLE
[BUG] The project-owner user cannot view the assigned namespace

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2289] opened 2022-05-19 06:52 UTC
**Describe the bug**

The project-owner user cannot see the vm resources assigned to it

**To Reproduce**
1. Importing a harvester cluster in a rancher cluster
2. access the imported harvester cluster from the `Virtualization Management` page
3. Create a new Project  (test-project-owner),  
4. Create a new namespace in the project   (test-project-owner-namespace)
5. Create vm, select namespace as `test-project-owner-namespace`
6. Create a new user  (Standard User)
![image](https://user-images.githubusercontent.com/24985926/169192769-4fec2c93-6b68-4b54-8c9f-627e79831ed2.png)
7. Assign Owner Project Permissions to the user (`test-project-owner-user`) in the imported harvester cluster , click save
![image](https://user-images.githubusercontent.com/24985926/169194240-503202be-2703-4dfc-8eb1-a4c40cff025c.png)
8. logout and login with `test-project-owner-user`
9. enter harvester cluster,  go to virtualMachine page，

**Expected behavior**

You should be able to see the created vm in the vm list page，  

Notice: Sometimes I don't see any vm in the list, and when I check the namespace, I find that I don't have access rights to the corresponding namespace (test-project-owner-namespace).   (`Unstable reproduce`)

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment] 2022-07-05 07:23
follow the steps https://github.com/harvester/harvester/issues/2289#issue-1241304365
unable to reproduce this issue in `rancher 2.6.6/2.6.5` + `harvester master-949bbb0c-head`
Users can view project, namespace, and VM
![image](https://user-images.githubusercontent.com/15064560/177272485-0cf6f521-14a2-4fc3-b3ee-c02f6c0c15cb.png)
![image](https://user-images.githubusercontent.com/15064560/177272515-a0c5d5e9-99ba-4b3d-a475-73f1c2127e2f.png)

**Comment by noahgildersleeve** [comment] 2022-07-06 19:24
Tested in master-a926a44e-head. I had to change the ui-index for Rancher v2.6.6 to https://releases.rancher.com/harvester-ui/dashboard/latest/index.html in order to get the projects tab to show up on the Harvester dashboard through Ranhcer virtualization.

## Verification steps
1. Install Harvester via ipxe-examples
2. Install Rancher v2.6.6 via Docker
3. import Harvester into Rancher
4. Create new project via admin user in imported Harvester
5. Create new namespace in project
6. Create new standeard user
7. Assign new user to project as project owner
8. Log in as new standard user
9. Navigate to Harvester dashboard via virtualization management in Rancher
10. Create a new image
11. Check in projects which namespaces and projects that user has access to.

It looks like the standard user shows they have access to `harvester-public`. It looks like this is because it isn't in a project. However the user can't create any resources in that namespace. This is an issue though because in this case the harvester-public namespace is alphabetically higher in the list so it's what all new requests defaIt looks like the standard user shows they have access to `harvester-public`. It looks like this is because it isn't in a project. However the user can't create any resources in that namespace. This is an issue though because in this case the harvester-public namespace is alphabetically higher in the list so it's what all new requests default to unless you change them. I'm closing this issue since that issue is out of scope
ult to unless you change them. I'm closing this issue since that issue is out of scope and created a new issue [here at 2460](https://github.com/harvester/harvester/issues/2460)

![Screenshot_20220706_120420](https://user-images.githubusercontent.com/83787952/177624536-6038ddcb-557f-49ca-9798-b4f87308a802.png)

**Closed as completed by noahgildersleeve** 2022-07-06 19:24 UTC
Labels: kind/bug, priority/0, area/multi-tenancy
