### ISSUE TITLE
[BUG] harvester ipxe fails on equinix arm nodes

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#6007] opened 2024-06-11 06:29 UTC
**Describe the bug**

Harvester installer fails to bootstrap on arm instances in equinix. 

**To Reproduce**
1. Lauch an arm instance on equinix using a custom ipxe script
2. Use equinix SOS console to access instance
3. The installer is waiting on login prompt and no installer is launched

**Expected behavior**

Installer should be launched

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
The issue is being caused due to the fact that equinix metal only exposes /dev/ttyAMA0 console to end users. 
As part of the arm enablement for self hosted instances, additional logic was added to skip /dev/AMA0 for arm instances since the installer is unable to resize for the serial console on ARM instances. This additional logic allow harvester to be easily installed on on-prem ARM nodes (Ampere Ultra based machines) as installer could use /dev/tty1 available via KVM interface.

Additional changes are needed to default to /dev/ttyAMA0 if no other console is found.

Changes are needed at the following two locations:
https://github.com/harvester/harvester-installer/blob/master/pkg/console/tty.go#L12
https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/files/usr/bin/setup-installer.sh#L51-L77

**Comment by TachunLin** [comment] 2024-10-24 09:02
@ibrokethecloud ,
May I know more about the test plan steps.
And do we need to have an arm node machine instance on equinix platform for verifying this issue. Thanks.

**Comment by TachunLin** [comment] 2024-10-29 14:56
Verified **failed** on `v1.4.0-rc4`. Move to implement

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Can launch Harvester installer on Equinix ARM based machine using ipxe-example file $~~$</summary>

 1. Use the following ipxe-example file set to the arm based release 
    ```
    #!ipxe
    dhcp
    iflinkwait -t 5000 && echo Detected link on ${ifname}
    set version v1.4.0-rc4
    set base https://releases.rancher.com/harvester/${version}
    set harvesterreleasebase https://releases.rancher.com/harvester/${version}
    kernel ${base}/harvester-${version}-vmlinuz-arm64 initrd=harvester-${version}-initrd-arm64 ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl root=live:${harvesterreleasebase}/harvester-${version}-rootfs-arm64.squashfs harvester.install.management_interface.interfaces="hwAddr:${net0/mac}" harvester.install.management_interface.method=dhcp harvester.install.management_interface.bond_options.mode=balance-tlb harvester.install.management_interface.bond_options.miimon=100 console=ttyS1,115200 harvester.install.automatic=true boot_cmd="echo include_ping_test=yes >> /etc/conf.d/net-online" harvester.install.config_url=https://metadata.platformequinix.com/userdata
    initrd ${base}/harvester-${version}-initrd-arm64
    boot
    ```
 2. We can launch the installer on Harvester v1.4.0-rc4 


https://github.com/user-attachments/assets/7b8b870c-60a1-495e-ae4b-dcc6951c23c7



 </details>

<details><summary>$\color{red}{\textsf{Failed}}$ Harvester ipxe-example installation on ARM based machine stuck and can't complete $~~$</summary>

  1. The installation stuck in `mlx5e_vport_context_update_vlans:180:(pid 3592): netdev vlans list size (4094) > (512) max vport list size, some vlans will be dropped`

  ![image](https://github.com/user-attachments/assets/16686bb6-daac-4c6f-82ed-fa956a857a8f)

 </details>



### Test Information
* Test Environment: Single node Equinix baremetal machine
* Harvester version: v1.4.0-rc4

### Verify Steps
<details><summary>Use ipxe file to provision on Equinix ARM based machine </summary>

  1. Prepare a v1.4.0-rc4 ipxe-example script point to the arm release file
  ```
  #!ipxe
  dhcp
  iflinkwait -t 5000 && echo Detected link on ${ifname}
  set version v1.4.0-rc4
  set base https://releases.rancher.com/harvester/${version}
  set harvesterreleasebase https://releases.rancher.com/harvester/${version}
  kernel ${base}/harvester-${version}-vmlinuz-arm64 initrd=harvester-${version}-initrd-arm64 ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl root=live:${harvesterreleasebase}/harvester-${version}-rootfs-arm64.squashfs harvester.install.management_interface.interfaces="hwAddr:${net0/mac}" harvester.install.management_interface.method=dhcp harvester.install.management_interface.bond_options.mode=balance-tlb harvester.install.management_interface.bond_options.miimon=100 console=ttyS1,115200 harvester.install.automatic=true boot_cmd="echo include_ping_test=yes >> /etc/conf.d/net-online" harvester.install.config_url=https://metadata.platformequinix.com/userdata
  initrd ${base}/harvester-${version}-initrd-arm64
  boot
  ``` 
  2. Place the ipxe-example file on a public web server, here I use ngrok service with python http server
  3. Create a new Equinix machine with type `c3.large.arm64`
  4. Select custom pxe and provide the ipxe-example url 
  
  ![image](https://github.com/user-attachments/assets/c5854bd6-697b-45a8-8134-ffc67dbac992)

  5. Launch the server
  6. After the server deployed, copy the out of bond access command 
  7. Execute the command in terminal and monitor the installation progress

</details>

**Comment by TachunLin** [comment] 2024-10-30 09:47
Retest **failed** on v1.4.0-rc4 using ipex file with Harvester configuration config in user data

* Prepare the ipxe file for v1.4.0-rc4 

  ```
  #!ipxe
  dhcp
  iflinkwait -t 5000 && echo Detected link on ${ifname}
  set version v1.4.0-rc4
  set base https://releases.rancher.com/harvester/${version}
  set harvesterreleasebase https://releases.rancher.com/harvester/${version}
  kernel ${base}/harvester-${version}-vmlinuz-amd64 initrd=harvester-${version}-initrd-amd64 ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl root=live:${harvesterreleasebase}/harvester-${version}-rootfs-amd64.squashfs harvester.install.management_interface.interfaces="hwAddr:${net0/mac}" harvester.install.management_interface.method=dhcp harvester.install.management_interface.bond_options.mode=balance-tlb harvester.install.management_interface.bond_options.miimon=100 console=ttyS1,115200 harvester.install.automatic=true boot_cmd="echo include_ping_test=yes >> /etc/conf.d/net-online" harvester.install.config_url=https://metadata.platformequinix.com/userdata
  initrd ${base}/harvester-${version}-initrd-amd64
  boot
  ```

* With the Harvester configuration user data 
  ```
  #cloud-config
  scheme_version: 1
  token: randomtoken
  os:
    password: randompassword
  install:
    mode: create
    device: /dev/sda
    iso_url: https://releases.rancher.com/harvester/v1.4.0-rc4/harvester-v1.4.0-rc4-arm64.iso
    tty: ttyS1,115200n8
    vip: 145.40.77.220  # not matter, will be replaced
    vip_mode: static
  ```

* Provision on the Equinix `c3.large.arm64` type machine 

* The installation but would stuck with continuously prompted message
  ```
  [  137.182506][ T3666] mlx5_core 0001:01:00.0: mlx5e_vport_context_update_vlans:180:(pid 3666): netdev vlans list size (4092) > (512) max vport list size, some vlans will be dropped
  [  137.200505][ T3666] mlx5_core 0001:01:00.0: mlx5e_vport_context_update_vlans:180:(pid 3666): netdev vlans list size (4093) > (512) max vport list size, some vlans will be dropped
  [  137.220375][ T3666] mlx5_core 0001:01:00.0: mlx5e_vport_context_update_vlans:180:(pid 3666): netdev vlans list size (4094) > (512) max vport list size, some vlans will be dropped
  ```

https://github.com/user-attachments/assets/f5b470d0-8694-47e8-8876-eb6c699f41ad

**Comment by ibrokethecloud** [comment] 2024-11-03 07:34
that is not really an error related to the installation. The error is just console related messages. Due to the nature of the  serial console it can be hard to observe the ready state. The VIP should still be reachable and cluster in working condition.

**Comment by bk201** [comment] 2024-11-04 02:34
@TachunLin the error you saw is not related to the fix, I'm moving this out of 1.4.0 to do further investigation.

**Comment by bk201** [comment] 2024-11-04 02:37
@TachunLin In fact @ibrokethecloud just pointed out the issue is fixed because the installer runs correctly (It was a TTY issue). Can you file a new one regarding the Mellanox nic issue?

**Comment by TachunLin** [comment] 2024-11-04 02:58
I have created issue #6932 to track the Mellanox nic issue on console.

**Comment by bk201** [comment] 2024-11-04 03:16
Close this one since the installer can boot and show message on the console.

**Closed as completed by bk201** 2024-11-04 03:16 UTC
Labels: kind/bug, area/installer, priority/0, require/reproduce, require/severity, area/arm
