### ISSUE TITLE
[BUG] fleet-agent has a very high CPU usage

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#1893] opened 2022-02-04 10:14 UTC
**Describe the bug**

`fleet-agent uses lots of CPU resource`  (updated, for tracking the CPU usage issue)
![image](https://user-images.githubusercontent.com/31133476/152509635-6658ffe5-3b06-48bc-931a-d35e6d582312.png)

`fleet-agent has log in every second, the "getting history for release" `
kubectl logs fleet-agent-78f694664b-69plq -n cattle-fleet-local-system
![image](https://user-images.githubusercontent.com/31133476/152509963-e07496e1-a259-45b5-8f31-0b8e0da985c5.png)

**To Reproduce**
1. Even for a single node harvester cluster, v1.0.0 master-head, fleet-agent is busy working

**Expected behavior**

The fleet-agent should not be so busy.

**Support bundle**

**Environment:**
 - Harvester ISO version:  V1.0.0 master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment] 2022-02-04 11:27
Further test:
1. kubectl scale --replicas=0 deployment fleet-agent
2. kubectl edit deploy fleet-agent, change CHECKIN_INTERVAL to 2s
3. kubectl scale --replicas=1 deployment fleet-agent
4. kubectl get deploy fleet-agent
5. kubectl get pods fleet-agent-69c9645d96-hj9rx
After step 3, at step 4, quickly, the CHECKIN_INTERVAL is reverted to 0s.
Step 5, the final fleet-agent POD is still using CHECKIN_INTERVAL 0s


```
harv2:~ # kubectl scale --replicas=0 deployment fleet-agent -n cattle-fleet-local-system
deployment.apps/fleet-agent scaled

harv2:~ # kubectl get deploy fleet-agent -n cattle-fleet-local-system -o JSON | grep INTER -2
                            },
                            {
                                "name": "CHECKIN_INTERVAL",
                                "value": "0s"
                            },
harv2:~ # kubectl edit deploy fleet-agent -n cattle-fleet-local-system
deployment.apps/fleet-agent edited

harv2:~ # kubectl get deploy fleet-agent -n cattle-fleet-local-system -o JSON | grep INTER -2
                            },
                            {
                                "name": "CHECKIN_INTERVAL",
                                "value": "2s"
                            },
harv2:~ #
harv2:~ # kubectl scale --replicas=1 deployment fleet-agent -n cattle-fleet-local-system
deployment.apps/fleet-agent scaled>

harv2:~ # kubectl get deploy fleet-agent -n cattle-fleet-local-system -o JSON | grep INTER -2
                            },
                            {
                                "name": "CHECKIN_INTERVAL",
                                "value": "2s"
                            },
harv2:~ # kubectl get deploy fleet-agent -n cattle-fleet-local-system -o JSON | grep INTER -2
                            },
                            {
                                "name": "CHECKIN_INTERVAL",
                                "value": "0s"
                            },
harv2:~ #

harv2:~ # kubectl get pods fleet-agent-69c9645d96-hj9rx -n cattle-fleet-local-system -o JSON | grep INTER -2
                    },
                    {
                        "name": "CHECKIN_INTERVAL",
                        "value": "0s"
                    },
harv2:~ #
```

**Comment by w13915984028** [comment] 2022-02-04 11:56
even when tried to set CHECKIN_INTERVAL  as `4s` to fleet-agent pod, but from the log, it seems fleet-agent is still busy working.

![image](https://user-images.githubusercontent.com/31133476/152525075-8ddbcfc4-3242-42ac-a93f-98d3f71447c6.png)

**Comment by w13915984028** [comment] 2022-02-07 15:57
Additional update:
The running environment when issue happened:

`One node Harvester, V1.0.0 master-head, runs 6 days.   There is a list of changes, which is caused by changing the resource limit of deployments.  The Helm Chart releases are stored in Secrets.`

![image](https://user-images.githubusercontent.com/31133476/152822238-3126787b-9caa-4492-b3a0-a3f5ab5c82c0.png)


`Today I rebooted the Harvester node, there are fewer Helm Chart releases, to now, fleet-agent looks not consuming too much CPU resources.`

![image](https://user-images.githubusercontent.com/31133476/152822567-d7f38db2-0462-4c70-96be-83e83c2430bd.png)
![image](https://user-images.githubusercontent.com/31133476/152822619-6af762b3-b803-432e-8d66-0dfc958c0594.png)

**Comment by aiyengar2** [comment] 2022-02-08 21:19
@w13915984028 the check-in interval has nothing do with the high CPU usage you are experiencing + the "getting history for release" logs.

The check-in interval described how often Fleet-Agent should report back its status (e.g. the last time the agent checked in with Fleet in the local / management cluster, the agent namespace, and the number of ready / non-ready nodes int he cluster).

On the other hand, the large number of "getting history for release" logs has to do with the fact that Fleet is trying to reconcile the state of existing resources in your cluster against what it expects, based on what was committed into the Git repository that is deploying this Bundle. This also correlates with the high CPU usage you are seeing, since **it appears that Fleet is continuously attempting to reconcile as it is continuously noticing changes to applied resources**, which makes me think **another controller is attempting to modify / manage resources that have been deployed by Fleet**.

**Comment by w13915984028** [comment] 2022-04-12 20:41
It still seems to be in Harvester v1.0.1.

**Two exceptions:
1. A DEAD? POD is shown as "Running"
2. fleet-agent still uses high percentage of CPU, the log seem to be related to exception 1, it complains:**

`time="2022-04-12T20:29:11Z" level=error msg="bundle mcc-rancher-monitoring: daemonset.apps cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter [progressing] Available: 2/3"`


![image](https://user-images.githubusercontent.com/31133476/163047921-ec491e27-847e-4af1-95ef-6f7b92fa7544.png)

steps:
1. Setup a 3-node Harvester cluster
2. Power off the cluster
3. Power on only 2-node

abnormal of POD status,
POD `rancher-monitoring-prometheus-node-exporter-cflm4` is DEAD, but shown as "Running"
![image](https://user-images.githubusercontent.com/31133476/163048730-84232005-a52e-4468-b384-77017cfac74f.png)

when fetching log from it, failed
![image](https://user-images.githubusercontent.com/31133476/163048814-f8bb0533-4998-4518-9444-9efcb4629b5f.png)

log of fleet-agent:
![image](https://user-images.githubusercontent.com/31133476/163049096-fd1f7bd5-0b69-41ae-a7ed-98c6aa57974e.png)

**Comment by w13915984028** [comment] 2022-05-09 10:18
Need to re-validate after fleet-agent solves https://github.com/rancher/fleet/issues/760.

**Comment by squadramunter** [comment] 2022-06-13 08:50
Same here. Brand new install and in the beginning all fine but when spinning up a new VM the CPU cycles just count up endless.  Then got the error message: 1.0/1 nodes available: 1 Insufficient cpu.

Edit: When refreshing the Dashboard page the CPU cycles seems to be lower and then begins counting up.

It is reserved at 120% when loading in the Dashboard and then counting up endless.

![cpu issues harvester](https://user-images.githubusercontent.com/26835124/173316285-111c72e0-40e1-4254-9937-931ac1f439cc.png)

**Comment by w13915984028** [comment] 2022-06-17 22:48
The root cause analysis:
https://github.com/w13915984028/harvester-develop-summary/blob/main/fleet-agent-high-cpu-usage.md

**Comment by guangbochen** [comment] 2022-12-08 07:52
Closed and merged with https://github.com/harvester/harvester/issues/3150, since they are the same root cause, so will be verified together.

**Closed as completed by guangbochen** 2022-12-08 07:52 UTC
Labels: kind/bug, area/control-plane, priority/1, require/investigate, area/embedded-rancher
