### ISSUE TITLE
[BUG] After click "Edit config", "Save“, vm will lose management network IP

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1760] opened 2021-12-31 13:26 UTC
**Describe the bug**

**To Reproduce**
1. create a vm use management network.
![image](https://user-images.githubusercontent.com/15064560/147825352-cf545ec4-29fc-466f-8a5e-28865107bfe0.png)

2. waiting vm become ”Running“.
3. check the default interface macaddress by yaml.
![image](https://user-images.githubusercontent.com/15064560/147825427-11800d15-d08a-4d98-aeb7-65a632ee36bc.png)
4.  Click "Edit Config" .
![image](https://user-images.githubusercontent.com/15064560/147825457-356a8ac2-7c85-4c90-82a5-ea3984812481.png)
5. Click "Save".
![image](https://user-images.githubusercontent.com/15064560/147825471-e184495c-f86d-440d-a2e3-61b477ba8d21.png)
It seems UI will put the vm resource, but the put payload doesn't contains mac address.
![image](https://user-images.githubusercontent.com/15064560/147825594-a416d0a5-fa5c-4606-90f0-4cadbea49b41.png)
 
6. waiting vm become ”Running“ again
7. check the default interface macaddress by yaml again
![image](https://user-images.githubusercontent.com/15064560/147825716-b0f49135-1388-4914-a488-f40f346d6cf9.png)
you will see that the mac address of default interface changed, and this will cause the vm lose it's ip and route

**Expected behavior**

the mac address of vm not be changed

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment] 2022-01-24 06:50
@DaiYuzeng 
Verified **not fixed** on master-1be9cb5e-head (1/23).Move issue to implement stage.

### Result
After editing config of virtual machine with management network, the mac address remain unchanged, 
However the original assigned network IP changed to another one, this can be treated as lost IP and route. 
Please help to check whether it's the design or issue. 

mac address before and after editing:   `52:54:00:57:79:1d` <-> `52:54:00:57:79:1d`
IP before and after editing:  `10.52.1.50` <-> `10.52.1.51`

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-1be9cb5e-head

### Verify Steps
1. Enable virtual network with management mgmt
2. Create virtual network `vlan1` with id `1`
3. Create a virtual machine with default management network
4. Wait for VM running and get IP 
5. Edit yaml of VM, check it's mac address
6. Edit config of VM, do nothing
7. Click save
8. Wait for VM restart to running status 
9. Edit yaml of VM, check whether mac address changes
10. Check the IP address of VM

### Additional Context
* `Before` edit vm config
 - default Mac address: 52:54:00:57:79:1d
 - default IP: 10.52.1.50

  ![image](https://user-images.githubusercontent.com/29251855/150732448-925d0213-a7c3-4ae6-9cf9-0c86c9256d93.png)
  ![image](https://user-images.githubusercontent.com/29251855/150732222-50a9fa16-7871-4be6-8642-c1ba3b850357.png)

* `After` edit vm config
 - default Mac address: 52:54:00:57:79:1d
 - default IP: 10.52.1.51
  ![image](https://user-images.githubusercontent.com/29251855/150733246-1ec19aa2-a218-4a29-830b-ac64b645cb0e.png)
  ![image](https://user-images.githubusercontent.com/29251855/150733375-389fb1c7-b703-47e7-80f3-25b575be07dd.png)
  ![image](https://user-images.githubusercontent.com/29251855/150733564-7ebe4982-af6c-4c03-ad70-e7129378be37.png)

**Comment by WuJun2016** [comment] 2022-02-09 07:51
Hi， @futuretea  Can you help locate whether this is a frontend or backend problem? thanks

**Comment by futuretea** [comment] 2022-02-09 15:31
> ### Result
> After editing config of virtual machine with management network, the mac address remain unchanged, However the original assigned network IP changed to another one, this can be treated as lost IP and route. Please help to check whether it's the design or issue.

@TachunLin @WuJun2016  The IP address change is expected.

**Comment by TachunLin** [comment] 2022-02-10 03:13
Since after editing config of virtual machine with management network, the mac address remain unchanged. 
And the VM ip address change is the expected behavior. Close this issue.

**Closed as completed by TachunLin** 2022-02-10 03:13 UTC
Labels: kind/bug, area/ui, priority/0
