### ISSUE TITLE
[BUG] Install fails

### ISSUE THREAD

**Issue by AndreiLazarescu** [harvester/harvester#3501] opened 2023-02-20 03:35 UTC
**Describe the bug**

**To Reproduce**
1. Boot from USB
2. Proceed with the installation
3. Fill out all the forms
4. Wait until images are copied
5. Containerd fails "Connection refused"

**Expected behavior**
1. Boot from USB
2. Proceed with the installation
3. Fill out all the forms
4. Wait until images are copied
5. Containerd install

**Environment**
 - Harvester ISO version: 1.1.0 and 1.1.1
 - Baremetal with Dell PowerEdge T630
 
**Additional context**
The network is set to DHCP
Reboot on the installed disk/partition will show Harvester with the unchanged status "Setting up node "
I am located in East Europe (Romania)

Thank you

**Comment by bk201** [comment] 2023-02-20 03:59
@AndreiLazarescu 

> Containerd fails "Connection refused"

Could you provide a screenshot? Wonder if it looks like this: https://github.com/harvester/harvester/issues/2651

**Comment by AndreiLazarescu** [comment] 2023-02-20 11:22
Yes, that is the error. It tries several times and then stops there.
I will provide a screenshot later, away from the server now.

Kind regards,
Andrei


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AndreiLazarescu** [comment] 2023-02-20 15:28
Hello

Screenshots:
![2023-02-20_16-25-35](https://user-images.githubusercontent.com/8302687/220146549-0e2d7346-d777-42a9-b4c1-800e7aaffb66.png)
![2023-02-20_17-12-59](https://user-images.githubusercontent.com/8302687/220146580-f9afd258-50d3-4c67-8120-20d4faa6259c.png)
![2023-02-20_17-19-46](https://user-images.githubusercontent.com/8302687/220146594-5b635ba8-3534-4745-baa6-7c83ceee964e.png)

**Comment by bk201** [comment] 2023-02-21 01:25
@AndreiLazarescu This means the images can't be preloaded within 30 minutes.
Can you use a fast USB stick or a USB slot? It might help.

**Comment by AndreiLazarescu** [comment] 2023-02-21 02:18
@bk201 That is strange, the errors pop up very fast (1-2 s), it is just like a retry mechanism. I thought it is from the containerd package. The stick is a SanDisk 32 Gb USB 2.0 and I do not have a 3.0 one free right now, have to order one.

My NAS is under construction, waiting on some parts. I will try PXE once I have it up and running. It will be my long-term solution. Do you think that it will fix this issue?

**Comment by bk201** [comment] 2023-02-21 02:25
iPXE will help if the USB is the bottleneck. Can you collect a supportconfig bundle when after this issue happens? It contains more log to debug. https://docs.harvesterhci.io/v1.0/troubleshooting/installation#collecting-troubleshooting-information

**Comment by AndreiLazarescu** [comment] 2023-02-21 03:18
This is what I could get from the server, some commands are not recognised and the "/run/cos/target/" does not exist.
Rebooted 2 times and it seems to be working after those errors. Did not deployed any VMS or Kubernetes clusters yet.
[console.log](https://github.com/harvester/harvester/files/10789253/console.log)
[dmesg.txt](https://github.com/harvester/harvester/files/10789255/dmesg.txt)

**Comment by AndreiLazarescu** [comment] 2023-03-01 23:41
Tried with a fast USB stick as well. It was a far cry but I tried it anyhow, does not work,

**Comment by bk201** [comment] 2023-03-02 01:49
@AndreiLazarescu Thanks. I think it should the same as https://github.com/harvester/harvester/issues/3501
Could you briefly provide the system info? CPU, memory, and the installation disk type.

**Comment by AndreiLazarescu** [comment] 2023-03-02 12:58
@bk201 Please view the system specifications below:

- **Server  Chassy**: Dell PowerEdge T630
- **Processor**: 2x Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
- **RAM**: 128 GB 
- **RAID Controller**: PERC H730 Adapter (PCI Express Gen3)
- **SSD**: 1 TB Samsung
- **Embedded NIC**: Intel(R) Gigabit 2P I350-t LOM
- **Extra NIC**: Intel(R) PRO/1000 PT Dual Port Network Connection

**Comment by raas-nnit** [comment] 2023-04-21 14:16
We have experienced this today. The solution is to reboot the machine from the ILO. Apparently the harvester cannot reboot, and there are no messages that it is trying to do so.

**Comment by AndreiLazarescu** [comment] 2023-04-21 14:26
I do not think it is a clean install. After reboot, it works the first time (20 minutes to come online) and the next time you start it, it did not come online.

**Comment by w13915984028** [comment] 2023-05-10 16:36
The root cause is same as 
https://github.com/harvester/harvester/issues/2651

and is fixed in https://github.com/harvester/harvester-installer/pull/458

could be verified in the comming v1.2.0 & v1.1.3 (if planned) releases.

**Closed as completed by w13915984028** 2023-05-10 16:36 UTC
Labels: kind/bug, require/reproduce, require/severity
