### ISSUE TITLE
[BUG]Virtual Machine termination doesn't remove the attached volume

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#973] opened 2021-06-23 20:03 UTC
**Describe the bug**
When the VM is deleted using the api, the VM is deleted but the attached volume is not deleted. When you manually try to delete that volume on UI, it fails with error -
admission webhook "validator.harvesterhci.io" denied the request: can not delete the volume 62a6b86fbc35454796a6dc6d808fb4b5-disk-0-0ihni which is currently owned by these VMs: 62a6b86fbc35454796a6dc6d808fb4b5
But In this case, the VM is already deleted

**To Reproduce**
1. Try to delete a VM using api.
2. Try to delete Volume attached to VM manually on UI

**Expected behavior**
When the VM is deleted using API the attached Volume should delete along with it
Manually on UI, you should be able to delete Volume if VM is already deleted

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):Harvester iPXE Boot Using Vagrant Libvirt

**Additional context**

**Comment by yasker** [comment] 2021-06-24 19:12
@guangbochen can you take a look at this?

**Comment by noahgildersleeve** [comment] 2021-06-24 19:16
When you try to delete this via the UI it hangs and won't finish `terminating`.
![Greenshot 2021-06-24 12 14 46](https://user-images.githubusercontent.com/83787952/123320016-108a5580-d4e6-11eb-840a-ef6355cecb51.png)

**Comment by bk201** [comment] 2021-06-25 00:25
The root cause of this issue is the same as the one in https://github.com/harvester/harvester/issues/970.
It should be fixed together.

**Comment by guangbochen** [comment] 2021-06-25 02:20
duplicate of https://github.com/harvester/harvester/issues/970

**Closed as completed by guangbochen** 2021-06-25 02:20 UTC
Labels: kind/bug
