### ISSUE TITLE
[BUG] Harvester UI Virtual Machine page shows "Restore" column even after none of the restore is in progress

### ISSUE THREAD

**Issue by devenkulkarni** [harvester/harvester#6195] opened 2024-07-18 13:09 UTC
Description:
Upon restoring a VM, the Virtual Machine page on Harvester UI shows the `Restore` column with the progress bar, but upon the completion of the restore, it does not go away.
 
 <img width="1728" alt="Screenshot 2024-07-18 at 6 19 19 PM" src="https://github.com/user-attachments/assets/f039a214-5768-4553-8a22-4e32564ff0e9">
 
Steps to reproduce the behaviour:
1. Setup backup target.
2. Create a backup for a virtual machine in harvester.
3. Restore backup to a new VM.
4. Check the Virtual Machine page the "Restore" column does not go away 

Expected behaviour:
1. Restore column should be removed after completion of the restore.

Workaround:

You may need to delete the completed restore from the harvester k8s cluster. We have identified it as a bug and as a workaround for now, you can delete the completed restore.

```
kubectl get virtualmachinerestores.harvesterhci -A
NAMESPACE   NAME                               TARGET_KIND      TARGET_NAME   COMPLETE   AGE     ERROR
default     restore-devendra-s3-backup-z5h5j   VirtualMachine   restored-vm   true       5m26s  
```

```
kubectl delete virtualmachinerestores.harvesterhci restore-devendra-s3-backup-z5h5 -n default
```

Environment:
 - Harvester ISO version:  v1.3.1

<img width="945" alt="Screenshot 2024-07-18 at 6 23 35 PM" src="https://github.com/user-attachments/assets/4934170f-8f64-46fe-81d7-fc3cc26edb50">
<img width="1726" alt="Screenshot 2024-07-18 at 6 23 52 PM" src="https://github.com/user-attachments/assets/d2aecb72-7d5b-4a3f-8038-c4b81b6fb0fe">

**Comment by w13915984028** [comment] 2024-07-18 14:46
@torchiaf Explained the condition:
```
The restore column is displayed in the following case:
The VMs list contains at least 1 VM restored from a backup, even if that restore is completed
The column contains:
the progress bar +  percentage number if the restore is still in progress
completed if the restore action is completed
- (dash) if the VM is not created from a backup
```

 https://docs.harvesterhci.io/v1.4/vm/backup-restore#vm-snapshot--restore has no detailed information about the VM page which with restore colume. It is worthy to update the document.

**Comment by WebberHuang1118** [comment] 2024-07-22 03:30
I can reproduce with the same steps https://github.com/harvester/harvester/issues/6195#issue-2416320314

> @torchiaf Explained the condition:
> 
> ```
> The restore column is displayed in the following case:
> The VMs list contains at least 1 VM restored from a backup, even if that restore is completed
> The column contains:
> the progress bar +  percentage number if the restore is still in progress
> completed if the restore action is completed
> - (dash) if the VM is not created from a backup
> ```

Hi @torchiaf @a110605 

This does a little not make sense to me, what if the `virtualmachinerestore` is created before Harvester v1.3.0? It is completed but has no information about the progress, it seems like a similar situation as #5068, but it's for  `virtualmachinerestore` .

IMHO, the front end may not have to show this column if the related `virtualmachinerestore` is completed. WDYT?

**Comment by WebberHuang1118** [comment] 2024-07-22 08:49
> Workaround:
> 
> You may need to delete the completed restore from the harvester k8s cluster. We have identified it as a bug and as a workaround for now, you can delete the completed restore.
> 
> ```
> kubectl get virtualmachinerestores.harvesterhci -A
> NAMESPACE   NAME                               TARGET_KIND      TARGET_NAME   COMPLETE   AGE     ERROR
> default     restore-devendra-s3-backup-z5h5j   VirtualMachine   restored-vm   true       5m26s  
> ```
> 
> ```
> kubectl delete virtualmachinerestores.harvesterhci restore-devendra-s3-backup-z5h5 -n default
> ```

This workaround can't be applied. 

The restoring VM's pvc has `ownerReferences` points to the matched CR `virtualmahcinerestore`, for example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ....
  name: restore-vm-b1-434fd2c1-fd7a-4c0f-bda7-9ac31becef13-disk-0
  namespace: default
  ownerReferences:
  - apiVersion: harvesterhci.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineRestore
    name: restore-vm-b1-5xcnx
    uid: 434fd2c1-fd7a-4c0f-bda7-9ac31becef13
  resourceVersion: "100298"
  uid: c7db72ed-d9c9-4fee-a424-14a3cefbb0bb
spec:
  accessModes:
  - ReadWriteMany
  ....
  storageClassName: longhorn-image-l8mlc
  volumeMode: Block
  volumeName: pvc-c7db72ed-d9c9-4fee-a424-14a3cefbb0bb
```

so once the `virtualmachinerestore` CR is deleted, the PVC will turn into `Terminating` status. If the restoring VM is stopped, the PVC will be completely deleted.

**Comment by torchiaf** [comment] 2024-07-22 14:55
> IMHO, the front end may not have to show this column if the related `virtualmachinerestore` is completed. WDYT?

Totally agree, I fixed the behavior so that the restore column will be removed once all VMs are restored.

**Comment by TachunLin** [comment] 2024-08-08 15:33
Verified **fixed** on `v1.3-5445e91-head`. Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ After restore to new vm complete, the restore column will disappear $~~$</summary>


https://github.com/user-attachments/assets/b94521f4-be09-4ab0-a756-45221917e719


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ After restore to replace vm (retain volume) complete, the restore column will disappear $~~$</summary>


https://github.com/user-attachments/assets/863d3a45-4304-415b-8f3d-1058248b0d52


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ After restore to replace vm (delete volume) complete, the restore column will disappear $~~$</summary>

https://github.com/user-attachments/assets/81d539c9-768d-4cbf-b3b3-89785e052e3d






 </details>




### Test Information
* Test Environment: Single nodes on local kvm machine
* Harvester version: `v1.3-5445e91-head` 

### Verify Steps
<details><summary> Restore backup to create new vm </summary>

1. Create a vm names `opensuse`
2. Setup nfs backup target
3. Create a backup named `opensuse-backup`
4. Restore the backup 
5. Select restore to new vm
6. Enter the new vm name
7. Check the restore process complete
8. Check the restore column will disappear after restore process finish

</details>

<details><summary> Restore backup to replace existing vm  </summary>

1. Create a vm names `opensuse`
2. Setup nfs backup target
3. Create a backup named `opensuse-backup`
4. Restore the backup 
5. Shutdown the vm
6. Select restore to existing vm
7. Select to retain (or delete) volume
8. Check the restore process complete
9. Check the restore column will disappear after restore process finish

</details>

**Comment by TachunLin** [comment] 2024-08-12 11:19
Verified **blocked** on `v1.4-4fe69de-head`. Move back to Ready for testing.
Blocked by issue: #6312 

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ After restore to new vm complete, the restore column will disappear $~~$</summary>


https://github.com/user-attachments/assets/4a744956-b4eb-40b3-80bf-bb7fbd53dce7



 </details>

<details><summary>$\color{red}{\textsf{Failed}}$ Blocked since failed to restore backup to existing vm, stuck in <strong>Restoring</strong> and can't complete $~~$</summary>

  ![image](https://github.com/user-attachments/assets/8c2ac109-49e7-4739-8772-db846708106e)

  https://github.com/user-attachments/assets/367b5227-2c44-44c7-ad7e-8218735e56ee

 </details>

<details><summary>$\color{grey}{\textsf{Not started}}$ After restore to replace vm (delete volume) complete, the restore column will disappear $~~$</summary>



 </details>




### Test Information
* Test Environment: Single nodes on local kvm machine
* Harvester version: `v1.4-4fe69de-head` 

### Verify Steps
<details><summary> Restore backup to create new vm </summary>

1. Create a vm names `opensuse`
2. Setup nfs backup target
3. Create a backup named `opensuse-backup`
4. Restore the backup 
5. Select restore to new vm
6. Enter the new vm name
7. Check the restore process complete
8. Check the restore column will disappear after restore process finish

</details>

<details><summary> Restore backup to replace existing vm  </summary>

1. Create a vm names `opensuse`
2. Setup nfs backup target
3. Create a backup named `opensuse-backup`
4. Restore the backup 
5. Shutdown the vm
6. Select restore to existing vm
7. Select to retain (or delete) volume
8. Check the restore process complete
9. Check the restore column will disappear after restore process finish

</details>

**Comment by rrajendran17** [comment] 2024-09-27 22:26
@WebberHuang1118 @torchiaf. Can you please confirm if I am missing something ?
I verified this on v1.4-00cd4ee-head (sep 19 build) and looks like restoring an existing vm is stuck.It is more than 40 mins its been restoring

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1MQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4821d7b090a56f5cdeeadedcdb43ce5fbec5f7e/6195img11.png" alt="6195img11.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72218ae1f59aaa535a43989bf14c425e6ecd7dc9/6195img22.png" alt="6195img22.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNklMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb855f67197bdde67351842c41c7618a27b867f6/6195img33.png" alt="6195img33.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd209bfdecb846dbdfcd8954334177f6d5775635/6195image44.png" alt="6195image44.png" />

**Comment by WebberHuang1118** [comment] 2024-09-30 03:04
Hi @rrajendran17 

I can restore the existing VM with the master-head builds 9/18 (`0e15f01377df856b7b00316fbeb57c4a25f13833`) and the latest (`606f485579d087def560e2a8a255a2b0f4bad019`). The steps are:
- Creating a VM `vm1`
- Setting a NFS backup target
- Creating a VM backup `vm1-b` for VM `vm1`
- Stopping VM `vm1`
- Restoring VM backup `vm1-b` as `replace existing`

Can you check again with the latest build and provide the SB if needed? the restoring replacing existing issue has been verified by #6312, thanks. cc @TachunLin

**Comment by TachunLin** [comment] 2024-09-30 07:18
Hi team, 
I just have a chance to retest this issue on recent Harvester v1.4-head. 

According to following test result, it looks like can restore backup well to the new vm and existing vm with both retain and delete volume options. 

After restore  complete, the `Restore` column would also disappear.

---

### Test result

Verified **Fixed** on `v1.4-97e60e1-head` (24/09/29)

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ After restore to new vm complete, the restore column will disappear $~~$</summary>


https://github.com/user-attachments/assets/18852e6c-e3a3-4cb9-9669-5d59e38d4863



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ After completely restore backup to existing vm with <strong>retain</strong> volume, the restore column will disappear $~~$</summary>

https://github.com/user-attachments/assets/c4915aea-c245-4e2f-aeca-a9e6fe594ca5


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ After completely restore backup to existing vm with <strong>delete</strong> volume, the restore column will disappear $~~$</summary>


https://github.com/user-attachments/assets/bb4d6beb-8d8f-429e-b3ff-5b822a1cae1a



 </details>




### Test Information
* Test Environment: Three nodes kvm machines
* Harvester version: `v1.4-97e60e1-head` (24/09/29)

### Verify Steps
<details><summary> Restore backup to create new vm </summary>

1. Create a vm names `opensuse`
2. Setup nfs backup target
3. Create a backup named `opensuse-backup`
4. Restore the backup 
5. Select restore to new vm
6. Enter the new vm name
7. Check the restore process complete
8. Check the restore column will disappear after restore process finish

</details>

<details><summary> Restore backup to replace existing vm  </summary>

1. Create a vm names `opensuse`
2. Setup nfs backup target
3. Create a backup named `opensuse-backup`
4. Restore the backup 
5. Shutdown the vm
6. Select restore to existing vm
7. Select to retain (or delete) volume
8. Check the restore process complete
9. Check the restore column will disappear after restore process finish

</details>

--- 

@rrajendran17, 
May I know the vm image used in your previous testing scenario.

And I am thinking whether the following factor would affect the restore result 
1. Failed to attach volume for some reason
2. The image have been encrypted 
3. Webhook not immediately reflect the changes (Maybe can try refresh the page)

**Comment by rrajendran17** [comment] 2024-10-01 17:31
@TachunLin I used v1.4-00cd4ee-head (sep 19 build) when testing the changes.

**Comment by WebberHuang1118** [comment] 2024-10-02 01:40
After checking with @rrajendran17,

In the stuck-restoring case, the NFS service is running in the VM, which is going to be replaced, so the volume can't be restored.

Since it's not the expected use scenario, and @TachunLin already [double-check this issue](https://github.com/harvester/harvester/issues/6195#issuecomment-2382301327), after discussion with @rrajendran17, we agree to close this ticket, thanks.

**Closed as completed by WebberHuang1118** 2024-10-02 01:40 UTC
Labels: kind/bug, require/doc, area/ui, severity/2, reproduce/always, require/reproduce, require/severity, backport-needed/1.3.2
