### ISSUE TITLE
[FEATURE] Support ingress configuration

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#452] opened 2021-01-27 10:16 UTC
**Is your feature request related to a problem? Please describe.**

currently, users need to configure ingress to access harvester server by manual.

**Describe the solution you'd like**

- [ ] users can configure ingress from harvester ui.
- [ ] if ingress configured, harvester-installer's management URL show ingress domain instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment] 2021-05-06 05:40
duplicate of https://github.com/harvester/harvester/issues/632

**Closed as completed by guangbochen** 2021-05-06 05:40 UTC
Labels: kind/enhancement, area/ui, area/control-plane
