### ISSUE TITLE
[BUG] Windows Server ISOs reboot system before getting to the installation screen

### ISSUE THREAD

**Issue by Yabbo** [harvester/harvester#1730] opened 2021-12-21 17:07 UTC
**Describe the bug**
When trying to install a Windows server from ISO or QCOW files on both Harvester 1.0.0 and 0.3.0 the windows ISO will start to boot up and get to the windows logo with the spinning circles and then the system will reboot before any menu screens come up.

**To Reproduce**
1. boot from any windows server ISO (2021, 2019 R2, 2012) 

**Expected behavior**
Boot into the installer and allow installation of windows server

**Support bundle**
[supportbundle_15168620-813b-473f-b970-920ec49356b8_2021-12-21T17-05-17Z.zip](https://github.com/harvester/harvester/files/7756925/supportbundle_15168620-813b-473f-b970-920ec49356b8_2021-12-21T17-05-17Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.0 and 0.3.0
 - Underlying Infrastructure Baremetal 2 node cluster with 10G nics 

**Additional context**
I can build and install Ubuntu and Arch based systems with no issue on this cluster

**Comment by yasker** [comment] 2021-12-22 19:03
I’ve just tried Windows 2012 R2 and it works. Not sure if it’s related but I set my root disk to 50G and give it 4c8g./

I do have issues with Windows 2019 at the moment. The VM keeps rebooting. Might be related to https://github.com/harvester/harvester/issues/276

**Comment by FrankYang0529** [comment] 2022-01-28 09:00
I can't reproduce this issue with Harvester `master-a67f96d-head` by following steps:

* Launch instance from `windows-iso-image-base-version` template.
* Give a VM name.
* Click `Volumes` tab.
  * Choose a windows image in `cdrom-disk`.
  * Volume Type will auto change to disk. Change it back to `cd-rom`.
* Click Create.
* Open in Web VNC for the VM.
* Choose `Custom: Install Windows only`.
![Screen Shot 2022-01-28 at 4 48 21 PM](https://user-images.githubusercontent.com/4927361/151515792-f2259f00-5aa4-4949-bed7-e38b71464e24.png)
* Click `Load driver`.
![Screen Shot 2022-01-28 at 4 49 56 PM](https://user-images.githubusercontent.com/4927361/151515985-dbf4af65-eb55-4668-8d70-c52bc3e1a71d.png)
* Click `Browse`.
* Choose driver under `vmdp-200205_virt` disk.
  * For WIndows 2022 & 2019, install `win 10-2019/x64/pvvx`.
  * For Windows 2012, install `win8.1-2012r2/x64/pvvx`
![Screen Shot 2022-01-28 at 4 52 21 PM](https://user-images.githubusercontent.com/4927361/151516322-e7e43790-53a2-46e7-8492-c372edee08c2.png)
* Click `Next` to install drivers.
* Click `Drive 0 Unallocated Space` and `Next` to install WIndows.

**2012 R2**
![w2012](https://user-images.githubusercontent.com/4927361/151517456-61c64e73-8f85-4ca9-af5e-c594d2482ec3.png)

**2019**
![w2019](https://user-images.githubusercontent.com/4927361/151516929-9be63258-a4f0-4deb-98a2-47f5a1f5344c.png)

**2022**
![w2022](https://user-images.githubusercontent.com/4927361/151516941-33a9030a-a026-419a-b8cf-91c566b51dd0.png)

**Comment by noahgildersleeve** [comment] 2022-02-10 22:16
This seems to be blocked by #1904 . I can't upload the windows ISOs to the server to test, and the WIndows server ISOs aren't on an easily accessible public server anywhere. There's also issues with the `windows-iso-image-base-template` in the UI. I'm going to look more into it and log a bug about it once I can test it.

**Comment by guangbochen** [comment] 2022-02-24 05:09
We can skip the https://github.com/harvester/harvester/issues/1904 using the download from remote URL method, the key is to verify the related Windows Server VMs can be spin-up successfully(e.g, 2021, 2019 R2, 2012).

**Comment by Br4v3St4rr** [comment] 2022-02-28 11:56
I seem to have had a similar experience when trying to install Server 2022 from the ISO.  It seems to be due to the Memory allocation.  Anything over 12GB seems to cause the installer to reboot. I'm not sure if this is relative to any underlying resource, RAM Capacity etc.

**To Reproduce**
Steps to reproduce the behaviour:

1. Select "windows-iso-image-base-version" -> Launch Instance from template
2. Set CPU = 2, Memory =13GB
3. Set windows server ISO (2022)

**Expected behaviour**
Boot into the installer and allow installation of windows server


**Environment:**

Harvester version: 1.0.0
Underlying Infrastructure: Baremetal 3 node cluster with 10G nics
Server Specs: Dell R610 - Dual X5660 - 96GB RAM
**Additional context**
Lower memory to 12GB or less and installer completes succesfully.
[supportbundle_cd422c6c-817b-48d9-9c53-54194db2d145_2022-02-28T11-55-12Z.zip](https://github.com/harvester/harvester/files/8153094/supportbundle_cd422c6c-817b-48d9-9c53-54194db2d145_2022-02-28T11-55-12Z.zip)

**Comment by FrankYang0529** [comment] 2022-03-03 04:28
Hi @Br4v3St4rr, thanks for the information. I also can reproduce this issue if I request RAM more than 12G.

From the system log, it's an OOM issue. The real memory request for a VM is not only from users but also from various [VM resources](https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#memory-overhead), such as a video adapter, IOThreads, etc. Although KubeVirt controller has already [requested more memory in Pod](https://github.com/kubevirt/kubevirt/blob/a6a84d0388b12d8c812e19cb7cc88f5193e42bdf/pkg/virt-controller/services/template.go#L1859), it's not enough. We can see if we set `spec.domain.resources.limits.memory` as `16Gi` in VM, the real memory limitation in the pod is `17416847361`.

A workaround way here is to reduce the memory that guest OS can use. For example, I request a Windows VM with 16G RAM and set `spec.domain.memory.guest` as `15Gi`. The Windows VM can be installed successfully.
![Screen Shot 2022-03-03 at 11 54 00 AM](https://user-images.githubusercontent.com/4927361/156496017-be1be991-678e-40b5-9244-ea9aa61decd1.png)

@guangbochen do you agree to modify `spec.domain.memory.guest` in Webhook if users request a Windows server with more than 12G RAM? cc @weihanglo

**Comment by guangbochen** [comment] 2022-03-03 14:28
According to [kubevirt-memory-overcommit](https://kubevirt.io/2018/KubeVirt-Memory-Overcommit.html), I think we should support both overcommit and under-commit because it is hard for the webhook to predict the user's OS or resource expectations.
By default, we should keep doing [under-commit action](https://github.com/harvester/harvester/blob/dba8594007123b89d5e54509ed80543b173d2375/pkg/webhook/resources/virtualmachine/mutator.go#L117-L120), but when the user manually enters a `spec.domain.memory.guest` value which is greater or equal to the `requests.limit`, then we should use the input directly.

**Comment by FrankYang0529** [comment] 2022-03-04 04:21
@guangbochen, from [KubeVirt webhook source code](https://github.com/kubevirt/kubevirt/blob/f8160a0b5eac2acafab74fd7916bfcaf0c39a6a3/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L1307-L1325), I don't think we can request `domain.memory.guest` more than `requests.limits.memory` as the article.

For [`overcommitGuestOverhead`](https://github.com/kubevirt/kubevirt/blob/f8160a0b5eac2acafab74fd7916bfcaf0c39a6a3/pkg/virt-controller/services/template.go#L973-L983), KubeVirt always add overhead memory to `resources.limits`, but not `resources.requests`. When we set `overcommitGuestOverhead: true`, it adds overhead memory to `resources.requests`.

For this issue, we can make under-commit as an input. Also, we let users know if there pods keep restarting with OOM issues, they can try to increase under-commit.

**Comment by FrankYang0529** [comment] 2022-03-04 09:11
We will need UI to add an Advanced Option `Reserved memory` after https://github.com/harvester/harvester/pull/1965 is merged. Thanks.

**Comment by lanfon72** [comment] 2022-03-10 10:03
Verified this bug should be fixed. (Based on the comment https://github.com/harvester/harvester/issues/1730#issuecomment-1054181984)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-fd872c99-head**
* **ui-source** Option: **Auto**
* **Virtio-win ISO**: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
* Windows Version: Windows 2019

### Verify Steps:
- Follow the **Steps to reproduce** in https://github.com/harvester/harvester/issues/1767#issue-1093194711
- Set VM's Memory to **16 GiB**, CPU to **4 C**
- Set `Reserved Memory` to **1024 MiB** in VM's Advanced Options
![image](https://user-images.githubusercontent.com/5169694/157638288-b97b0534-b9ae-479a-a30e-24b9aa17353a.png)

**Closed as completed by lanfon72** 2022-03-10 10:03 UTC
Labels: kind/bug, area/ui, priority/1, area/vm-windows
