### ISSUE TITLE
[BUG] Harvester import fails if Rancher certificate is self-signed

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2028] opened 2022-03-17 16:27 UTC
**To Reproduce**

1. Install Rancher with a self-signed certificate
2. Configure the self-signed certificate in Harvester -> Settings -> Additional CA
3. Import the Harvester Cluster into Rancher

**Result:**

Import fails

Harvester 1.0.0

**Comment by joshmeranda** [comment] 2022-04-15 16:33
Verified, here are some of the relevant logs:

```
time="2022-04-15T16:29:20Z" level=info msg="Certificate details from https://192.168.0.104"
time="2022-04-15T16:29:20Z" level=info msg="Certificate #0 (https://192.168.0.104)"
time="2022-04-15T16:29:20Z" level=info msg="Subject: CN=*.qa.rancher.space"
time="2022-04-15T16:29:20Z" level=info msg="Issuer: CN=Rancher QA CA"
time="2022-04-15T16:29:20Z" level=info msg="IsCA: false"
time="2022-04-15T16:29:20Z" level=info msg="DNS Names: [*.qa.rancher.space *.qa.rancher.space]"
time="2022-04-15T16:29:20Z" level=info msg="IPAddresses: <none>"
time="2022-04-15T16:29:20Z" level=info msg="NotBefore: 2021-10-19 18:51:31 +0000 UTC"
time="2022-04-15T16:29:20Z" level=info msg="NotAfter: 2022-10-19 18:51:31 +0000 UTC"
time="2022-04-15T16:29:20Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2022-04-15T16:29:20Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2022-04-15T16:29:20Z" level=info msg="Certificate details for /etc/kubernetes/ssl/certs/serverca"
time="2022-04-15T16:29:20Z" level=info msg="Certificate #0 (/etc/kubernetes/ssl/certs/serverca)"
time="2022-04-15T16:29:20Z" level=info msg="Subject: CN=Rancher QA CA"
time="2022-04-15T16:29:20Z" level=info msg="Issuer: CN=Rancher QA CA"
time="2022-04-15T16:29:20Z" level=info msg="IsCA: true"
time="2022-04-15T16:29:20Z" level=info msg="DNS Names: <none>"
time="2022-04-15T16:29:20Z" level=info msg="IPAddresses: <none>"
time="2022-04-15T16:29:20Z" level=info msg="NotBefore: 2021-10-19 18:51:31 +0000 UTC"
time="2022-04-15T16:29:20Z" level=info msg="NotAfter: 2026-10-18 18:51:31 +0000 UTC"
time="2022-04-15T16:29:20Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2022-04-15T16:29:20Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2022-04-15T16:29:20Z" level=fatal msg="Server certificate does not contain correct DNS and/or IP address entries in the Subject Alternative Names (SAN). Certificate information is displayed above. error: Get \"https://192.168.0.104\": x509: cannot validate certificate for 192.168.0.104 because it doesn't contain any IP SANs"
```

**Comment by joshmeranda** [comment] 2022-04-15 18:57
Looking like this is an issue with the self-signed certs rather than a bug in harvester. The portion of the last log entry `x509: cannot validate certificate for 192.168.0.104 because it doesn't contain any IP SANs` indicates that the host name / ip of your rancher deployment is not listed as an accepted hos. In my development environment my rancher deployment is on `192.168.0.104` so I needed that it to the list of Ip Addresses:

```sh
docker run -v $PWD/certs:/certs \
    -e CA_SUBJECT="2028 Test Cert" \
    -e CA_EXPIRE="1825" \
    -e SSL_EXPIRE="365" \
    -e SSL_SUBJECT="2028 Test Cert" \
    -e SSL_IP="192.168.0.104" \
    superseb/omgwtfssl
```

The `X509v3` section of the cert should look something like this:
```
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:2028 Test Cert, IP Address:192.168.0.104
```

**Comment by joshmeranda** [comment] 2022-04-15 19:06
@janeczku Are seeing similar `IP SANs` error logs in the `cattle-cluster-agent-xxxxxxxxxx-xxxxx` in the `cattle-system` pod on your harvester cluster?

**Comment by janeczku** [comment] 2022-04-22 12:35
@joshmeranda I do not. But i am using a DNS-based Rancher URL for importing, while you seem to use an IP-based Rancher URL based on [your logs above](https://github.com/harvester/harvester/issues/2028#issuecomment-1100215508):
> time="2022-04-15T16:29:20Z" level=fatal msg="Server certificate does not contain correct DNS and/or IP address entries in the Subject Alternative Names (SAN). Certificate information is displayed above. error: Get \"https://192.168.0.104\": x509: cannot validate certificate for 192.168.0.104 because it doesn't contain any IP SANs"

**Comment by janeczku** [comment] 2022-04-22 13:22
Related issue: https://github.com/harvester/harvester/issues/2176

**Comment by janeczku** [comment] 2022-04-22 13:22
Related issue: https://github.com/harvester/harvester/issues/2175

**Comment by joshmeranda** [comment] 2022-04-29 19:25
hmmm I changed to a DNS setup but I'm still seeing the cluster register properly. Have you added the DNS names to the list of alternatives? I generated the certs with:

```bash
docker run -v $PWD/certs:/certs \
    -e CA_SUBJECT="2028 Test Cert" \
    -e CA_EXPIRE="1825" \
    -e SSL_EXPIRE="365" \
    -e SSL_SUBJECT="2028 Test Cert" \
    -e SSL_DNS="rancher.mgmt.com" \
    superseb/omgwtfssl
```

Where `rancher.mgmt.com` is the DNS record for the rancher deployment.

Can you share the logs of the `cattle-cluster-agent` and the commands you used to generated the certs?

**Comment by joshmeranda** [comment] 2022-11-02 15:17
Re-validated that importing with self-signed certs seems to work using rancher `v2.6.9` and Harvester `v1.`1.1.0` so I'm going to close this issue.

If this is still reproducible for you, please collect the logs of the `cattle-system/cattle-cluster-agent-xxxxxxxxxx-xxxxx` on your harvester cluster and any error messages you encounter and I'm happy to take another look.

**Closed as completed by joshmeranda** 2022-11-02 15:17 UTC
Labels: kind/bug, priority/1, require/reprioritize

**Comment by zeinali0** [comment] 2023-12-11 11:48
I'm having same issue on `harvester 1.2` and `rancher 2.7.9`

here are logs of cattle-cluster-agent on harvester node:
```
# kubectl logs pod/cattle-cluster-agent-6df9b5cb57-hxr7r -n cattle-system
INFO: Environment: CATTLE_ADDRESS=10.52.0.94 CATTLE_CA_CHECKSUM=913129f0dcb4c15ca3d2f48889e02184eca4db0f9ff0bef38dc66efee3182814 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.53.235.105:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.53.235.105:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.53.235.105 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.53.235.105:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.53.235.105 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.53.235.105 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=34409118-c866-4a82-a867-901c55ec8449 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-6df9b5cb57-hxr7r CATTLE_RANCHER_WEBHOOK_MIN_VERSION= CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6 CATTLE_SERVER=https://192.168.10.119:30444 CATTLE_SERVER_VERSION=v2.7.9
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.53.0.10 options ndots:5
INFO: https://192.168.10.119:30444/ping is accessible
INFO: Value from https://192.168.10.119:30444/v3/settings/cacerts is an x509 certificate
time="2023-12-11T11:25:35Z" level=info msg="Listening on /tmp/log.sock"
time="2023-12-11T11:25:35Z" level=info msg="Rancher agent version v2.7.9 is starting"
time="2023-12-11T11:25:35Z" level=info msg="Certificate details from https://192.168.10.119:30444"
time="2023-12-11T11:25:35Z" level=info msg="Certificate #0 (https://192.168.10.119:30444)"
time="2023-12-11T11:25:35Z" level=info msg="Subject: CN=dynamic,O=dynamic"
time="2023-12-11T11:25:35Z" level=info msg="Issuer: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T11:25:35Z" level=info msg="IsCA: false"
time="2023-12-11T11:25:35Z" level=info msg="DNS Names: [localhost]"
time="2023-12-11T11:25:35Z" level=info msg="IPAddresses: [10.42.2.2 10.42.2.3 10.42.2.5 10.42.2.8 10.43.247.0 127.0.0.1 192.168.10.119]"
time="2023-12-11T11:25:35Z" level=info msg="NotBefore: 2023-12-04 14:05:32 +0000 UTC"
time="2023-12-11T11:25:35Z" level=info msg="NotAfter: 2024-12-05 20:53:38 +0000 UTC"
time="2023-12-11T11:25:35Z" level=info msg="SignatureAlgorithm: ECDSA-SHA256"
time="2023-12-11T11:25:35Z" level=info msg="PublicKeyAlgorithm: ECDSA"
time="2023-12-11T11:25:35Z" level=info msg="Certificate #1 (https://192.168.10.119:30444)"
time="2023-12-11T11:25:35Z" level=info msg="Subject: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T11:25:35Z" level=info msg="Issuer: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T11:25:35Z" level=info msg="IsCA: true"
time="2023-12-11T11:25:35Z" level=info msg="DNS Names: <none>"
time="2023-12-11T11:25:35Z" level=info msg="IPAddresses: <none>"
time="2023-12-11T11:25:35Z" level=info msg="NotBefore: 2023-12-04 14:05:32 +0000 UTC"
time="2023-12-11T11:25:35Z" level=info msg="NotAfter: 2033-12-01 14:05:32 +0000 UTC"
time="2023-12-11T11:25:35Z" level=info msg="SignatureAlgorithm: ECDSA-SHA256"
time="2023-12-11T11:25:35Z" level=info msg="PublicKeyAlgorithm: ECDSA"
time="2023-12-11T11:25:35Z" level=info msg="Certificate details for /etc/kubernetes/ssl/certs/serverca"
time="2023-12-11T11:25:35Z" level=info msg="Certificate #0 (/etc/kubernetes/ssl/certs/serverca)"
time="2023-12-11T11:25:35Z" level=info msg="Subject: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T11:25:35Z" level=info msg="Issuer: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T11:25:35Z" level=info msg="IsCA: true"
time="2023-12-11T11:25:35Z" level=info msg="DNS Names: <none>"
time="2023-12-11T11:25:35Z" level=info msg="IPAddresses: <none>"
time="2023-12-11T11:25:35Z" level=info msg="NotBefore: 2023-12-04 14:05:32 +0000 UTC"
time="2023-12-11T11:25:35Z" level=info msg="NotAfter: 2033-12-01 14:05:32 +0000 UTC"
time="2023-12-11T11:25:35Z" level=info msg="SignatureAlgorithm: ECDSA-SHA256"
time="2023-12-11T11:25:35Z" level=info msg="PublicKeyAlgorithm: ECDSA"
time="2023-12-11T11:25:35Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://192.168.10.119:30444\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"dynamiclistener-ca@1701698732\")"
```
