### ISSUE TITLE
[BUG] Placeholder column header shown after VM Restore

### ISSUE THREAD

**Issue by bathomas** [harvester/harvester#5795] opened 2024-05-13 16:25 UTC
**Describe the bug**

On performing a VM Restore from S3, the table on the `Virtual Machines` displays `%tableHeaders.restore%`

![Screenshot 2024-05-13 at 17 09 23](https://github.com/harvester/harvester/assets/6682729/3c0342c7-884d-4a24-b3d8-8e242e184518)

**To Reproduce**
1. Restore VM from S3
2. Navigate to `Virtual Machines` page.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  1.3.0; Rancher 2.7.6
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Lenovo SD630 V2 and SR670 V2.

**Additional context**

**Comment by Vicente-Cheng** [comment] 2024-05-14 16:03
Hi @bathomas
Thanks for raising this issue!

Hi @torchiaf, @a110605,
Would you like to help with this?

cc @bk201

**Comment by a110605** [comment] 2024-05-15 06:57
> Hi @bathomas Thanks for raising this issue!
> 
> Hi @torchiaf, @a110605, Would you like to help with this? 
> 
> cc @bk201

I restore a VM backup locally, but unable to reproduce when choosing `English language` preference.

The [tableHeaders.restore](https://github.com/a110605/harvester-dashboard/blob/bbeb6b81af7f2f6f640de347264339beccd41c21/pkg/harvester/list/kubevirt.io.virtualmachine.vue#L118) key is statically defined [here](https://github.com/a110605/harvester-dashboard/blob/bbeb6b81af7f2f6f640de347264339beccd41c21/shell/assets/translations/en-us.yaml#L5437) 
<img width="1218" alt="english" src="https://github.com/harvester/harvester/assets/5744158/bf8dc872-cf05-465b-980c-a6821c43755a">

@bathomas, will translation key be interpreted after refresh the page ? Maybe just flaky case

**Comment by a110605** [comment] 2024-05-15 06:59
Seems we miss simplied chinese translation, it falls back to English when choosing `Simplied Chinese` preference.
cc @torchiaf 

<img width="1450" alt="chinese" src="https://github.com/harvester/harvester/assets/5744158/134e2df3-e265-48aa-bed6-8e6f50553e32">

**Comment by dawid10353** [comment] 2024-07-02 20:05
Harvester v1.3.1:
![image](https://github.com/harvester/harvester/assets/46601922/2840ba90-b208-44fc-b742-946027a5c46f)

**Comment by torchiaf** [comment] 2024-07-10 14:09
We are using the wrong label key for Restore column. I think it wouldn't work in Rancher embedded world.
This is annoying, we should add a linting rule to check if the label keys exist in the translations file.

**Comment by TachunLin** [comment] 2024-07-12 08:57
Verified **failed** on Harvester `v1.4-6e24bbc-head` with Rancher `v2.8.5`. Move to the implement 


### Result
<details><summary>$\color{red}{\textsf{FAILED}}$ The vm restore progress percentage still display <strong>%tableHeaders.restore%</strong> on the virtual machine page $~~$</summary>

  1. Access Harvester from Rancher virtualization management and try to restore the vm, we can find the progress sill display with  `%tableHeaders.restore%`

  ![image](https://github.com/user-attachments/assets/22e662ba-1070-416e-9772-f2171e1edaa9)
  
  https://github.com/user-attachments/assets/33f8c262-2c40-4a80-b280-dab6be148c8a


 </details>

### Test Information
* Test Environment: Single node Harvester on local kvm machine
* Harvester version: `v1.4-6e24bbc-head`
* Rancher version: `v2.8.5`

### Verify Steps
<details><summary>Restore from S3 backup </summary>

  1. Prepare minio bucket for the S3 backup target 
  2. Set the S3 backup target on Harvester
  3. Create a vm named vm1
  4. Create a backup of th vm1
  5. Access Harvester from Rancher virtualization management page
  6. Restore the backup to a new vm 
  7. Check the progress percentage on the virtual machine page

</details>

### Additional Context 
Should we verify in the master branch release ?

**Comment by torchiaf** [comment] 2024-07-12 10:47
Sorry, @TachunLin the fix is on `master` but not in `release-1.4` yet.

**Comment by TachunLin** [comment] 2024-07-12 10:51
Thanks @torchiaf , I will verify it again on the `master` release.

**Comment by TachunLin** [comment] 2024-07-15 03:13
Verified **fixed** on Harvester `master-8c709ba-head` (07/14) with Rancher `v2.8.5`. Close this issue.


### Result
<details><summary>$\color{green}{\textsf{PASS}}$ The vm restore progress percentage display the correct `restore` text on the virtual machine page $~~$</summary>

  1. Access Harvester from Rancher virtualization management and try to restore to the new vm, we can find the restore progress display the correct text 

  ![image](https://github.com/user-attachments/assets/58e62fe7-c4ee-46df-bcd4-f48d57edddd4)



https://github.com/user-attachments/assets/f8b19fd7-d529-4015-bb09-ffb3837c6ded



  2. Access Harvester from Rancher virtualization management and try to restore to the new vm, we can find the restore progress display the correct text 

  ![image](https://github.com/user-attachments/assets/63f18092-978d-4e9f-b1d5-233e536404bb)



https://github.com/user-attachments/assets/192f0314-f85e-410c-95c1-36a4c3765d67



 </details>


### Test Information
* Test Environment: Single node Harvester on local kvm machine
* Harvester version: `v1.4-6e24bbc-head`
* Rancher version: `v2.8.5`

### Verify Steps
<details><summary>Restore from S3 backup </summary>

  1. Prepare minio bucket for the S3 backup target 
  2. Set the S3 backup target on Harvester
  3. Create a vm named vm1
  4. Create a backup of th vm1
  5. Access Harvester from Rancher virtualization management page
  6. Restore the backup to a new vm 
  7. Check the progress percentage on the virtual machine page

</details>

**Closed as completed** 2024-07-15 03:13 UTC
Labels: kind/bug, require/reproduce, require/severity, backport-needed/1.3.2
