### ISSUE TITLE
[BUG] The favicon icon is incorrect

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4315] opened 2023-07-26 12:57 UTC
**Describe the bug**

The newly installed harvester-rc4 has an incorrect favicon icon。
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/8011f478-feb5-4164-8b5e-f25a71882c34)

According to this pr, we expect the value of `v1/management.cattle.io.settings/ui-brand` to be equivalent to harvester, which is now  '' . https://github.com/harvester/harvester/pull/3784
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/60c899be-8b34-4f58-8ed3-6a96552ee506)

**To Reproduce**

**Expected behavior**

The expected icon should be the harvester icon

**Support bundle**

**Environment**
 - Harvester ISO version:  harvester-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment] 2023-08-14 19:59
Tested in Harvester `master-a3ee4dcb-head`. Validated that Harvester favicon is showing on the main pages and that it is also showing on the support page. Although on the support page it briefly goes to the Rancher icon then it changes back. 

If harvester is imported into upstream Rancher the icon stays as rancher even when in the Virtualization management pages. I assume this is by design. Closing as fixed.

**Closed as completed by noahgildersleeve** 2023-08-14 19:59 UTC
Labels: kind/bug, area/control-plane, priority/1, severity/4, reproduce/always
