### ISSUE TITLE
[BUG] external harvester clusters don't populate entries in RKE1/RKE2 node-driver

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1297] opened 2021-09-27 22:35 UTC
**Describe the bug**

If you create cloud credentials for Harvester with an external Harvester (Using the KUBECONFIG), then the dropdowns don't populate for the 
**To Reproduce**
1. Create cloud credentials using the KUBECONFIG for a harvester cluster
2. Verify that the KUBECONFIG should work
3. Create a new harvester cluster using those credentials
4. Check in the creation screen for dropdowns next to things like image, namespace, network etc

**Expected behavior**

You should have the dropdowns. If you import the harvester cluster into virtualization management and use those cloud credentials it will populate the dropdowns
**Support bundle**

**Environment:**
 - Harvester ISO version: master-b7b757e9-head
 - Rancher version: v2.6-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**

This is an issue because you would have to know the resolution for the namespace and the name of the backing image to get this working without the dropdowns. I also validated that the KUBECONFIG worked with `kubectl` from my Rancher box.

![Greenshot 2021-09-27 15 26 40](https://user-images.githubusercontent.com/8378795
![Greenshot_2021-09-27_15_24_57](https://user-images.githubusercontent.com/83787952/134994316-30438401-b80f-47a9-bbe4-122bf0a2a69f.jpg)
2/134994238-984b56d0-82ac-421b-86dc-0039e7c36901.png)
![Greenshot 2021-09-27 15 26 56](https://user-images.githubusercontent.com/83787952/134994246-0c947236-efe7-4cf6-907d-31a65986ebcf.png)

**Comment by yasker** [comment] 2021-09-27 22:37
@noahgildersleeve This is expected for v0.3.0. It looks like a duplicate of https://github.com/harvester/harvester/issues/1244

**Comment by guangbochen** [comment] 2021-09-28 07:30
close as duplicate of #1244

**Closed as completed by guangbochen** 2021-09-28 07:30 UTC
Labels: kind/bug
