### ISSUE TITLE
[BUG] RKE2 built LoadBalancers w/ (unregistered) SLES 15 SP4 & SP6 Stuck in Pending in Rancher w/ Harvester

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6418] opened 2024-08-25 03:58 UTC
**Describe the bug**
With:
- Harvester v1.3.1 & Rancher v2.8.5 
- Harvester v1.3.1 & Rancher v2.8.6
- Harvester v1.3.2-rc1 & Rancher v2.8.6
RKE2 -  v1.28.10 +rke2r1
On SLES 15 Service Pack 4 or SLES Service Pack 6 Guest OS

RKE2 Load Balancers built never become fully active through Rancher.

In v2.8.6 w/ v1.3.2-rc2, no external hyperlink ever gets built, so it doesn't even build the 'proxy" link like:
```
https://rancher.192.168.120.231.sslip.io/k8s/clusters/c-m-xnmnjplg/api/v1/namespaces/default/services/http:nginx1:8080/proxy/
```
Instead, it will just display in Rancher under the "Target" column, the pod ip:
```
10.43.132.81:8181 80/TCP
``` 

In Harvester v1.3.1 w/ Rancher v2.8.5 & Rancher v2.8.6 it does build the link in the "Target" column to take the user to the "proxy" service.

In Harvester Side under Networks -> Load Balancers in:
- Harvester v1.3.1 & Harvester v1.3.2-rc2
It does not display the address for the Load Balancer.

Also, can be reproduced on:
- Harvester v1.3.2 & Rancher v2.8.5 w/ RKE2  v1.28.12 +rke2r1 ( feel free to adopt in Repro steps )

**To Reproduce**
1. Download SLES 15 SP4 & SLES SP6 (don't register)
2. Ensure images on Harvester v1.3.1
3. Install Rancher v2.8.5 
4. Import Harvester
5. Create v1.28.10+rke2r1 single node cluster w/ either SLES SP4 or SLES SP6 -> or both (user: sles) 
6.  Build nginx:latest -> create Load Balancer Service
7. The Load Balancer, will always be stuck in "pending"

**Expected behavior**
Load Balancer to not just always stuck in pending.  But to resolve on Harvester & Rancher side successfully.

**Support bundle**
[supportbundle_ebd2bdb5-f1db-4006-b453-e5f5d8598eef_2024-08-25T03-13-31Z.zip](https://github.com/user-attachments/files/16738862/supportbundle_ebd2bdb5-f1db-4006-b453-e5f5d8598eef_2024-08-25T03-13-31Z.zip)

**Environment**
 - Harvester ISO version: v1.3.2-rc2 & v1.3.1
 - Rancher Version: v2.8.5, v2.8.6
 - RKE2 Version:  v1.28.12 +rke2r1 ,  v1.28.10+rke2r1
 - Underlying Infrastructure: qemu/kvm or bare-metal && airgap or not-airgap
 - Guest OS: SLES Service Pack 4 , SLES Service Pack 6

**Additional context**
![Screenshot from 2024-08-24 20-52-05](https://github.com/user-attachments/assets/72265702-8a62-4384-a7e7-de7d2990d5f2)
![Screenshot from 2024-08-24 20-12-00](https://github.com/user-attachments/assets/51d0d442-e4a8-4fb9-8ff8-d37b7e99543c)
![Screenshot from 2024-08-24 20-11-35](https://github.com/user-attachments/assets/2d326adc-039b-426b-8462-7ac2401cb181)

**Comment by irishgordo** [comment] 2024-08-25 04:54
This doesn't seem to happen with Ubuntu Noble 24.04 Image.
![Screenshot from 2024-08-24 21-53-59](https://github.com/user-attachments/assets/45255599-edaa-4964-a209-b324eece5196)

**Comment by starbops** [comment] 2024-08-26 07:39
Hi @irishgordo, do you have the logs from the guest clusters, especially the one for the kube-vip pod. The DHCP negotiation in the guest cluster LB scenario is happened between the kube-vip pod and the DHCP server.

I do notice that with specific DHCP server configurations, e.g. `--dhcp-reply-delay=5`, will make kube-vip DHCP negotiation timed-out (default timeout value seems to be 10 seconds). Is there anything special in your DHCP server config?

**Comment by starbops** [comment] 2024-08-26 09:33
With the following:

- Harvester v1.3.1
- Rancher v2.8.4
- Guest cluster
  - SLES 15 SP4
  - RKE2 v1.28.10

I can reproduce the issue. When the LB service (in DHCP type) was created, the following logs in the kube-vip pod showed up:

```
2024-08-26T07:13:15.769149678Z time="2024-08-26T07:13:15Z" level=info msg="Creating new macvlan interface for DHCP [vip-1d547c95]"
2024-08-26T07:13:15.769197827Z time="2024-08-26T07:13:15Z" level=info msg="Generated mac: 00:00:6C:33:68:77"
2024-08-26T07:13:15.769204455Z time="2024-08-26T07:13:15Z" level=info msg="New interface [vip-1d547c95] mac is 00:00:6c:33:68:77"
2024-08-26T07:13:15.776999451Z time="2024-08-26
T07:13:15Z" level=error msg="could not add vip-1d547c95: operation not supported"
```

By tracing the code base in the kube-vip project, the last log line indicated that kube-vip cannot create the macvlan interface https://github.com/kube-vip/kube-vip/blob/fbb2746d076963b4374373c05cb8f3cbb4d5f9d9/pkg/manager/instance.go#L252-L255 (creating macvlan interfaces are required for DHCP). So I tried to manually create a macvlan interface on the node, it showed a different error message:

```shell
sles@bug-6418-expgrp-pool1-27971c20-v5dv8:~> sudo ip link add macvlan1 link eth0 type macvlan 
Error: Unknown device type.
```

There was no `macvlan` kernel module loaded, and it cannot be loaded manually either:

```shell
sles@bug-6418-expgrp-pool1-27971c20-v5dv8:~> lsmod | grep macvlan
sles@bug-6418-expgrp-pool1-27971c20-v5dv8:~> sudo modprobe macvlan
modprobe: FATAL: Module macvlan not found in directory /lib/modules/5.14.21-150400.22-default
```

On the other hand, the guest cluster consists of Ubuntu VMs does have the macvlan module loaded (so there's no issue for Ubuntu-based guest clusters):

```shell
ubuntu@bug-6418-ctrlgrp-pool1-043cbaf9-2qkrt:~$ lsmod | grep mac
macvlan                24576  0
```

Back to SLES, I used a minimal cloud image (`SLES15-SP4-Minimal-VM.x86_64-OpenStack-Cloud-GM.qcow2`):

```shell
sles@bug-6418-expgrp-pool1-27971c20-v5dv8:~> uname -r
5.14.21-150400.22-default
sles@bug-6418-expgrp-pool1-27971c20-v5dv8:~> cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

After installing the `kernel-default` package (the one installed by default is `kernel-default-base`) and rebooting the system, everything worked fine, including the LBs. Regular logs emitted after creating a DHCP-type LB service would be like the following:

```
2024-08-26T09:19:42.939822479Z time="2024-08-26T09:19:42Z" level=info msg="Creating new macvlan interface for DHCP [vip-961305ca]"
2024-08-26T09:19:42.940459629Z time="2024-08-26T09:19:42Z" level=info msg="Generated mac: 00:00:6C:c9:59:7e"
2024-08-26T09:19:42.940473892Z time="2024-08-26T09:19:42Z" level=info msg="New interface [vip-961305ca] mac is 00:00:6c:c9:59:7e"
2024-08-26T09:19:45.990619492Z time="2024-08-26T09:19:45Z" level=info msg="DHCP VIP [0.0.0.0] for [default/web-lb-dhcp] "
2024-08-26T09:19:45.990653792Z time="2024-08-26T09:19:45Z" level=info msg="[service] adding VIP [0.0.0.0] for [default/web-lb-dhcp]"
2024-08-26T09:19:46.209346028Z time="2024-08-26T09:19:46Z" level=info msg="[service] synchronised in 3269ms"
```

Not sure if there's any other lighter way to get the macvlan module loaded. cc @bk201

**Comment by starbops** [comment] 2024-09-04 03:44
harvester/docs#632 has been merged. The relevant doc can be found [here](https://docs.harvesterhci.io/v1.4/rancher/cloud-provider#prerequisites).

Close as resolved.

**Closed as completed by starbops** 2024-09-04 03:44 UTC
Labels: kind/bug, severity/1, area/embedded-rancher, area/os, area/rke2, area/load-balancer, reproduce/always, not-require/release-note
