### ISSUE TITLE
[BUG] prevent users from creating RWX PVCs on the guest k8s cluster

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2151] opened 2022-04-14 09:17 UTC
**Describe the bug**
Currently, users are able to create an RWX PVCs in the guest k8s cluster using the Harvester node driver, however only RWO should be supported(future enhancement of https://github.com/harvester/harvester/issues/1992) in the current stage.

**To Reproduce**
1. Create a Harvester cluster and import it into the Rancher dashboard.
2. Spin up the guest k8s cluster using the Harvester node driver(e.g. with RKE2)
3. Create the PVCs with RWX mode of the `harvester` storageClass.
4. However LH's RWX with block device is just for live migration/data synchronization, users/pods can't use it as a real RWX (refer to https://github.com/longhorn/longhorn/blob/master/enhancements/20201220-rwx-volume-support.md).

**Expected behavior**
Should reject to create RWX PVCs using the `harvester` storageClass of the Harvester CSI driver.

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by yasker** [comment] 2022-04-14 15:11
Bump up the priority since it misleads and breaks all the users with RWX workload in the guest cluster.

**Comment by PhanLe1010** [comment] 2022-04-14 18:19
We can:
1. Remove the `VolumeCapability_AccessMode_MULTI_NODE_MULTI_WRITER` [here](https://github.com/harvester/harvester-csi-driver/blob/5700629c292bf005e3c5042553ee1fedc654e5e6/pkg/csi/controller_server.go#L54)
2. Put a check validation [here](https://github.com/harvester/harvester-csi-driver/blob/5700629c292bf005e3c5042553ee1fedc654e5e6/pkg/csi/controller_server.go#L79) to reject the PVC with  RWX access mode. See example on Longhorn CSI [here](https://github.com/longhorn/longhorn-manager/blob/1c261cab59443013b398c4a99889661cfe2e6fe5/csi/controller_server.go#L1010-L1036)

**Comment by PhanLe1010** [comment] 2022-04-14 18:22
Btw, @gitlawr  I am not sure why we hard-coded the access mode to RWX when we create the PVC in the host cluster [here](https://github.com/harvester/harvester-csi-driver/blob/5700629c292bf005e3c5042553ee1fedc654e5e6/pkg/csi/controller_server.go#L94)? 

Also, the [volumeParameters](https://github.com/harvester/harvester-csi-driver/blob/5700629c292bf005e3c5042553ee1fedc654e5e6/pkg/csi/controller_server.go#L75) info are not passed to the host CSI, is it intended?

**Comment by guangbochen** [comment] 2022-04-15 03:15
Hi @PhanLe1010, Harvester VMs use block device volumes with RWX mode so they can support VM live migration. Those PVCs created by the CSI driver are consumed by pods running within these VMs via the Harvester csi-driver plugin(with passthrough), we are considering supporting RWX with filesystem mode in a separate issue at https://github.com/harvester/harvester/issues/1992 .
In regards to not passing [volumeParameters](https://github.com/harvester/harvester-csi-driver/blob/5700629c292bf005e3c5042553ee1fedc654e5e6/pkg/csi/controller_server.go#L75), most likely is for the same reasons as above, and thanks for the above detailed investigation.

**Comment by PhanLe1010** [comment] 2022-04-15 05:28
Thanks @guangbochen for the explanation!

> pods running within these VMs via the Harvester csi-driver plugin(with passthrough)

It is an interesting design. Do we have a design doc for this feature? I would like to learn more about what does `passthrough` mean

**Comment by guangbochen** [comment] 2022-04-15 06:45
**Validation steps:**
1. Spin up the guest k8s cluster via the Harvester node driver(e.g RKE2 with k8s v1.22.7+rke2r2) and the cloud provider is set to `Harvester`.
2. once the cluster is up and running path the embedded csi driver image with custom build e.g. `docker.io/rancher/harvester-csi-driver:v0.1.3`
3. Creating PVCs on the `Storage -> PersistentVolumeClaims` page:
    - PVC with the mode of  `Read-Write-Many` or `Read-Only-Many` will be stuck on pending and the event will contain an appropriate error message.
    - PVC with the mode of `Read-Write-Only` will works as expected (the same rules apply to the deployment creation)
<img width="627" alt="image" src="https://user-images.githubusercontent.com/4569037/163526441-f37c372e-74b9-4487-b63d-21e3a9b551c6.png">

Notes: since the validation steps have skipped the RKE2/KDM release so we can just move it back to `ice-box` once the validation passes, and close it either after RKE2/KDM release with a proper regression test, thanks.

**Comment by TachunLin** [comment] 2022-04-15 09:44
Verified **fixed** on `master-03ee6213-head` (04/15) with Rancher `v2.6.4`. Close this issue.

### Result
After replacing the harvester csi driver image to `docker.io/rancher/harvester-csi-driver:v0.1.3`

1. Create PVC with `Read-Write-Many` and `Read-Only-Many` would stuck in `pending` status
2. Create PVC with `Read-Write-Only` can work and bound as expected
![image](https://user-images.githubusercontent.com/29251855/163552863-ccd8ca08-4b8e-4e23-b9e1-21cd5a60e4e3.png)

3. PVC with `Read-Write-Many` have appropriate error message on events
  ![image](https://user-images.githubusercontent.com/29251855/163551581-ce3b77c7-d05b-4d30-b91e-8817c138c6ec.png)
4. PVC with `Read-Write-Only` have appropriate error message on events
  ![image](https://user-images.githubusercontent.com/29251855/163552507-b2eb62bf-47c4-4a2c-a34f-29612e99c7de.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: v1.0.1
* Rancher version: v2.6.4
* RKE2 version: v1.22.7+rke2r2
* OS version: ubuntu focal 

### Verify Steps
1. Spin up the guest k8s cluster via the Harvester node driver (RKE2 v1.22.7+rke2r2)
2. Access RKE2 cluster in cluster management
3. Execute the kubectl shell
4. Run command `kubectl edit ds -n kube-system harvester-csi-driver`
  ![image](https://user-images.githubusercontent.com/29251855/163550144-7b5cff7f-7b0e-4ca3-a66b-c1ffc626331f.png)
5. Change the image value to  `docker.io/rancher/harvester-csi-driver:v0.1.3`
  ![image](https://user-images.githubusercontent.com/29251855/163550427-534c2db9-8412-4cf4-84ab-a34040331b0f.png)
6. Open Storage -> PersistentVolumesClaims 
7. Create a new PVC, set storage to `Harvester` and `Many-Nodes-Read-Write` 
  ![image](https://user-images.githubusercontent.com/29251855/163555220-cbea2758-b3d2-4d23-badd-9ee6afec0cb6.png)
  ![image](https://user-images.githubusercontent.com/29251855/163555317-fffa372f-f205-4ac3-a6fe-35e308126b18.png)

8. Create a new PVC, set storage to `Harvester` and `Many-Nodes-Read-Only` 
  ![image](https://user-images.githubusercontent.com/29251855/163555503-8caf87c2-cdc0-401d-9852-ab0783cee442.png)
  ![image](https://user-images.githubusercontent.com/29251855/163555597-f850904a-3dc7-4880-a02c-e85670de6dcf.png)

9. Create a new PVC, set storage to `Harvester` and `Single-Nodes-Read-Write` 
  ![image](https://user-images.githubusercontent.com/29251855/163555740-7502dd08-1752-4780-a534-e560b0f7fd59.png)

10. Check the status and recent events of PVC `Read-Write-Many`
11. Check the status and recent events of PVC `Read-Only-Many`
12. Check the status and recent events of PVC `Read-Write-Only`

**Closed as completed by TachunLin** 2022-04-15 09:44 UTC
Labels: kind/bug, priority/0, area/guest-cluster-csi-driver

**Comment by TachunLin** [comment] 2022-04-24 14:29
Verified **`fixed`** for KDM release regression test with the following configuration
* Rancher: v2.6.4
* RKE2 version: v1.23.6-rc3+rke2r1
* CSI driver version: 0.1.1100 

* Create `Many Nodes Ready Only` PVC will `pending` with appropriate error message on events
![image](https://user-images.githubusercontent.com/29251855/164980412-696214b0-864b-4b5e-adad-a64ae4092f15.png)

* Create `Many Nodes Ready Write` PVC will `pending` with appropriate error message on events
![image](https://user-images.githubusercontent.com/29251855/164981260-8b99415b-1d2b-4d5e-a82d-aa6ae9338a96.png)

* Create `Single Node Ready Write` PVC will `running` correctly
![image](https://user-images.githubusercontent.com/29251855/164981341-216c7442-ea93-4f82-a72e-db1e3a0cb64e.png)
