### ISSUE TITLE
[BUG] UI - losing graph on dashboard after 24h uptime... 

### ISSUE THREAD

**Issue by marcuspocus1** [harvester/harvester#1522] opened 2021-11-08 21:40 UTC
**Describe the bug**
After approx 24h of uptime, grafana is not showing anything... 
Graph are coming back on the dashboard after a complete reboot of the cluster... 

**To Reproduce**
build up a cluster of 4 nodes, spin up 1 or 2 VM, wait 24h...

**Expected behavior**
Graph should be available all the time... 

**Support bundle**
... included... 

**Environment:**
 - Harvester ISO version: v0.3.0-rc2
 - Underlying Infrastructure: Dell PowerEdge R740xd

**Additional context**
[supportbundle_b89bc142-c79a-4c6c-95a6-27838d57853b_2021-11-08T21-34-50Z.zip](https://github.com/harvester/harvester/files/7500289/supportbundle_b89bc142-c79a-4c6c-95a6-27838d57853b_2021-11-08T21-34-50Z.zip)
![Screen Shot 2021-11-08 at 4 35 38 PM](https://user-images.githubusercontent.com/79535752/140822432-7e50fdf2-8264-4bc5-96d1-a930a5b8d9a7.png)

**Comment by guangbochen** [comment] 2021-11-19 06:12
close as a duplicate of https://github.com/harvester/harvester/issues/1531

**Closed as completed by guangbochen** 2021-11-19 06:12 UTC
Labels: kind/bug
