### ISSUE TITLE
[BUG]  can't shut down virtual machine using poweroff

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#872] opened 2021-05-18 04:53 UTC
**Describe the bug**

Use the poweroff command to shut down the VM, the VM will restart and the VM status in the VM list will not change
**To Reproduce**
1. Create a VM instance using ubuntu-18.04-server-cloudimg-amd64.img
2. Log in to the VM and use the command poweroff to shut down the VM

**Expected behavior**

1. the virtual machine can be shut down and not restarted
2. The status of the VM in the virtual machine list becomes off

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment] 2021-09-27 15:08
duplicate of https://github.com/harvester/harvester/issues/574

**Closed as completed by guangbochen** 2021-09-27 15:08 UTC
Labels: kind/bug
