### ISSUE TITLE
[BUG] standard virtual machine templates missing

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#968] opened 2021-06-22 06:10 UTC
**Describe the bug**
Out-of-the-box virtual machines templates are missing from the master master ISO.

**To Reproduce**
1. install Harvester from https://releases.rancher.com/harvester/master/harvester-amd64.iso
2. login to the UI
3. click on Advanced -> Templates and notice that no templates are found. There used to be 3 out-of-the-box templates.

**Expected behavior**
Expecting 3 out-of-the-box virtual machine templates as v0.2.0.

**Support bundle**

**Environment:**
 - Harvester ISO version: master (https://releases.rancher.com/harvester/master/harvester-amd64.iso)

**Additional context**
![harvester_missing_templates](https://user-images.githubusercontent.com/1808417/122872820-d5b9cf00-d2e5-11eb-8467-b63b6414d507.png)

**Comment by weihanglo** [comment] 2021-06-22 10:24
You can switch to a namespace other than`Only User Namespaces` and they will show up again.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/14314532/122908461-ba52d080-d386-11eb-9134-5970c375bb28.png">

**Comment by ldevulder** [comment] 2021-08-18 14:22
Tested with latest `master-head` build and by default the templates are visible (`All Namespaces` is selected by default).

But I have a question before closing this issue: the referenced fix [harvester/harvester-ui#489](https://github.com/harvester/harvester-ui/pull/489) seems to be about issues #782 and #966 and not this one... Is it normal? Or what is the correct fix if not?

**Comment by WuJun2016** [comment] 2021-08-23 02:38
@ldevulder    Sorry, this reference address https://github.com/harvester/harvester-ui/pull/489 is wrong。  but this problem is not a bug, because the user chose the User namespace, and our default template is placed in the harvester-publice namespace, it is normal that you can’t see the default template when you use it.

**Comment by ldevulder** [comment] 2021-08-23 08:24
@WuJun2016 thx. But I didn't say that it was a bug to see the templates ;-) it was just to say that the issue was fixed. My question was only for the referenced fix. I should have been more clear on my comment, sorry ;-)

**Comment by ldevulder** [comment] 2021-08-23 08:24
So the issue is resolved, can be closed.

**Closed as completed by ldevulder** 2021-08-23 08:24 UTC
Labels: kind/bug, area/ui, area/control-plane
