### ISSUE TITLE
[BUG] Harvester node driver deployed cluster won't connect after cluster reboot

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1846] opened 2022-01-19 14:49 UTC
**Describe the bug**
An RKE2 cluster won't reconnect to Rancher if the Harvester cluster it is on was fully restarted.

**To Reproduce**
1. Create an RKE2 cluster using Harvester as the target.
2. Power off all Harvester Nodes
3. Power On all Harvester Nodes
4. Rancher will show that cluster with: Cluster agent is not connected

**Expected behavior**
Rancher RKE2 downstream cluster should connect and become manageable by Rancher again.

**Support bundle**
https://drive.google.com/file/d/16jySe879kKtedEwaSjmsqbg4pm4ycFlh/view?usp=sharing

**Environment:**
 - Harvester ISO version: 1.0
 - Underlying Infrastructure: R620

**Additional context**
```
Unavailable | ubuntu-large | rke2 | v1.22.4+rke2r2 | 0/6 cores | 0 B/47 GiB | 2/330
-- | -- | -- | -- | -- | -- | --
Cluster agent is not connected
```

```
root@ubuntu-large-focal-c59fd150-n9qj6:~# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes
NAME                                STATUS   ROLES                              AGE   VERSION
ubuntu-large-focal-c59fd150-brsv7   Ready    control-plane,etcd,master,worker   18h   v1.22.4+rke2r2
ubuntu-large-focal-c59fd150-dct47   Ready    control-plane,etcd,master,worker   18h   v1.22.4+rke2r2
ubuntu-large-focal-c59fd150-n9qj6   Ready    control-plane,etcd,master,worker   18h   v1.22.4+rke2r2
root@ubuntu-large-focal-c59fd150-n9qj6:~# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get all -n kube-system
NAME                                                            READY   STATUS      RESTARTS      AGE
pod/etcd-ubuntu-large-focal-c59fd150-brsv7                      1/1     Running     1 (28m ago)   18h
pod/etcd-ubuntu-large-focal-c59fd150-dct47                      1/1     Running     1 (27m ago)   18h
pod/etcd-ubuntu-large-focal-c59fd150-n9qj6                      1/1     Running     1 (28m ago)   18h
pod/harvester-cloud-provider-5d5cdf686c-6bp6h                   0/1     Unknown     0             18h
pod/harvester-cloud-provider-5d5cdf686c-ssvzc                   0/1     Unknown     0             18h
pod/harvester-csi-driver-5ld62                                  0/2     Unknown     0             18h
pod/harvester-csi-driver-786vv                                  0/2     Unknown     0             18h
pod/harvester-csi-driver-controllers-8ff47d84b-dnfqv            0/3     Unknown     0             18h
pod/harvester-csi-driver-controllers-8ff47d84b-gdc8l            0/3     Unknown     0             18h
pod/harvester-csi-driver-controllers-8ff47d84b-w9r87            0/3     Unknown     0             18h
pod/harvester-csi-driver-tzpsx                                  0/2     Unknown     0             18h
pod/helm-install-harvester-cloud-provider--1-8jjvf              0/1     Completed   0             18h
pod/helm-install-harvester-csi-driver--1-7qnk4                  0/1     Completed   0             18h
pod/helm-install-rke2-calico--1-lmfxj                           0/1     Completed   2             18h
pod/helm-install-rke2-calico-crd--1-n6xl6                       0/1     Completed   0             18h
pod/helm-install-rke2-coredns--1-ck9db                          0/1     Completed   0             18h
pod/helm-install-rke2-ingress-nginx--1-xkm9d                    0/1     Completed   0             18h
pod/helm-install-rke2-metrics-server--1-qwlbl                   0/1     Completed   0             18h
pod/kube-apiserver-ubuntu-large-focal-c59fd150-brsv7            1/1     Running     1 (28m ago)   18h
pod/kube-apiserver-ubuntu-large-focal-c59fd150-dct47            1/1     Running     1 (27m ago)   18h
pod/kube-apiserver-ubuntu-large-focal-c59fd150-n9qj6            1/1     Running     1 (28m ago)   18h
pod/kube-controller-manager-ubuntu-large-focal-c59fd150-brsv7   1/1     Running     2 (28m ago)   18h
pod/kube-controller-manager-ubuntu-large-focal-c59fd150-dct47   1/1     Running     2 (27m ago)   18h
pod/kube-controller-manager-ubuntu-large-focal-c59fd150-n9qj6   1/1     Running     2 (28m ago)   18h
pod/kube-proxy-ubuntu-large-focal-c59fd150-brsv7                1/1     Running     1 (28m ago)   18h
pod/kube-proxy-ubuntu-large-focal-c59fd150-dct47                1/1     Running     1 (27m ago)   18h
pod/kube-proxy-ubuntu-large-focal-c59fd150-n9qj6                1/1     Running     1 (28m ago)   18h
pod/kube-scheduler-ubuntu-large-focal-c59fd150-brsv7            1/1     Running     1 (28m ago)   18h
pod/kube-scheduler-ubuntu-large-focal-c59fd150-dct47            1/1     Running     1 (27m ago)   18h
pod/kube-scheduler-ubuntu-large-focal-c59fd150-n9qj6            1/1     Running     1 (28m ago)   18h
pod/rke2-coredns-rke2-coredns-5679c85bbb-ks885                  0/1     Unknown     0             18h
pod/rke2-coredns-rke2-coredns-5679c85bbb-qw5jm                  0/1     Unknown     0             18h
pod/rke2-coredns-rke2-coredns-autoscaler-6889866896-fnjcn       0/1     Unknown     0             18h
pod/rke2-ingress-nginx-controller-ffbbf                         1/1     Running     1 (28m ago)   18h
pod/rke2-ingress-nginx-controller-krqvk                         1/1     Running     1 (28m ago)   18h
pod/rke2-ingress-nginx-controller-q7xqk                         1/1     Running     1 (27m ago)   18h
pod/rke2-metrics-server-8574659c85-db5d2                        0/1     Unknown     0             18h

NAME                                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
service/rke2-coredns-rke2-coredns                 ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP   18h
service/rke2-ingress-nginx-controller-admission   ClusterIP   10.43.100.82    <none>        443/TCP         18h
service/rke2-metrics-server                       ClusterIP   10.43.156.118   <none>        443/TCP         18h

NAME                                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/harvester-csi-driver            3         3         0       3            0           <none>                   18h
daemonset.apps/rke2-ingress-nginx-controller   3         3         3       3            3           kubernetes.io/os=linux   18h

NAME                                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/harvester-cloud-provider               0/2     2            0           18h
deployment.apps/harvester-csi-driver-controllers       0/3     3            0           18h
deployment.apps/rke2-coredns-rke2-coredns              0/2     2            0           18h
deployment.apps/rke2-coredns-rke2-coredns-autoscaler   0/1     1            0           18h
deployment.apps/rke2-metrics-server                    0/1     1            0           18h

NAME                                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/harvester-cloud-provider-5d5cdf686c               2         2         0       18h
replicaset.apps/harvester-csi-driver-controllers-8ff47d84b        3         3         0       18h
replicaset.apps/rke2-coredns-rke2-coredns-5679c85bbb              2         2         0       18h
replicaset.apps/rke2-coredns-rke2-coredns-autoscaler-6889866896   1         1         0       18h
replicaset.apps/rke2-metrics-server-8574659c85                    1         1         0       18h

NAME                                              COMPLETIONS   DURATION   AGE
job.batch/helm-install-harvester-cloud-provider   1/1           37s        18h
job.batch/helm-install-harvester-csi-driver       1/1           38s        18h
job.batch/helm-install-rke2-calico                1/1           56s        18h
job.batch/helm-install-rke2-calico-crd            1/1           40s        18h
job.batch/helm-install-rke2-coredns               1/1           38s        18h
job.batch/helm-install-rke2-ingress-nginx         1/1           2m41s      18h
job.batch/helm-install-rke2-metrics-server        1/1           2m5s       18h
```

```
root@ubuntu-large-focal-c59fd150-n9qj6:~# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get all -n cattle-system
NAME                                             READY   STATUS        RESTARTS   AGE
pod/cattle-cluster-agent-6975cb7b7f-hs5pq        0/1     Unknown       0          18h
pod/cattle-cluster-agent-6975cb7b7f-vk6n4        0/1     Unknown       0          18h
pod/cattle-cluster-agent-6975cb7b7f-x4ks7        0/1     Terminating   0          18h
pod/cattle-cluster-agent-75568b65b-s7nmj         0/1     Terminating   0          18h
pod/cattle-cluster-agent-75568b65b-x5dq5         0/1     Terminating   0          18h
pod/system-upgrade-controller-5b6457d644-rznd6   0/1     Unknown       0          18h

NAME                           TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
service/cattle-cluster-agent   ClusterIP   10.43.91.68   <none>        80/TCP,443/TCP   18h

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cattle-cluster-agent        0/2     2            0           18h
deployment.apps/system-upgrade-controller   0/1     1            0           18h

NAME                                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/cattle-cluster-agent-6975cb7b7f        2         2         0       18h
replicaset.apps/cattle-cluster-agent-75568b65b         0         0         0       18h
replicaset.apps/system-upgrade-controller-5b6457d644   1         1         0       18h
```

**Comment by dweomer** [comment] 2022-02-07 18:06
@abonillabeeche can you specify which version of Rancher? My guess is 2.6.3

**Comment by dweomer** [comment] 2022-02-07 21:38
@abonillabeeche:

- RKE2 1.22.x support is marked as experimental. Is the use of such here intentional?
- This issue does not reproduce for me with RKE2 1.21.8+rke2r2 on Harvester 1.0.0 using a Rancher 2.6.3-patch1 MCM.
- This issue does not reproduce for me with RKE2 **_1.22.5+rke2r2_** on Harvester 1.0.0 using a Rancher 2.6.3-patch1 MCM.

**Comment by dweomer** [comment] 2022-02-22 16:51
- This issue does not reproduce for me with RKE2 1.21.9+rke2r1 (3 server nodes) on Harvester 1.0.0 (3 server hosts) using Rancher 2.6.3-patch1.

**Comment by lanfon72** [comment] 2022-03-04 12:26
Moved to _**Implement**_, same problem as https://github.com/harvester/harvester/issues/1770#issuecomment-1049669061 and following comments.

**Comment by guangbochen** [comment] 2022-04-19 10:20
Move the issue forward to `ready-for-testing` as I can't reproduce it via Rancher v2.6.4 + Harvester v1.0.1 combination, the issue https://github.com/harvester/harvester/issues/1770#issuecomment-1049669061 is already resolved, thanks.

**Comment by lanfon72** [comment] 2022-04-20 14:46
closed as this issue can't be reproduced on Harvester **v1.0.1-master-b20a3b47-head** with Rancher **v2.6.4**.
(RKE2 3 nodes with opensuse, Harverster single node)

**Closed as completed by lanfon72** 2022-04-20 14:46 UTC
Labels: kind/bug, area/control-plane, priority/1
