### ISSUE TITLE
[FEATURE] Support shared storage for VM workloads

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2126] opened 2022-04-07 13:10 UTC
**Is your feature request related to a problem? Please describe.**

Today, Harvester provides shared storage to Kubernetes workloads (via read-write-many CSI volume) but not to VM workloads. There are use cases that require shared storage for applications deployed in VMs.

**Describe the solution you'd like**

Users are able to provision read-write-many volumes in Harvester.
When provisioning VMs the users can select the read-write-many volume as additional volume. The same volume can be attached to multiple VMs using the `shareable` option from Kubevirt.

**Comment by Lucostus** [comment] 2022-04-09 14:27
Would this solve the problem of double Longhorning a k3s cluster, or is there already a solution?

**Comment by yasker** [comment] 2022-06-03 20:43
Duplicate of https://github.com/harvester/harvester/issues/2272. 

@Lucostus You can install Harvester CSI plugin in K3s, which will provide baremetal Longhorn storage to the workloads in the k3s cluster.

**Closed as completed by yasker** 2022-06-03 20:43 UTC
Labels: kind/enhancement

**Comment by kfehrenbach** [comment] 2024-07-18 05:52
I don't think, that this is a duplicate... #2272 is talking about a shared filesystem... The request here ist so make a block device shareable. 
We need this as well as there are some Applications, that are organizing the write itself and therefore need a shared block device. Using NFS or CephFS is very slow compared to a longhorn or ceph block device!

KubeVirt has exactly this feature by making a disk shareable using the "shareable" flag. You can already pass this option in the yaml of the virtualMachine during creation and the csi for longhorn respects the option setting the volume to "share: true", but the admission controller of harvester does not accept a second vm using this volume...

**Comment by kfehrenbach** [comment] 2024-07-18 05:58
Opened new Feature Request #6191
