### ISSUE TITLE
[BUG] Upgrade stuck due to the unremove longhorn service

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#6664] opened 2024-09-26 16:41 UTC
**Describe the bug**
We are testing the upgrade from v1.3.2 to v1.4 (master branch with rancher upgrade).
Found that the upgrade is stuck with the below bundle error:
```
fleet-local   mcc-harvester                                 0/1                       Modified(1) [Cluster fleet-local/local]; service.v1 longhorn-system/longhorn-engine-manager extra; service.v1 longhorn-system/longhorn-replica-manager extra
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-hvst-upgrade-rzcdn-upgradelog-operator    0/1                       ErrApplied(1) [Cluster fleet-local/local: execution error at (rancher-logging/templates/validate-install-crd.yaml:24:7): Required CRDs are missing. Please install the corresponding CRD chart before installing this chart.]
```

After @FrankYang0529 investigated, we found the issue was caused by unremoved services `longhorn-engine-manager` and `longhorn-replica-manager`.
Longhorn has the corresponding mechanism to delete it. (REF: https://github.com/longhorn/longhorn-manager/blob/8bc7575fc3be2b72c72ba4899f465762a57c55ea/upgrade/v16xto170/upgrade.go#L238-L251)

But somehow, these services have not been deleted. I checked the longhorn-manager log and did not find any error like https://github.com/longhorn/longhorn-manager/blob/8bc7575fc3be2b72c72ba4899f465762a57c55ea/upgrade/v16xto170/upgrade.go#L240 

**To Reproduce**
1. create three nodes 1.3.2 cluster
2. create the downstream cluster
3. upgrade to master-head (master-head already included the rancher upgrade)

**Expected behavior**
upgrade should be smooth

**Support bundle**
None

**Environment**
 - Harvester ISO version: 1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
We will try to reproduce this situation. Seems it does not always reproduce.
Also, the workaround is manually to delete these two services, `longhorn-engine-manager` and `longhorn-replica-manager`

**Comment by PhanLe1010** [comment] 2024-09-27 02:22
It is a bit weird that why the service is still in Harvester. I check the the helm chart in master-head Harvester and see that the services are already removed https://github.com/harvester/harvester/blob/master/deploy/charts/harvester/dependency_charts/longhorn/templates/services.yaml

**Comment by Vicente-Cheng** [comment] 2024-09-27 02:28
> It is a bit weird that why the service is still in Harvester. I check the the helm chart in master-head Harvester and see that the services are already removed https://github.com/harvester/harvester/blob/master/deploy/charts/harvester/dependency_charts/longhorn/templates/services.yaml

Thanks @PhanLe1010,
This is the upgrade scenario, which means we upgrade from v1.6.2 to v1.7.1.
These two services were installed on v1.6.2 but were not deleted when upgrading to v1.7.1.
(It should be deleted like https://github.com/longhorn/longhorn-manager/blob/8bc7575fc3be2b72c72ba4899f465762a57c55ea/upgrade/v16xto170/upgrade.go#L238-L251)

We are trying to reproduce/investigate this case.

**Comment by PhanLe1010** [comment] 2024-09-27 04:43
Hi @Vicente-Cheng 

Without the deletion login inside [longhorn-manager](https://github.com/longhorn/longhorn-manager/blob/8bc7575fc3be2b72c72ba4899f465762a57c55ea/upgrade/v16xto170/upgrade.go#L238-L251), I think helm should still delete the services because:
1. Helm chart 1.6.2 have them
2. Helm chart  1.7.1 don't have it ---> they should be removed by Helm

Or Harvester is not deploying Longhorn using Helm chart?

**Comment by FrankYang0529** [comment] 2024-09-27 05:19
> Or Harvester is not deploying Longhorn using Helm chart?

We deploy it by ManagedChart which is using fleet and helm.

**Comment by bk201** [comment] 2024-10-24 09:55
Caused by https://github.com/harvester/harvester/issues/6851
The chart is rollback.

**Comment by innobead** [comment] 2024-10-28 09:35
It seems a side effect of #6851 instead of a real issue. Suggest closing and focusing on the source issue instead.

**Comment by bk201** [comment] 2024-11-01 05:51
The issue is caused by #6851 and should be fixed with the issue together.

**Closed as completed by bk201** 2024-11-01 05:51 UTC
Labels: kind/bug, priority/2, require/investigate, require/reproduce, require/severity
