### ISSUE TITLE
[BUG] Bulk restore multiple vm backups to replace existing vm would cause all vms stuck in Restoring 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5028] opened 2024-01-25 10:15 UTC
**Describe the bug**

When we restore five vm backups to replace the existing vms in `stopped state` in a short time. 
All the vms are stuck in `Restoring` state and can't proceed anymore.  
![image](https://github.com/harvester/harvester/assets/29251855/cd8a4356-fe79-4046-85de-734670831911)

https://github.com/harvester/harvester/assets/29251855/1e461380-0dcd-4d0f-b45f-2dcdd717ce03

**To Reproduce**
1. Create 5 vms, each have 30Gi opensuse image, 20Gi volume-1 and 20Gi volume-2 extra disks
2. Create vm backups for all the vms
3. Stopped all 5 vms
4. Restore the backup of 1st vm to replace the existing one (delete volume)
5. Restore the backup of 2nd vm to replace the existing one (retain volume)
6. Restore the backup of 3rd vm to replace the existing one (delete volume)
7. Restore the backup of 4th vm to replace the existing one (delete volume)
8. Restore the backup of 5th vm to create a new one

**Expected behavior**

Bulk restore multiple vm backups should all complete without stuck in restoring

**Support bundle**

[supportbundle_fa20098d-1e06-4783-b38c-66bdd7dd2c34_2024-01-08T03-53-34Z.zip](https://github.com/harvester/harvester/files/14050247/supportbundle_fa20098d-1e06-4783-b38c-66bdd7dd2c34_2024-01-08T03-53-34Z.zip)

**Environment**
 - Harvester ISO version: `master-6ca6acfd-head` (24/01/23)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes Harvester on baremetal machines

**Additional Context**
Found during verification of issue #4102

**Comment by WebberHuang1118** [comment] 2024-01-26 02:24
Hi @TachunLin,
The attached SB seems not completed, I couldn't open it with SB simulator, thanks.

**Comment by TachunLin** [comment] 2024-01-26 03:42
Just regenerate the support bundle on target Harvester cluster. 
And build the support-bundle-kit to run the SB simulator to test the downloaded support bundle 

[supportbundle_d9688221-8d20-4e81-9e77-b817adb64637_2024-01-26T02-46-52Z.zip](https://github.com/harvester/harvester/files/14060037/supportbundle_d9688221-8d20-4e81-9e77-b817adb64637_2024-01-26T02-46-52Z.zip)


I also encounter the SB loaded failure.

```
I0126 11:25:58.454683   25207 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
I0126 11:25:58.461527   25207 storage_scheduling.go:93] created PriorityClass system-node-critical with value 2000001000
I0126 11:25:58.464809   25207 storage_scheduling.go:93] created PriorityClass system-cluster-critical with value 2000000000
I0126 11:25:58.464821   25207 storage_scheduling.go:109] all system priority classes are created successfully or already exist.
I0126 11:25:58.487823   25207 alloc.go:329] "allocated clusterIPs" service="default/kubernetes" clusterIPs=map[IPv4:10.53.0.1]
W0126 11:25:58.494967   25207 lease.go:233] Resetting endpoints for master service "kubernetes" to [192.168.1.112]
I0126 11:25:58.496018   25207 controller.go:611] quota admission added evaluator for: endpoints
I0126 11:25:58.499254   25207 controller.go:611] quota admission added evaluator for: endpointslices.discovery.k8s.io
FATA[0038] Error loading cluster scoped objects error looking up GVR no matches for kind "FlowSchema" in version "flowcontrol.apiserver.k8s.io/v1beta3" for object &{map[apiVersion:flowcontrol.apiserver.k8s.io/v1beta3 kind:FlowSchema metadata:map[annotations:map[apf.kubernetes.io/autoupdate-spec:true sim.harvesterhci.io/creationTimestamp:2024-01-24T04:27:59Z] creationTimestamp:2024-01-24T04:27:59Z generation:1 managedFields:[map[apiVersion:flowcontrol.apiserver.k8s.io/v1beta3 fieldsType:FieldsV1 fieldsV1:map[f:status:map[f:conditions:map[k:{"type":"Dangling"}:map[.:map[] f:lastTransitionTime:map[] f:message:map[] f:reason:map[] f:status:map[] f:type:map[]]]]] manager:api-priority-and-fairness-config-consumer-v1 operation:Apply subresource:status time:2024-01-24T04:27:59Z] map[apiVersion:flowcontrol.apiserver.k8s.io/v1beta3 fieldsType:FieldsV1 fieldsV1:map[f:metadata:map[f:annotations:map[.:map[] f:apf.kubernetes.io/autoupdate-spec:map[]]] f:spec:map[f:distinguisherMethod:map[.:map[] f:type:map[]] f:matchingPrecedence:map[] f:priorityLevelConfiguration:map[f:name:map[]] f:rules:map[]]] manager:api-priority-and-fairness-config-producer-v1 operation:Update time:2024-01-24T04:27:59Z]] name:catch-all uid:5d320705-5cbc-4cc7-9dbf-3aa95205beb0] spec:map[distinguisherMethod:map[type:ByUser] matchingPrecedence:10000 priorityLevelConfiguration:map[name:catch-all] rules:[map[nonResourceRules:[map[nonResourceURLs:[*] verbs:[*]]] resourceRules:[map[apiGroups:[*] clusterScope:true namespaces:[*] resources:[*] verbs:[*]]] subjects:[map[group:map[name:system:unauthenticated] kind:Group] map[group:map[name:system:authenticated] kind:Group]]]]] status:map[conditions:[map[lastTransitionTime:2024-01-24T04:27:59Z message:This FlowSchema references the PriorityLevelConfiguration object named "catch-all" and it exists reason:Found status:False type:Dangling]]]]}
```

It would probably related to insufficient disk space on the Harvester node.

**Comment by WebberHuang1118** [comment] 2024-01-26 03:46
After a quick check with @TachunLin, multiple volumes failed to schedule replicas due to `insufficient storage` in the env. This could be the main reason for restoring stuck

**Comment by TachunLin** [comment] 2024-01-26 03:50
After discussed with @WebberHuang1118  on the existing environment. 

On the Longhorn dashboard, all volumes state changed to `Detached`

![image](https://github.com/harvester/harvester/assets/29251855/0e865fe6-58c2-40aa-9911-24666f28a2e5)

Check the `volumes` state in Harvester, lots of disk shows `Not ready`
![image](https://github.com/harvester/harvester/assets/29251855/7198371b-faf5-4cbb-844c-c43df2784ba5)

The warning indicate `insufficient storage`
![image](https://github.com/harvester/harvester/assets/29251855/c7b1a076-5e87-47b1-91e3-c6e26f47bfb4)

We can also find the volumes of the `Restoring` vm have similar state and message
![image](https://github.com/harvester/harvester/assets/29251855/3739d9c9-4f5e-4e37-923a-a065a3853fdd)

**Comment by WebberHuang1118** [comment] 2024-01-26 06:33
Checked all restoring VM's volumes have the condition `insufficient storage` in @TachunLin's env , we can confirm by Harvester GUI or from the PV objects, e.q.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    longhorn.io/volume-scheduling-error: insufficient storage
  name: pvc-f3fb0dbc-85be-40e4-b5cd-ccbf239d8c7b
spec:
  ...
status:
  phase: Bound
```
We may consider improving the VM restore status which is reported to users, instead of only `restoring` and `complete`, Harvester UI could provide the current restoring phase, e.q. `volume creating`, `volume creation failure with insufficient storage`, `VM creating`, `VM running` and so on

Besides, reproduce [the same steps mentioned](https://github.com/harvester/harvester/issues/5028#issue-2100037551) by @TachunLin, the VM restore could complete, just make sure the LH storage space is sufficient (the allocatable size should be greater than double of source volume's summation).

**Comment by bk201** [comment] 2024-01-26 08:06
The not ready issue could be https://github.com/harvester/harvester/issues/5020. @TachunLin is it OK to close the issue?

**Comment by TachunLin** [comment] 2024-01-26 08:10
I think we can close this issue as it would be related to the environment and user should consider the disk usage operation.

**Closed as completed** 2024-01-26 08:11 UTC
Labels: kind/bug, require/investigate, severity/2, reproduce/rare, area/vm-lifecycle
