### ISSUE TITLE
[BUG] harvester is showing embedded rancher version

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1099] opened 2021-08-17 21:57 UTC
**Describe the bug**

The version at the bottom of the harvester window is showing the embedded rancher version
**To Reproduce**
1. Log into harvester
2. Check header

**Expected behavior**

It should show the harvester version
**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
You can't change this in settings anymore.
![Greenshot 2021-08-17 13 25 49](https://user-images.githubusercontent.com/83787952/129805986-77296cc7-fd73-4ec2-90fc-0f13a1026699.png)
![Greenshot 2021-08-17 14 51 36](https://user-images.githubusercontent.com/83787952/129805988-296560c4-574d-4dd7-a43f-bb1ec71a5062.png)

**Comment by guangbochen** [comment] 2021-08-18 02:44
duplicate of https://github.com/harvester/harvester/issues/1094

**Closed as completed by guangbochen** 2021-08-18 02:44 UTC
Labels: kind/bug, area/ui
