### ISSUE TITLE
[BUG] Kubectl Error - Waited for ... due to client-side throttling, not priority and fairness, request:..

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1617] opened 2021-12-02 12:58 UTC
**Environmental Info:**
Node(s) CPU architecture, OS, and Version: Dell PowerEdge XR11 (32Core, 128GB RAM, 2 x 1.5TB SSD)

Cluster Configuration: I was able to install only first node and Kubectl was showing those errors

**Describe the bug:**

UI is not responsive and kubectl gets error messages
 see Error messages examples:
![image](https://user-images.githubusercontent.com/51060150/141523629-3a78363e-f95b-4ac0-9e15-952aec32fef8.png)

**Steps To Reproduce:**

- Installed RKE2: harvester-v0.3.0-amd64.iso
[Testing Harvester 030 - SUSE Alliances - Installation Screenshots - Draft 3.pdf](https://github.com/rancher/rke2/files/7529912/Testing.Harvester.030.-.SUSE.Alliances.-.Installation.Screenshots.-.Draft.3.pdf)

**Expected behavior:**

- Ability to use Bond0 
- no Kubectl errors

**Actual behavior:**

- Kubectl error messages and UI performance makes it difficult to work

**Additional context / logs:**

[kubectl-debug.log](https://github.com/rancher/rke2/files/7529950/kubectl-debug.log)
[rke2-server.log](https://github.com/rancher/rke2/files/7529951/rke2-server.log)
[containerd.log](https://github.com/rancher/rke2/files/7529952/containerd.log)

**Environment:**
 - Harvester ISO version: v1.0.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
backport https://github.com/rancher/rke2/issues/2119

**Comment by yasker** [comment] 2021-12-07 23:50
FYI: It is caused by the read-only filesystem on the root disk.

https://github.com/rancher/rke2/issues/2119#issuecomment-984627066

Use `kubectl -v3 get pod` to get the full debug message.
<img width="1445" alt="Screen Shot 2021-12-07 at 3 48 30 PM" src="https://user-images.githubusercontent.com/3344618/145123638-4074b1ce-80a8-4385-819d-c9a955ff7c79.png">

**Comment by johnliu55tw** [comment] 2022-01-20 08:19
The main reason is that if you switch to Shell by pressing F12, **you won't have the `$HOME` environment variable**.

Lacking `$HOME` would cause `kubectl` to use the current working directory (`/`) to create the `.kube/cache` folder, and it would just fail because `/` is a read-only file system.

There are two workarounds:
- Switch to Shell by **switching virtual terminal** (Press `Ctrl-Alt-F2`). Login with `rancher/<Your password>`
- Add `$HOME` environment variable after you switched to Shell by pressing F12: `export HOME=/root`

As for why switching by F12 would have `$HOME` undefined, I suppose it's because the Shell is not started by `/bin/login` so it's not been set up correctly.

**Comment by TachunLin** [comment] 2022-03-14 11:09
Verified **fixed** on master-75cc3ced-head.(03/11) Close this issue.

### Result
Can switch to shell console directly with root by pressing F12 for 
1. Run kubectl command with root privilege without error
2. Response time and smooth experience 
![image](https://user-images.githubusercontent.com/29251855/158139527-ffdf275a-822e-4b84-b4ba-bff5159b3c21.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-75cc3ced-head.(03/11)

### Verify Steps
1. PXE boot installation
2. Access PXE boot server
3. Edit the config-create-cluster-01.yaml and config-join-cluster-01.yaml file 
4. Set **`tty: tty1`**
5. PXE install harvester node 
6. Wait for installation complete, display Ready on console terminal 
7. Press **`F12`**
8. Run `kubectl get nodes` 
9. Run `kubectl get all -A`

**Closed as completed by TachunLin** 2022-03-14 11:09 UTC
Labels: kind/bug, area/control-plane, priority/1
