### ISSUE TITLE
[BUG] Management IP was changed automaticately to a wrong one

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#650] opened 2021-04-06 02:05 UTC
**Describe the bug**

**Log**

![image](https://user-images.githubusercontent.com/15064560/113648596-6efe1f80-96bf-11eb-8b31-2f79ce6a7fcd.png)

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment] 2021-04-08 09:09
Validated on master-621eedd7-head

I can't reproduce it, close it.
If you still have doubts, please reopen it and let me know.

**Closed as completed by kingsd041** 2021-04-08 09:09 UTC
Labels: kind/bug, area/installer
