### ISSUE TITLE
[BUG] When a host is down, VMs on it stay in running status

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#913] opened 2021-05-31 02:56 UTC
**Describe the bug**
When a host is down, VMs on it stay in running status. The VMs are not available indeed.

**To Reproduce**
1. Deploy VMs in a multi-node Harvester.
2. Power off one of the node.
3. Check status of the VMs running on that node.

**Result**
VMs stay in running status but are not available.

**Expected behavior**
VMs should report unhealthy status.
VMs can recover on other healthy nodes(automatically done after some time, or can be done manually by users).

**Environment:**
 - Harvester ISO version: v0.2.0

**Additional context**
Related to: https://github.com/kubernetes/kubernetes/issues/55713

**Comment by guangbochen** [comment] 2021-09-27 15:08
duplicate of https://github.com/harvester/harvester/issues/982

**Closed as completed by guangbochen** 2021-09-27 15:08 UTC
Labels: kind/bug
