### ISSUE TITLE
[BUG] creating a VM snapshot sometimes will be stuck in the Progressing

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#3813] opened 2023-04-21 14:42 UTC
**Describe the bug**
Creating a VM snapshot on UI would get chances stuck in the `Progressing`.

**To Reproduce**
1. Create a VM and attach more than one volume.
2. Stop the VM
3. Create a VM Snapshot on the VM page (by clicking `Take VM Snapshot`)
4. You would get a chance to see the snapshot stuck in the `Progressing`
 
**Expected behavior**
The VM Snapshot should be `Ready`

**Support bundle**
[supportbundle_61baa0ed-95bb-45ec-8778-5bc39d289e81_2023-04-21T14-29-16Z.zip](https://github.com/harvester/harvester/files/11296646/supportbundle_61baa0ed-95bb-45ec-8778-5bc39d289e81_2023-04-21T14-29-16Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc8
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3VMs for harvester cluster

**Additional context**
The controller would get confused with volume status. It means the Volume is on the way to detaching, but the snapshot controller would think the volume is attached and does not need to attach again. So that would cause the snapshot controller is waiting for the volume status change to attached. It is more like the timing issue, and the user could retake a snapshot, then it will succeed.

**Comment by bk201** [comment] 2023-04-21 14:45
@FrankYang0529 Please help check. It could be because volumes are still attached in the window.
It's easier to reproduce if a VM has multiple volumes. Just try to take a snapshot right after the VM becomes stopped.

**Comment by FrankYang0529** [comment] 2023-04-24 09:58
This issue also happened in VM backup. If we detach a volume when a related VM backup is in progress, the VM backup will be broken. We can encounter the error with following steps:
1. Create a VM.
2. Stop the VM and take a backup immediately.
3. If the backup takes longer time, we can see that related volumes are detached.
4. Finally, we will get an error in LH backup.
```
  error: 'proxyServer=10.52.0.46:8501 destination=10.52.2.12:10000: failed to get
    backup-0a918634cffd40bb backup status: rpc error: code = Unknown desc = failed
    to list replicas for volume 10.52.2.12:10000: rpc error: code = Unavailable desc
    = all SubConns are in TransientFailure, latest connection error: connection error:
    desc = "transport: Error while dialing dial tcp 10.52.2.12:10000: connect: connection
    refused"'
```
5. We can't fix the above error even if we attach the volume again.

Adding a webhook to prevent volumes from detaching when having any related VM backup/snapshot is not a good idea because other controllers may get errors. I prefer to expose the LH backup error message to VM backup, so users can know what happened instead of getting an in-progress VM backup.

**Comment by Yu-Jack** [comment] 2024-05-14 09:20
@bk201 I found out there is no snapshot or backup button when I'm stopping vm. Does it fix on GUI side?

![image](https://github.com/harvester/harvester/assets/6960289/03fe9365-1dcd-44c7-835a-a3ffa28a81bb)

**Comment by WebberHuang1118** [comment] 2024-05-16 02:28
I think this is not going to happen for LH v1.5+,  since LH has [better attachment/detachment management](https://github.com/longhorn/longhorn/blob/master/enhancements/20221024-longhorn-volumeattachment.md) from LH v1.5.0

**Comment by Yu-Jack** [comment] 2024-05-16 10:01
In my case, my step is:

1. Stop vm
2. Create backup during vm stopping

I stuck in error state instead of progressing. For the record, upload my demo here. Then, I got the different result `failed to update status for engine pvc-c100a660-b235-412c-be2d-755dbe39aca7-e-0: proxyServer=10.52.0.50:8501 destination=10.52.0.50:10025: failed to list replicas for volume: rpc error: code = Unavailable desc = failed to list replicas for volume 10.52.0.50:10025: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 10.52.0 .50:10025: connect: connection refused"`

Skip the middle of video, I just waited for vm being stopped.

https://github.com/harvester/harvester/assets/6960289/73717ced-78c8-4593-8756-32c611c28284

Sometime, it show error state, but it's still processing, then it end up `ready`.

![image](https://github.com/harvester/harvester/assets/6960289/bd08031d-9292-4cdf-abe3-00381e27b0df)

And when I’m testing this, although it shows error state in the beginning, but it ends up ready state cause we’ll re-queue it. I can’t get the processing state in this case. Whatever flows I tried, it ends up ready state.

Flow 1
1. stop vm
2. create backup during vm stopping

Flow 2
1. stop vm
2. create backup after vm became stopped

**Comment by Yu-Jack** [comment] 2024-07-04 09:37
@bk201 I can't reproduce this bug anymore in v1.3.1.

I tried with `curl` to do snapshot on purpose:

1. when vm becomes stopping, snapshot immediately with `curl`
2. when vm becomes stopped, snapshot immediately with `curl`
3. when vm becomes stopping, snapshot immediately with `curl`, then force vm stopped.
4. when vm becomes stopping, snapshot immediately with `curl`, then force vm stopped, then start vm.  

After discussion with @WebberHuang1118 , it's only related to v1.2.2 version https://github.com/harvester/harvester/issues/5841#issuecomment-2122957306. The key point is to check the tag whether includes this PR https://github.com/harvester/harvester/pull/4910 or not. If it includes that, then no this bug.

I think we could close this issue since there is already one issue https://github.com/harvester/harvester/issues/5841 in v1.2.3 milestone.

**Comment by bk201** [comment] 2024-07-04 11:02
Thanks, @Yu-Jack and @WebberHuang1118, close because the issue can't be reproduced.

**Closed as completed by bk201** 2024-07-04 11:02 UTC
Labels: kind/bug, wontfix, priority/1, area/admission-webhook, severity/3, reproduce/often
