### ISSUE TITLE
terraform provider - harvester_clusternetwork resource test fails as already exists

### ISSUE THREAD

**Issue by yarunachalam** [harvester/harvester#1215] opened 2021-09-13 22:41 UTC
**Describe the bug**
Test the harvester_clusternetwork resource - failed 
`clusternetworks.network.harvesterhci.io "vlan" already exists
│ 
│   with harvester_clusternetwork.vlan,
│   on resource.tf line 1, in resource "harvester_clusternetwork" "vlan":
│    1: resource "harvester_clusternetwork" "vlan" {
`
Is the terraform supposed to be idempotent.

**To Reproduce**
1. edit -  resource.tf with the following to test harvester_clusternetwork  
`resource "harvester_clusternetwork" "vlan" {
  lifecycle {
    prevent_destroy = true
  }
  name                 = "vlan"
  enable               = true
  default_physical_nic = "eth0"
}
`
- terraform init
- terraform plan
- terraform apply will fail with 
`harvester_clusternetwork.vlan: Creating...
╷
│ Error: clusternetworks.network.harvesterhci.io "vlan" already exists
│ 
│   with harvester_clusternetwork.vlan,
│   on resource.tf line 1, in resource "harvester_clusternetwork" "vlan":
│    1: resource "harvester_clusternetwork" "vlan" {
`

**Expected behavior**
I assume it should update clusternetwork vlan

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment] 2021-09-14 02:17
duplicate of #1042

**Closed as completed** 2021-09-14 02:50 UTC
Labels: kind/bug, area/terraform-provider

**Comment by yarunachalam** [comment] 2021-10-05 16:43
Validated with import resource as per the suggestion https://github.com/harvester/harvester/issues/1042. It works as expected. Closing the ticket
