### ISSUE TITLE
[BUG] First time login shows Rancher UI and show up "object has been modified", requires second log in 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1530] opened 2021-11-09 15:25 UTC
**Describe the bug**

When user trying to access harvester url after iso installation complete but not yet completely setup.  
It will first show harvester change password page, then prompt the following rancher first time login page

![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/1c8e22ad-5e5a-4eee-83ef-6c9a74a426c1)

Input correct password will fail to login and prompt error message `object has been modified`
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/0618effa-1019-46bd-9c77-a3b4318c88a7)

if user click the error or wait a few seconds, it can login harvester  

**To Reproduce**
1. Iso install harvester
2. Wait for the first time console display ready
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/0397e55b-4801-47c1-a5df-0ea21f6168ec)
3. At the first time access harvester url 
4. It may prompt `handler disconnect`
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/42491ba8-9f24-4974-b1af-7953b42c8493) 
5. Wait for a while when harvester load first time login page

**Expected behavior**

Every time harvester should avoid displaying rancher first login page. 
Should not prompt error message `object has been modified`

**Support bundle**

**Environment:**
 - Harvester ISO version: master-d21b9161-head
 - Underlying Infrastructure: 1 node  harvester on local kvm machine

**Additional context**
Not always happen, it is possible to happen when previously exists `Handler disconnected` error

**Comment by WuJun2016** [comment] 2022-01-05 03:14
Hi @TachunLin,  I have not been able to reproduce the problem so far, so I may need you to provide a video to help me troubleshoot the problem. thx

**Comment by TachunLin** [comment] 2022-01-07 06:53
Hi @WuJun2016, the frequency of occurrence for this issue is low during the v0.3.0 release since I encounter 1 ~ 2 times.
I will reproduce it on v1.0.0 to see whether it will happen again

**Comment by TachunLin** [comment] 2022-01-12 10:56
@WuJun2016, the original rancher startup page did not happen after several trials of harvester installation. 

During the issue reproduction I found something strange:

At harvester first login page, if we press `ctrl+r` to refresh page. 
It will show up the page with bootstrap password requirement to proceed.  
However we don't know which the password thus the Continue button is greyed out. 

I thinks it's somehow related to original issue and worth take a look at it to fix. 
Recommend  move it to `implement` for your further investigation. 

![Peek 2022-01-12 18-33](https://user-images.githubusercontent.com/29251855/149125965-32e9fbe6-5823-45b9-99c3-e2514d26bf45.gif)

![image](https://user-images.githubusercontent.com/29251855/149124498-137abfa6-a287-4115-a2c0-e37c66b5bc67.png)

**Comment by WuJun2016** [comment] 2022-01-13 05:45
@TachunLin  I don't think this is a problem: In the previous step we will use  `admin` as the password to request a login, if it succeeds it will jump to the set password page and hide the `bootstrap password` input box, if the user refreshes the page we don't know what the initial password is, so the user needs to enter the correct initial password in `bootstrap password` box.

cc @guangbochen

**Comment by TachunLin** [comment] 2022-01-14 15:32
@WuJun2016 , regarding to the refresh page behavior on first time login page, I think it somehow may cause user confused while they refresh the page but prompt the the bootstrap password that they have no idea where to find it out. 
A workaround is user can access the harvester with VIP address in URL again. 
If that is the normal behavior according to the design I have no more concern since it's more like the user experience. 
 
By the way, the original issue was occasionally reproduced today while using pxe install harvester on provo bare machines with harvester `v0.3.0`

Reproduce step: 

1. Install the 1st harvester node in create mode
2. Leave the harvester first time login page without setting admin password 
3. Install the 2nd harvester node in join mode 
4. Access the harvester first time login page, provide admin password and click Login
5. Then it will prompt the following rancher first time login page 

![Peek 2022-01-14 17-21](https://user-images.githubusercontent.com/29251855/149537912-3e94e819-6478-4378-a2eb-0646c02fbaea.gif)

I would check it again on `v1.0.0` master head by using pxe install after finish the manual upgrade test

**Comment by TachunLin** [comment] 2022-01-18 09:31
Validate the issue did not happen on `v1.0.0` GA by using pxe installation.  
With the same reproduce steps, the harvester first time login page did not show rancher UI.

**Comment by TachunLin** [comment] 2022-02-07 10:18
@WuJun2016 , This issue was found while reproducing issue #1830  on `master-1a861fc1-head`. (02/07/22) 

After ISO install 3 nodes harvester in ready status, access dashboard via VIP. 
The bootstrap page hanging for a while and display the rancher bootstrap page. 

* In the following screen, user have no way to set password to proceed 
![0207_bootstrap_rancher](https://user-images.githubusercontent.com/29251855/152768148-f3d253a9-d745-4f5b-9608-a0e95257ed41.gif)

* The workaround is wait for harvester fully promoted, access dashboard via VIP again 
![0207_bootstrap_ranche2](https://user-images.githubusercontent.com/29251855/152768306-f586b3e9-987c-4e6c-b962-105da5e41d2f.gif)


### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: master-1a861fc1-head (02/07/22) 
* Browser: Firefox

### Verify Steps

1. ISO install harvester node 1 in fixed VIP
2. Do not access harvester dashboard
3. ISO install harvester node 2 in join mode
4. ISO install harvester node 3 in join mode
5. Once node 3 display `ready` on console UI
6. Access dashboard via VIP

**Comment by mantis-toboggan-md** [comment] 2022-04-21 21:53
> @WuJun2016 , This issue was found while reproducing issue #1830 on `master-1a861fc1-head`. (02/07/22)
> 
> After ISO install 3 nodes harvester in ready status, access dashboard via VIP. The bootstrap page hanging for a while and display the rancher bootstrap page.
> 
> * In the following screen, user have no way to set password to proceed
>   ![0207_bootstrap_rancher](https://user-images.githubusercontent.com/29251855/152768148-f3d253a9-d745-4f5b-9608-a0e95257ed41.gif)
> * The workaround is wait for harvester fully promoted, access dashboard via VIP again

This doesn't look like a UI bug to me: the UI only shows 'Invalid username or password' if the login request returned 401 unauthorized, but it sounds like the actual problem is that the server isn't ready so maybe we want a 503 response here? Or perhaps not show the UI at all at this stage? This needs input from outside the UI team.

**Comment by WuJun2016** [comment] 2022-04-22 11:17
> > @WuJun2016 , This issue was found while reproducing issue #1830 on `master-1a861fc1-head`. (02/07/22)
> > After ISO install 3 nodes harvester in ready status, access dashboard via VIP. The bootstrap page hanging for a while and display the rancher bootstrap page.
> > 
> > * In the following screen, user have no way to set password to proceed
> >   ![0207_bootstrap_rancher](https://user-images.githubusercontent.com/29251855/152768148-f3d253a9-d745-4f5b-9608-a0e95257ed41.gif)
> > * The workaround is wait for harvester fully promoted, access dashboard via VIP again
> 
> This doesn't look like a UI bug to me: the UI only shows 'Invalid username or password' if the login request returned 401 unauthorized, but it sounds like the actual problem is that the server isn't ready so maybe we want a 503 response here? Or perhaps not show the UI at all at this stage? This needs input from outside the UI team.

Yes, I also think it's not a bug

**Comment by guangbochen** [comment] 2022-04-24 02:45
Move this issue to the v1.1 milestone since it is a rare-reproduce issue and the team does not have an extra buffer for it, thanks.

**Comment by WuJun2016** [comment] 2023-07-12 03:22
It's not a problem, I'm closing this issue, feel free to reopen it, if there's any doubt about it.

**Closed as completed by WuJun2016** 2023-07-12 03:22 UTC
Labels: kind/bug, area/ui, area/installer, priority/2, severity/2, reproduce/rare
