### ISSUE TITLE
[BUG] Some images should not be purged after the upgrade is completed

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5749] opened 2024-05-07 10:16 UTC
**Describe the bug**

We introduced a new step, image cleanup, after the upgrade has completed (tracked in #4995). This saves lots of precious disk spaces. However, removing the images still used by some of the Pods could be a catastrophe in **air-gapped** environments. We've already added the `harvester-upgrade` image to the retaining list, but there are more.

For example:

- docker.io/longhornio/longhorn-engine
- docker.io/rancher/mirrored-fluent-fluent-bit

**To Reproduce**
1. Prepare an air-gapped 3-node Harvester cluster 
2. Upgrade the cluster
3. After the upgrade ends, observe the cluster state, there should be some Pods fail to run

**Expected behavior**

After the upgrade completed, all of the Pods should be running without problems.

**Support bundle**

[supportbundle_2687bb0c-dea1-4978-956d-bdbb2f5d927a_2024-05-07T03-28-20Z.zip](https://github.com/harvester/harvester/files/15233947/supportbundle_2687bb0c-dea1-4978-956d-bdbb2f5d927a_2024-05-07T03-28-20Z.zip)

**Environment**
 - Harvester ISO version: v1.2.1 (upgrading to v1.2.2-rc2)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

This is first found in [here](https://github.com/harvester/harvester/issues/5473#issuecomment-2097793487).

**Comment by w13915984028** [comment] 2024-05-08 07:58
This is kind of silent behaviour change.

(1) Is it mentioned in the Harvester docuement?

(2) Could we add a harvester-setting, or some labels/annotations for user to enable/disable it?  For some users, maybe system disk usage is not an important issue.

Or when the system disk reachs certain percent before kubelet trigger the purging, Harvester does it in advance.

Or we list all the container imges in Harvester NODE page, let user have chance to choose & remove those `old-versioned` images.

**Comment by bk201** [comment] 2024-05-13 09:03
>(1) Is it mentioned in the Harvester docuement?

@starbops Please add a section in the doc to mention the cleanup.

> (2) Could we add a harvester-setting, or some labels/annotations for user to enable/disable it? For some users, maybe system disk usage is not an important issue.
> 
> Or when the system disk reachs certain percent before kubelet trigger the purging, Harvester does it in advance.
> 
> Or we list all the container imges in Harvester NODE page, let user have chance to choose & remove those old-versioned images.

@w13915984028 For the remaining suggestions, please create a new issue to track. They are out of scope of this issue, the issue is for adding more retaining images.

**Comment by w13915984028** [comment] 2024-09-23 14:13
@starbops In my validation test, after a single-node cluster is upgraded from v1.3.2->v1.4.0 (harvester-v1.4.0-dev-20240918-amd64.iso), it looks all images are still kept. Any label/annotation/config is needed to enable the image auto cleaning? thanks.

```
harv21:/home/rancher # crictl image ls
IMAGE                                                                       TAG                                         IMAGE ID            SIZE
docker.io/longhornio/backing-image-manager                                  v1.6.2                                      9b8cf5184bda1       377MB
docker.io/longhornio/backing-image-manager                                  v1.7.1                                      8d4b5ca1f0b0c       408MB
docker.io/longhornio/csi-attacher                                           v4.5.1                                      ebcde6f69ddda       64.7MB
docker.io/longhornio/csi-attacher                                           v4.6.1                                      11aa3c05dd35a       67.8MB
docker.io/longhornio/csi-node-driver-registrar                              v2.12.0                                     419650e8c5967       29.6MB
docker.io/longhornio/csi-node-driver-registrar                              v2.9.2                                      438c692b0cb6d       23.2MB
docker.io/longhornio/csi-provisioner                                        v3.6.4                                      cc753cf7b8127       67.6MB
docker.io/longhornio/csi-provisioner                                        v4.0.1                                      d4b4b5e471352       69.1MB
docker.io/longhornio/csi-resizer                                            v1.10.1                                     644d77abe33db       66MB
docker.io/longhornio/csi-resizer                                            v1.11.1                                     95ba1a4c52f0c       68MB
docker.io/longhornio/csi-snapshotter                                        v6.3.4                                      eccecdceb86c0       64.4MB
docker.io/longhornio/csi-snapshotter                                        v7.0.2                                      069f97e4dc68a       65.2MB
...
docker.io/rancher/harvester-node-manager                                    v0.2.1                                      8e1a6a5cff4e3       166MB
docker.io/rancher/harvester-node-manager                                    v0.3.2                                      3b33bc31d5a16       172MB
docker.io/rancher/harvester-pcidevices                                      v0.3.3                                      4971416ac776f       260MB
docker.io/rancher/harvester-pcidevices                                      v0.4.0                                      defb69137971d       261MB
docker.io/rancher/harvester-seeder                                          v0.3.2                                      ee45310337360       213MB
docker.io/rancher/harvester-seeder                                          v0.4.0                                      235c3dda83eff       216MB
docker.io/rancher/harvester-upgrade                                         v1.3.2                                      92366e24ee6fb       444MB
docker.io/rancher/harvester-upgrade                                         v1.4.0-dev-20240918                         0a5a58e6a6e89       446MB
docker.io/rancher/harvester-vm-import-controller                            v0.3.2                                      7b9b69f343357       271MB
docker.io/rancher/harvester-vm-import-controller                            v0.4.0                                      8c0d7f7929132       271MB
docker.io/rancher/harvester-webhook                                         v1.3.2                                      4797ce7e9b50b       240MB
docker.io/rancher/harvester-webhook                                         v1.4.0-dev-20240918                         278b6e25c8a54       243MB
docker.io/rancher/harvester                                                 v1.3.2                                      23b6d97d1f821       330MB
docker.io/rancher/harvester                                                 v1.4.0-dev-20240918                         7fc6733eba93e       334MB
...
```

**Comment by starbops** [comment] 2024-09-24 01:55
@w13915984028 It is enabled by default and does not require any label or annotation. Might need to check the logs from the harvester pod. My guess is that the image list querying timed out during the repo VM booting up. If that's the case, we might need to prolong the retry loop for single node upgrades. But such a change will cause the upgrade to finish much longer.

**Comment by w13915984028** [comment] 2024-09-24 07:18
@starbops I added a new issue https://github.com/harvester/harvester/issues/6620 to track it, and will continue validate this issue in multi-node cluster.

**Comment by w13915984028** [comment] 2024-09-24 15:40
Update the QA validation progress:

Due to the upgrade-matrix file is not updated when building the v140 ISO, there is no v132 image list info in the v140 ISO, it is not possible to validate this issue from v132-v140 upgrade path. Also refer: https://github.com/harvester/harvester/issues/6620#issuecomment-2371305994

After PR https://github.com/harvester/harvester/pull/6626 is merged, we will re-validate.

cc @khushboo-rancher

**Comment by w13915984028** [comment] 2024-10-02 08:05
v132->v140-rc1 upgrade, after upgraded:

```
harv21:/home/rancher # cat /etc/harvester-release.yaml 
harvester: v1.4.0-rc1
harvesterChart: 1.4.0-rc1
installer: e7aa395
os: Harvester v1.4.0-rc1
kubernetes: v1.29.9+rke2r1
rancher: v2.9.2
monitoringChart: 103.1.1+up45.31.1
loggingChart: 103.1.0+up4.4.0
kubevirt: 1.2.2-150500.8.21.1
minUpgradableVersion: 'v1.3.2'
rancherDependencies:
  fleet:
    chart: 104.0.2+up0.10.2
    app: 0.10.2
  fleet-crd:
    chart: 104.0.2+up0.10.2
    app: 0.10.2
  rancher-webhook:
    chart: 104.0.2+up0.5.2
    app: 0.5.2


$kubectl crictl image ls
IMAGE                                                                       TAG                                         IMAGE ID            SIZE
<none>                                                                      <none>                                      00df8b41cfd2e       72.6MB
docker.io/rancher/mirrored-ingress-nginx-kube-webhook-certgen               v20221220-controller-v1.5.1-58-g787ea74b6   057e081088898       47.5MB
ghcr.io/kube-vip/kube-vip-iptables                                          v0.8.1                                      001f7c55557c9       68.7MB
registry.suse.com/suse/sles/15.5/virt-operator                              1.2.2-150500.8.21.1                         00086cc1dd739       192MB
<none>                                                                      <none>                                      00511613dec56       100MB
docker.io/rancher/harvester-webhook                                         v1.4.0-rc1                                  00e4576b09d82       243MB
registry.suse.com/suse/sles/15.5/virt-controller                            1.2.2-150500.8.21.1                         05cf5397ea763       189MB
<none>                                                                      <none>                                      05fdc669b160a       192MB
docker.io/longhornio/csi-attacher                                           v4.6.1                                      11aa3c05dd35a       67.8MB
docker.io/longhornio/csi-snapshotter                                        v7.0.2                                      069f97e4dc68a       65.2MB
docker.io/longhornio/longhorn-engine                                        v1.7.1                                      146f7443786b2       407MB
docker.io/longhornio/longhorn-instance-manager                              v1.6.2                                      23292e266e0eb       748MB
docker.io/longhornio/longhorn-ui                                            v1.7.1                                      1ed35f9e6145f       236MB
docker.io/rancher/hardened-coredns                                          v1.11.1-build20240910                       1ebdf98f6ac9e       74.1MB
docker.io/rancher/hardened-etcd                                             v3.5.13-k3s1-build20240910                  19f8e656ed901       45.9MB
docker.io/rancher/harvester-seeder                                          v0.4.0                                      235c3dda83eff       216MB
docker.io/rancher/harvester                                                 v1.4.0-rc1                                  2045791b98f26       335MB
docker.io/rancher/klipper-helm                                              v0.9.2-build20240828                        1932cb543c3e4       198MB
docker.io/rancher/klipper-lb                                                v0.4.9                                      11a5d8a9f31aa       12.7MB
docker.io/rancher/mirrored-grafana-grafana                                  9.1.5                                       0d9dace86a5c3       306MB
docker.io/rancher/mirrored-kiwigrid-k8s-sidecar                             1.24.6                                      12bfdf6df7b01       83.9MB
docker.io/rancher/mirrored-library-busybox                                  1.31.1                                      1c35c44120825       1.44MB
docker.io/rancher/mirrored-prometheus-node-exporter                         v1.3.1                                      1dbe0e9319764       22.3MB
docker.io/rancher/mirrored-sig-storage-snapshot-controller                  v6.2.1                                      1ef6c138bd5f2       58.4MB
docker.io/rancher/shell                                                     v0.2.1                                      0688642661385       307MB
<none>                                                                      <none>                                      0c1204a22f132       264MB
docker.io/rancher/support-bundle-kit                                        v0.0.44                                     11e28c96745c6       277MB
<none>                                                                      <none>                                      1fd729acccd8b       211MB
<none>                                                                      <none>                                      23b6d97d1f821       330MB
docker.io/longhornio/longhorn-manager                                       v1.7.1                                      23e2491df978b       355MB
<none>                                                                      <none>                                      2563e24ce2d2c       64MB
<none>                                                                      <none>                                      25a8bfcd2d7e2       228MB
docker.io/longhornio/support-bundle-kit                                     v0.0.42                                     2951ba2556248       281MB
docker.io/rancher/fleet                                                     v0.10.2                                     36cde7f197537       305MB
docker.io/rancher/hardened-cluster-autoscaler                               v1.8.11-build20240910                       3bf9ae903993c       38.3MB
docker.io/rancher/harvester-upgrade                                         v1.4.0-rc1                                  2c91cfcfa2ea4       431MB
docker.io/rancher/mirrored-jimmidyson-configmap-reload                      v0.4.0                                      37e6075b1356c       10.9MB
docker.io/rancher/mirrored-library-nginx                                    1.24.0-alpine                               249f59e1dec7f       42.9MB
docker.io/rancher/mirrored-prometheus-operator-prometheus-config-reloader   v0.65.1                                     27473df42d72c       13.9MB
docker.io/rancher/mirrored-prometheus-operator-prometheus-operator          v0.65.1                                     2a1fa9d2dda1a       57.5MB
docker.io/rancher/rancher-webhook                                           v0.5.2                                      2a4fb7a5cd10f       88.3MB
docker.io/rancher/shell                                                     v0.1.26                                     33dc949c57f81       304MB
registry.suse.com/suse/sles/15.5/virt-launcher                              1.2.2-150500.8.21.1                         2ccd4d88a5427       594MB
<none>                                                                      <none>                                      3497a01296944       45.8MB
<none>                                                                      <none>                                      385faeb1267ea       279MB
<none>                                                                      <none>                                      38ae1b6759b01       28.7MB
<none>                                                                      <none>                                      3dbea18127270       84.6MB
<none>                                                                      <none>                                      3dc3bc0ec02b0       170MB
<none>                                                                      <none>                                      433c4e427541b       592MB
<none>                                                                      <none>                                      438c692b0cb6d       23.2MB
<none>                                                                      <none>                                      4797ce7e9b50b       240MB
<none>                                                                      <none>                                      4971416ac776f       260MB
<none>                                                                      <none>                                      4d4d5a67078c8       193MB
<none>                                                                      <none>                                      4df343cccbed2       115MB
<none>                                                                      <none>                                      5a86b03a88d23       48.5MB
<none>                                                                      <none>                                      636aff9a37178       49.7MB
<none>                                                                      <none>                                      644d77abe33db       66MB
<none>                                                                      <none>                                      6b0b2d18564be       317MB
<none>                                                                      <none>                                      6d80f01a1966b       58.3MB
<none>                                                                      <none>                                      70db9d75e8172       240MB
<none>                                                                      <none>                                      739301b6065ee       619MB
<none>                                                                      <none>                                      784091d851edf       200MB
docker.io/longhornio/backing-image-manager                                  v1.7.1                                      8d4b5ca1f0b0c       408MB
docker.io/longhornio/csi-node-driver-registrar                              v2.12.0                                     419650e8c5967       29.6MB
docker.io/longhornio/csi-resizer                                            v1.11.1                                     95ba1a4c52f0c       68MB
docker.io/longhornio/longhorn-cli                                           v1.7.1                                      7092b534bc000       272MB
docker.io/longhornio/longhorn-engine                                        v1.6.2                                      7fb50a1bbe317       363MB
docker.io/longhornio/longhorn-share-manager                                 v1.7.1                                      ab322cbc26954       240MB
docker.io/rancher/fleet-agent                                               v0.10.2                                     63855309456d0       85MB
docker.io/rancher/hardened-dns-node-cache                                   1.23.1-build20240910                        81eccd9918702       53MB
docker.io/rancher/hardened-k8s-metrics-server                               v0.7.1-build20240910                        690ef3e34d41b       58.9MB
docker.io/rancher/hardened-kubernetes                                       v1.29.9-rke2r1-build20240912                64b4ff36acfb1       605MB
docker.io/rancher/hardened-multus-cni                                       v4.1.0-build20240910                        5dc861e831a77       119MB
docker.io/rancher/harvester-cluster-repo                                    v1.4.0-rc1                                  49c53d734e5a9       190MB
docker.io/rancher/harvester-eventrouter                                     v0.3.2                                      4682a8df751f1       92.9MB
docker.io/rancher/harvester-load-balancer-webhook                           v0.4.2                                      7a580e34c2c86       108MB
docker.io/rancher/harvester-load-balancer                                   v0.4.2                                      78633e71e85b3       105MB
docker.io/rancher/harvester-network-webhook                                 v0.5.3                                      7aeef5265bf44       123MB
docker.io/rancher/harvester-networkfs-manager                               v0.1.1                                      9e8e7e20ca790       206MB
docker.io/rancher/harvester-node-disk-manager                               v0.7.4                                      5257f854815eb       202MB
docker.io/rancher/harvester-node-manager-webhook                            v0.3.3                                      56ab60dd08c80       176MB
docker.io/rancher/harvester-upgrade                                         v1.3.2                                      92366e24ee6fb       444MB
docker.io/rancher/harvester-vm-import-controller                            v0.4.0                                      8c0d7f7929132       271MB
docker.io/rancher/kubectl                                                   v1.21.5                                     43e8b9390c725       46.7MB
docker.io/rancher/kubectl                                                   v1.29.2                                     5e6f8325b118e       49.7MB
docker.io/rancher/mirrored-banzaicloud-fluentd                              v1.14.6-alpine-5                            9aae16d37878a       221MB
docker.io/rancher/mirrored-ingress-nginx-kube-webhook-certgen               v1.4.1                                      684c5ea3b61b2       56.8MB
docker.io/rancher/mirrored-pause                                            3.6                                         6270bb605e12e       686kB
docker.io/rancher/mirrored-prometheus-alertmanager                          v0.26.0                                     9f27df16978d8       67.9MB
docker.io/rancher/rke2-cloud-provider                                       v1.29.8-build20240910                       78a70ecb41035       64.6MB
docker.io/rancher/rke2-runtime                                              v1.29.9-rke2r1                              7da29c592fac5       338MB
docker.io/rancher/system-upgrade-controller                                 v0.13.4                                     73422422df50b       34.5MB
registry.k8s.io/sig-storage/snapshot-controller                             v6.3.3                                      4f642f162057e       61.2MB
registry.k8s.io/sig-storage/snapshot-validation-webhook                     v6.3.3                                      520d048805e05       51.4MB
registry.suse.com/bci/bci-base                                              15.6                                        7ef4bb2b3e2ac       125MB
registry.suse.com/suse/sles/15.5/libguestfs-tools                           1.2.2-150500.8.21.1                         565b24528ef79       619MB
<none>                                                                      <none>                                      7b9b69f343357       271MB
<none>                                                                      <none>                                      845f01a870ec2       78.1MB
<none>                                                                      <none>                                      8893d4d256709       94.3MB
<none>                                                                      <none>                                      897c86442550f       121MB
registry.suse.com/suse/sles/15.5/virt-handler                               1.2.2-150500.8.21.1                         8be0421933251       326MB
<none>                                                                      <none>                                      8c85c56c021ad       127MB
<none>                                                                      <none>                                      8c8f8d91c79fc       35.9MB
<none>                                                                      <none>                                      8cfcb66f43649       234MB
<none>                                                                      <none>                                      8e1a6a5cff4e3       166MB
registry.suse.com/suse/vmdp/vmdp                                            2.5.4.2                                     90567499610d4       66.3MB
<none>                                                                      <none>                                      90f211c9a06a1       188MB
<none>                                                                      <none>                                      91a26da6b860b       2.1GB
<none>                                                                      <none>                                      945e0ec017079       104MB
ghcr.io/k8snetworkplumbingwg/whereabouts                                    v0.6.3                                      95601e6931ef0       104MB
<none>                                                                      <none>                                      9b8cf5184bda1       377MB
<none>                                                                      <none>                                      a57fa2d36d426       32.8MB
<none>                                                                      <none>                                      a621bb7a95528       301MB
<none>                                                                      <none>                                      a86d934733e78       91MB
<none>                                                                      <none>                                      abc5338582c4f       33.7MB
docker.io/rancher/harvester-node-manager                                    v0.3.3                                      bf735140fb8b6       172MB
docker.io/rancher/kubectl                                                   v1.20.2                                     b119c4dfc78c8       40.2MB
docker.io/rancher/mirrored-kube-logging-logging-operator                    4.4.0                                       aceed871957bf       61.3MB
<none>                                                                      <none>                                      aef054cc887e5       596MB
<none>                                                                      <none>                                      b1c8e3638fc43       217MB
docker.io/rancher/hardened-addon-resizer                                    1.8.20-build20240910                        c5473dc96d71a       32.6MB
docker.io/rancher/hardened-cni-plugins                                      v1.5.1-build20240910                        b6ac3f0f43ed7       98MB
<none>                                                                      <none>                                      ba59c048c1040       63.9MB
docker.io/rancher/hardened-flannel                                          v0.25.6-build20240910                       c5b9d8599cc07       224MB
docker.io/rancher/harvester-network-controller                              v0.5.3                                      af8047c48582d       211MB
docker.io/rancher/nginx-ingress-controller                                  v1.10.4-hardened3                           c5e49f8eeb13e       726MB
docker.io/rancher/system-agent                                              v0.3.9-suc                                  bd83c4957fabe       191MB
<none>                                                                      <none>                                      c8568f914cd25       66.5MB
<none>                                                                      <none>                                      c9a2c30e2eb1c       333MB
<none>                                                                      <none>                                      cc753cf7b8127       67.6MB
<none>                                                                      <none>                                      cd00dc5289588       38.3MB
<none>                                                                      <none>                                      d11ba2973ed49       106MB
docker.io/longhornio/csi-provisioner                                        v4.0.1                                      d4b4b5e471352       69.1MB
docker.io/longhornio/longhorn-instance-manager                              v1.7.1                                      d1a693d2db537       1.01GB
<none>                                                                      <none>                                      d95a72f5fb03e       326MB
<none>                                                                      <none>                                      df2168e6bf552       277MB
<none>                                                                      <none>                                      dfc0a0f57ff8a       570MB
docker.io/longhornio/livenessprobe                                          v2.14.0                                     e31cb887d0420       30MB
docker.io/rancher/gitjob                                                    v0.9.8                                      e36bf72008411       230MB
<none>                                                                      <none>                                      ebcde6f69ddda       64.7MB
<none>                                                                      <none>                                      ec6e2d871c544       39.7MB
<none>                                                                      <none>                                      eccecdceb86c0       64.4MB
<none>                                                                      <none>                                      edc812b8e25d0       12.2MB
<none>                                                                      <none>                                      ee45310337360       213MB
<none>                                                                      <none>                                      eec68fd77ec94       55.3MB
<none>                                                                      <none>                                      f4a42eedee373       729MB
<none>                                                                      <none>                                      f578840264031       210MB
<none>                                                                      <none>                                      f90cbbf4fdd98       192MB
docker.io/rancher/hardened-calico                                           v3.28.1-build20240911                       ff76eadb17450       576MB
docker.io/rancher/harvester-network-helper                                  v0.5.3                                      cd29e15d7f5f8       117MB
docker.io/rancher/harvester-pcidevices                                      v0.4.0                                      defb69137971d       261MB
docker.io/rancher/mirrored-cluster-api-controller                           v1.7.3                                      f77e4ed7046c5       87MB
docker.io/rancher/mirrored-fluent-fluent-bit                                2.2.0                                       cd5b76149224a       87.4MB
docker.io/rancher/mirrored-kube-state-metrics-kube-state-metrics            v2.10.1                                     f5f9f4739d5f4       44MB
docker.io/rancher/mirrored-prometheus-adapter-prometheus-adapter            v0.10.0                                     e92afb5b902be       70.1MB
docker.io/rancher/mirrored-prometheus-prometheus                            v2.45.0                                     e1fbd49323c62       238MB
docker.io/rancher/mirrored-sig-storage-snapshot-validation-webhook          v6.2.2                                      ff52c2bcf9f88       49MB
docker.io/rancher/rancher                                                   v2.9.2                                      fa75bdc890565       2.15GB
docker.io/rancher/shell                                                     v0.1.24                                     deabd25af88c6       399MB
registry.suse.com/suse/sles/15.5/virt-api                                   1.2.2-150500.8.21.1                         f19e280975e30       193MB


```

logs:
```
time="2024-10-02T07:53:46Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:53:56Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:54:07Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:54:17Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:54:27Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:54:37Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:54:48Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:54:59Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:55:09Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:55:19Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:55:30Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:55:41Z" level=info msg="Trying to get v1.3.2 image list"
time="2024-10-02T07:55:41Z" level=info msg="Trying to get current image list"
time="2024-10-02T07:55:41Z" level=info msg="Diff: [docker.io/rancher/hardened-cluster-autoscaler:v1.8.10-build20240124 docker.io/rancher/rancher:v2.8.5 registry.suse.com/suse/sles/15.5/virt-api:1.1.1-150500.8.18.1 docker.io/longhornio/csi-node-driver-registrar:v2.9.2 docker.io/rancher/harvester-cluster-repo:v1.3.2 docker.io/rancher/harvester-eventrouter:v0.2.0 docker.io/rancher/harvester-network-helper:v0.4.1 docker.io/rancher/harvester-network-webhook:v0.4.1 docker.io/longhornio/csi-snapshotter:v6.3.4 docker.io/longhornio/support-bundle-kit:v0.0.37 docker.io/rancher/hardened-multus-cni:v4.0.2-build20240612 registry.suse.com/bci/bci-base:15.5 docker.io/longhornio/csi-provisioner:v3.6.4 docker.io/longhornio/longhorn-manager:v1.6.2 docker.io/rancher/fleet-agent:v0.9.5 docker.io/rancher/klipper-helm:v0.8.4-build20240523 docker.io/rancher/nginx-ingress-controller:v1.10.1-hardened1 docker.io/rancher/support-bundle-kit:v0.0.38 docker.io/rancher/fleet:v0.9.5 docker.io/rancher/mirrored-prometheus-alertmanager:v0.25.0 docker.io/rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794 docker.io/rancher/harvester:v1.3.2 docker.io/rancher/rke2-runtime:v1.28.12-rke2r1 docker.io/rancher/system-agent:v0.3.6-suc registry.suse.com/suse/sles/15.5/libguestfs-tools:1.1.1-150500.8.18.1 docker.io/longhornio/csi-attacher:v4.5.1 docker.io/longhornio/longhorn-share-manager:v1.6.2 docker.io/rancher/harvester-load-balancer:v0.3.0 docker.io/rancher/harvester-network-controller:v0.4.1 docker.io/rancher/mirrored-banzaicloud-logging-operator:3.17.10 docker.io/rancher/mirrored-prometheus-prometheus:v2.42.0 docker.io/longhornio/longhorn-ui:v1.6.2 docker.io/rancher/hardened-flannel:v0.25.4-build20240610 ghcr.io/kube-vip/kube-vip-iptables:v0.6.0 registry.suse.com/suse/sles/15.5/virt-handler:1.1.1-150500.8.18.1 docker.io/rancher/hardened-addon-resizer:1.8.20-build20240410 docker.io/rancher/system-upgrade-controller:v0.13.1 docker.io/longhornio/livenessprobe:v2.12.0 docker.io/rancher/hardened-etcd:v3.5.13-k3s1-build20240531 docker.io/rancher/harvester-vm-import-controller:v0.3.2 docker.io/rancher/mirrored-kube-state-metrics-kube-state-metrics:v2.6.0 docker.io/rancher/system-agent-installer-rancher:v2.8.5 docker.io/longhornio/backing-image-manager:v1.6.2 docker.io/rancher/harvester-load-balancer-webhook:v0.3.0 docker.io/rancher/harvester-webhook:v1.3.2 docker.io/rancher/mirrored-cluster-api-controller:v1.4.4 docker.io/rancher/hardened-k8s-metrics-server:v0.7.1-build20240401 docker.io/rancher/harvester-node-manager:v0.2.1 docker.io/rancher/harvester-seeder:v0.3.2 docker.io/rancher/klipper-lb:v0.4.7 docker.io/rancher/rke2-cloud-provider:v1.29.3-build20240515 docker.io/rancher/hardened-kubernetes:v1.28.12-rke2r1-build20240717 docker.io/rancher/harvester-node-disk-manager:v0.6.4 docker.io/rancher/harvester-node-manager-webhook:v0.2.1 registry.suse.com/suse/sles/15.5/virt-launcher:1.1.1-150500.8.18.1 docker.io/rancher/hardened-calico:v3.28.0-build20240625 docker.io/rancher/hardened-coredns:v1.11.1-build20240305 docker.io/rancher/hardened-dns-node-cache:1.22.28-build20240125 docker.io/rancher/harvester-pcidevices:v0.3.3 docker.io/rancher/rancher-webhook:v0.4.7 registry.suse.com/suse/sles/15.5/virt-controller:1.1.1-150500.8.18.1 registry.suse.com/suse/sles/15.5/virt-operator:1.1.1-150500.8.18.1 docker.io/longhornio/csi-resizer:v1.10.1 docker.io/rancher/system-agent-installer-rke2:v1.28.12-rke2r1 docker.io/rancher/hardened-cni-plugins:v1.4.1-build20240430]"
time="2024-10-02T07:55:41Z" level=info msg="Start purging unneeded container images on the nodes"
time="2024-10-02T07:55:41Z" level=error msg="error syncing 'cattle-system/apply-hvst-upgrade-v49fj-cleanup-on-harv21-with-3c26f4b0f-0d0b0': handler promote-node-controller: Operation cannot be fulfilled on jobs.batch \"apply-hvst-upgrade-v49fj-cleanup-on-harv21-with-3c26f4b0f-0d0b0\": StorageError: invalid object, Code: 4, Key: /registry/jobs/cattle-system/apply-hvst-upgrade-v49fj-cleanup-on-harv21-with-3c26f4b0f-0d0b0, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 39271de9-8d96-4a2c-b005-c6d544fe8b79, UID in object meta: , requeuing"
time="2024-10-02T07:55:54Z" level=info msg="handle upgrade harvester-system/hvst-upgrade-v49fj with labels map[harvesterhci.io/latestUpgrade:true harvesterhci.io/upgradeState:Succeeded]"
time="2024-10-02T07:55:54Z" level=info msg="Add OwnerReference upgrade-repo-hvst-upgrade-v49fj-disk-0 to upgrade repo image harvester-system/hvst-upgrade-v49fj"
time="2024-10-02T07:55:54Z" level=info msg="Delete upgrade repo VM harvester-system/upgrade-repo-hvst-upgrade-v49fj"
time="2024-10-02T07:55:54Z" level=info msg="Reset RKEConfig and set provisionGeneration to 0"
W1002 07:55:54.614124       7 warnings.go:70] child pods are preserved by default when jobs are deleted; set propagationPolicy=Background to remove them or set propagationPolicy=Orphan to suppress this warning
```

**Comment by w13915984028** [comment] 2024-10-02 08:09
@starbops The image list (https://github.com/harvester/harvester/issues/5749#issuecomment-2387865742) after purging looks weird, did you notice this?

**Comment by w13915984028** [comment] 2024-10-02 08:47
Per PR https://github.com/harvester/harvester/pull/5750, those images are kept after upgrade.

```
rancher/harvester-upgrade
longhornio/longhorn-engine
longhornio/longhorn-instance-manager
rancher/mirrored-banzaicloud-fluentd
rancher/mirrored-fluent-fluent-bit
```

The weird container image list issue is tracked on https://github.com/harvester/harvester/issues/6691

**Comment by w13915984028** [comment] 2024-10-02 08:48
Issue is solved.

**Closed as completed by w13915984028** 2024-10-02 08:48 UTC
Labels: kind/bug, require/doc, priority/0, area/install-upgrade, require/severity, backport-needed/1.2.2, backport-needed/1.3.1
