### ISSUE TITLE
[BUG] Console Login via "f12" does not work on v1.0.3 with password set during auto-installation

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3051] opened 2022-10-27 08:55 UTC
**Describe the bug**
Can not login on the console - password does not work:

![grafik](https://user-images.githubusercontent.com/13362573/198239101-584525b7-28d2-4534-a283-b1cefa9ee034.png)

Realized this during the upgrade 1.0.3 to 1.1.0 when we had to access the console due to broken network upgrade issue (two bond slaves).

When switching to other console with ctrl-alt-f2 we can login as user rancher with the password that is not working with the f12 way.

**To Reproduce**
Install harvester 1.0.3 automated and specify the password in the openssl encrypted way in the create.yaml.
Try to login with f12 on the console.

**Expected behavior**
Login / password should work.

**Environment**
 - Harvester ISO version: 1.0.3 (already seeing the issue, here) and upgraded to 1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal and also nested in KVM

**Comment by Martin-Weiss** [comment] 2022-10-31 08:24
Seems the issue is related to how the password hash has been created. 
Based on https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#ospassword -openssl passwd -1 seems to cause this problem, openssl passwd -6 does not seem to have this issue.

**Comment by tjjh89017** [comment] 2022-10-31 08:25
The root cause:
Dashboard will treat all hash as SHA-512 hash and use SHA-512 to compare.
But if users put other hash algorithm passwords into config.yaml, it will never match the hash in the shadow.
For example, Martin used MD5 hash for password, and MD5 hash is still valid for Linux TTY PAM.

https://github.com/harvester/harvester-installer/blob/5991dcf6307aa5da79c5d6926566541f48105778/pkg/util/crypt.go#L10-L19

**Comment by Martin-Weiss** [comment] 2022-10-31 08:28
Why is the dashboard hard coded on SHA-512 - in this scenario any other hash for the password in shadow might not work.. Can´t the dashboard use PAM?

**Comment by masteryyh** [comment] 2022-10-31 11:01
Tested with v1.0.3 & v1.1.0 without any issue using F12 to login.
Environment: Nested KVM in Proxmox

**Comment by masteryyh** [comment] 2022-11-01 01:36
Tested with v1.0.3 and v1.1.0 using iPXE boot can always reproduce.
Thanks to @tjjh89017 @Martin-Weiss SHA-512 using `openssl passwd -6` can be used with iPXE boot.

**Comment by TachunLin** [comment] 2023-02-16 10:17
### Test plan 

1. Prepare an iPXE installation environment 
2. Set the password using `openssl passwd` command to create based password 
    - [x] `openssl passwd -1` for MD5
    - [x] `openssl passwd -apr1` for MD5, Apache variant 
    - [x] `openssl passwd -5` for SHA256
    - [x] `openssl passwd -6` for SHA512

  
3. Copy the output value
4. Add the shadowed value in os.password of config.yaml 
5. Install a Harvester instance using iPXE;
6. After boot up, click `F12` on the dashboard console  
7. Try to use the password set in config.yaml to get into the console.

**Comment by TachunLin** [comment] 2023-02-16 12:55
Verified **fixed** on `master-676c1eca-head` (02/16). Close this issue.

### Result
We can use password provided in config.yaml to console login correctly on the Harvester installation dashboard
For the following types of encryption 
  - MD5
  - MD5, Apache variant 
  - SHA256
  - SHA512
 
![image](https://user-images.githubusercontent.com/29251855/219344372-b54c2291-7c12-498a-ae64-7efe6d03e102.png)

![image](https://user-images.githubusercontent.com/29251855/219344453-7ca20e93-12f8-4dfb-a633-b79da58582d1.png)

### Test Information
* Test Environment: 1 node local kvm machine
* Harvester version: master-676c1eca-head (02/16)

### Verify Steps
https://github.com/harvester/harvester/issues/3051#issuecomment-1432848704

**Closed as completed** 2023-02-16 12:56 UTC
Labels: kind/bug, require/doc, priority/1, severity/4, blocker, regression, reproduce/always
