### ISSUE TITLE
[BUG] Installation failed: "Could find partition device path for partition 6"

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1583] opened 2021-11-24 07:22 UTC
**Describe the bug**
Installer reports fatal error during installation:
<img width="1050" alt="screen_shot_2021-11-23_at_10 31 23_am" src="https://user-images.githubusercontent.com/5047724/143192870-0244d415-0d8f-41df-8063-5fc289a360e8.png">

**To Reproduce**
Install Harvester with all default options. **This issue is easier to reproduce on bare-metals**.

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Fremont `1.46`

**Additional context**
This is the error message from the installer saying that it failed to partition the storage device. The main reason is the tool for performing disk partitioning "`yip`" sometimes can't synchronize the latest disk partitioning layout, and the inconsistency is detected and thus stops the whole process.

To verify this issue, you could solely run `yip` to see if it could properly and consistently partitioning the device:
1. Boot the Harvester ISO and proceed with the installation **until you finished configuring networking**. Having network access to the machine would make things easier.
2. SSH into the machine with credential `rancher/rancher`. You could also switch to another virtual terminal using `Ctrl-Alt-F2`, but it would make things a bit harder, as we later need to copy data into the machine.
3. Switch to root user `sudo -s`
4. Copy the following data into a file named `part-layout.yaml`. It's a partitioning layout for `yip` to execute:
    ```
    stages:
      partitioning:
      - layout:
          add_partitions:
          - fsLabel: COS_OEM
            size: 50
            pLabel: oem
            filesystem: ext4
          - fsLabel: COS_STATE
            size: 15360
            pLabel: state
            filesystem: ext4
          - fsLabel: COS_RECOVERY
            size: 8192
            pLabel: recovery
            filesystem: ext4
          - fsLabel: COS_PERSISTENT
            size: 102400
            pLabel: persistent
            filesystem: ext4
          - fsLabel: HARV_LH_DEFAULT
            pLabel: longhorn
            filesystem: ext4
          device:
            path: /dev/sda  # Change this line if you have different disk
        name: Part layout
    ```

5. Run this command to **wipe the disk `/dev/sda`** first, then partition the disk with `yip` using the layout from last step:
    ```
    # wipefs -af /dev/sda && yip -s partitioning part-layout.yaml
    ```
6. If partitioning succeeds, you should see messages like this:
    ```
    INFO[0007] Finished yip file execution                   stage=partitioning stages=1 success=true
    ```
    If failed, you would see messages similar to the screenshot.
7. You could repeatedly run the command from step 5, or write a bash script to try to reproduce the issue.

**Comment by bk201** [comment] 2021-11-24 12:32
Attach logs: [support.tar.gz](https://github.com/harvester/harvester/files/7595550/support.tar.gz)

`blkid` output
```
/dev/loop0: TYPE="squashfs"
/dev/sr0: BLOCK_SIZE="2048" UUID="2021-11-23-05-56-15-00" LABEL="COS_LIVE" TYPE="iso9660" PTUUID="2e604cff" PTTYPE="dos"
/dev/sda2: LABEL="COS_OEM" UUID="9552886c-4cb5-43ec-9d02-ac0e65b0e464" BLOCK_SIZE="1024" TYPE="ext4" PARTLABEL="oem" PARTUUID="d0dfd2bc-6f77-4841-9b04-3183cc3e9768"
/dev/sda3: LABEL="COS_STATE" UUID="0e9c0cb3-8f0e-449d-908d-8e278bc2d884" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="state" PARTUUID="1cf13246-848f-4b81-8239-e767ede4cb2d"
/dev/sda4: LABEL="COS_RECOVERY" UUID="adc16f53-fe53-49a4-bc88-61d6c9ee5174" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="recovery" PARTUUID="8a27ed74-e4a9-4da1-89d8-b7a711e19940"
/dev/sda5: LABEL="COS_PERSISTENT" UUID="32706ba8-e5c0-4aa0-88c0-e304fcad20a6" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="persistent" PARTUUID="43e5c4d5-507a-4d7e-8965-9c63aeb3af3b"
/dev/sda1: PARTLABEL="primary" PARTUUID="f955cbe3-763c-4b00-93c6-d995d633f958"
/dev/sda6: PARTLABEL="longhorn" PARTUUID="e46038b8-231d-4c6e-80b4-ae2bbd2f1be6"
```
From the result, `/dev/sda6` is created eventually but yip can't find it: https://github.com/mudler/yip/blob/0422627fba31e9d2c51b6e9c421eb0142a6981e4/pkg/plugins/layout.go#L357

**Comment by Itxaka** [comment] 2021-11-24 14:14
I have also hit that while adding test to the installer and testing the same path, i.e using force-gpt and a layout file.

Looks like the problem is that it sets the `PARTLABEL` but misses to set the `LABEL` so it cannot find it.

Maybe we are missing some sync(s) in there to have the disk table updated?

Hit: You can export the var `LOGLEVEL=debug` to see yip debug output which may show whats going on here :thinking:

**Comment by Itxaka** [comment] 2021-11-24 14:17
oh, there is already a sync on `ReloadPartitionTable` so it should be updated :thinking:

**Comment by w13915984028** [comment] 2021-11-24 16:04
Just a doubt:  Seems the error message is lack of a ` not`
`    Could find partition device path for partition %d `
@Itxaka 
```
func (dev Disk) FindPartitionDevice(partNum int, console Console) (string, error) {
...
	match := re.FindStringSubmatch(out)
	if match == nil {
		return "", errors.New(fmt.Sprintf("Could find partition device path for partition %d", partNum))
	}
	return match[1], nil
}
```

**Comment by w13915984028** [comment] 2021-11-24 19:23
Please check this possibility:

**In short: if the partition is not found after creation, try delay a few seconds and read again.**


The main process of creating a new partition : ` sgdisk`, `partprobe`, `lsblk`
https://github.com/mudler/yip/blob/master/pkg/plugins/layout.go
```
 console.Run(fmt.Sprintf("sgdisk %s", strings.Join(opts[:], " ")))

 console.Run(fmt.Sprintf("partprobe %s", dev))

 console.Run(fmt.Sprintf("lsblk -ltnpo name,type %s", dev))
```

All of them are run in the same go routine, no delay.


For `partprobe`, it has a silent return when dev is not ready, but we don`t know.

https://github.com/bcl/parted/blob/master/partprobe/partprobe.c

```
static int
process_dev (PedDevice* dev)
{
	PedDiskType*	disk_type;
	PedDisk*	disk;

	if (!ped_device_open (dev))
		return 0;  --------------------------------------> no error is returned


```

Notice, if `!ped_device_open (dev)`, it does not return an error. The new device may not be ready at the kernel side.


https://unix.stackexchange.com/a/521858

Talked a similar case:

```
..
Welcome to fdisk (util-linux 2.23.2).
..
WARNING: Re-reading the partition table failed with error 16: Device or resource busy. 
The kernel still uses the old table. The new table will be used at the next reboot or 
after you run partprobe(8) or kpartx(8) Syncing disks.

..
```
The author said:
```

“My suspicion was that my piped-in command stream was surfacing a timing issue in
 fdisk (that wouldn't be triggered by slower/manual input) 
 so I started sprinkling sleep commands to delay various inputs until the error went away. 
 The problem in my case was that the w was happening too soon after the new partition was defined.
A sleep 5 before the w results in consistent success:
“

```

**Comment by Itxaka** [comment] 2021-11-24 20:18
@w13915984028 yup, that was also our main suspect, the silent return 0 if it can't be opened. A patch should follow up tomorrow probably to try to avoid this :)

**Comment by bk201** [comment] 2021-11-29 02:14
@johnliu55tw I've re-triggered an OS build. https://drone-publish.rancher.io/harvester/os2/23/
Image `rancher/harvester-os:dev-head` should contain `yip` `0.9.24`.

**Comment by johnliu55tw** [comment] 2021-11-29 07:57
I will test installing Harvester with the latest `yip` to see if this issue still occurred frequently.

**Comment by Itxaka** [comment] 2021-11-29 14:57
yip 0.9.25 has been released which hopefully fully resolves this! https://github.com/mudler/yip/releases/tag/0.9.25

**Comment by guangbochen** [comment] 2021-11-29 14:59
thanks @Itxaka , just wondering how long does the `udevadm settle` command normally takes on the installer side? or it will be fast since the device is quite less?

**Comment by Itxaka** [comment] 2021-11-29 15:06
if there is nothing in the udev queue it will be an instant return of 0
if there is something in the queue it will wait until those events are handled. In this case until partitions are refreshed probably. Shouldn't take long if there are events, I tested this about 700 times in an automated script and there was no appreciable difference against an un-patched version. The margin of udev events being handled should be pretty fast, thus why this is difficult to reproduce and happens about 1 out of 5 times in a specific machine (we could not reproduce it in qemu or vbox with both slow and fast HDDs!)

**Comment by w13915984028** [comment] 2021-11-30 11:34
Another point:

It seems the failure is always related to "`HARV_LH_DEFAULT`" partition, does anyone encounter failure with other partitions? And this failure came after the new feature of multi partition was merged.

One difference is that the `HARV_LH_DEFAULT `partition configures size to be 0, I guess it means using all the remaining size on that disk, could it cause some hidden bugs? or try to use a bit less than the remaining disk size.

```
547                                                 "add_partitions": []yipSchema.Partition{
548                                                         {
549                                                                 FSLabel:    "COS_OEM",
550                                                                 PLabel:     "oem",
551                                                                 Size:       50,
552                                                                 FileSystem: "ext4",
553                                                         },
554                                                         {
555                                                                 FSLabel:    "COS_STATE",
556                                                                 PLabel:     "state",
557                                                                 Size:       15360,
558                                                                 FileSystem: "ext4",
559                                                         },
560                                                         {
561                                                                 FSLabel:    "COS_RECOVERY",
562                                                                 PLabel:     "recovery",
563                                                                 Size:       8192,
564                                                                 FileSystem: "ext4",
565                                                         },
566                                                         {
567                                                                 FSLabel:    "COS_PERSISTENT",
568                                                                 PLabel:     "persistent",
569                                                                 Size:       uint(cosPersistentSizeGiB << 10),
570                                                                 FileSystem: "ext4",
571                                                         },
572                                                         {
573                                                                 FSLabel:    "HARV_LH_DEFAULT",
574                                                                 PLabel:     "longhorn",
575                                                                 Size:       0,
576                                                                 FileSystem: "ext4",
577                                                         },
578                                                 },
```

**Comment by johnliu55tw** [comment] 2021-11-30 13:39
This issue is fixed with `yip-0.9.25`.

**Comment by lanfon72** [comment] 2021-12-01 06:53
@johnliu55tw as we can't reproduce this on Provo's bare metals, would you please provide positive/negative test cases so that we can verify this bug is fixed.

**Comment by johnliu55tw** [comment] 2021-12-01 08:24
@lanfon72 Please see the **Additional Context** in the description.

**Comment by lanfon72** [comment] 2021-12-01 09:36
positive test: yip version `0.9.25`, verified 30 times, all succeed
negative test: yip version `0.9.18`, verified in 6th times

Test Information
----
* Environment: **qemu/KVM**, SCSI bus, 150Gb disk
* Harvester Version: **master-7a54d362-head**(positive test), **master-d05a6cc7-head**(negative test)

### Verify Steps:
follow the **Additional Context** in https://github.com/harvester/harvester/issues/1583#issue-1062085248

**Closed as completed by lanfon72** 2021-12-01 09:36 UTC
Labels: kind/bug, area/installer, priority/0, blocker
