### ISSUE TITLE
[FEATURE] Freeze VM before live backup

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#2279] opened 2022-05-17 02:19 UTC
**Is your feature request related to a problem? Please describe.**
Freeze VM to avoid users keep writing data during live backup.

**Describe the solution you'd like**
Try to call `freeze` and `unfreeze` for VMI.

**Additional context**
https://github.com/kubevirt/kubevirt/pull/5942

**Comment by yasker** [comment] 2022-06-03 20:58
Duplicate of #1723 .

**Closed as completed by yasker** 2022-06-03 20:58 UTC
Labels: kind/enhancement
