### ISSUE TITLE
Unable to create a VM with multiple SSH keys which are created using the same public key

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#184] opened 2020-09-28 08:19 UTC
**Steps to reproduce:**
1. Create several ssh keys using the same public key, name them key1, key2, and key3
2. Create a VM, select key1, key2, and key3, along with other required fields, then click the create button

**Result:**
An error occurs
![image](https://user-images.githubusercontent.com/57614736/94406541-c5385600-01a4-11eb-8740-bee5aa7214be.png)

**Comment by WuJun2016** [comment] 2021-08-19 06:55
duplicate of https://github.com/harvester/harvester/issues/760,   The reason is the same, verified in 760.
close this issue

**Closed as completed** 2021-08-19 06:56 UTC
Labels: kind/enhancement, area/ui
