### ISSUE TITLE
[FEATURE] Hope to create a secret in the output page through the UI

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3190] opened 2022-11-22 05:22 UTC
**Is your feature request related to a problem? Please describe.**

secret are useful in the `Monitoring&Logging>Logging>output` page, but there is no place to create secret in the UI.

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/111ff12e-fadd-47f3-9b41-9331df5924bf)

**Describe the solution you'd like**

hope to create secret through the harvester UI

**Describe alternatives you've considered**

**Additional context**

**Comment by n313893254** [comment] 2023-01-30 03:43
According to https://github.com/harvester/dashboard/pull/552#pullrequestreview-1225408533, we will move to ready for testing after namespace [PR](https://github.com/harvester/dashboard/pull/550) is merged.

**Comment by irishgordo** [comment] 2023-02-10 18:06
@n313893254 since https://github.com/harvester/dashboard/pull/550 isn't merged in yet, I'll move this back to Review - if that works?

I noticed that I can create a secret, but not currently in the `cattle-logging-system` namespace.
Off of Harvester Version: master-6fd9a5bb-head 

![Screenshot from 2023-02-10 10-04-34](https://user-images.githubusercontent.com/5370752/218164360-a2096e63-8320-4993-9bbe-99170f7fbc9e.png)
![Screenshot from 2023-02-10 10-00-18](https://user-images.githubusercontent.com/5370752/218164363-bd5f48b5-5ae6-4cb0-92ee-86a2ec67cc0f.png)

**Comment by n313893254** [comment] 2023-02-11 01:42
@irishgordo Sorry. The issue should move back to Review.

**Comment by irishgordo** [comment] 2023-02-21 23:27
**validation issue**

@DaiYuzeng  I noticed that when building an output for ElasticSearch to an local docker ElasticSearch (version: 6.8.23) that the POST sees a 201, but th index page of all "Outputs" is empty.
Do I need to do something in particular to see the list of Outputs?
Also from https://github.com/harvester/dashboard/pull/552:
> Go to create a secret in the `cattle-logging-system` namespace.

I noticed that the `cattle-logging-system` namespace was not available but the `cattle-monitoring-system` namespace was and I could create secrets from that.

![Screenshot from 2023-02-21 15-24-02](https://user-images.githubusercontent.com/5370752/220481849-eca28af4-1857-47c5-b303-94cdf66ed998.png)
![Screenshot from 2023-02-21 15-19-20](https://user-images.githubusercontent.com/5370752/220481853-bc940dac-755f-491c-9415-35f513db240b.png)

**Comment by irishgordo** [comment] 2023-02-21 23:32
I'm also noticing in "Cluster Outputs" that I'm not able to see any of the secrets that I created:
![Screenshot from 2023-02-21 15-31-26](https://user-images.githubusercontent.com/5370752/220482519-7df9d995-d90e-4e26-a77e-39a94006f9c3.png)

**Comment by DaiYuzeng** [comment] 2023-02-22 02:52
Hi @irishgordo ! Thanks for your testing!

We need to enable `cattle-logging-system` when creating secrets, I'll fix it.
Cluster Outputs only can choose the secrets in `cattle-logging-system` so you cannot see the secret just created if it's not in `cattle-logging-system`.

And I'll try to reproduce:
> @DaiYuzeng I noticed that when building an output for ElasticSearch to an local docker ElasticSearch (version: 6.8.23) that the POST sees a 201, but th index page of all "Outputs" is empty.

**Comment by DaiYuzeng** [comment] 2023-02-22 04:52
@irishgordo I filed an [issue](https://github.com/harvester/harvester/issues/3517) to track:

> @DaiYuzeng I noticed that when building an output for ElasticSearch to an local docker ElasticSearch (version: 6.8.23) that the POST sees a 201, but th index page of all "Outputs" is empty.
Do I need to do something in particular to see the list of Outputs?
Also from https://github.com/harvester/dashboard/pull/552:


I guess you created a resource (maybe Secret) in `cattle-monitoring-system` at first and then you went to create an Output which preset namespace is `cattle-monitoring-system`. 
You would realise that you cannot see it just created.

Can you please have a try to switch Output namespace manually to `default` after this issue is ready-for-testing?
I guess you will see it on the Output list page.

**Comment by irishgordo** [comment] 2023-02-22 19:31
**validation question:**

@DaiYuzeng thanks for the response back :smile: 

**Question:**
- is it expected that a user **must** create the secret for Logging-> "Cluster Output" through the "Access Embedded Rancher UI"?
![Screenshot from 2023-02-22 11-25-18](https://user-images.githubusercontent.com/5370752/220737641-deea4524-f3b3-44b8-986f-c3c39bcb86a9.png)
As, I wasn't noticing a way to preselect the `cattle-logging-system` namespace from the dashboard:
![Screenshot from 2023-02-22 11-28-59](https://user-images.githubusercontent.com/5370752/220738548-5436adf2-850a-45ea-acb7-018a79b8e5eb.png)
 
I noticed that I was unable to create a secret via Harvester dashboard and place inside of `cattle-logging-system`.
I was able to access the Embedded Rancher, `https://harvester-vip-ip/dashboard/c/local/explorer#cluster-metrics`, and build the secret via a kubectl shell from their with:
```yaml
> kubectl create secret generic elasticsearchmanualinembeddedrancher --from-literal=passwordtouse='harvestertesting' --namespace cattle-logging-system
secret/elasticsearchmanualinembeddedrancher created
```

Then once it was built from the "Embedded Rancher", I was able to use that secret for a Cluster Output, before creating a Cluster Flow.

I did notice that **after** creating the secret via Embedded Rancher on Harvester that when I navigated to "Advanced" -> "Secrets" -> "Create" that the `Namespace` was already set of `cattle-logging-system` - yet it was unavailable to be selected from the drop-down list.

I was able to create a Secret in the `default` namespace with an `Output` in the default namespace and a `Flow` in the `default` namespace and validate that logs got funneled into ElasticSearch, visually through Kibana - leveraging the secret that provided the ElasticSearch password.

![Screenshot from 2023-02-22 10-58-18](https://user-images.githubusercontent.com/5370752/220736912-515bf222-a2b0-4668-a123-09b3f3fa4b32.png)
![Screenshot from 2023-02-22 10-56-23](https://user-images.githubusercontent.com/5370752/220736917-9f90e5ae-b619-4122-b040-81ce22659f75.png)
![Screenshot from 2023-02-22 10-55-19](https://user-images.githubusercontent.com/5370752/220736921-c30dceab-4ff1-44fc-8765-401cc4de1a62.png)
![Screenshot from 2023-02-22 10-54-09](https://user-images.githubusercontent.com/5370752/220736925-23c809d3-019f-4800-bf00-bd90ef1d9f03.png)
![Screenshot from 2023-02-22 10-34-24](https://user-images.githubusercontent.com/5370752/220736927-af9b9f36-b5c6-477b-89da-7c153cdfadf9.png)

**Comment by irishgordo** [comment] 2023-02-22 19:33
I also created https://github.com/harvester/harvester/issues/3527 - to track the UI's tag overflowing if the Cluster Output name was 42 characters long

**Comment by DaiYuzeng** [comment] 2023-02-23 08:33
> is it expected that a user must create the secret for Logging-> "Cluster Output" through the "Access Embedded Rancher UI"?


No, it's unexpected.
I took a record here:
![logging](https://user-images.githubusercontent.com/15041915/220855902-02a42581-39c4-4d96-8f5b-9f717ea62337.gif)

May I know your UI-index? I can create a secret in `cattle-logging-system` in the latest UI.
(UI Index: https://releases.rancher.com/harvester-ui/dashboard/latest/index.html)

**Comment by DaiYuzeng** [comment] 2023-02-23 08:34
> I also created https://github.com/harvester/harvester/issues/3527 - to track the UI's tag overflowing if the Cluster Output name was 42 characters long

We'll fix it at v1.1.2, Thanks!

**Comment by irishgordo** [comment] 2023-02-23 20:14
**validation issue**

Hi @DaiYuzeng  - thanks for the response back :smile:  - I was working through attempting to re-test to see if I could see the "cattle-logging-system" namespace in the secret dropdown menu selection list, but I'm not seeing it.

The flow was:
- install v1.1.2-rc1 on single vm
- login
- head to Advanced -> Settings:
    - update `ui-index`
    - update `ui-source` from `auto` to `external`
- head to Monitoring & Logging -> Logging -> Configuration, click save on fluentbit & fluentd
- head to Advanced -> Secrets -> Create, attempt to see "cattle-logging-system" namespace available

It looks like the requests out to `/namespace` are correct, and we can see the JSON payload coming back with the appropriate results.
Also the KubeConfig from the Harvester node, does show the namespaces.

![Screenshot from 2023-02-23 11-49-15](https://user-images.githubusercontent.com/5370752/221018857-7a8f4013-6fea-4add-b6f0-8afb0aadd4d4.png)
![Screenshot from 2023-02-23 11-47-47](https://user-images.githubusercontent.com/5370752/221018859-fb319e32-18ec-4e44-8bf2-98d31ce99080.png)


I've also tried with:
```
ui-index:
https://releases.rancher.com/harvester-ui/dashboard/latest/index.html
ui-plugin-index:
https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js
```
In the Settings and wasn't able to see "cattle-logging-system" namespace as an available drop-down selection from the Secret.

**Comment by irishgordo** [comment] 2023-02-24 18:31
@WuJun2016 & @DaiYuzeng 
This may have been an environmental issue on my end :sweat_smile: 
But I am able to successfully now see the "cattle-logging-system" namespace available in the drop down section from the Secret creation form.
Validating that I'll go ahead and close this out :smile: :+1: - thanks for your help!
![Screenshot from 2023-02-24 10-25-56](https://user-images.githubusercontent.com/5370752/221260451-c0049b0f-daca-4de3-b6fc-7a34c58aeccc.png)

**Closed as completed by irishgordo** 2023-02-24 18:31 UTC
Labels: kind/enhancement, area/ui, priority/0, severity/1, reproduce/always
