### ISSUE TITLE
[BUG]Timeout Issue while destroying the harvester_virtualmachine resource created by Terraform 

### ISSUE THREAD

**Issue by Prasadrpatil** [harvester/harvester#5786] opened 2024-05-10 06:32 UTC
**Describe the bug**
while destroying harvester_virtualmachine resource using terraform, getting timeout error. The resource is getting destroyed in harvester. But through terraform I am getting this kind of error.

harvester_virtualmachine.iqem: Destroying... [id=testpipeline/terraform-test]
harvester_virtualmachine.iqem: Still destroying... [id=testpipeline/terraform-test, 10s elapsed]
harvester_virtualmachine.iqem: Still destroying... [id=testpipeline/terraform-test, 20s elapsed]
harvester_virtualmachine.iqem: Still destroying... [id=testpipeline/terraform-test, 30s elapsed]
harvester_virtualmachine.iqem: Still destroying... [id=testpipeline/terraform-test, 40s elapsed]
harvester_virtualmachine.iqem: Still destroying... [id=testpipeline/terraform-test, 50s elapsed]
harvester_virtualmachine.iqem: Still destroying... [id=testpipeline/terraform-test, 1m0s elapsed]
╷
│ Error: timeout waiting for virtualmachine testpipeline/terraform-test to be deleted
│ 

**To Reproduce**
1. create a harvester_virtualmachine resource using terraform, and destory it using terraform destroy command

**Expected behavior**
harvester_virtualmachine resource should be destroyed using terraform destroy

**Support bundle**
N/A

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure: bare-metal

**Additional context**
Providing my tf files here:

vm.tf

```
resource "harvester_virtualmachine" "test" {

  cpus         = 4
  description  = "Vm created for testing purpose"
  efi          = true
  hostname     = "terraform-test"
  machine_type = "q35"
  memory       = "16Gi"
  name         = "terraform-test"
  namespace    = "testpipeline"
  secure_boot  = false
  run_strategy = "RerunOnFailure"

  disk {
    access_mode        = "ReadWriteMany"
    auto_delete        = true
    boot_order         = 1
    bus                = "virtio"
    hot_plug           = false
    image              = "testpipeline/test-image"
    name               = "disk-0"
    size               = "40Gi"
    storage_class_name = "warm-hrvst1"
    type               = "disk"
    volume_mode        = "Block"
  }


  network_interface {
    model = "virtio"
    name  = "default"
    type  = "masquerade"
  }

  network_interface {
    model          = "virtio"
    name           = "nic-1"
    network_name   = "harvester-public/network1"
    type           = "bridge"
  }
  
  network_interface {
    model          = "virtio"
    name           = "nic-2"
    network_name   = "harvester-public/network2"
    type           = "bridge"
  }

  tpm {
    name = null
  }

}

```

provider.tf

```
terraform {
  required_version = ">= 0.13"
  required_providers {
    harvester = {
      source  = "harvester/harvester"
      version = "0.6.4"
    }
  }

}

provider "harvester" {
  kubeconfig = var.harvester_kubeconfig_path
}
```

**Comment by irishgordo** [comment] 2024-05-10 21:37
Hi @Prasadrpatil  -thanks for reporting this, this looks to be similar to:
- https://github.com/harvester/harvester/issues/5632

And also related to:
- https://github.com/harvester/terraform-provider-harvester/pull/96

There is a current, WIP branch here:
https://github.com/m-ildefons/terraform-provider-harvester/tree/wip/timeouts

cc: @bk201

**Comment by bk201** [comment] 2024-05-13 03:52
@irishgordo @m-ildefons Is this identical to https://github.com/harvester/harvester/issues/5632? I didn't see the timeout block in the issue description.

**Comment by irishgordo** [comment] 2024-05-14 18:39
@bk201 as far as I can tell I think this is probably broken down into two segments:

1. VM Timeouts, seem to have the potential to be a common place, on a VM that is doing a lot of work, with #5632 - I opened it due to continually "seeing" the symptoms of a VM not deleting in Terraform and things being in a strange state ( but not always reproducible ), when that VM was under heavy load / doing things -> which prompted the discovery of:
https://github.com/harvester/terraform-provider-harvester/blob/4e07ed02cba6fe7fc37bc0d41ff433df81e69915/internal/provider/virtualmachine/resource_virtualmachine.go#L25

2. Because of:
https://github.com/harvester/terraform-provider-harvester/blob/4e07ed02cba6fe7fc37bc0d41ff433df81e69915/internal/provider/virtualmachine/resource_virtualmachine.go#L25
The common Terraform convention seems to be implementing "configurable" timeout blocks, for a mix of large images or maybe long'ish running VMs so that maybe a user can then just utilize terraform convention instead of relying on the default `300` second timeout for the virtual machine to be deleted.  Additionally, leveraging that convention for "all" Harvester terraform resources.
Then with: https://github.com/m-ildefons/terraform-provider-harvester/tree/wip/timeouts - that would be implemented.

**Comment by m-ildefons** [comment] 2024-05-15 08:28
> @irishgordo @m-ildefons Is this identical to https://github.com/harvester/harvester/issues/5632? I didn't see the timeout block in the issue description.

I believe the user is facing an issue with the current lack of support for timeouts, so yes these issues are in essence identical.

The current implementation of the Terraform plugin uses either Terraform's defaults, or a fixed 5 minute timeout, depending on the resource and operation in question.
With support for timeout blocks, we would allow users to explicitly set a timeout.
We should also make sure that the default timeouts in our Terraform plugin work well for most use cases, so that users only need to utilize timeout blocks, if they have some rare edgecase.

**Comment by m-ildefons** [comment] 2024-11-08 15:27
I tried to reproduce this problem on Harvester v1.4.0-rc5 with the latest Terraform provider, but I wasn't able to.
Even though there are a few variables[1] unaccounted for, I think this bug has been fixed in the last release, especially since the [code to detect when a virtual machine is deleted](https://github.com/harvester/terraform-provider-harvester/pull/97/files#diff-7832ce67f142bd24bbb26fcaf34f4f4a9793c85e2760538cc83581152bf0280a) has been changed and tested for that release as well as support for timeout blocks, which allow for extended wait periods for resources that are slow to delete.

```
│ ~/repos/harvester/terraform-provider-harvester │► terraform destroy
harvester_virtualmachine.test: Refreshing state... [id=default/terraform-test]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # harvester_virtualmachine.test will be destroyed
  - resource "harvester_virtualmachine" "test" {
      - cpu                  = 4 -> null
      - description          = "Vm created for testing purpose" -> null
      - efi                  = true -> null
      - hostname             = "terraform-test" -> null
      - id                   = "default/terraform-test" -> null
      - machine_type         = "q35" -> null
      - memory               = "16Gi" -> null
      - name                 = "terraform-test" -> null
      - namespace            = "default" -> null
      - node_name            = "harvester-node-0" -> null
      - restart_after_update = false -> null
      - run_strategy         = "RerunOnFailure" -> null
      - secure_boot          = false -> null
      - ssh_keys             = [] -> null
      - state                = "Ready" -> null
      - tags                 = {} -> null

      - disk {
          - access_mode        = "ReadWriteMany" -> null
          - auto_delete        = true -> null
          - boot_order         = 1 -> null
          - bus                = "virtio" -> null
          - hot_plug           = false -> null
          - image              = "default/image-nzj7b" -> null
          - name               = "disk-0" -> null
          - size               = "40Gi" -> null
          - storage_class_name = "longhorn-image-nzj7b" -> null
          - type               = "disk" -> null
          - volume_mode        = "Block" -> null
          - volume_name        = "terraform-test-disk-0-wrq9f" -> null
        }

      - network_interface {
          - ip_address     = "10.52.0.119" -> null
          - mac_address    = "be:64:ba:e1:13:40" -> null
          - model          = "virtio" -> null
          - name           = "default" -> null
          - type           = "masquerade" -> null
          - wait_for_lease = false -> null
        }
      - network_interface {
          - mac_address    = "86:6b:7e:3c:12:3d" -> null
          - model          = "virtio" -> null
          - name           = "nic-1" -> null
          - network_name   = "harvester-public/network1" -> null
          - type           = "bridge" -> null
          - wait_for_lease = false -> null
        }
      - network_interface {
          - mac_address    = "9a:af:d2:c7:b4:52" -> null
          - model          = "virtio" -> null
          - name           = "nic-2" -> null
          - network_name   = "harvester-public/network2" -> null
          - type           = "bridge" -> null
          - wait_for_lease = false -> null
        }

      - tpm {}
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

harvester_virtualmachine.test: Destroying... [id=default/terraform-test]
harvester_virtualmachine.test: Destruction complete after 6s

Destroy complete! Resources: 1 destroyed.

```

I'd consider this issue solved.
Do you agree, @khushboo-rancher, @bk201 ?

[1]:
I used the default storage class config and a Ubuntu image that is known to work well.
Although the `.tf` example code implies that both a custom storage class as well as a custom VM image is in use by the user, I don't think that it would explain the issue.

**Comment by khushboo-rancher** [comment] 2024-11-08 20:12
I agree with @m-ildefons, this should be considered as resolved and we can close it.

**Comment by bk201** [comment] 2024-11-11 02:45
We can't reproduce the issue. Please re-open if needed.

**Closed as completed by bk201** 2024-11-11 02:45 UTC
Labels: kind/bug, wontfix, require/investigate, require/reproduce, require/severity, not-require/release-note
