### ISSUE TITLE
[BUG] rename vm-force-deletion-policy for vm-force-reset-policy

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1661] opened 2021-12-10 16:26 UTC
The setting name infers a deletion of the virtual machine based on this policy but the real effect is that the virtual machine is being reset in order to start on another node. We should rename this setting to avoid confusion.

**Comment by yasker** [comment] 2021-12-10 16:46
@guangbochen can we rename? I think the name comes from a similar setting in Longhorn but since we're deleting pods, not VMs, it's better to use `reset` instead of `deletion` in the name.

**Comment by FrankYang0529** [comment] 2021-12-13 04:15
@guangbochen, we may also need a PR to rename `vm-force-deletion-policy` to `vm-force-reset-policy` on dashboard. Thank you.

**Comment by guangbochen** [comment] 2021-12-13 04:18
it should be updated automatically once the backend is changed, but need to sync the setting whitelist cc @WuJun2016, also need to change the description to `Config the force-reset action when a VM is stuck on a node that is down.`

**Comment by yasker** [comment] 2021-12-15 16:36
Confirmed that the setting name has been updated in Harvester when using UI from upstream.
<img width="1568" alt="Screen Shot 2021-12-15 at 8 33 38 AM" src="https://user-images.githubusercontent.com/3344618/146226444-93e1ef2a-3f9b-457f-bdb2-5744720ae821.png">

**However, the option doesn't show up when accessing the Harvester UI from Rancher.** @guangbochen @n313893254  is it by design?

**Comment by n313893254** [comment] 2021-12-16 01:56
My bad. As harvester UI dose not create PR for dashboard UI for now. we should replace the ui-dashboard-index setting of Rancher to 'https://releases.rancher.com/harvester-ui/dashboard/latest/index.html' to test Harvester UI from Rancher.

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/9aa57f3d-9e7f-4b5e-96c6-6478764b1c4b)

**Comment by noahgildersleeve** [comment] 2021-12-16 21:01
Tested in master-5e8d9764-head. Verified as fixed in the harvester ui-index that hasn't been merged upstream yet
## Test Steps
1. Update ui-offline-preferred to Remote
2. Update ui-dashboard-index to https://releases.rancher.com/harvester-ui/dashboard/latest/index.html
3. Check advanced settings in Harvester UI and Rancher Harvester dashboard and verify setting is named vm-force-reset-policy
![Screenshot from 2021-12-16 13-00-13](https://user-images.githubusercontent.com/83787952/146448317-a259d86d-2020-4bed-adc2-f19ecf0d3fbb.png)
![Screenshot from 2021-12-16 12-57-39](https://user-images.githubusercontent.com/83787952/146448321-d0cfeb53-7c30-474e-9cee-207958d25ecf.png)

**Closed as completed by noahgildersleeve** 2021-12-16 21:01 UTC
Labels: kind/bug, area/ui, priority/1
