### ISSUE TITLE
[BUG] After we enabled or disabled the rancher-manager-support setting, the  cluster-registration-url setting disappeared

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4010] opened 2023-05-31 11:33 UTC
**Describe the bug**

After we enabled the `rancher-manager-support` in settings and refresh the page. 
The original `cluster-registration-url` setting disappear from settings, thus we can no longer integrate with external Rancher 

![image](https://github.com/harvester/harvester/assets/29251855/c8711bf3-19a5-4709-9680-a9e59a55a476)

**To Reproduce**
1. Prepare a v1.2.0-rc1 cluster
2. Check the `cluster-registration-url` exists in settings
3. Enable the `rancher-manager-support` setting
4. Check the  `cluster-registration-url` exists in settings
5. Disable the the `rancher-manager-support` setting
6. Check the  `cluster-registration-url` exists in settings

**Expected behavior**

After enabled or disabled the the `rancher-manager-support` settings, the `cluster-registration-url` setting should exists for the requirement to integrate with external Rancher instance 

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0-rc1
 - Rancher version: v2.7.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single nodes on local kvm machine 

**Additional context**
* cluster-registration-url setting
  ![image](https://github.com/harvester/harvester/assets/29251855/dc7f230a-08cc-4003-8aaa-af16b8fb26fe)

**Comment by lanfon72** [comment] 2023-05-31 11:49
This should be expected behavior as the HEP described. https://github.com/harvester/harvester/pull/3673/files#diff-f75d1cbfeff893ffa1f5d166a616d1a23aa27b7f76e34d84f91bd8f1f2cd15feR44

**Comment by WuJun2016** [comment] 2023-05-31 14:03
> This should be expected behavior as the HEP described. https://github.com/harvester/harvester/pull/3673/files#diff-f75d1cbfeff893ffa1f5d166a616d1a23aa27b7f76e34d84f91bd8f1f2cd15feR44

Yes, this is the expected behavior，  When the cluster is enabled with `rancher-manage-support,` it will act as a rancher cluster to manage other clusters, so this cluster will not be imported by other rancher clusters (So we hide the `cluster-registration-url`)

**Comment by TachunLin** [comment] 2023-06-01 06:11
After we implemented the MCM feature on the `rancher-manager-support` setting, here comes the following 
**three** user scenarios we need to take into consideration:

1. `Default` value which `did not enable` the MCM Rancher: 
   - We can integrate Harvester to external Rancher instance as we were in v1.1.2
2. `Enabled` the MCM Rancher: 
   - In this case we can only use the embedded Rancher to integrate with Harvester 
3. `Disable` the MCM Rancher: 
   - In this case, we should still be able to integrate Harvester to external Rancher 

And these user scenarios also related to some v1.2.0 new feature like

- #1676
- #1458 

which requires to integrate with guest cluster, project etc.. 

And we also need to consider the current user requirement and setup of the external Rancher integration.  

According to the [HEP](https://github.com/harvester/harvester/pull/3673/files#diff-f75d1cbfeff893ffa1f5d166a616d1a23aa27b7f76e34d84f91bd8f1f2cd15feR44), we have no doubt for **user scenario 2** , we can only have on Rancher control one Harvester


@guangbochen, @bk201, @WuJun2016 
May I confirm for `user scenario 3` when we disable the `rancher-manager-support` setting, what would be the supposed behavior we need to provide for Rancher integration? 

Since after we disable the MCM feature, in concept we should still provide the capability to integrate Harvester to external Rancher as in the default case.

**Comment by guangbochen** [comment] 2023-06-01 07:22
For case 3, yes, users should still be able to import the MCM-disabled Harvester cluster into the upstream Rancher again; however, the auth provider and users will not get synced with each other. Also, we will need to add more validations on the Harvester to ensure the admin should clean up the resources like the guest k8s cluster and delete imported clusters before disabling the MCM setting. cc @ibrokethecloud

**Comment by ibrokethecloud** [comment] 2023-06-05 06:43
based on a quick investigation we should disable `cluster-registeration-url` setting when `rancher-manager-support` is enabled due to the following reasons:
* cluster provisioning objects exist in the local management cluster, so there is likely to be confusion/conflicts since one of the rancher installations will not have the correct view / relationship of provisioned infrastructure with the associated cluster objects.
* project and rbac information is stored in the local cluster, as a result when a cluster with  `rancher-manager-support` enabled is imported into another rancher cluster, the project/rbac membership is missing from the external cluster. for example in the 2nd rancher manager, the Default / System projects have no namespaces attached since the project id annotations are already populated and dont match the view of the 2nd rancher.
<img width="658" alt="image" src="https://github.com/harvester/harvester/assets/19664014/662de8bf-45d5-417a-92a2-1a67ca28af30">

* inconsistent auditing since the clusters can now be accessed via two different api endpoints.

**Comment by WuJun2016** [comment] 2023-07-12 02:08
Close this issue, because `rancher-manager-support` has been removed.   cc @guangbochen

**Closed as completed by WuJun2016** 2023-07-12 02:08 UTC
Labels: kind/bug, area/ui, severity/1, reproduce/always
