### ISSUE TITLE
[BUG] harvester-csi-driver pod stuck in creating

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#1895] opened 2022-02-08 08:07 UTC
**Describe the bug**
When we create a new RKE2 cluster, harvester-csi-driver can't be deployed successfully. The error message is `FailedMount	Pod harvester-csi-driver-xxxxx
MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /etc/kubernetes/cloud-config is not a file`.

**To Reproduce**
1. Create a new RKE2 1.22.5-rke2r2 cluster.
2. After the RKE2 cluster created, click `Explore`.
3. Choose `All Namespaces`.
4. Click `Apps & Marketplace` -> `Installed Apps` -> `harvester-csi-driver`.
5. We can see `harvester-csi-driver` daemonset is stuck in `In Progress`.

![Screen Shot 2022-02-08 at 3 15 26 PM](https://user-images.githubusercontent.com/4927361/152943686-b86e6057-7e83-4477-8bef-4519d7524700.png)
![Screen Shot 2022-02-08 at 3 15 38 PM](https://user-images.githubusercontent.com/4927361/152943700-213e1b30-01a7-4e88-ac50-fdc6a6e2832b.png)
![Screen Shot 2022-02-08 at 3 15 48 PM](https://user-images.githubusercontent.com/4927361/152943703-8ae172e6-01c4-42b5-ad22-0729a43507dd.png)
![Screen Shot 2022-02-08 at 3 15 55 PM](https://user-images.githubusercontent.com/4927361/152943709-e0182441-27f4-4ef8-859c-9176e1b0a6e4.png)

**Expected behavior**
`harvester-csi-driver` can be deployed successfully.

**Environment:**
 - Harvester ISO version: `master-1a861fc1-head`
 - Underlying Infrastructure: KVM

**Additional context**
If we change `Cloud config file path` to `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config`, `harvester-csi-driver` can be deployed without error.
![Screen Shot 2022-02-08 at 4 05 01 PM](https://user-images.githubusercontent.com/4927361/152943953-a5df94cf-4bb5-42fa-a07d-5b7a7821c795.png)

**Comment by yaocw2020** [comment] 2022-03-07 10:11
Test plan before RKE2 release: 
- Use harvester node driver to spin up an RKE2 cluster with harvester-cloud-provider.
- Delete the old harvester-csi-driver manually.
![image](https://user-images.githubusercontent.com/7421463/157011002-94ed1be4-d734-4b6b-9e6d-f1242bff7081.png)
- Install the latest version by helm manually.
```
$ helm repo add harvester https://charts.harvesterhci.io
$ helm repo update
$ helm install harvester-csi-driver harvester/harvester-csi-driver -n kube-system
```

**Comment by guangbochen** [comment] 2022-03-07 10:23
@TachunLin @lanfon72 @noahgildersleeve since both RKE2 and Rancher KDM release cycle is much longer than our dev-complete cycle, I think we should verify those issues AEAP if we can. And if there are any bugs we can fix them before the KDM release, WDUT thanks.

If the manual verification is passed we can move it to the `ice-box` and run a full-regression test once the RKE2/KDM is released, thanks.

**Comment by TachunLin** [comment] 2022-03-07 15:28
Verified the workaround `before RKE2 release` **works** on rancher `v2.6-head` (33db2f5) with `v1.21.10+rke2r1`
Move issue to ice box for follow up regression test. 

@guangbochen, @yaocw2020  
I would suggest maybe we can add this workaround to harvester document 

### Result
Delete the old harvester-csi-driver manually and manually helm install latest version. 
harvester csi driver can be deployed correctly on rke2 cluster

![image](https://user-images.githubusercontent.com/29251855/157061020-3ffe0d75-b3d4-41bc-8601-a0e7361d3e3c.png)

```
# e.g. kubectl get all
> helm repo add harvester https://charts.harvesterhci.io
"harvester" has been added to your repositories
> helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "harvester" chart repository
Update Complete. ⎈Happy Helming!⎈
> helm install harvester-csi-driver harvester/harvester-csi-driver -n kube-system
creating 7 resource(s)
NAME: harvester-csi-driver
LAST DEPLOYED: Mon Mar  7 15:07:48 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Successfully deployed Harvester CSI driver to the kube-system namespace.
```
![image](https://user-images.githubusercontent.com/29251855/157060828-4177238d-83e3-4871-9869-fc2be1f846f9.png)

### Test Information
* Test Environment: 1 node1 harvester on local kvm machine
* Harvester version: master-088a020f-head (03/06)
* Rancher version: v2.6-head (33db2f5)
* OS image: Ubuntu cloud focal image
* RKE2 version: v1.21.10+rke2r1

### Verify Steps
1. Import harvester from rancher v2.6-head
2. Create cloud credential
3. Provision a RKE2 cluster with v1.21.10 and ubuntu focal image 
4. Check installed apps after rke2 provision complete
5. Change the namespace to all 
6. Delete the old csi driver
![image](https://user-images.githubusercontent.com/29251855/157059945-627d424c-de54-40d4-a7dd-b7cafc9f00dc.png) 
7. Open kubectl shell 
8. Run the following command 
  ```
  $ helm repo add harvester https://charts.harvesterhci.io
  $ helm repo update
  $ helm install harvester-csi-driver harvester/harvester-csi-driver -n kube-system
  ```
9. Check the csi driver apps status

**Comment by TachunLin** [comment] 2022-03-16 14:10
Verified **PASS** the regression test on Rancher `v2.6-head 2642acc` (03/16) with Harvester `v1.0-591d8015-head` (03/16). Close this issue.

### Result
The Harvester csi driver have been bumped and installed by default after provisioning RKE2 cluster complete.
* The csi driver application deployment correctly without stuck, no need to use workaround
  ![image](https://user-images.githubusercontent.com/29251855/158606755-526447e2-9459-412f-adae-bd135e7ed684.png)

* All resource component running correctly
  ![image](https://user-images.githubusercontent.com/29251855/158605738-699095c1-0a05-4f7f-ad36-9f2859f5d1b3.png)

* Harvester already set as default storage class
  ![image](https://user-images.githubusercontent.com/29251855/158605985-b5141954-efe4-48f5-925e-1e13bacae3f0.png)
  
* Can deploy nginx workload with create harvester PVC
  ![image](https://user-images.githubusercontent.com/29251855/158608690-f76496f7-04ca-45ed-b15c-f4eb9914d53c.png)
  ![image](https://user-images.githubusercontent.com/29251855/158608816-17b60a24-5ecf-4f77-8b56-11fc9b65ce0e.png)



### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: v1.0-591d8015-head (03/16)
* Rancher version: v2.6-head 2642acc
* Kubernetes version: v1.21.7+rke2r2
* OS image: Ubuntu focal, SLES JeOS

### Verify Steps
### Verify Steps
1. Create a one node harvester 
2. Upload Ubuntu focal image
3. Create virtual network vlan1 with id 1
4. Import Harvester from Rancher
5. Create cloud credential 
6. Provision an RKE2 cluster 
7. Add the following use cloud-init data 
```
  password: 123456
  chpasswd: { expire: False }
  ssh_pwauth: True
  ```
8. Select Ubuntu focal image
9. Provide available cpu and memory resources
10. Provision the RKE2 cluster
11. Change namespace to `All`
12. Open Installed Apps under Apps & Market 
13. Check the harvester-csi-provider status
14. Check the Storage Class page
15. Deploy a nginx workload 
16. Create a new PVC with harvester provider

**Closed as completed by TachunLin** 2022-03-16 14:10 UTC
Labels: kind/bug, priority/0, area/guest-cluster-node-driver, severity/1, regression
