### ISSUE TITLE
[BUG] When accessing imported Harvester in Rancher, VM Metrics don't work correctly

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4343] opened 2023-07-31 08:28 UTC
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/fab08206-dd50-478e-9c8f-15e00cc7cd0d)

**To Reproduce**
1. Go to Rancher.
2. Go to import existing Harvester cluster.
3. Access Harvester cluster.
4. create a VM
5. enable `rancher-monitoring` addon
6. go to vm detail page
7. choose `VM Metrics` tab

**Expected behavior**

VM metrics should be displayed correctly

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.2.0-rc3, v1.2.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment] 2023-08-02 15:22
refer: this is similar to the issue https://github.com/harvester/harvester/issues/4087 but its last PR was for the home dashboard page, which could be the same issue caused by the monitoring chart bump.

**Comment by w13915984028** [comment] 2023-08-08 03:44
@WuJun2016 found such differences between different versions:

`vm-info-detail` vs `harvester-vm-info-detail`

harvester-master: 
>https://172.16.1.31/k8s/clusters/c-m-vc5r69ht/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/harvester-vm-detail-1/vm-info-detail?orgId=1&from=now-5m&to=now&refresh=30s&var-namespace=default&var-vm=v2&theme=light

harvester-v112:   
>https://172.16.1.31/k8s/clusters/c-m-ftjqlvl8/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/harvester-vm-detail-1/harvester-vm-info-detail?orgId=1&from=now-5m&to=now&refresh=30s&var-namespace=default&var-vm=112&theme=light
harvester-v110:   

>https://172.16.1.31/k8s/clusters/c-m-bll742jq/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/harvester-vm-detail-1/harvester-vm-info-detail?orgId=1&from=now-5m&to=now&refresh=30s&var-namespace=default&var-vm=test1&theme=light

continue checking

**Comment by w13915984028** [comment] 2023-08-08 03:56
by contrast, harvester local cluster, the VM metrics has no differences in URL:

v112: 
>https://VIP/dashboard/harvester/c/local/kubevirt.io.virtualmachine/default/vm-name#vm-metrics

v120: 
>https://VIP/dashboard/harvester/c/local/kubevirt.io.virtualmachine/default/vm-name#vm-metrics

**Comment by w13915984028** [comment] 2023-08-09 12:09
after a local fix: https://github.com/harvester/harvester-installer/pull/555
link like: https://VIP/dashboard/harvester/c/c-m-8zxqjrgg/kubevirt.io.virtualmachine/default/vm2#vm-metrics

result:
<img width="1184" alt="image" src="https://github.com/harvester/harvester/assets/31133476/0b138dc9-831c-4e46-908b-eb91fc92bbab">

**Comment by irishgordo** [comment] 2023-08-14 21:33
Tested on  Version: v1.2-57b26312-head  & Rancher v2.7-head - :+1: :smile: 
This looks good - thanks for the fix @w13915984028 !
I'll go ahead and close this out :smile: 
![Screenshot from 2023-08-14 14-32-06](https://github.com/harvester/harvester/assets/5370752/f8f57435-d366-4e22-8a6d-2327ca28620f)
![Screenshot from 2023-08-14 14-31-44](https://github.com/harvester/harvester/assets/5370752/0a140c17-450c-48c8-990c-30d7eba01be5)
![Screenshot from 2023-08-14 14-31-09](https://github.com/harvester/harvester/assets/5370752/4c63f90d-6950-4886-bf4b-0c8a85a07eb1)

**Closed as completed by irishgordo** 2023-08-14 21:33 UTC
Labels: kind/bug, priority/1, area/observability, severity/3, reproduce/always
