### ISSUE TITLE
[BUG] kube-vip not assigned etcd toleration when creating rke2 cluster with dedicated worker

### ISSUE THREAD

**Issue by devclef** [harvester/harvester#4538] opened 2023-09-16 11:53 UTC
**Describe the bug**
When creating a new rke2 cluster via rancher with the following:
3x etcd/controlplan
1x worker

The nodes with etcd/control plane have two tolerations one for each role respectively.

The kube-vip daemonset only has a toleration for controlplane, not etcd

**To Reproduce**
Create rke2 cluster via rancher
3x control/etcd 
1x worker

Expected:
3x kube-vip deployed on control plan/etcd nodes due to tolerations being properly set.

Deploy. 

Check daemonset for kube-vip -- 0 running pods.
Check config of daemonset, pod. Only controlplane toleration is set, not etcd
**Expected behavior**

**Environment**
 - Harvester ISO version: v1.2.0
 - Underlying Infrastructure: Dell optiplex 3080 mini PCs
 - Rancher addon enabled within harvester

**Additional context**
Running a single or multiple node cluster which has all roles (etcd, worker, controlplane) will behave as expected. It is only when you split the roles where this occurs.

This has the side effect of load balancing not being provisioned. I discovered this when trying to isolate a configuration which load balancer provisioning worked. -- Ultimately doing a series of single node cluster, 3 node cluster, and finally 3 masters + workers. Upon trying to find differences noticed the daemonset for kip-vip was never deploying any pods.

If a dump of some sort is needed please let me know. As a work around I added the toleration for etcd to the daemon set and immediately 3x pods started and I just provisioned an LB vip for the first time on a 3+X cluster configuration in nearly a week of trying :)

**Comment by slackspace-io** [comment] 2023-09-16 12:34
Perhaps related, I notice system upgrade fail jobs on the workers as well.
```
+ TMPDIRBASE=/var/lib/rancher/agent/tmp
2023-09-16T12:14:56.567570404Z + mkdir -p /host/var/lib/rancher/agent/tmp
2023-09-16T12:14:56.568220895Z + chroot /host /bin/sh -c 'mktemp -d -p /var/lib/rancher/agent/tmp'
2023-09-16T12:14:56.569615770Z + TMPDIR=/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16
2023-09-16T12:14:56.573176854Z + trap cleanup EXIT
2023-09-16T12:14:56.573193680Z + trap exit INT HUP TERM
2023-09-16T12:14:56.573201800Z + cp /opt/rancher-system-agent-suc/install.sh /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16
2023-09-16T12:14:56.573391816Z + cp /opt/rancher-system-agent-suc/rancher-system-agent /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16
2023-09-16T12:14:56.591882433Z + cp /opt/rancher-system-agent-suc/system-agent-uninstall.sh /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/rancher-system-agent-uninstall.sh
2023-09-16T12:14:56.592381810Z + chmod +x /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/install.sh
2023-09-16T12:14:56.592817586Z + chmod +x /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/rancher-system-agent-uninstall.sh
2023-09-16T12:14:56.593282107Z + '[' -n slack-work-e807568f-nk4n9 ]
2023-09-16T12:14:56.593287794Z + NODE_FILE=/host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/node.yaml
+ kubectl get node slack-work-e807568f-nk4n9 -o yaml
2023-09-16T12:16:26.889126310Z + '[' -z  ]
2023-09-16T12:16:26.889144799Z + grep -q 'node-role.kubernetes.io/etcd: "true"' /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/node.yaml
2023-09-16T12:16:26.889893481Z + '[' -z  ]
2023-09-16T12:16:26.889904825Z + grep -q 'node-role.kubernetes.io/controlplane: "true"' /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/node.yaml
2023-09-16T12:16:26.891282948Z + '[' -z  ]
2023-09-16T12:16:26.891307934Z + grep -q 'node-role.kubernetes.io/control-plane: "true"' /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/node.yaml
2023-09-16T12:16:26.892606686Z + '[' -z  ]
2023-09-16T12:16:26.892631544Z + grep -q 'node-role.kubernetes.io/worker: "true"' /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/node.yaml
2023-09-16T12:16:26.893213530Z + export 'CATTLE_AGENT_BINARY_LOCAL=true'
2023-09-16T12:16:26.893221684Z + export 'CATTLE_AGENT_UNINSTALL_LOCAL=true'
2023-09-16T12:16:26.893224353Z + export 'CATTLE_AGENT_BINARY_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/rancher-system-agent'
2023-09-16T12:16:26.893239822Z + export 'CATTLE_AGENT_UNINSTALL_LOCAL_LOCATION=/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/rancher-system-agent-uninstall.sh'
2023-09-16T12:16:26.893281382Z + '[' -s /host/etc/systemd/system/rancher-system-agent.env ]
2023-09-16T12:16:26.893322075Z + chroot /host /var/lib/rancher/agent/tmp/tmp.n7zGOBLD16/install.sh
2023-09-16T12:16:26.896539762Z [FATAL]  You must select at least one role.
2023-09-16T12:16:26.896649257Z + cleanup
+ rm -rf /host/var/lib/rancher/agent/tmp/tmp.n7zGOBLD16
```

Checking a node has this label set:
`    rke.cattle.io/worker-role: 'true'
`
was there a change in format? At least the upgrade script is checking for worker: 'true', not worker-role. Wonder if similar root cause is why kube-vip daemon set ends up in correctly configured?

**Comment by starbops** [comment] 2023-12-01 02:19
I'm going to close this as #4678 has more information. We'll keep working on it there. Thank you for reporting the issue!

**Closed as completed by starbops** 2023-12-01 02:19 UTC
Labels: kind/bug, require/reproduce, require/severity
