### ISSUE TITLE
[BUG] Sometimes vm stuck in terminating state on network disruption 

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#1705] opened 2021-12-19 04:59 UTC
**Describe the bug**
On creating network disruption on a node where the vm was running vm stuck in `starting` state.

**To Reproduce**
1. Create a vm.
2. Disrupt the network for 200 sec on the node where the node is attached using  iptables.
3. vm stuck in 'starting` state.

**Expected behavior**
The vm should recover.

**Support bundle**
[supportbundle_b25e9adb-2f56-4422-9aaf-a2f94ead1fcc_2021-12-19T04-40-55Z.zip](https://github.com/harvester/harvester/files/7740329/supportbundle_b25e9adb-2f56-4422-9aaf-a2f94ead1fcc_2021-12-19T04-40-55Z.zip)
VM name - vm-test-1
Volume name - restore-2nd-backup-f47295a4-d963-43c2-8f89-179e63910c1c-disk-0
Time stamp - around 2021-12-19 04:30:00

```
kubectl get pods
NAME                            READY   STATUS        RESTARTS   AGE
virt-launcher-vm-test-1-2x78g   0/1     Terminating   0          34m
```
```
kubectl logs virt-launcher-vm-test-1-2x78g
Error from server (BadRequest): container "compute" in pod "virt-launcher-vm-test-1-2x78g" is terminated
```

**Environment:**
 - Harvester ISO version: v1.0.0-rc2

**Note:**
Not reproducible all the times.

**Comment by tjjh89017** [comment] 2022-02-14 06:27
> Disrupt the network for 200 sec on the node where the node is attached using iptables.

@khushboo-rancher Could you please provide more detail about how did you disrupt?
tks a lot

**Comment by khushboo-rancher** [comment] 2022-02-14 17:42
I used the below script to disrupt the network.
[network_down.sh.zip](https://github.com/harvester/harvester/files/8062826/network_down.sh.zip)

**Comment by tjjh89017** [comment] 2022-03-07 05:30
Note:
VMI will enter status `Phase: Failed`
VM will enter status `Stopped`

**Comment by tjjh89017** [comment] 2022-03-07 06:54
@khushboo-rancher need your help to confirm.
Could you please describe the reason and purpose to use `iptables -P <FILTER_NAME> DROP` to test?
Thanks a lot.

If node is disconnected and re-connected, kubevirt virt-controller will kill VMI and restart it, kubelet will try to kill the pod but stuck in killing stage.

**Comment by tjjh89017** [comment] 2022-03-07 07:17
```
{"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"test","namespace":"default","pos":"vm.go:581","timestamp":"2022-03-07T07:13:26.153715Z","uid":"fa5b601b-6818-4dc6-b6da-b57238eeec76"}
{"component":"virt-controller","level":"info","msg":"deleting pdb default/kubevirt-disruption-budget-5rnlt due to VMI deletion","pos":"disruptionbudget.go:489","timestamp":"2022-03-07T07:13:26.160282Z"}
{"component":"virt-controller","kind":"","level":"info","msg":"Dispatching delete event for vmi default/test with phase Failed","name":"test","namespace":"default","pos":"vm.go:936","timestamp":"2022-03-07T07:13:26.160970Z","uid":"fa5b601b-6818-4dc6-b6da-b57238eeec76"}
W0307 07:13:26.168939       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
{"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"test","namespace":"default","pos":"vm.go:307","reason":"the server rejected our request due to an error in our request","timestamp":"2022-03-07T07:13:26.186082Z","uid":"fa5b601b-6818-4dc6-b6da-b57238eeec76"}
{"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine default/test","pos":"vm.go:175","reason":"the server rejected our request due to an error in our request","timestamp":"2022-03-07T07:13:26.186139Z"}
{"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"test","namespace":"default","pos":"vm.go:581","timestamp":"2022-03-07T07:13:26.186196Z","uid":"fa5b601b-6818-4dc6-b6da-b57238eeec76"}
{"component":"virt-controller","kind":"","level":"info","msg":"Stopping VM with VMI in phase Failed and VM runStrategy: Always","name":"test","namespace":"default","pos":"vm.go:581","timestamp":"2022-03-07T07:13:26.198876Z","uid":"fa5b601b-6818-4dc6-b6da-b57238eeec76"}

```

**Comment by tjjh89017** [comment] 2022-03-07 07:42
```
Events:
  Type     Reason            Age                    From                         Message
  ----     ------            ----                   ----                         -------
  Normal   SuccessfulCreate  14m                    disruptionbudget-controller  Created PodDisruptionBudget kubevirt-disruption-budget-g9vc9
  Normal   SuccessfulCreate  14m                    virtualmachine-controller    Created virtual machine pod virt-launcher-test-95fst
  Normal   Started           14m                    virt-handler                 VirtualMachineInstance started.
  Normal   Created           9m42s (x3 over 13m)    virt-handler                 VirtualMachineInstance defined.
  Normal   Created           9m (x9 over 14m)       virt-handler                 VirtualMachineInstance defined.
  Warning  IOerror           8m45s (x3 over 9m18s)  virt-handler                 VM Paused due to IO error at the volume: disk-0
  Normal   ShuttingDown      8m45s (x5 over 9m)     virt-handler                 Signaled Graceful Shutdown
  Warning  SyncFailed        8m44s (x8 over 8m45s)  virt-handler                 server error. command Shutdown failed: "LibvirtError(Code=55, Domain=10, Message='Requested operation is not valid: domain is not running')"
  Normal   SuccessfulDelete  7m51s                  disruptionbudget-controller  Deleted PodDisruptionBudget kubevirt-disruption-budget-g9vc9
[date@dell5560 pkg]$ kubectl describe vmi
```

**Comment by tjjh89017** [comment] 2022-03-07 08:38
workaround:
force kill the pod, kubevirt will recreate the VM.
`kubectl delete pod virt-launcher-XXX-XXX --force --grace-period=0`

**Comment by khushboo-rancher** [comment] 2022-03-07 23:14
@tjjh89017 We need to test some general problematic scenarios where users have disruption in network due to any software/hardware problem. So, for testing purpose to reproduce it I've used `iptable drop`

**Comment by tjjh89017** [comment] 2022-05-23 06:11
Note: https://groups.google.com/g/kubevirt-dev/c/fiVJeNgiAIk

**Comment by guangbochen** [comment] 2022-05-24 09:57
Move this issue to future planning since it is a rare-reproduce case. additionally, the PR https://github.com/harvester/harvester/pull/2168 has also mitigated this issue.

**Comment by tjjh89017** [comment] 2022-11-10 06:17
Cannot reproduce this.
We will close this ticket first.
If we need, we could reopen this ticket 
Thanks a lot

**Closed as completed by tjjh89017** 2022-11-10 06:17 UTC
Labels: kind/bug, priority/1, severity/2, reproduce/rare
